/**
 * b1-examen — English.
 *
 * A translation of the Dutch body in `../b1-examen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_BOOK, I_CHECK, I_HEADPHONES, I_MIC, I_PEN, I_ROUTE, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_AANMELDEN, SRC_BESLUIT55, SRC_DIPLOMA, SRC_IND, SRC_NT2, SRC_NT2_GELD, SRC_PLAATSEN, SRC_ROUTES, SRC_TAALEXAMENS, card, row } from '../b1-examen';

const translation: GuideLocale = {
  title: 'The B1 language exam: staatsexamen NT2 explained',
  description: 'You are in the B1 route. What is a staatsexamen NT2, how long are the four parts at B1, where do you sit them, and what if B1 turns out too high?',
  breadcrumb: 'The B1 exam',
  dateLabel: '24 August 2026',
  eyebrow: 'Language exam',
  heroTitle: 'The language exam at level B1',
  heroSubtitle: 'B1 is not the same exam as A2, one size bigger. It is a different exam, from a different department, at different locations. Here is what that means for you.',
  ctaTitle: 'Practise an exam at B1',
  ctaDesc: 'Free practice exam Lezen at level B1, with an explanation after every answer. Without an account.',
  ctaLabel: 'Start the free practice exam',

  articleHtml: `
<h2 id="wat-is-b1">B1 is a staatsexamen NT2, not a bigger A2 exam</h2>

<p>This is the first thing that goes wrong. People think: I have seen A2, B1 is the same but harder.
That is not correct. The inburgeringsexamen at A2 and the staatsexamen NT2 at B1 are <strong>two
different exams</strong>, from two different departments of DUO, at different locations, each with
its own fee and its own uitslagtermijn (the time until you get your result).</p>

<div class="compare-2">
  <div class="compare-card">
    <div class="compare-head">
      <h3>Inburgeringsexamen A2</h3>
      <p class="compare-when">For the Z-route and the Wet 2013</p>
    </div>
    <div class="compare-rows">
      ${row('Where', 'Six exam locations: Amsterdam, Eindhoven, Rijswijk, Rotterdam, Utrecht, Zwolle')}
      ${row('Registering', 'Mijn Inburgering')}
      ${row('Parts', 'Lezen, Luisteren, Schrijven, Spreken + KNM')}
      ${row('Schrijven', 'With pen and paper')}
    </div>
  </div>
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>Staatsexamen NT2 (B1 and B2)</h3>
      <p class="compare-when">For the B1-route and the onderwijsroute</p>
    </div>
    <div class="compare-rows">
      ${row('Where', 'Separate DUO locations for the staatsexamen NT2')}
      ${row('Registering', 'Mijn Inburgering, and the information is on staatsexamensnt2.nl')}
      ${row('Parts', 'The same four language parts + KNM')}
      ${row('Duration', 'Longer: 110, 90, 100 and about 30 minutes')}
    </div>
  </div>
</div>

${factTwoIn('en', 'You take the kennisexamens and the language exams at level A2 at six exam locations: Amsterdam, Eindhoven, Rijswijk, Rotterdam, Utrecht and Zwolle. The language exams at level B1 and B2 are staatsexamens NT2; you take those at separate locations of DUO. You register through Mijn Inburgering.', [['inburgeren.nl — Examenplaatsen', SRC_PLAATSEN], ['inburgeren.nl — Aanmelden voor het examen', SRC_AANMELDEN]], CHECKED)}

${note('Please note: Zwolle is moving on 1 October 2026, and there are no exams there from 18 up to and including 30 September 2026. That affects the A2 locations. Always check your location in your oproep (exam invitation letter), not in a guide.')}

<h2 id="wie-doet-b1">Who takes the exams at B1?</h2>

<p>Not everyone. Your gemeente (municipality) decides after the brede intake and the
leerbaarheidstoets which leerroute (learning route) you follow, and the route decides your level.</p>

<div class="guide-cards">
  ${card(I_ROUTE, 'B1-route', 'The standard route under the Wet 2021. You take the language exams at level B1, within three years.')}
  ${card(I_ROUTE, 'Onderwijsroute', 'Mainly for young people who want to go to mbo, hbo or university. You reach B1 or higher.')}
  ${card(I_ROUTE, 'Z-route', 'You learn Dutch at level A1. You may take exams at A2, but you do not have to. So no B1.')}
</div>

<p>Are you doing your inburgering under the <strong>Wet 2013</strong>, the old act? Then your language
exams are at A2 or higher, and B1 is a choice, not an obligation.</p>

${factIn('en', 'The gemeente decides on the basis of the brede intake which learning route you follow. In the B1-route you take the language exams at level B1 within 3 years. The onderwijsroute is mainly for young people who want to go to mbo, hbo or university and leads to B1 or B2. In the Z-route you learn Dutch at language level A1 and you may take language exams at level A2, but you do not have to.', 'inburgeren.nl — U gaat inburgeren', SRC_ROUTES, CHECKED)}

<h2 id="de-vier-onderdelen">The four parts at B1</h2>

<p>The same four parts as at A2 — Lezen (reading), Luisteren (listening), Schrijven (writing) and
Spreken (speaking) — and all four longer. That extra time is not a present: the texts are longer and
you have to produce more yourself.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>Part</th><th>A2</th><th>B1</th></tr></thead>
  <tbody>
    <tr><td><strong>Lezen</strong></td><td>65 minutes</td><td>110 minutes</td></tr>
    <tr><td><strong>Luisteren</strong></td><td>45 minutes</td><td>90 minutes</td></tr>
    <tr><td><strong>Schrijven</strong></td><td>40 minutes, with pen and paper</td><td>100 minutes</td></tr>
    <tr><td><strong>Spreken</strong></td><td>35 minutes</td><td>about 30 minutes</td></tr>
  </tbody>
</table>
</div>

${factIn('en', 'DUO on the language exams: Lezen A2 takes 65 minutes and Lezen B1 110 minutes; Luisteren A2 takes 45 minutes and Luisteren B1 90 minutes; Schrijven A2 you do with pen and paper and it takes 40 minutes, Schrijven B1 takes 100 minutes; Spreken A2 takes 35 minutes and Spreken B1 about 30 minutes.', 'inburgeren.nl — Taalexamens A2, B1 en B2', SRC_TAALEXAMENS, CHECKED)}

<p><strong>We do not say how many questions there are.</strong> For A2 you can read that off DUO's
own practice exams; for B1 DUO does not publish it anywhere. Every site that promises you an exact
number of questions at B1 has made it up. What is available is on
<a href="${SRC_NT2}" target="_blank" rel="noopener">staatsexamensnt2.nl</a>.</p>

<div class="guide-cards">
  ${card(I_BOOK, 'Lezen', 'Longer, connected texts: a news item, a leaflet, an article. You have to find not only what it says, but also why it says it.')}
  ${card(I_HEADPHONES, 'Luisteren', 'Conversations and fragments at normal speed, with more speakers and more detours. You get almost twice as much time as at A2 — and you need it.')}
  ${card(I_PEN, 'Schrijven', 'On the computer, and longer than A2. You no longer fill in a form but write connected text: a letter, a message, a reply with a reason in it.')}
  ${card(I_MIC, 'Spreken', 'You record your answers, just as at A2 — but with longer turns. At B1 an answer of four words is not an answer.')}
</div>

${docentIn('en', 'The difference between A2 and B1 is not in the number of words you know. It is in <em>connecting</em>. At A2 you may say separate sentences: "I am not going. I am ill." At B1 you are expected to make one story out of it: "I am not coming tomorrow, because I am ill — I hope it will work next week." That is one sentence with three pieces in it, and you do not practise that by learning word lists by heart.')}

<h2 id="kosten-en-uitslag">What it costs and when you get your result</h2>

<p>Here we stay vague on purpose, and that is not laziness. The staatsexamen NT2 has its
<strong>own fee</strong>, separate from the €50 per part that DUO charges for the
inburgeringsexamens, and it changes. The same goes for the uitslagtermijn: DUO says "within 8 weeks"
for the kennisexamens and the language exams at A2, but that is not the same promise as for the
staatsexamen NT2.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">Check this yourself, before you register</p>
    <ul>
      <li>${I_CHECK}<span>The current examengeld (exam fee) is on <a href="${SRC_NT2_GELD}" target="_blank" rel="noopener">duo.nl — examengeld staatsexamen NT2</a></span></li>
      <li>${I_CHECK}<span>The organisation of the exam is described on <a href="${SRC_NT2}" target="_blank" rel="noopener">staatsexamensnt2.nl</a></span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Do not count on the A2 figures</p>
    <ul>
      <li>${I_X}<span>&euro;50 per part belongs to the inburgeringsexamens, not to the staatsexamen NT2</span></li>
      <li>${I_X}<span>&quot;Result within 8 weeks&quot; is DUO&rsquo;s promise for the kennisexamens and the language exams at A2</span></li>
      <li>${I_X}<span>If you plan your B1 on those figures, you are planning on the wrong ones</span></li>
    </ul>
  </div>
</div>

${note('Planning with a deadline? Count backwards from your <strong>result</strong>, not from your exam date — and not from today. For most people the queue before the exam is the problem, not the deadline itself.')}

${inlineCta('Put your own dates in a row', 'The timeline maker works out your registration and start dates from your own deadline. No DigiD, no BSN.', '/inburgering/tools/tijdlijn', 'Make your timeline')}

<h2 id="te-hoog">And if B1 turns out to be too high?</h2>

<p>That happens, and there is a way out — but only one, and with conditions. From the
<strong>B1-route</strong> you can, under conditions, <strong>move down (afschalen) to A2</strong>.
From the onderwijsroute or the Z-route that is not possible.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>At least 600 hours of language lessons</h3>
    <p>At a language school with a keurmerk (quality mark). Without those hours there is nothing to assess.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>You can show you did your best</h3>
    <p>Attendance, effort, results. Your school records this; the gemeente checks it.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>The gemeente decides</h3>
    <p>Not DUO and not your school. Ask for it at your klantmanager (case manager), and do not wait until your last months.</p>
  </div></div>
</div>

${factTwoIn('en', 'Moving down (afschalen) from B1 to A2 is only possible from the B1-route. For that you must have followed at least 600 course hours of NT2 at an institution with a keurmerk, and you must have made demonstrably sufficient effort. The gemeente checks that and decides.', [['Besluit inburgering 2021, artikel 5.5', SRC_BESLUIT55], ['inburgeren.nl — U gaat inburgeren', SRC_ROUTES]], CHECKED)}

${docentIn('en', 'Do not wait with this conversation until you have failed twice. I would rather have someone say after one year "I think B1 is not going to work" than that we find out in month 32. Moving down takes time — those 600 hours have to be there first, and after that the gemeente still has to look at it.')}

<h2 id="naturalisatie">B1 and your passport: be careful what you read</h2>

<p>A lot is written as if you need B1 to become Dutch. That is <strong>not the case at the
moment</strong>. For naturalisatie (naturalisation) the minimum is A2. Raising it to B1 is a
<em>wetsvoorstel</em> (a bill), not law in force.</p>

${factIn('en', 'For a residence permit for an indefinite period and for naturalisation you need an inburgeringsdiploma at level A2 at least. Raising that requirement to B1 is a bill (wetsvoorstel) and not law in force.', 'IND — Inburgering bij een sterkere verblijfsvergunning en naturalisatie', SRC_IND, CHECKED)}

<p>That your diploma states your level is correct: your inburgeringsdiploma shows whether you passed
at A2, B1 or B2, and you download it for free in Mijn Diploma's.</p>

${factIn('en', 'You can download your diploma in Mijn Diplomas. That is free. The diploma states at which level you passed the exams: A2, B1 or B2.', 'inburgeren.nl — Diploma', SRC_DIPLOMA, CHECKED)}

<h2 id="oefenen">Practising at B1</h2>

<p>On this site there are practice exams at B1 for <strong>Lezen, Schrijven and Spreken</strong>,
written and checked in the same way as the A2 exams. Luisteren at B1 is not there yet: there is no
reliable reference material for it, and then we prefer to make nothing up.</p>

<p>For Lezen at B1 there is a <strong>free practice exam</strong> of ten questions ready, without an
account. After every answer you see straight away why it is right or wrong.</p>

${inlineCta('Try B1 Lezen for free', 'Ten questions at level B1, with an explanation after every answer. No account needed.', '/oefenen', 'Start the free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>B1 is a <strong>staatsexamen NT2</strong>, not the A2 exam.</li>
  <li>Different locations, its own fee, its own uitslagtermijn.</li>
  <li>Duration: 110, 90, 100 and about 30 minutes.</li>
  <li>DUO does not publish the number of questions at B1.</li>
  <li>Moving down to A2: only from the B1-route, after 600 hours of lessons.</li>
  <li>Naturalisation now asks for <strong>A2</strong>, not B1.</li>
</ul>`,

  faq: [
  {
    q: 'Is the B1 exam the same exam as A2, only harder?',
    a: 'No. The language exam at A2 is the inburgeringsexamen; at B1 and B2 you take the staatsexamen NT2. That is a different exam, at different locations, with its own fee and its own uitslagtermijn. The parts have the same names and take longer: 110, 90, 100 and about 30 minutes.',
  },
  {
    q: 'How many questions are there in the Lezen exam at B1?',
    a: 'DUO does not publish that anywhere, and we do not make it up. For A2 you can read it off DUO\'s own practice exams; for B1 no such source exists. What is officially known about the staatsexamen NT2 is on staatsexamensnt2.nl.',
  },
  {
    q: 'Who decides whether I have to do A2 or B1?',
    a: 'Your gemeente, after the brede intake and the leerbaarheidstoets. In the B1-route you take the language exams at B1 within three years, in the onderwijsroute at B1 or higher, and in the Z-route you learn A1 and may take A2 exams. What applies to you is in your PIP.',
  },
  {
    q: 'Can I move down from B1 to A2?',
    a: 'Only from the B1-route, and under conditions. You must have followed at least 600 course hours of NT2 at an institution with a keurmerk and have made demonstrably sufficient effort. The gemeente checks that and decides about it, not DUO and not your school.',
  },
  {
    q: 'Do I need B1 to become Dutch?',
    a: 'At the moment, no. For naturalisation and for a residence permit for an indefinite period the minimum is A2. Raising that requirement to B1 is a bill and not yet law in force. Your diploma does state which level you passed: A2, B1 or B2.',
  },
  {
    q: 'What does the staatsexamen NT2 at B1 cost?',
    a: 'It has its own fee, separate from the €50 per part that applies to the inburgeringsexamens. Because that amount changes, it is not stated here: check the current examengeld on duo.nl under the staatsexamen NT2, before you register.',
  },
  ],
};

export default translation;
