/**
 * b1-examen — Arabic.
 *
 * A translation of the Dutch body in `../b1-examen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_BOOK, I_CHECK, I_HEADPHONES, I_MIC, I_PEN, I_ROUTE, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_AANMELDEN, SRC_BESLUIT55, SRC_DIPLOMA, SRC_IND, SRC_NT2, SRC_NT2_GELD, SRC_PLAATSEN, SRC_ROUTES, SRC_TAALEXAMENS, card, row } from '../b1-examen';

const translation: GuideLocale = {
  title: 'امتحان اللغة في المستوى B1: staatsexamen NT2 بوضوح',
  description: 'أنت في مسار B1. ما هو staatsexamen NT2، وكم تستغرق الأجزاء الأربعة في المستوى B1، وأين تؤدّيها، وماذا تفعل إذا تبيّن أن B1 مرتفع جدًا بالنسبة لك؟',
  breadcrumb: 'امتحان B1',
  dateLabel: '24 أغسطس 2026',
  eyebrow: 'امتحان اللغة',
  heroTitle: 'امتحان اللغة في المستوى B1',
  heroSubtitle: 'المستوى B1 ليس امتحان A2 نفسه بحجم أكبر. إنه امتحان آخر، لدى قسم آخر، وفي مواقع أخرى. هنا تجد ما يعنيه ذلك بالنسبة لك.',
  ctaTitle: 'تدرّب على امتحان في المستوى B1',
  ctaDesc: 'امتحان تجريبي مجاني في القراءة على المستوى B1، مع شرح بعد كل إجابة. بدون حساب.',
  ctaLabel: 'ابدأ الامتحان التجريبي المجاني',

  articleHtml: `
<h2 id="wat-is-b1">B1 هو staatsexamen NT2، وليس امتحان A2 بصيغة أكبر</h2>

<p>هذه أول نقطة يُساء فهمها. يظن الناس: لقد رأيتُ A2، وB1 هو الشيء نفسه لكن أصعب. هذا غير صحيح.
فامتحان الاندماج (inburgeringsexamen) في المستوى A2 وstaatsexamen NT2 في المستوى B1 هما
<strong>امتحانان مختلفان</strong>، من قسمين مختلفين داخل DUO، في مواقع مختلفة، ولكل منهما تعريفة
خاصة (tarief) ومهلة خاصة لإعلان النتيجة (uitslagtermijn).</p>

<div class="compare-2">
  <div class="compare-card">
    <div class="compare-head">
      <h3>inburgeringsexamen في المستوى A2</h3>
      <p class="compare-when">لمسار Z-route ولقانون Wet 2013</p>
    </div>
    <div class="compare-rows">
      ${row('أين', 'ستة مواقع امتحانية: Amsterdam وEindhoven وRijswijk وRotterdam وUtrecht وZwolle')}
      ${row('التسجيل', 'عبر Mijn Inburgering')}
      ${row('الأجزاء', 'القراءة والاستماع والكتابة والتحدث + KNM')}
      ${row('الكتابة', 'بالقلم والورق')}
    </div>
  </div>
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>Staatsexamen NT2 (المستويان B1 وB2)</h3>
      <p class="compare-when">لمسار B1-route ولمسار onderwijsroute</p>
    </div>
    <div class="compare-rows">
      ${row('أين', 'مواقع خاصة تابعة لـ DUO لامتحان staatsexamen NT2')}
      ${row('التسجيل', 'عبر Mijn Inburgering، والمعلومات موجودة على staatsexamensnt2.nl')}
      ${row('الأجزاء', 'أجزاء اللغة الأربعة نفسها + KNM')}
      ${row('المدة', 'أطول: 110 و90 و100 وحوالي 30 دقيقة')}
    </div>
  </div>
</div>

${factTwoIn('ar', 'امتحانات المعرفة وامتحانات اللغة في المستوى A2 تؤدّونها في ستة مواقع امتحانية: Amsterdam وEindhoven وRijswijk وRotterdam وUtrecht وZwolle. أما امتحانات اللغة في المستويين B1 وB2 فهي staatsexamens NT2؛ وتؤدّونها في مواقع خاصة تابعة لـ DUO. والتسجيل يتم عبر Mijn Inburgering.', [['inburgeren.nl — Examenplaatsen', SRC_PLAATSEN], ['inburgeren.nl — Aanmelden voor het examen', SRC_AANMELDEN]], CHECKED)}

${note('انتبه: موقع Zwolle ينتقل اعتبارًا من 1 أكتوبر 2026، ولا تُقام فيه امتحانات من 18 حتى 30 سبتمبر 2026. وهذا يخص مواقع A2. تحقّق دائمًا من موقعك في رسالة الاستدعاء (oproep) الخاصة بك، وليس في دليل.')}

<h2 id="wie-doet-b1">من يؤدّي الامتحانات في المستوى B1؟</h2>

<p>ليس الجميع. تحدّد بلديتك (gemeente) بعد المقابلة الشاملة (brede intake) واختبار القابلية للتعلّم
(leerbaarheidstoets) مسار التعلّم الذي تتبعه، والمسار يحدّد مستواك.</p>

<div class="guide-cards">
  ${card(I_ROUTE, 'B1-route', 'المسار القياسي بموجب Wet 2021. تؤدّي امتحانات اللغة في المستوى B1، خلال ثلاث سنوات.')}
  ${card(I_ROUTE, 'Onderwijsroute', 'خاصةً للشباب الذين يريدون الالتحاق بـ mbo أو hbo أو الجامعة. تصل إلى B1 أو أعلى.')}
  ${card(I_ROUTE, 'Z-route', 'تتعلّم الهولندية في المستوى A1. يجوز لك أداء امتحانات في المستوى A2، لكن ذلك ليس إلزاميًا. أي لا B1.')}
</div>

<p>هل تندمج بموجب <strong>Wet 2013</strong>، القانون القديم؟ إذًا تكون امتحانات اللغة لديك في المستوى A2 أو
أعلى، ويكون B1 خيارًا لا واجبًا.</p>

${factIn('ar', 'تحدّد البلدية (gemeente) بناءً على المقابلة الشاملة (brede intake) مسار التعلّم الذي تتبعونه. في مسار B1-route تؤدّون امتحانات اللغة في المستوى B1 خلال 3 سنوات. ومسار onderwijsroute مخصّص خاصةً للشباب الذين يريدون الالتحاق بـ mbo أو hbo أو الجامعة، ويؤدّي إلى B1 أو B2. وفي مسار Z-route تتعلّمون الهولندية في المستوى اللغوي A1 ويجوز لكم أداء امتحانات اللغة في المستوى A2، لكن ذلك ليس إلزاميًا.', 'inburgeren.nl — U gaat inburgeren', SRC_ROUTES, CHECKED)}

<h2 id="de-vier-onderdelen">الأجزاء الأربعة في المستوى B1</h2>

<p>الأجزاء الأربعة نفسها كما في A2، وكلها أطول. هذا الوقت الإضافي ليس هدية: النصوص أطول وعليك أن
تصوغ المزيد بنفسك.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>الجزء</th><th>A2</th><th>B1</th></tr></thead>
  <tbody>
    <tr><td><strong>القراءة (Lezen)</strong></td><td>65 دقيقة</td><td>110 دقيقة</td></tr>
    <tr><td><strong>الاستماع (Luisteren)</strong></td><td>45 دقيقة</td><td>90 دقيقة</td></tr>
    <tr><td><strong>الكتابة (Schrijven)</strong></td><td>40 دقيقة، بالقلم والورق</td><td>100 دقيقة</td></tr>
    <tr><td><strong>التحدث (Spreken)</strong></td><td>35 دقيقة</td><td>حوالي 30 دقيقة</td></tr>
  </tbody>
</table>
</div>

${factIn('ar', 'DUO عن امتحانات اللغة: Lezen في A2 يستغرق 65 دقيقة وLezen في B1 يستغرق 110 دقيقة؛ Luisteren في A2 يستغرق 45 دقيقة وLuisteren في B1 يستغرق 90 دقيقة؛ Schrijven في A2 تؤدّونه بالقلم والورق ويستغرق 40 دقيقة، وSchrijven في B1 يستغرق 100 دقيقة؛ Spreken في A2 يستغرق 35 دقيقة وSpreken في B1 يستغرق حوالي 30 دقيقة.', 'inburgeren.nl — Taalexamens A2, B1 en B2', SRC_TAALEXAMENS, CHECKED)}

<p><strong>أما عدد الأسئلة فلا نذكره.</strong> بالنسبة إلى A2 يمكنك استنتاجه من امتحانات التدريب
الخاصة بـ DUO؛ أما بالنسبة إلى B1 فلا تنشر DUO ذلك في أي مكان. كل موقع يعدك بعدد دقيق للأسئلة في
B1 يكون قد اختلقه. أما ما هو منشور فعلًا فتجده على
<a href="${SRC_NT2}" target="_blank" rel="noopener">staatsexamensnt2.nl</a>.</p>

<div class="guide-cards">
  ${card(I_BOOK, 'القراءة (Lezen)', 'نصوص أطول ومترابطة: خبر صحفي، منشور إرشادي، مقال. عليك ألا تجد ما هو مكتوب فحسب، بل أيضًا لماذا كُتب.')}
  ${card(I_HEADPHONES, 'الاستماع (Luisteren)', 'محادثات ومقاطع بسرعة عادية، مع عدد أكبر من المتحدثين والمزيد من الالتفاف. تحصل على ضِعف الوقت تقريبًا مقارنةً بـ A2 — وأنت بحاجة إليه.')}
  ${card(I_PEN, 'الكتابة (Schrijven)', 'على الكمبيوتر، وأطول من A2. لم تعد تملأ استمارة، بل تكتب نصًا مترابطًا: رسالة، أو خبرًا، أو ردًّا مع ذكر السبب.')}
  ${card(I_MIC, 'التحدث (Spreken)', 'تسجّل صوتك، تمامًا كما في A2 — لكن بأدوار كلام أطول. إجابة من أربع كلمات ليست إجابة في B1.')}
</div>

${docentIn('ar', 'الفرق بين A2 وB1 لا يكمن في عدد الكلمات التي تعرفها، بل في <em>الربط</em>. في A2 يجوز لك قول جمل منفصلة: "Ik ga niet. Ik ben ziek." أما في B1 فيُتوقّع منك أن تصنع منها حكاية واحدة: "Ik kom morgen niet, omdat ik ziek ben — ik hoop dat het volgende week wel lukt." هذه جملة واحدة فيها ثلاثة أجزاء، ولا تتدرّب على ذلك بحفظ الكلمات عن ظهر قلب.')}

<h2 id="kosten-en-uitslag">كم يكلّف ومتى تصلك النتيجة</h2>

<p>هنا نبقى غامضين عن قصد، وهذا ليس كسلًا. فلـ staatsexamen NT2 <strong>تعريفة خاصة به</strong>،
منفصلة عن مبلغ €50 لكل جزء الذي تتقاضاه DUO عن امتحانات الاندماج، وهي تتغيّر. والأمر نفسه ينطبق
على مهلة النتيجة: تذكر DUO "خلال 8 أسابيع" لامتحانات المعرفة ولامتحانات اللغة في المستوى A2،
لكن ذلك ليس الوعد نفسه الخاص بـ staatsexamen NT2.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">تحقّق من هذا بنفسك، قبل أن تسجّل</p>
    <ul>
      <li>${I_CHECK}<span>رسوم الامتحان الحالية موجودة على <a href="${SRC_NT2_GELD}" target="_blank" rel="noopener">duo.nl — examengeld staatsexamen NT2</a></span></li>
      <li>${I_CHECK}<span>تنظيم الامتحان موضّح على <a href="${SRC_NT2}" target="_blank" rel="noopener">staatsexamensnt2.nl</a></span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">لا تحسب بأرقام A2</p>
    <ul>
      <li>${I_X}<span>مبلغ €50 لكل جزء يخص امتحانات الاندماج، وليس staatsexamen NT2</span></li>
      <li>${I_X}<span>"النتيجة خلال 8 أسابيع" هو وعد DUO الخاص بامتحانات المعرفة وامتحانات اللغة في المستوى A2</span></li>
      <li>${I_X}<span>إذا خطّطت لـ B1 بناءً على تلك الأرقام، فأنت تخطّط بالأرقام الخاطئة</span></li>
    </ul>
  </div>
</div>

${note('هل تخطّط وأمامك موعد نهائي؟ احسب رجوعًا من <strong>نتيجتك</strong>، لا من تاريخ امتحانك — ولا من اليوم. طابور الانتظار قبل الامتحان هو المشكلة عند معظم الناس، وليس الموعد النهائي نفسه.')}

${inlineCta('رتّب تواريخك الخاصة', 'أداة الجدول الزمني تحسب لك تواريخ التسجيل والبدء انطلاقًا من مهلتك. بدون DigiD وبدون BSN.', '/inburgering/tools/tijdlijn', 'أنشئ جدولك الزمني')}

<h2 id="te-hoog">وماذا لو تبيّن أن B1 مرتفع جدًا؟</h2>

<p>هذا يحدث، وهناك مخرج — لكنه واحد فقط، وبشروط. من <strong>مسار B1-route</strong> يمكنك بشروط
<strong>النزول إلى A2 (afschalen)</strong>. أما من onderwijsroute أو Z-route فذلك غير ممكن.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>600 ساعة درس لغة على الأقل</h3>
    <p>لدى مدرسة لغة حاصلة على علامة جودة (keurmerk). بدون تلك الساعات لا يوجد شيء يمكن تقييمه.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>إثبات أنك بذلت جهدًا كافيًا</h3>
    <p>الحضور والاجتهاد والنتائج. مدرستك تسجّل ذلك، والبلدية (gemeente) تتحقّق منه.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>البلدية هي التي تقرّر</h3>
    <p>ليست DUO ولا مدرستك. قدّم الطلب لدى مدير ملفك (klantmanager)، ولا تنتظر بذلك حتى أشهرك الأخيرة.</p>
  </div></div>
</div>

${factTwoIn('ar', 'النزول (afschalen) من B1 إلى A2 ممكن فقط انطلاقًا من مسار B1-route. ولذلك يجب أن تكونوا قد اتّبعتم 600 ساعة درس NT2 على الأقل لدى مؤسسة حاصلة على علامة جودة (keurmerk)، وأن تكونوا قد بذلتم جهدًا كافيًا يمكن إثباته. والبلدية (gemeente) تتحقّق من ذلك وتقرّر.', [['Besluit inburgering 2021, artikel 5.5', SRC_BESLUIT55], ['inburgeren.nl — U gaat inburgeren', SRC_ROUTES]], CHECKED)}

${docentIn('ar', 'لا تنتظر بهذا الحديث حتى ترسب مرتين. أفضّل أن يقول أحدهم بعد سنة "أظن أن B1 لن ينجح معي" على أن نكتشف ذلك في الشهر 32. النزول إلى A2 يستغرق وقتًا — يجب أولًا أن تكون تلك الـ 600 ساعة موجودة، وبعد ذلك على البلدية أن تنظر في الأمر.')}

<h2 id="naturalisatie">B1 وجواز سفرك: انتبه لما تقرأه</h2>

<p>يُكتب الكثير وكأنك بحاجة إلى B1 لتصبح هولنديًا. هذا <strong>ليس صحيحًا في الوقت الحالي</strong>.
فللتجنّس (naturalisatie) يسري المستوى A2 كحد أدنى. ورفع هذا الشرط إلى B1 هو <em>مشروع قانون
(wetsvoorstel)</em>، وليس قانونًا نافذًا.</p>

${factIn('ar', 'للحصول على تصريح إقامة لمدة غير محدودة وللتجنّس تحتاجون إلى شهادة اندماج (inburgeringsdiploma) في المستوى A2 على الأقل. ورفع هذا الشرط إلى B1 هو مشروع قانون وليس قانونًا نافذًا.', 'IND — Inburgering bij een sterkere verblijfsvergunning en naturalisatie', SRC_IND, CHECKED)}

<p>أما أن شهادتك تذكر مستواك فهذا صحيح: على شهادة الاندماج الخاصة بك مكتوب هل حصلت على A2 أو B1 أو
B2، وتنزّلها مجانًا في Mijn Diploma's.</p>

${factIn('ar', 'يمكنكم تنزيل شهادتكم في Mijn Diplomas. وهذا مجاني. وعلى الشهادة مكتوب في أي مستوى اجتزتم الامتحانات: A2 أو B1 أو B2.', 'inburgeren.nl — Diploma', SRC_DIPLOMA, CHECKED)}

<h2 id="oefenen">التدرّب على المستوى B1</h2>

<p>على هذا الموقع توجد امتحانات تدريبية في المستوى B1 لـ <strong>القراءة والكتابة والتحدث</strong>،
مكتوبة ومراجَعة بالطريقة نفسها المتّبعة في امتحانات A2. أما الاستماع في المستوى B1 فغير متوفر بعد:
لا توجد مادة مرجعية موثوقة لذلك، وفي هذه الحالة نفضّل ألا نختلق شيئًا.</p>

<p>للقراءة في المستوى B1 يوجد <strong>امتحان تجريبي مجاني</strong> من عشرة أسئلة، بدون حساب. بعد كل
إجابة ترى فورًا لماذا هي صحيحة أو خاطئة.</p>

${inlineCta('جرّب B1 القراءة مجانًا', 'عشرة أسئلة في المستوى B1، مع شرح بعد كل إجابة. لا حاجة إلى حساب.', '/oefenen', 'ابدأ الامتحان التجريبي المجاني')}
`,

  sidebarHtml: `
<p><strong>باختصار</strong></p>
<ul>
  <li>B1 هو <strong>staatsexamen NT2</strong>، وليس امتحان A2.</li>
  <li>مواقع أخرى، وتعريفة خاصة، ومهلة نتيجة خاصة.</li>
  <li>المدة: 110 و90 و100 وحوالي 30 دقيقة.</li>
  <li>عدد الأسئلة في B1 لا تنشره DUO.</li>
  <li>النزول إلى A2: فقط من مسار B1-route، بعد 600 ساعة درس.</li>
  <li>التجنّس يتطلب الآن <strong>A2</strong>، وليس B1.</li>
</ul>`,

  faq: [
  {
    q: 'هل امتحان B1 هو امتحان A2 نفسه لكن أصعب؟',
    a: 'لا. امتحان اللغة في المستوى A2 هو inburgeringsexamen؛ أما في B1 وB2 فتؤدّي staatsexamen NT2. وهو امتحان آخر، في مواقع أخرى، بتعريفة خاصة ومهلة نتيجة خاصة. أسماء الأجزاء هي نفسها لكن مدتها أطول: 110 و90 و100 وحوالي 30 دقيقة.',
  },
  {
    q: 'كم عدد الأسئلة في امتحان القراءة في المستوى B1؟',
    a: 'لا تنشر DUO ذلك في أي مكان، ونحن لا نختلقه. بالنسبة إلى A2 يمكنك استنتاجه من امتحانات التدريب الخاصة بـ DUO؛ أما بالنسبة إلى B1 فلا يوجد مصدر كهذا. وما هو معروف رسميًا عن staatsexamen NT2 تجده على staatsexamensnt2.nl.',
  },
  {
    q: 'من يحدّد هل عليّ أداء A2 أم B1؟',
    a: 'بلديتك (gemeente)، بعد المقابلة الشاملة (brede intake) واختبار القابلية للتعلّم (leerbaarheidstoets). في مسار B1-route تؤدّي امتحانات اللغة خلال ثلاث سنوات في المستوى B1، وفي onderwijsroute في B1 أو أعلى، وفي Z-route تتعلّم A1 ويجوز لك أداء امتحانات A2. وما ينطبق عليك مذكور في خطتك PIP.',
  },
  {
    q: 'هل يمكنني النزول من B1 إلى A2؟',
    a: 'فقط انطلاقًا من مسار B1-route، وبشروط. يجب أن تكون قد اتّبعت 600 ساعة درس NT2 على الأقل لدى مؤسسة حاصلة على علامة جودة (keurmerk) وأن تكون قد بذلت جهدًا كافيًا يمكن إثباته. والبلدية (gemeente) تتحقّق من ذلك وتقرّر بشأنه، لا DUO ولا مدرستك.',
  },
  {
    q: 'هل أحتاج إلى B1 لأصبح هولنديًا؟',
    a: 'في الوقت الحالي لا. للتجنّس ولتصريح الإقامة لمدة غير محدودة يسري المستوى A2 كحد أدنى. ورفع هذا الشرط إلى B1 هو مشروع قانون (wetsvoorstel) وليس بعد قانونًا نافذًا. أما على شهادتك فمكتوب أي مستوى اجتزته: A2 أو B1 أو B2.',
  },
  {
    q: 'كم يكلّف staatsexamen NT2 في المستوى B1؟',
    a: 'له تعريفة خاصة، منفصلة عن مبلغ €50 لكل جزء الذي يسري على امتحانات الاندماج. ولأن هذا المبلغ يتغيّر فهو غير مذكور هنا: تحقّق من رسوم الامتحان الحالية على duo.nl في صفحة staatsexamen NT2، قبل أن تسجّل.',
  },
  ],
};

export default translation;
