/**
 * boete-en-termijn — English.
 *
 * A translation of the Dutch body in `../boete-en-termijn.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_CLIPBOARD, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_BOETE, SRC_EXTRATIJD, SRC_KENNIS, SRC_NIEUWS, SRC_RVS, SRC_WET11, price } from '../boete-en-termijn';

const translation: GuideLocale = {
  title: 'Inburgering deadline and fine: how much time do you have?',
  description: 'Your inburgering deadline is three years, but waiting times eat into it. How the term runs, when you get extra time, and who can no longer be fined.',
  breadcrumb: 'Term and fine',
  dateLabel: '23 August 2026',
  eyebrow: 'Term',
  heroTitle: 'Your term and the fine',
  heroSubtitle: 'Three years sounds like a lot of time. But there are months between registering and your result, and those months count. Here is how your term really works — and what happens if you do not manage it.',
  ctaTitle: 'Do not lose months to a resit',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after each answer. No account needed.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="geen-boete">First the most important thing: asielstatushouders do not get a fine</h2>

<div class="verdict ok">
  <p class="verdict-answer">Are you an asielstatushouder (holder of an asylum residence permit)? Then you cannot get a fine.</p>
  <p>The Raad van State — the highest administrative court in the Netherlands — ruled on 9 July 2025 that asielstatushouders may not be fined for completing their inburgering (civic integration) too late. DUO may also not reclaim their loan. You do not have to do anything yourself for this.</p>
</div>

<p>DUO had already paused the fines and the reclaiming of loans for this group in February 2025, after a ruling by the European Court of Justice. The ruling of the Raad van State made that final.</p>

${factTwoIn('en', 'The Raad van State ruled on 9 July 2025 that asielstatushouders may not be fined for completing their inburgering too late and that their loan may not be reclaimed; DUO had already paused those fines and reclaims in February 2025. DUO\'s own page says: "Asielstatushouders krijgen nooit een boete." (Asielstatushouders never get a fine.)', [['Rijksoverheid — Uitspraak Raad van State', SRC_RVS], ['inburgeren.nl — Boete', SRC_BOETE]], CHECKED)}

${docentIn('en', 'I notice that this fear dominates everything for many of my students, even though for a large part of them it is no longer justified. Are you not sure which group you are in? Look in your letter from DUO or ask your klantmanager (case manager) at the gemeente (municipality). That is one question, and it can save you months of stress.')}

<h2 id="termijn">How long is your term?</h2>

<p>Under the Wet inburgering 2021 you have <strong>three years</strong>. But the start date is more precise than people think: the term starts on the day <strong>after the dagtekening (date of issue) of your first PIP</strong> — the personal plan that the gemeente makes with you.</p>

<p>Two things follow from that:</p>

<ul>
  <li>Not the day you arrived in the Netherlands, and not the day you got your residence permit. The day after the date on your first PIP.</li>
  <li>If your PIP is <strong>revised</strong> later, the term does not start again. The start date stays that of the first PIP.</li>
</ul>

${factIn('en', 'The inburgering term is three years and starts on the day after the dagtekening of the first persoonlijk plan inburgering en participatie (PIP). A revision of the PIP does not move that start date.', 'Wet inburgering 2021, artikel 11', SRC_WET11, CHECKED)}

${note('Are you doing your inburgering under the <strong>Wet inburgering 2013</strong>? Then different rules and a different start date apply. What applies to you is in the letter from DUO and in Mijn Inburgering. Do not go by what a friend with a different year on their residence permit experienced.')}

<h2 id="wachttijden">The trap: the queue, not the deadline</h2>

<p>This is where people run into trouble, and it is almost never because they took too long to learn. It is the sum of the waiting times.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Registering takes weeks</h3>
    <p>Between your registration and the first free exam date there are often more than six weeks.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>The result takes weeks</h3>
    <p>Normally 8 weeks for the A2 language exams and the kennisexamens (knowledge exams).</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>For Schrijven and Spreken it is longer at the moment</h3>
    <p>DUO reported on 31 July 2026 that Spreken A2 and Schrijven A2 can take up to 16 weeks, with an automatic six-month extension for anyone who runs into trouble because of this.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>And then a resit starts again at step 1</h3>
    <p>Register, wait, exam, wait. Anyone who gambles on the last months has no room left for a second attempt.</p>
  </div></div>
</div>

<p>The practical conclusion: <strong>count back from your end date, not forward from today.</strong> Subtract the result period from your end date, and then about another seven weeks for registering. What is left is your real final registration date — and that is months earlier than the date in your letter.</p>

${factIn('en', 'DUO reported on 31 July 2026 that marking the exams Spreken A2 and Schrijven A2 takes a maximum of 16 weeks at that moment. Anyone who runs into trouble with the inburgering term because of this automatically gets a six-month extension.', 'inburgeren.nl — Nieuwsbericht 31-07-2026', SRC_NIEUWS, CHECKED)}

${inlineCta('Work out your own dates', 'The timeline maker calculates, for each exam part, the latest date you can register to stay within your term.', '/oefenen', 'Start practising for free')}

<h2 id="extra-tijd">When do you get extra time?</h2>

<p>If you do not manage it within the term, you can in certain situations apply to DUO for an extension. These are situations that DUO itself names.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">Can be a reason for extra time</p>
    <ul>
      <li>${I_CHECK}<span>You first had to learn to read and write (alfabetisering, literacy training)</span></li>
      <li>${I_CHECK}<span>You are following a course of study</span></li>
      <li>${I_CHECK}<span>Illness</span></li>
      <li>${I_CHECK}<span>A death in the family</span></li>
      <li>${I_CHECK}<span>Giving birth</span></li>
      <li>${I_CHECK}<span>Homelessness, or staying in an institution</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Important to know</p>
    <ul>
      <li>${I_X}<span>In one period you can get extra time <strong>only once</strong> — even if several situations apply at the same time</span></li>
      <li>${I_X}<span>On that page DUO names <strong>no fixed length of extension</strong>. Numbers you read elsewhere cannot be substantiated.</span></li>
      <li>${I_X}<span>An application is not an approval. Never plan on an extension that has not been granted yet.</span></li>
    </ul>
  </div>
</div>

${factIn('en', 'DUO names as situations that can give extra time, among others: first learning to read and write, following a course of study, illness, a death in the family, giving birth, homelessness and staying in an institution. "U kunt in een periode maar 1 keer extra tijd krijgen" (In one period you can only get extra time once), even if several situations apply at the same time.', 'inburgeren.nl — Extra tijd', SRC_EXTRATIJD, CHECKED)}

${docentIn('en', 'Apply for extra time as soon as you know you are not going to manage it, not in the last month. And keep taking exams in the meantime. The worst scenario is that you stop because you expect the extension to come, and then it is refused.')}

<h2 id="boete">The fine: amounts and consequences</h2>

<p>If you are <strong>not</strong> an asielstatushouder — you came to the Netherlands for your partner or your family, for example — then you can get a fine if you do not complete your inburgering on time and you have no right to extra time. These are the maximum amounts.</p>

<div class="price-list">
  ${price(I_CLIPBOARD, 'Leerroute not completed', 'Wet inburgering 2021', 'max. &euro;1,000')}
  ${price(I_CLIPBOARD, 'PVT not completed', 'Wet inburgering 2021', '&euro;340')}
  ${price(I_CLIPBOARD, 'MAP not completed', 'Wet inburgering 2021', '&euro;340')}
  ${price(I_CLIPBOARD, 'No inburgeringsdiploma', 'Wet inburgering 2013', 'max. &euro;1,250')}
  ${price(I_CLIPBOARD, 'PVT not signed', 'Wet inburgering 2013', '&euro;340')}
</div>

<p>A fine is not the end of your inburgering. You get <strong>extra time</strong> with it to still finish it. How much depends on what you have already passed or how many lesson hours you have followed: that runs from six months to two years.</p>

${factIn('en', 'For other people with an inburgering obligation, under the Wet 2021 there is a maximum fine of €1,000 for the leerroute and €340 for the PVT and for the MAP; under the Wet 2013 a maximum of €1,250 for the inburgeringsdiploma and €340 for the PVT. After a fine, the person gets extra time to still complete their inburgering, depending on exams passed or lesson hours followed.', 'inburgeren.nl — Boete', SRC_BOETE, CHECKED)}

<h3>The PVT has its own term</h3>

<p>Watch out for this, because it is a separate clock: under the <strong>Wet 2013</strong> you have only <strong>one year</strong> to sign the participatieverklaring (participation statement), counted from your registration with the gemeente. If you do not manage that and it is your own fault, a fine of &euro;340 follows and you can also no longer borrow from DUO. Under the <strong>Wet 2021</strong> you have three years for it.</p>

${factIn('en', 'Under the Wet inburgering 2021 you have three years to sign the participatieverklaring. Under the Wet inburgering 2013 it is one year from the registration with the gemeente; anyone who does not manage this through their own fault gets a fine of €340 and can no longer borrow from DUO.', 'inburgeren.nl — Kennisexamens en PVT', SRC_KENNIS, CHECKED)}

<h2 id="wat-nu">What do you do if you are in trouble?</h2>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Look up your end date</h3>
    <p>It is in Mijn Inburgering and in your PIP. Work from that date, not from a feeling.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Call your klantmanager at the gemeente</h3>
    <p>They know your file, and can think along with you about your route, your lessons and a possible application.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Apply for extra time if you have a reason for it</h3>
    <p>On time, with evidence, and at DUO. Do not wait until the last month.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>In the meantime, register for the part that is closest</h3>
    <p>One part you have passed always counts, even if the rest does not work out — and it counts in the assessment of whether you have done your best.</p>
  </div></div>
</div>

${note('Do you get a letter with a fine or a decision you do not agree with? It states a <strong>bezwaartermijn</strong> (period for objecting), usually six weeks. Respond within that period, even if you do not have everything in order yet. You can get free help with an objection at Het Juridisch Loket or from the sociaal raadslieden (social counsellors) of your gemeente.')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>Since 2025 asielstatushouders never get a fine.</li>
  <li>The term is 3 years, from the day after the date on your first PIP.</li>
  <li>Count back: registering and the result together take months.</li>
  <li>Extra time is possible, but only once in one period.</li>
  <li>Fine Wet 2021: max. &euro;1,000 leerroute, &euro;340 PVT, &euro;340 MAP.</li>
</ul>`,

  faq: [
  {
    q: 'How long is the inburgering term?',
    a: 'Under the Wet inburgering 2021 it is three years. The term starts on the day after the dagtekening of your first PIP, the personal plan that the gemeente makes with you. If your PIP is revised later, that start date does not move.',
  },
  {
    q: 'Do I get a fine if I do not complete my inburgering on time?',
    a: 'If you are an asielstatushouder, no: the Raad van State ruled on 9 July 2025 that DUO may not give you a fine and may not reclaim your loan. Other people with an inburgering obligation can get a fine if they have no right to extra time — a maximum of €1,000 for the leerroute under the 2021 act, and €340 for the PVT or the MAP.',
  },
  {
    q: 'Can I get an extension of my term?',
    a: 'In certain situations you can, for example if you first had to learn to read and write, in case of illness, giving birth, a death in the family or homelessness. You apply for it at DUO. Note: in one period you can only get extra time once, and DUO names no fixed length of extension.',
  },
  {
    q: 'When is the latest I should register for my last exam?',
    a: 'Much earlier than you think. Subtract the result period from your end date — normally 8 weeks, and for Schrijven A2 and Spreken A2 up to 16 weeks at the moment — and then about another seven weeks for registering on top of that. What is left is your real final registration date.',
  },
  {
    q: 'What happens after a fine?',
    a: 'The inburgering obligation stays. With the fine you get extra time to still complete it; how much depends on which exams you have already passed or how many lesson hours you have followed, and that runs from six months to two years. If you do not agree with the decision, you can object within the bezwaartermijn.',
  },
  {
    q: 'How much time do I have for the participatieverklaring?',
    a: 'Under the Wet inburgering 2021 three years. Under the Wet inburgering 2013 only one year, counted from your registration with the gemeente. If you do not manage that through your own fault, a fine of €340 follows and you can no longer borrow from DUO.',
  },
  ],
};

export default translation;
