/**
 * geschiedenis-en-geografie — Arabic.
 *
 * A translation of the Dutch body in `../geschiedenis-en-geografie.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_BOOK, I_HOME, I_LANDMARK, I_ROUTE, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_CANON, SRC_CBS, SRC_EINDTERMEN, SRC_KONINKLIJK, SRC_PROVINCIES, SRC_WATER, card, row } from '../geschiedenis-en-geografie';

const translation: GuideLocale = {
  title: 'KNM: تاريخ هولندا وجغرافيتها',
  description: 'الخطوط الكبرى لتاريخ هولندا وموقع المقاطعات والمدن والمياه والأعياد الوطنية. شرح مبسّط وواضح لموضوع KNM الخامس: التاريخ والجغرافيا للامتحان.',
  breadcrumb: 'التاريخ والجغرافيا',
  dateLabel: '23 أغسطس 2026',
  eyebrow: 'موضوع KNM رقم 5',
  heroTitle: 'التاريخ والجغرافيا',
  heroSubtitle: 'أين يقع كل شيء، وكيف صارت هولندا على ما هي عليه؟ هذا الموضوع لا يطلب منك قائمة تواريخ، لكنه يطلب أن تعرف الخطوط الكبرى وأن تستطيع قراءة الخريطة.',
  ctaTitle: 'تدرّب على موضوع التاريخ والجغرافيا',
  ctaDesc: 'امتحان تجريبي مجاني من عشرة أسئلة، مع شرح بعد كل إجابة. بدون حساب.',
  ctaLabel: 'ابدأ امتحانًا تجريبيًا مجانيًا',

  articleHtml: `
<h2 id="wat-vraagt-knm">ماذا يطلب KNM في هذا الموضوع؟</h2>

<p>هدفان نهائيان (eindtermen). انتبه جيدًا لصياغتهما — فهي تقول كل شيء عمّا يجب أن تكون قادرًا عليه.</p>

<div class="compare-rows">
  ${row('5.1', 'التعمّق في تاريخ هولندا')}
  ${row('5.2', '<strong>استخدام</strong> المعرفة الجغرافية بهولندا')}
</div>

<p>في التاريخ المسألة هي <em>التعمّق</em>: فهم الخطوط الكبرى، وإدراك لماذا بعض الأمور هنا على ما هي عليه. وفي الجغرافيا المسألة هي <em>الاستخدام</em>: أن تقرأ الخريطة، وتعرف أين أنت، وتفهم لماذا تختلف رحلة بالقطار من Groningen إلى Maastricht عن رحلة من Amsterdam إلى Utrecht.</p>

${factIn('ar', 'الأهداف النهائية لـ KNM في موضوع التاريخ والجغرافيا هي: التعمّق في تاريخ هولندا، واستخدام المعرفة الجغرافية بهولندا.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

${docentIn('ar', 'هذا هو الموضوع الذي يحفظ فيه الدارسون بأشد قوة ويستفيدون منه بأقل قدر. لن يأتي سؤال "في أي سنة بدأت حرب الثمانين عامًا". لكن سيأتي سؤال عن شخص يريد إجازة في 5 مايو، أو شخص عليه أن يذهب من Rotterdam إلى Zeeland. تعلّم الخطوط، لا القوائم.')}

<h2 id="geografie">البلد: الماء والمقاطعات والمدن</h2>

<p>هولندا بلد صغير، كثيف السكان، وجزء كبير منه منخفض. نحو ربع البلاد يقع تحت مستوى سطح البحر، ولولا السدود (dijken) والكثبان الرملية ومحطات الضخ لغُمر جزء كبير منه بالماء. لذلك فالماء هنا ليس أمرًا ثانويًا بل سياسة حكومية: هناك <strong>waterschappen</strong> (هيئات المياه) لا تُعنى إلا بذلك، وتدفع لها ضريبة منفصلة وتصوّت لها في انتخابات منفصلة.</p>

${factIn('ar', 'جزء كبير من هولندا منخفض، وتحميه السدود والكثبان والحواجز المائية. تتولى waterschappen بالاشتراك مع الدولة الحماية من الفيضانات وإدارة المياه.', 'Rijksoverheid — Water en veiligheid', SRC_WATER, CHECKED)}

<h3>المقاطعات الاثنتا عشرة</h3>

<p>في هولندا اثنتا عشرة مقاطعة (provincies). لكل مقاطعة عاصمة وإدارة مقاطعة وطابع خاص. هذه هي القائمة، من الشمال إلى الجنوب.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>المقاطعة</th><th>العاصمة</th></tr></thead>
  <tbody>
    <tr><td><strong>Groningen</strong></td><td>Groningen</td></tr>
    <tr><td><strong>Friesland</strong> (Frysl&acirc;n)</td><td>Leeuwarden</td></tr>
    <tr><td><strong>Drenthe</strong></td><td>Assen</td></tr>
    <tr><td><strong>Overijssel</strong></td><td>Zwolle</td></tr>
    <tr><td><strong>Flevoland</strong></td><td>Lelystad</td></tr>
    <tr><td><strong>Gelderland</strong></td><td>Arnhem</td></tr>
    <tr><td><strong>Utrecht</strong></td><td>Utrecht</td></tr>
    <tr><td><strong>Noord-Holland</strong></td><td>Haarlem</td></tr>
    <tr><td><strong>Zuid-Holland</strong></td><td>Den Haag</td></tr>
    <tr><td><strong>Zeeland</strong></td><td>Middelburg</td></tr>
    <tr><td><strong>Noord-Brabant</strong></td><td>'s-Hertogenbosch</td></tr>
    <tr><td><strong>Limburg</strong></td><td>Maastricht</td></tr>
  </tbody>
</table>
</div>

${note('انتبه إلى أمرين كثيرًا ما يقع فيهما الخطأ. <strong>Amsterdam هي عاصمة هولندا، لكن الحكومة والبرلمان مقرّهما في Den Haag.</strong> و<strong>Flevoland لم تكن موجودة قبل مئة سنة</strong>: هذه المقاطعة قاع بحر جُفّف.')}

<h3>أين يعيش معظم الناس؟</h3>

<p>في الغرب. المدن الكبرى الأربع — <strong>Amsterdam وRotterdam وDen Haag وUtrecht</strong> — تقع قريبة من بعضها في المنطقة التي تُسمّى <strong>Randstad</strong>. هناك يعيش ويعمل الغالبية العظمى من الناس، وهناك أيضًا معظم فرص العمل وأغلى المساكن.</p>

<div class="guide-cards">
  ${card(I_HOME, 'Amsterdam', 'العاصمة. القنوات المائية والسياحة وكثير من الشركات الدولية، ومطار Schiphol قريب منها.')}
  ${card(I_ROUTE, 'Rotterdam', 'أكبر ميناء في أوروبا. مدينة حديثة، قُصفت بشدة في الحرب ثم أُعيد بناؤها.')}
  ${card(I_LANDMARK, 'Den Haag', 'الحكومة والبرلمان والملك يعملون هنا. وهي أيضًا مدينة القضاء الدولي.')}
  ${card(I_BOOK, 'Utrecht', 'في وسط البلاد وهي عقدة شبكة السكك الحديدية. من Utrecht تصل إلى كل مكان.')}
</div>

<p>وكلما ابتعدت عن Randstad — Groningen وFriesland وDrenthe وZeeland وLimburg — كان الجو أهدأ، والمساكن أرخص، والمسافات أطول. وهذه معلومة عملية لمعظم المشاركين في الاندماج: مكان سكنك يحدّد كم يجب أن تسافر إلى العمل وإلى المدرسة وإلى موقع الامتحان.</p>

${factTwoIn('ar', 'في هولندا اثنتا عشرة مقاطعة، لكل منها إدارة مقاطعة خاصة بها. ويَنشر مكتب الإحصاء المركزي Centraal Bureau voor de Statistiek أرقام السكان الحالية لكل مقاطعة وبلدية.', [['Rijksoverheid — Provincies', SRC_PROVINCIES], ['CBS — Dashboard bevolking', SRC_CBS]], CHECKED)}

<h2 id="geschiedenis">الخطوط الكبرى للتاريخ</h2>

<p>لست مضطرًا لأن تصبح مؤرخًا. لكن هذه الخطوط تعود في الأحاديث وفي الأخبار وفي الأعياد وفي الامتحان.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>الماء والأرض</h3>
    <p>انتزع الهولنديون على مدى قرون أرضًا من الماء بالسدود وطواحين الهواء ثم بمحطات الضخ. "خلق الله العالم، أما هولندا فخلقها الهولنديون" نكتة تقول شيئًا حقيقيًا: هذا المشهد الطبيعي مصنوع.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>الجمهورية والعصر الذهبي</h3>
    <p>في القرن السابع عشر كانت هولندا جمهورية، أثرت من التجارة عبر البحار. من ذلك الزمن جاءت بيوت القنوات وRembrandt وVermeer — لكن أيضًا تجارة الرقيق والمستعمرات. كلاهما جزء من تلك القصة، وهكذا تُروى اليوم هنا.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>المملكة والدستور</h3>
    <p>منذ 1815 صارت هولندا مملكة. وفي 1848 جاء تعديل الدستور على يد Thorbecke: منذ ذلك الحين لا يحكم الملك بل البرلمان، والملك غير قابل للمساءلة. وما زال الأمر كذلك حتى اليوم.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>الحرب العالمية الثانية</h3>
    <p>من 1940 إلى 1945 كانت هولندا محتلة من ألمانيا النازية. وقُتل الجزء الأكبر من السكان اليهود. لهذا السبب يحمل يوما 4 و5 مايو كل سنة هذا الثقل، ولهذا فإن التمييز موضوع حسّاس وثقيل هنا.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">5</span><div class="guide-step-body">
    <h3>إعادة الإعمار ودولة الرعاية والهجرة</h3>
    <p>بعد 1945 أُعيد بناء البلد ونشأت دولة الرعاية: AOW (معاش الشيخوخة) والتأمين الصحي والإعانات. جاء أناس من Indonesi&euml; وSuriname وجزر الأنتيل، وعمال ضيوف من تركيا والمغرب، ثم لاحقًا لاجئون من بلدان كثيرة. وبذلك صارت هولندا البلد الذي هي عليه الآن.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">6</span><div class="guide-step-body">
    <h3>أوروبا</h3>
    <p>هولندا من مؤسسي ما صار الآن الاتحاد الأوروبي. لذلك يمكنك بجواز سفر هولندي أن تسافر وتعمل بحرية داخل الاتحاد الأوروبي، ونحن ندفع باليورو.</p>
  </div></div>
</div>

${factIn('ar', 'Canon van Nederland هي سلسلة النوافذ على تاريخ هولندا وثقافتها التي أنشأتها الحكومة، وهي مقصودة كإطار مرجعي مشترك وتُستخدم في التعليم.', 'Canon van Nederland', SRC_CANON, CHECKED)}

<h2 id="feestdagen">الأعياد وأيام الذكرى</h2>

<p>هذه التواريخ تعود في الامتحان، وهي عملية أيضًا: في بعض الأيام يكون كل شيء مغلقًا.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>اليوم</th><th>ما هو</th></tr></thead>
  <tbody>
    <tr><td><strong>1 يناير</strong></td><td>رأس السنة (Nieuwjaarsdag)</td></tr>
    <tr><td><strong>Pasen</strong> (عيد الفصح)</td><td>عيد مسيحي في الربيع. يومان عطلة.</td></tr>
    <tr><td><strong>27 أبريل</strong></td><td>Koningsdag — عيد ميلاد الملك. سوق حرة، اللون البرتقالي، احتفال.</td></tr>
    <tr><td><strong>4 مايو</strong></td><td>Dodenherdenking (إحياء ذكرى الموتى). عند الساعة 20:00 دقيقتا صمت في كل أنحاء البلاد.</td></tr>
    <tr><td><strong>5 مايو</strong></td><td>Bevrijdingsdag (يوم التحرير). نهاية الاحتلال في 1945.</td></tr>
    <tr><td><strong>Hemelvaart وPinksteren</strong></td><td>عيدان مسيحيان في مايو أو يونيو (الصعود والعنصرة).</td></tr>
    <tr><td><strong>5 ديسمبر</strong></td><td>Sinterklaas. ليس يوم عطلة رسمية، لكنه كبير عند الأطفال.</td></tr>
    <tr><td><strong>25 و26 ديسمبر</strong></td><td>يوما عيد الميلاد الأول والثاني.</td></tr>
  </tbody>
</table>
</div>

<p>في 4 مايو عند الساعة الثامنة مساءً يسود الصمت دقيقتين. في الشارع أيضًا، وفي القطار، وفي السوبرماركت. وهذا متوقَّع من الجميع، بغضّ النظر عن الدين أو الأصل — فهي ليست لحظة دينية بل لحظة وطنية.</p>

${factIn('ar', 'يُحتفل بـ Koningsdag في 27 أبريل، وهو عيد ميلاد الملك Willem-Alexander. وإذا صادف هذا التاريخ يوم أحد، فيُحتفل بـ Koningsdag في 26 أبريل.', 'Het Koninklijk Huis — Koningsdag', SRC_KONINKLIJK, CHECKED)}

${docentIn('ar', 'إذا حفظت تاريخًا واحدًا فقط من هذا الموضوع كله، فليكن 4 مايو. إنها اللحظة التي تلفت الأنظار إليك أكثر ما يكون إن لم تكن تعرفها، وهي عند الهولنديين أثقل لحظة في السنة.')}

<h2 id="in-het-examen">كيف يعود هذا في الامتحان</h2>

<p>على شكل أسئلة عملية: أي يوم هو اليوم، وإلى أين يجب أن يذهب أحدهم، ولماذا المتجر مغلق. لا على شكل اختبار في التاريخ.</p>

${inlineCta('تدرّب على هذا الموضوع بأسئلة امتحانية', 'الخريطة والمقاطعات والأعياد والخطوط الكبرى — مع شرح بعد كل إجابة.', '/oefenen', 'ابدأ امتحانًا تجريبيًا مجانيًا')}
`,

  sidebarHtml: `
<p><strong>باختصار</strong></p>
<ul>
  <li>اثنتا عشرة مقاطعة؛ Amsterdam هي العاصمة، وDen Haag مدينة الحكومة.</li>
  <li>جزء كبير من البلاد منخفض؛ وwaterschappen تدير المياه.</li>
  <li>معظم الناس يعيشون في Randstad.</li>
  <li>الخطوط الكبرى: الماء، العصر الذهبي، المملكة 1815، الدستور 1848، الحرب العالمية الثانية، دولة الرعاية، أوروبا.</li>
  <li>27 أبريل Koningsdag، و4 مايو إحياء الذكرى، و5 مايو التحرير.</li>
</ul>`,

  faq: [
  {
    q: 'كم مقاطعة في هولندا؟',
    a: 'اثنتا عشرة: Groningen وFriesland وDrenthe وOverijssel وFlevoland وGelderland وUtrecht وNoord-Holland وZuid-Holland وZeeland وNoord-Brabant وLimburg. لكل مقاطعة عاصمة وإدارة خاصة بها، على رأسها commissaris van de Koning (مفوّض الملك).',
  },
  {
    q: 'ما هي عاصمة هولندا؟',
    a: 'Amsterdam. لكن الحكومة والبرلمان والوزارات مقرّها في Den Haag، وهناك يعمل الملك أيضًا. وهذا استثناء يفاجئ كثيرًا من الناس: العاصمة ومدينة الحكومة ليستا هنا المدينة نفسها.',
  },
  {
    q: 'ماذا يحدث في 4 و5 مايو؟',
    a: 'في 4 مايو يكون Dodenherdenking (إحياء ذكرى الموتى): عند الساعة الثامنة مساءً تسود دقيقتان من الصمت في كل أنحاء البلاد تكريمًا لضحايا الحرب العالمية الثانية والحروب التي تلتها. وفي 5 مايو يكون Bevrijdingsdag، اليوم الذي انتهى فيه الاحتلال سنة 1945. وتُقام حينها مهرجانات.',
  },
  {
    q: 'لماذا توجد waterschappen في هولندا؟',
    a: 'لأن جزءًا كبيرًا من البلاد منخفض، ولولا السدود والكثبان ومحطات الضخ لغُمر بالماء. وwaterschappen هي إدارات لا تُعنى إلا بالماء: السدود ومنسوب المياه وجودة المياه. تدفع لها ضريبة منفصلة وتصوّت لها في انتخابات منفصلة، مستقلة عن البلدية والمقاطعة.',
  },
  {
    q: 'هل عليّ حفظ التواريخ عن ظهر قلب من أجل KNM؟',
    a: 'لا. الهدف النهائي يطلب أن تتعمّق في تاريخ هولندا، لا أن تكون قادرًا على سرد تسلسل زمني. والامتحان يطرح أسئلة عملية عن مواقف. اعرف الخطوط الكبرى وأهم الأيام في السنة، وبذلك تكون قد قطعت شوطًا كبيرًا.',
  },
  ],
};

export default translation;
