/**
 * geschiedenis-en-geografie — English.
 *
 * A translation of the Dutch body in `../geschiedenis-en-geografie.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_BOOK, I_HOME, I_LANDMARK, I_ROUTE, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_CANON, SRC_CBS, SRC_EINDTERMEN, SRC_KONINKLIJK, SRC_PROVINCIES, SRC_WATER, card, row } from '../geschiedenis-en-geografie';

const translation: GuideLocale = {
  title: 'KNM: History and geography of the Netherlands',
  description: 'The main lines of Dutch history and where the provinces, cities and water are. The KNM theme History and geography, explained in simple terms.',
  breadcrumb: 'History and geography',
  dateLabel: '23 August 2026',
  eyebrow: 'KNM theme 5',
  heroTitle: 'History and geography',
  heroSubtitle: 'Where is what, and how did the Netherlands become what it is? This theme does not ask for a list of dates, but it does ask you to know the main lines and to be able to read the map.',
  ctaTitle: 'Practise the theme History and geography',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after every answer. No account needed.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="wat-vraagt-knm">What does KNM ask about this theme?</h2>

<p>Two eindtermen (final attainment targets). Look carefully at how they are worded — that tells you
everything about what you need to be able to do.</p>

<div class="compare-rows">
  ${row('5.1', 'Study Dutch history in depth')}
  ${row('5.2', '<strong>Use</strong> geographical knowledge of the Netherlands')}
</div>

<p>For history it is about <em>studying in depth</em>: understanding the main lines, and understanding
why some things here are the way they are. For geography it is about <em>using</em>: being able to read
the map, knowing where you are, and understanding why a train journey from Groningen to Maastricht
is different from one from Amsterdam to Utrecht.</p>

${factIn('en', 'The eindtermen for KNM in the theme History and geography are: study Dutch history in depth, and use geographical knowledge of the Netherlands.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

${docentIn('en', 'This is the theme that students cram hardest for and get the least out of. There will be no question "in which year did the Eighty Years War (Tachtigjarige Oorlog) begin". There will be a question in which someone wants a day off on 5 May, or someone has to travel from Rotterdam to Zeeland. Learn the lines, not the lists.')}

<h2 id="geografie">The country: water, provinces and cities</h2>

<p>The Netherlands is small, densely populated and to a large extent low-lying. About a quarter of
the country lies below sea level, and without dykes, dunes and pumping stations a large part would
be under water. That is why water is not a side issue here but government policy: there are
<strong>waterschappen</strong> (regional water authorities) that deal with nothing else, that you pay
a separate tax to and vote for separately.</p>

${factIn('en', 'A large part of the Netherlands is low-lying and is protected by dykes, dunes and dams. Waterschappen, together with the national government, provide protection against flooding and manage the water.', 'Rijksoverheid — Water en veiligheid', SRC_WATER, CHECKED)}

<h3>The twelve provinces</h3>

<p>The Netherlands has twelve provinces. Each province has a capital, a provincial government and
its own character. This is the list, from north to south.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>Province</th><th>Capital</th></tr></thead>
  <tbody>
    <tr><td><strong>Groningen</strong></td><td>Groningen</td></tr>
    <tr><td><strong>Friesland</strong> (Frysl&acirc;n)</td><td>Leeuwarden</td></tr>
    <tr><td><strong>Drenthe</strong></td><td>Assen</td></tr>
    <tr><td><strong>Overijssel</strong></td><td>Zwolle</td></tr>
    <tr><td><strong>Flevoland</strong></td><td>Lelystad</td></tr>
    <tr><td><strong>Gelderland</strong></td><td>Arnhem</td></tr>
    <tr><td><strong>Utrecht</strong></td><td>Utrecht</td></tr>
    <tr><td><strong>Noord-Holland</strong></td><td>Haarlem</td></tr>
    <tr><td><strong>Zuid-Holland</strong></td><td>Den Haag</td></tr>
    <tr><td><strong>Zeeland</strong></td><td>Middelburg</td></tr>
    <tr><td><strong>Noord-Brabant</strong></td><td>'s-Hertogenbosch</td></tr>
    <tr><td><strong>Limburg</strong></td><td>Maastricht</td></tr>
  </tbody>
</table>
</div>

${note('Watch out for two things that often go wrong. <strong>Amsterdam is the capital of the Netherlands, but the government and the parliament are in Den Haag (The Hague).</strong> And <strong>Flevoland did not exist a hundred years ago</strong>: that province is drained sea bed.')}

<h3>Where do most people live?</h3>

<p>In the west. The four big cities — <strong>Amsterdam, Rotterdam, Den Haag and Utrecht</strong>
— lie close together in the area that is called the <strong>Randstad</strong>. By far the most people
live and work there, and that is also where most of the jobs and the most expensive homes are.</p>

<div class="guide-cards">
  ${card(I_HOME, 'Amsterdam', 'The capital. Canals, tourism, many international companies and Schiphol nearby.')}
  ${card(I_ROUTE, 'Rotterdam', 'The largest port in Europe. A modern city, heavily bombed in the war and rebuilt afterwards.')}
  ${card(I_LANDMARK, 'Den Haag', 'The government, the parliament and the king work here. Also the city of international justice.')}
  ${card(I_BOOK, 'Utrecht', 'In the middle of the country and the hub of the railway network. From Utrecht you can get anywhere.')}
</div>

<p>Further away from the Randstad — Groningen, Friesland, Drenthe, Zeeland, Limburg — it is quieter,
homes are cheaper and distances are greater. For most people doing inburgering (civic integration)
that is practical information: where you live determines how far you have to travel to work, to
school and to your exam location.</p>

${factTwoIn('en', 'The Netherlands has twelve provinces, each with its own provincial government. The Centraal Bureau voor de Statistiek publishes the current population figures per province and per gemeente (municipality).', [['Rijksoverheid — Provincies', SRC_PROVINCIES], ['CBS — Dashboard bevolking', SRC_CBS]], CHECKED)}

<h2 id="geschiedenis">The main lines of history</h2>

<p>You do not have to become a historian. But these lines come back in conversations, in the news,
on public holidays and in the exam.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Water and land</h3>
    <p>For centuries the Dutch have won land from the water with dykes, windmills and later pumping stations. “God created the world, but the Dutch created the Netherlands” is a joke that says something real: the landscape is made.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>The Republic and the Gouden Eeuw (Golden Age)</h3>
    <p>In the seventeenth century the Netherlands was a republic, made rich by trade over sea. The canal houses, Rembrandt and Vermeer come from that time — but so do the slave trade and the colonies. Both belong to that story, and that is also how it is told here nowadays.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Kingdom and constitution</h3>
    <p>Since 1815 the Netherlands has been a kingdom. In 1848 came the constitutional reform of Thorbecke: from that moment on it is not the king who governs but the parliament, and the king is inviolable. That is still the case.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>The Second World War</h3>
    <p>Occupied by Nazi Germany from 1940 to 1945. The great majority of the Jewish population was murdered. This is the reason why 4 and 5 May weigh so heavily every year, and why discrimination is a sensitive and serious subject here.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">5</span><div class="guide-step-body">
    <h3>Reconstruction, welfare state and migration</h3>
    <p>After 1945 the country was rebuilt and the welfare state came into being: AOW, health care costs, benefits. People came from Indonesia, Suriname and the Antilles, gastarbeiders (guest workers) from Turkey and Morocco, and later refugees from many countries. That is how the Netherlands became the country it is now.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">6</span><div class="guide-step-body">
    <h3>Europe</h3>
    <p>The Netherlands is one of the founders of what is now the European Union. That is why you may travel and work freely in the EU with a Dutch passport, and why we pay with the euro.</p>
  </div></div>
</div>

${factIn('en', 'The Canon van Nederland is the series of windows on Dutch history and culture set up by the government, intended as a shared frame of reference and used in education.', 'Canon van Nederland', SRC_CANON, CHECKED)}

<h2 id="feestdagen">Public holidays and commemorations</h2>

<p>These dates come back in the exam, and they are practical: on some days everything is closed.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>Day</th><th>What it is</th></tr></thead>
  <tbody>
    <tr><td><strong>1 January</strong></td><td>Nieuwjaarsdag (New Year’s Day)</td></tr>
    <tr><td><strong>Pasen</strong> (Easter)</td><td>Christian celebration, in spring. Two days off.</td></tr>
    <tr><td><strong>27 April</strong></td><td>Koningsdag — the birthday of the king. Vrijmarkt (open-air market), orange, celebration.</td></tr>
    <tr><td><strong>4 May</strong></td><td>Dodenherdenking (remembrance of the dead). At 20:00 two minutes of silence, in the whole country.</td></tr>
    <tr><td><strong>5 May</strong></td><td>Bevrijdingsdag (Liberation Day). The end of the occupation in 1945.</td></tr>
    <tr><td><strong>Hemelvaart and Pinksteren</strong></td><td>Christian public holidays in May or June.</td></tr>
    <tr><td><strong>5 December</strong></td><td>Sinterklaas. Not an official day off, but a big day for children.</td></tr>
    <tr><td><strong>25 and 26 December</strong></td><td>Eerste en tweede kerstdag (first and second Christmas day).</td></tr>
  </tbody>
</table>
</div>

<p>On 4 May at eight o’clock in the evening there are two minutes of silence. Also in the street, also
on the train, also in the supermarket. That is expected of everyone, whatever their religion or
background — it is not a religious moment but a national moment.</p>

${factIn('en', 'Koningsdag is celebrated on 27 April, the birthday of King Willem-Alexander. If that date falls on a Sunday, Koningsdag is celebrated on 26 April.', 'Het Koninklijk Huis — Koningsdag', SRC_KONINKLIJK, CHECKED)}

${docentIn('en', 'If you remember only one date from this whole theme, make it 4 May. It is the moment when not knowing it shows the most, and for Dutch people it is the heaviest moment of the year.')}

<h2 id="in-het-examen">How this comes back in the exam</h2>

<p>As practical questions: what day is it, where does someone have to go, why is the shop closed.
Not as a history test.</p>

${inlineCta('Practise this theme with exam questions', 'Map, provinces, public holidays and the main lines — with an explanation after every answer.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>Twelve provinces; Amsterdam is the capital, Den Haag is the seat of government.</li>
  <li>A large part of the country is low-lying; waterschappen manage the water.</li>
  <li>Most people live in the Randstad.</li>
  <li>Main lines: water, Gouden Eeuw, kingdom 1815, constitution 1848, the Second World War, welfare state, Europe.</li>
  <li>27 April Koningsdag, 4 May remembrance, 5 May liberation.</li>
</ul>`,

  faq: [
  {
    q: 'How many provinces does the Netherlands have?',
    a: 'Twelve: Groningen, Friesland, Drenthe, Overijssel, Flevoland, Gelderland, Utrecht, Noord-Holland, Zuid-Holland, Zeeland, Noord-Brabant and Limburg. Each province has a capital and its own government, with a commissaris van de Koning (King’s commissioner) at the head.',
  },
  {
    q: 'What is the capital of the Netherlands?',
    a: 'Amsterdam. But the government, the parliament and the ministries are in Den Haag (The Hague), and the king works there too. That is an exception that surprises many people: here the capital and the seat of government are not the same city.',
  },
  {
    q: 'What happens on 4 and 5 May?',
    a: 'On 4 May there is the Dodenherdenking: at eight o’clock in the evening there are two minutes of silence in the whole country for the victims of the Second World War and of wars after it. On 5 May it is Bevrijdingsdag, the day on which the occupation ended in 1945. Then there are festivals.',
  },
  {
    q: 'Why are there waterschappen in the Netherlands?',
    a: 'Because a large part of the country is low-lying and would end up under water without dykes, dunes and pumping stations. Waterschappen are authorities that deal only with water: dykes, water levels and water quality. You pay a separate tax to them and you vote for them separately, apart from the gemeente (municipality) and the province.',
  },
  {
    q: 'Do I have to learn dates by heart for KNM?',
    a: 'No. The eindterm asks you to study Dutch history in depth, not to be able to recite a chronology. The exam asks practical questions about situations. Know the main lines and the most important days of the year, and you will get a long way.',
  },
  ],
};

export default translation;
