/**
 * gezondheid-en-gezondheidszorg — English.
 *
 * A translation of the Dutch body in `../gezondheid-en-gezondheidszorg.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_USER, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_112, SRC_EIGENRISICO, SRC_EINDTERMEN, SRC_HUISARTS, SRC_WMO, SRC_ZORGTOESLAG, SRC_ZORGVERZ, card, row } from '../gezondheid-en-gezondheidszorg';

const translation: GuideLocale = {
  title: 'KNM: Health and Healthcare in the Netherlands',
  description: 'How the huisarts works as your first step, referral to hospital, calling 112 in an emergency, your health insurance and eigen risico. KNM theme 4 explained.',
  breadcrumb: 'Healthcare',
  dateLabel: '23 August 2026',
  eyebrow: 'KNM theme 4',
  heroTitle: 'Health and healthcare',
  heroSubtitle: 'Dutch healthcare works differently from many other countries: almost everything starts with the huisarts (family doctor). Here you can read how it works, and what to do in an emergency.',
  ctaTitle: 'Practise the theme Healthcare',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after every answer. No account needed.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="wat-vraagt-knm">What does KNM ask about this theme?</h2>

<p>This is the theme with the most eindtermen (final attainment targets): five. They follow the path of a patient.</p>

<div class="compare-rows">
  ${row('4.1', 'Using care without a referral')}
  ${row('4.2', 'Using care with a referral')}
  ${row('4.3', 'Acting in a medical emergency')}
  ${row('4.4', 'Handling the financial and administrative side correctly')}
  ${row('4.5', 'Using welfare facilities')}
</div>

${factIn('en', 'The KNM eindtermen for the theme Health and healthcare are: using care without a referral; using care with a referral; acting in a medical emergency; handling the financial and administrative side correctly; using welfare facilities.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

<h2 id="huisarts">Everything starts with the huisarts</h2>

<p>This is the most important rule of Dutch healthcare. The huisarts (family doctor) is the
<strong>gatekeeper</strong>: he or she treats what can be treated there, and refers you on if that
is needed. You do not go to a hospital specialist by yourself.</p>

<p>So register <strong>straight away</strong> with a huisarts in your neighbourhood, even if you
are not ill. Do not wait until you need one: many practices are full.</p>

<h3>Care you may go to yourself</h3>
<p>This is eindterm 4.1: for this care you do not need a referral.</p>

<div class="guide-cards">
  ${card(I_USER, 'The huisarts', 'Your first point of contact for everything: complaints, medicines, doubts, mental health problems. You make an appointment by phone or online.')}
  ${card(I_USER, 'The tandarts (dentist)', 'You choose one yourself. Note: for adults, the dentist is usually not included in the basisverzekering.')}
  ${card(I_USER, 'The apotheek (pharmacy)', 'This is where you collect prescription medicines. You register with one pharmacy, so that it knows your full medicine list.')}
  ${card(I_USER, 'The verloskundige (midwife)', 'Are you pregnant? Then you go directly to a verloskundige, not to the huisarts first.')}
  ${card(I_USER, 'The fysiotherapeut (physiotherapist)', 'You may usually visit one yourself, but check whether your insurance covers it.')}
  ${card(I_USER, 'The consultatiebureau', 'For babies and young children: growth, vaccinations and advice. Free, and you receive an invitation automatically.')}
</div>

<h3>Care for which you need a referral</h3>
<p>This is eindterm 4.2. Think of a hospital specialist — a cardiologist, a dermatologist, a
surgeon — and of much psychological care. The huisarts then writes a
<strong>verwijsbrief</strong> (referral letter). Without that letter, your insurance usually does not
pay.</p>

${factIn('en', 'In the Netherlands the huisarts is the first point of contact for health complaints and refers you to a specialist if needed. Thuisarts.nl is the public information site of Dutch huisartsen.', 'Thuisarts.nl — informatie van huisartsen', SRC_HUISARTS, CHECKED)}

${docentIn('en', 'Students often ask me: "Why does my huisarts not give antibiotics?" In many countries you get them quickly. Here only if it is really necessary. That is not unwillingness and not cost-cutting — it is policy, because otherwise bacteria become resistant. Feel free to ask for an explanation, that is what the huisarts is there for.')}

<h2 id="spoed">Emergency: 112, the huisartsenpost, or simply wait?</h2>

<p>Eindterm 4.3, and the question the exam asks most often. Remember these three situations.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Life-threatening: call 112</h3>
    <p>Someone is not breathing, is unconscious, has had an accident, has heavy bleeding, or shows signs of a stroke or heart attack. 112 is free, day and night, and you get the ambulance, fire brigade or police.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Cannot wait, but not life-threatening: the huisartsenpost</h3>
    <p>In the evening, at night and at the weekend, the huisartsenpost (HAP, out-of-hours doctors service) takes over from your own huisarts. You call <strong>first</strong>; you do not just walk in.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>During the day and it can wait: your own huisarts</h3>
    <p>Call the practice. If you are unsure how serious it is: you may always call, also just to ask. That is what the assistant is there for.</p>
  </div></div>
</div>

${note('In an emergency, do <strong>not</strong> go to the hospital Spoedeisende Hulp (accident and emergency department) yourself without calling. In the Netherlands almost all emergency care goes through 112 or through the huisartsenpost, and without a referral you can be sent away — or receive a high bill.')}

${factIn('en', 'Call 112 if there is immediate danger to life or health, in the case of a crime happening at that moment, or in a suspicious situation. For situations that are not urgent, the number is 0900-8844.', 'Politie.nl — Wanneer bel ik 112?', SRC_112, CHECKED)}

<h2 id="verzekering">Your health insurance</h2>

<p>Eindterm 4.4. In the Netherlands a zorgverzekering (health insurance) is
<strong>compulsory</strong> for everyone who lives or works here. You arrange it yourself, within
four months after you become liable for insurance. If you do not, you get a fine and in the end you
are insured compulsorily.</p>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>Basisverzekering</h3>
      <p class="compare-when">Compulsory, content determined by the government</p>
    </div>
    <div class="compare-rows">
      ${row('What it includes', 'Huisarts, hospital, medicines, verloskundige, emergency care')}
      ${row('Price', 'Differs per insurer, the content does not')}
      ${row('Refusal', 'An insurer may never refuse you for this')}
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>Aanvullende verzekering</h3>
      <p class="compare-when">Voluntary</p>
    </div>
    <div class="compare-rows">
      ${row('What it includes', 'For example dentist, physiotherapy, glasses, alternative care')}
      ${row('Price', 'You choose a package yourself')}
      ${row('Refusal', 'For this an insurer <em>may</em> refuse you')}
    </div>
  </div>
</div>

<h3>Eigen risico</h3>
<p>For most care from the basisverzekering there is an <strong>eigen risico</strong> (own risk, or
deductible): you pay the first part of the costs in a calendar year yourself. The amount is set by
the government every year, so check it.</p>

<p>Two things fall <strong>outside</strong> it, and that is exactly what the exam likes to ask:</p>
<ul>
  <li>The <strong>huisarts</strong> does not fall under the eigen risico. So a visit costs you nothing extra.</li>
  <li>Care for <strong>children under 18</strong> also falls outside it. In addition, children are insured with their parents free of charge.</li>
</ul>

${factTwoIn('en', 'Everyone who lives or works in the Netherlands is obliged to take out a basisverzekering; the government determines its content and it is the same at every insurer. For care from the basisverzekering there is a compulsory eigen risico, with exceptions such as the huisarts; children under 18 pay no eigen risico and are insured free of charge.', [['Rijksoverheid — Zorgverzekering', SRC_ZORGVERZ], ['Rijksoverheid — Eigen risico', SRC_EIGENRISICO]], CHECKED)}

<p>If you have a low income, you can apply for <strong>zorgtoeslag</strong> (healthcare allowance) at
the Belastingdienst (tax administration). That is a monthly contribution towards your premium. You
have to apply for it yourself, and report changes in your income yourself.</p>

${factIn('en', 'Zorgtoeslag is a contribution from the Belastingdienst towards the costs of health insurance, for people with an income below a certain limit. You apply for the allowance yourself and report changes yourself.', 'Belastingdienst — Zorgtoeslag', SRC_ZORGTOESLAG, CHECKED)}

${docentIn('en', 'Do not forget to stop your allowance if you start earning more. I have had students who had to pay back thousands of euros after two years. That is one of the most unpleasant things you can do to yourself, and one phone call prevents it.')}

<h2 id="welzijn">Welfare: help that is not a doctor</h2>

<p>Eindterm 4.5 is about facilities that are not medical, but that do concern your health. Almost
all of these go through your <strong>gemeente</strong> (municipality), under the Wmo.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">What the gemeente is for</p>
    <ul>
      <li>${I_CHECK}<span>Help with the household if you can no longer manage it yourself</span></li>
      <li>${I_CHECK}<span>Aids: a stairlift, a wheelchair, an adaptation in the home</span></li>
      <li>${I_CHECK}<span>Day activities and guidance</span></li>
      <li>${I_CHECK}<span>Support for mantelzorgers (informal carers)</span></li>
      <li>${I_CHECK}<span>Maatschappelijk werk (social work): help with debts, paperwork and problems at home</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">What the gemeente is not for</p>
    <ul>
      <li>${I_X}<span>Medical treatment — that is the huisarts or the hospital</span></li>
      <li>${I_X}<span>Medicines — that is the apotheek, through your insurance</span></li>
      <li>${I_X}<span>Long-term intensive care in an institution — that goes through the Wlz</span></li>
    </ul>
  </div>
</div>

<p>You report to the <strong>Wmo-loket</strong> (Wmo desk) or the sociaal wijkteam (social
neighbourhood team) of your gemeente. After that there is a conversation — the
"keukentafelgesprek" (kitchen table conversation) — in which they look at what you need.</p>

${factIn('en', 'Under the Wet maatschappelijke ondersteuning (Wmo 2015), municipalities are responsible for supporting people who cannot manage on their own, for example with household help, guidance, day activities and home adaptations.', 'Rijksoverheid — Wmo 2015', SRC_WMO, CHECKED)}

<h2 id="in-het-examen">How this comes back in the exam</h2>

<p>Almost always as a complaint with a question: someone has a fever, someone falls off a ladder,
someone receives a bill. The question is then who you call and in what order.</p>

<p>If you remember only one thing from this theme: <strong>huisarts first, 112 only when life is in
danger</strong>. That already covers most questions.</p>

${inlineCta('Practise this theme with exam questions', 'Real situations: huisarts, emergencies, insurance and the gemeente. With an explanation after every answer.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>The huisarts is the gatekeeper: register straight away.</li>
  <li>A specialist only with a verwijsbrief.</li>
  <li>112 when life is in danger; otherwise call the huisarts or huisartsenpost first.</li>
  <li>Health insurance is compulsory; the eigen risico does not apply to the huisarts and not to children.</li>
  <li>Welfare and help at home go through the Wmo-loket of the gemeente.</li>
</ul>`,

  faq: [
  {
    q: 'Can I go to a specialist myself in the Netherlands?',
    a: 'No, usually not. You first go to your huisarts (family doctor). He or she treats what can be treated there and gives you a verwijsbrief (referral letter) if a specialist is needed. Without a referral, your health insurance normally does not pay for the hospital visit. The tandarts (dentist), verloskundige (midwife) and consultatiebureau are exceptions: you may go there yourself.',
  },
  {
    q: 'When do I call 112 and when the huisartsenpost?',
    a: 'Call 112 only if there is immediate danger to someone\'s life: unconsciousness, a serious accident, heavy bleeding, signs of a heart attack or stroke. If it is urgent but not life-threatening, and your own huisarts is closed, then you call the huisartsenpost. During the day you simply call your own practice.',
  },
  {
    q: 'What is the eigen risico?',
    a: 'The first part of your healthcare costs in a calendar year that you pay yourself, before the basisverzekering pays. The government sets the amount every year. Important: the huisarts does not fall under it, and children under 18 pay no eigen risico.',
  },
  {
    q: 'Is health insurance compulsory in the Netherlands?',
    a: 'Yes, for everyone who lives or works here. You take out a basisverzekering yourself, and you must do this within four months after you become liable for insurance. If you do not, you get a fine and in the end you are insured compulsorily. Children under 18 are insured with their parents free of charge.',
  },
  {
    q: 'Where do I apply for household help or an aid?',
    a: 'At your gemeente (municipality), through the Wmo-loket or the sociaal wijkteam. After you report your situation there is a conversation in which they look at what you need and what you can do yourself or with help from people around you. The gemeente deals with household help, guidance, day activities and adaptations in the home — not with medical treatment.',
  },
  ],
};

export default translation;
