/**
 * instanties — Arabic.
 *
 * A translation of the Dutch body in `../instanties.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_CLIPBOARD, I_EURO, I_HOME, I_LANDMARK, I_USERS, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_AANGIFTE, SRC_DIGID, SRC_EINDTERMEN, SRC_GEMEENTE, SRC_JURIDISCHLOKET, SRC_POLITIE, SRC_RECHTSBIJSTAND, SRC_TOESLAGEN, card, row } from '../instanties';

const translation: GuideLocale = {
  title: 'موضوع KNM «Instanties»: من المسؤول عن ماذا في هولندا؟',
  description: 'البلدية وBelastingdienst وDUO وUWV والشرطة وJuridisch Loket: من المسؤول عن ماذا، وإلى أين تذهب؟ شرح واضح ومرتّب لموضوع Instanties في امتحان KNM.',
  breadcrumb: 'Instanties',
  dateLabel: '23 أغسطس 2026',
  eyebrow: 'موضوع KNM رقم 6',
  heroTitle: 'Instanties (الهيئات والمؤسسات)',
  heroSubtitle: 'تنظّم هولندا أمورًا كثيرة عبر منظمات تُعرف باختصاراتها. من المسؤول عن ماذا؟ هذا الموضوع هو دفتر عناوين حياتك الجديدة — ويعود في معظم أسئلة الامتحان.',
  ctaTitle: 'تدرّب على موضوع Instanties',
  ctaDesc: 'امتحان تجريبي مجاني من عشرة أسئلة، مع شرح بعد كل إجابة. بدون حساب.',
  ctaLabel: 'ابدأ امتحانًا تجريبيًا مجانيًا',

  articleHtml: `
<h2 id="wie-doet-wat">من المسؤول عن ماذا؟</h2>

<p>ابدأ من هنا. إذا عرفت هذا الجدول، ستتمكن من الإجابة عن معظم أسئلة هذا الموضوع — وعن جزء كبير من بقية الامتحان أيضًا.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>الموضوع</th><th>الجهة التي عليك التوجه إليها</th></tr></thead>
  <tbody>
    <tr><td>التسجيل، الانتقال إلى عنوان آخر، جواز السفر، رخصة القيادة، الزواج، تسجيل المواليد</td><td><strong>gemeente (البلدية)</strong></td></tr>
    <tr><td>bijstand (إعانة المعيشة)، المساعدة في الأعمال المنزلية، المساعدة في الديون، مسار الاندماج inburgering</td><td><strong>gemeente (البلدية)</strong></td></tr>
    <tr><td>الإقرار الضريبي، zorgtoeslag (بدل التأمين الصحي)، huurtoeslag (بدل الإيجار)، kinderopvangtoeslag (بدل رعاية الأطفال)</td><td><strong>Belastingdienst (مصلحة الضرائب)</strong></td></tr>
    <tr><td>kinderbijslag (علاوة الأطفال) وAOW (معاش الشيخوخة)</td><td><strong>SVB</strong> (Sociale Verzekeringsbank)</td></tr>
    <tr><td>إعانة البطالة WW والعجز عن العمل</td><td><strong>UWV</strong></td></tr>
    <tr><td>امتحانات الاندماج، والاقتراض لتمويل دورتك</td><td><strong>DUO</strong></td></tr>
    <tr><td>تصريح الإقامة، التجنّس</td><td><strong>IND</strong></td></tr>
    <tr><td>تقديم بلاغ (aangifte)، الإبلاغ عن جريمة، الأشياء المعثور عليها</td><td><strong>politie (الشرطة)</strong></td></tr>
    <tr><td>أول استشارة قانونية مجانية</td><td><strong>Het Juridisch Loket (المكتب القانوني)</strong></td></tr>
    <tr><td>نزاع حول الإيجار أو تكاليف الخدمات أو الصيانة (السكن الاجتماعي)</td><td><strong>Huurcommissie (لجنة الإيجارات)</strong></td></tr>
  </tbody>
</table>
</div>

${docentIn('ar', 'إذا بدأ سؤال في الامتحان بعبارة "يتلقى Ali رسالة من…"، فالسؤال في الحقيقة هو: من هي هذه الجهة وماذا تريد. لذلك لا تحفظ الأسماء، بل المواضيع. من يتعامل مع المال الذي تحصل عليه، ومن مع المال الذي تدفعه، ومن مع الأوراق.')}

<h2 id="eindtermen">ماذا يسأل KNM عن هذا الموضوع؟</h2>

<p>ستة أهداف نهائية (eindtermen) — أكثر من أي موضوع آخر. وهذا يدل على أهمية هذا الجزء.</p>

<div class="compare-rows">
  ${row('6.1', 'التعامل مع معلومات الحكومة')}
  ${row('6.2', 'الاستفادة من خدمات البلدية')}
  ${row('6.3', 'التعامل مع الإقرار الضريبي والبدلات (toeslagen)')}
  ${row('6.4', 'التعامل مع خدمات الشرطة')}
  ${row('6.5', 'الاستفادة من المساعدة القانونية')}
  ${row('6.6', 'التعامل مع التأمينات')}
</div>

${factIn('ar', 'الأهداف النهائية لـ KNM في موضوع Instanties هي: التعامل مع معلومات الحكومة؛ الاستفادة من خدمات البلدية؛ التعامل مع الإقرار الضريبي والبدلات؛ التعامل مع خدمات الشرطة؛ الاستفادة من المساعدة القانونية؛ التعامل مع التأمينات.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

<h2 id="overheidsinformatie">معلومات الحكومة وDigiD</h2>

<p>تعمل الحكومة الهولندية رقميًا بشكل شبه كامل. والمفتاح لذلك هو
<strong>DigiD</strong>: رمز الدخول الشخصي الخاص بك لدى الحكومة. به تسجّل الدخول لدى
Belastingdienst وDUO والـ gemeente وUWV وSVB وشركة التأمين الصحي الخاصة بك.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">هكذا تتعامل مع DigiD</p>
    <ul>
      <li>${I_CHECK}<span>اطلبه فور حصولك على رقم BSN وتسجيلك لدى الـ gemeente</span></li>
      <li>${I_CHECK}<span>ثبّت تطبيق DigiD؛ فهو أكثر أمانًا وأسهل من الرسائل النصية</span></li>
      <li>${I_CHECK}<span>لم ينجح تسجيل الدخول؟ اتصل بالجهة نفسها — ستساعدك</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">لا تفعل هذا أبدًا</p>
    <ul>
      <li>${I_X}<span>مشاركة DigiD الخاص بك، ولا حتى مع العائلة أو مع وسيط</span></li>
      <li>${I_X}<span>تسجيل الدخول عبر رابط في بريد إلكتروني أو رسالة نصية — هذا احتيال في معظم الأحيان</span></li>
      <li>${I_X}<span>دفع المال لشخص كي «يرتّب لك البدلات»</span></li>
    </ul>
  </div>
</div>

<p>هل وصلتك رسالة لا تفهمها؟ لا ترمِها ولا تتجاهلها. في معظم البلديات وفي المكتبات توجد
<strong>informatiepunten digitale overheid</strong> (نقاط معلومات الحكومة الرقمية) مجانية
حيث ينظر معك أحدهم في الرسالة. اطلب المساعدة؛ هذا أمر عادي وهو مجاني.</p>

${factIn('ar', 'بواسطة DigiD تسجّل الدخول لدى الحكومة الهولندية ولدى منظمات في مجالات الرعاية والتعليم والمعاشات. DigiD شخصي ولا يجوز لك إعطاؤه لشخص آخر.', 'DigiD — over DigiD', SRC_DIGID, CHECKED)}

${note('غالبًا ما يكون للرسائل الرسمية في هولندا <strong>مهلة زمنية (termijn)</strong>: عدد من الأسابيع يجب أن تردّ خلالها أو يمكنك خلالها تقديم اعتراض. وهي في العادة ستة أسابيع. إذا تأخرت، يصبح القرار نهائيًا، حتى لو كان خاطئًا. لذلك انظر دائمًا أولًا إلى التاريخ وإلى المهلة المذكورة في الرسالة.')}

<h2 id="gemeente">الـ gemeente (البلدية)</h2>

<p>البلدية هي الجهة الحكومية الأقرب إليك، والتي تتعامل معها أكثر من غيرها.</p>

<div class="guide-cards">
  ${card(I_HOME, 'Burgerzaken (شؤون المواطنين)', 'التسجيل، الانتقال إلى عنوان آخر، جواز السفر أو بطاقة الهوية، رخصة القيادة، المستخرجات، الزواج، تسجيل المواليد.')}
  ${card(I_EURO, 'العمل والدخل', 'إعانة المعيشة bijstand، والمساعدة الخاصة bijzondere bijstand، والمساعدة في الديون.')}
  ${card(I_USERS, 'Wmo والشباب', 'المساعدة في المنزل، الوسائل المساعدة، الأنشطة النهارية، ومساعدة الشباب للأطفال.')}
  ${card(I_CLIPBOARD, 'الاندماج (inburgering)', 'المقابلة الشاملة brede intake، وخطتك PIP، والمرافقة أثناء مسار الاندماج.')}
  ${card(I_LANDMARK, 'التصاريح والحي', 'أعمال البناء، إقامة فعالية، النفايات، مواقف السيارات، والبلاغات عن الفضاء العام.')}
  ${card(I_EURO, 'الضرائب البلدية', 'رسوم النفايات afvalstoffenheffing، ورسوم الصرف الصحي rioolheffing، وضريبة العقار ozb — مع إمكانية الإعفاء عند الدخل المنخفض.')}
</div>

${factIn('ar', 'تنفّذ البلديات كثيرًا من المهام الحكومية التي تمسّ السكان مباشرة، ومنها شؤون المواطنين، وإعانة المعيشة، والدعم الاجتماعي، ومساعدة الشباب، والتصاريح.', 'Rijksoverheid — Gemeenten', SRC_GEMEENTE, CHECKED)}

<h2 id="belasting">الضرائب والبدلات (toeslagen)</h2>

<p>أمران كثيرًا ما يُخلط بينهما.</p>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>الإقرار الضريبي (belastingaangifte)</h3>
      <p class="compare-when">مال تدفعه أنت (أو تستردّه)</p>
    </div>
    <div class="compare-rows">
      ${row('متى', 'مرة واحدة في السنة، عادةً قبل 1 مايو')}
      ${row('كيف', 'عبر الإنترنت باستخدام DigiD؛ كثير من البيانات تكون معبّأة مسبقًا')}
      ${row('لماذا تفعل ذلك', 'غالبًا تسترد مالًا، حتى لو كان دخلك قليلًا')}
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>البدلات (toeslagen)</h3>
      <p class="compare-when">مال تحصل عليه أنت</p>
    </div>
    <div class="compare-rows">
      ${row('أي بدلات', 'zorgtoeslag، huurtoeslag، kinderopvangtoeslag، kindgebonden budget')}
      ${row('كيف', 'تقدّم الطلب بنفسك لدى Belastingdienst، باستخدام DigiD')}
      ${row('انتبه', 'إنها دفعة مقدّمة: إذا تغيّر دخلك، فأبلغ عن ذلك فورًا')}
    </div>
  </div>
</div>

<p>هذه النقطة الأخيرة هي أهم جملة في هذا الموضوع كله. البدل هو
<strong>دفعة مقدّمة (voorschot)</strong> على أساس دخلك المتوقع. إذا صرت تكسب أكثر، أو جاء شخص
ليسكن معك، ولم تبلّغ عن ذلك، فسيتعين عليك لاحقًا إعادة كل شيء. يحدث هذا كثيرًا، ويمكن تفاديه
بتغيير واحد في Mijn Toeslagen.</p>

${factTwoIn('ar', 'تُدفع البدلات كدفعة مقدّمة على أساس وضعك المتوقع؛ ويجب عليك أنت الإبلاغ عن التغيّرات في الدخل أو في تكوين الأسرة، وإلا وجب عليك إعادة ما استلمته زائدًا. أما الإقرار الضريبي على الدخل فتقدّمه سنويًا عبر الإنترنت باستخدام DigiD.', [['Belastingdienst — Toeslagen', SRC_TOESLAGEN], ['Belastingdienst — Aangifte inkomstenbelasting', SRC_AANGIFTE]], CHECKED)}

${docentIn('ar', 'أنصح الجميع بتقديم الإقرار الضريبي، حتى لو لم يكن إلزاميًا. كثير من ذوي الدخل المنخفض أو من عملوا جزءًا من السنة يستردّون مالًا. ولن تبحث عنك Belastingdienst من أجل ذلك — عليك أن تفعل ذلك بنفسك.')}

<h2 id="politie">الشرطة (politie)</h2>

<p>الهدف النهائي 6.4. ثلاثة أرقام، والفرق بينها مهم.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>112 — الطوارئ</h3>
    <p>خطر مباشر، أو جريمة تقع الآن، أو وضع مشبوه. مجاني، ليلًا ونهارًا. تصلك الشرطة أو الإطفاء أو الإسعاف.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>0900-8844 — غير طارئ</h3>
    <p>للإبلاغ عن شيء، أو طرح سؤال، أو حجز موعد لتقديم بلاغ (aangifte).</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Politie.nl — عبر الإنترنت</h3>
    <p>في حالات كثيرة، مثل سرقة دراجة أو احتيال عبر الإنترنت، يمكنك تقديم البلاغ عبر الإنترنت.</p>
  </div></div>
</div>

<p><strong>تقديم البلاغ (aangifte) مسموح دائمًا</strong>، والشرطة ملزمة بتسجيله. إذا كنت ضحية
عنف أو سرقة أو تمييز، فتقديم البلاغ هو الطريقة لكي يُتخذ إجراء بشأنه. الشرطة ليست مسؤولة عن
تصريح إقامتك؛ فذلك من اختصاص IND.</p>

${factIn('ar', 'اتصل بالرقم 112 عند وجود خطر مباشر على الحياة أو الصحة، أو عند وقوع جريمة في تلك اللحظة، أو عند وضع مشبوه. وإذا لم تكن الحالة طارئة، فاتصل بالرقم 0900-8844.', 'Politie.nl — Wanneer bel ik 112?', SRC_POLITIE, CHECKED)}

<h2 id="juridische-hulp">المساعدة القانونية</h2>

<p>الهدف النهائي 6.5. إذا كانت لديك مشكلة قانونية — مع المؤجّر، أو صاحب العمل، أو متجر إلكتروني،
أو جهة رسمية — فلست مضطرًا لحلّها وحدك، ولست مضطرًا للاستعانة فورًا بمحامٍ باهظ التكلفة.</p>

<div class="guide-cards">
  ${card(I_CLIPBOARD, 'Het Juridisch Loket', 'استشارة أولى مجانية، هاتفيًا أو في الموقع. وغالبًا ما تكفي لتعرف ما عليك فعله.')}
  ${card(I_EURO, 'gesubsidieerde rechtsbijstand (المساعدة القانونية المدعومة)', 'هل تحتاج رغم ذلك إلى محامٍ ودخلك منخفض؟ عندها تدفع الحكومة جزءًا من التكلفة وتدفع أنت مساهمة ذاتية. ويسمّى ذلك toevoeging.')}
  ${card(I_USERS, 'rechtsbijstandverzekering (تأمين المساعدة القانونية)', 'بعض الناس لديهم هذا التأمين عبر شركة تأمينهم أو عبر نقابة. تحقّق من ذلك أولًا.')}
  ${card(I_LANDMARK, 'sociaal raadslieden (المستشارون الاجتماعيون)', 'موجودون في كثير من البلديات: مساعدة مجانية في الرسائل والاعتراضات والاستمارات.')}
</div>

${factTwoIn('ar', 'يقدّم Het Juridisch Loket استشارة قانونية مجانية. ومن يحتاج إلى محامٍ أو وسيط ودخله منخفض، قد يكون مؤهلًا للمساعدة القانونية المدعومة: عندها تدفع الحكومة جزءًا من التكاليف ويدفع طالب العون مساهمة ذاتية.', [['Het Juridisch Loket', SRC_JURIDISCHLOKET], ['Rijksoverheid — Rechtsbijstand', SRC_RECHTSBIJSTAND]], CHECKED)}

<h2 id="verzekeringen">التأمينات</h2>

<p>الهدف النهائي 6.6. تؤمّن هولندا على أشياء كثيرة. اعرف ما هو إلزامي وما ليس كذلك.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">إلزامي</p>
    <ul>
      <li>${I_CHECK}<span><strong>zorgverzekering (التأمين الصحي)</strong> — لكل من يسكن أو يعمل هنا</span></li>
      <li>${I_CHECK}<span><strong>تأمين WA لسيارتك أو دراجتك النارية أو سكوترك</strong> — لا يجوز لك النزول إلى الطريق بدونه</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">ليس إلزاميًا، لكنه حكيم</p>
    <ul>
      <li>${I_X}<span><strong>تأمين المسؤولية المدنية (AVP)</strong> — للأضرار التي تسببها أنت أو طفلك</span></li>
      <li>${I_X}<span><strong>inboedelverzekering (تأمين محتويات المنزل)</strong> — لأغراضك في حالة الحريق أو السطو</span></li>
      <li>${I_X}<span><strong>تأمين السفر وتأمين الجنازة</strong> — اختيار شخصي</span></li>
    </ul>
  </div>
</div>

${note('انظر في كل تأمين إلى <strong>eigen risico (التحمّل الذاتي)</strong> وإلى <strong>opzegtermijn (مهلة الإلغاء)</strong>. وانتبه إلى التكرار: أحيانًا تكون مؤمّنًا على شيء ما عبر بنكك أو صاحب عملك دون أن تعرف.')}

<h2 id="in-het-examen">كيف يعود هذا في الامتحان</h2>

<p>على شكل موقف فيه عنوان خاطئ. شخص يتصل بالشرطة بسبب خلاف مع الجيران، وشخص يذهب إلى البلدية من
أجل zorgtoeslag، وشخص يتجاهل رسالة فيها مهلة زمنية. والسؤال في كل مرة هو: إلى أين كان يجب أن
يتوجّه هذا الشخص، ومتى؟</p>

${inlineCta('تدرّب على هذا الموضوع بأسئلة امتحانية', 'رسائل وشبابيك ومهل زمنية — تمامًا كما في امتحان KNM الحقيقي.', '/oefenen', 'ابدأ امتحانًا تجريبيًا مجانيًا')}
`,

  sidebarHtml: `
<p><strong>باختصار</strong></p>
<ul>
  <li>gemeente: الأوراق، bijstand، Wmo، الاندماج.</li>
  <li>Belastingdienst: الإقرار الضريبي والبدلات معًا. البدلات دفعة مقدّمة.</li>
  <li>UWV: إعانة البطالة WW. SVB: علاوة الأطفال وAOW. DUO: امتحاناتك.</li>
  <li>112 عند الطوارئ، و0900-8844 عند عدم الطوارئ.</li>
  <li>Het Juridisch Loket يقدّم استشارة مجانية.</li>
  <li>انتبه دائمًا إلى المهلة الزمنية في الرسالة — وهي في الغالب ستة أسابيع.</li>
</ul>`,

  faq: [
  {
    q: 'ما هو DigiD وكيف أطلبه؟',
    a: 'DigiD هو رمز الدخول الشخصي الخاص بك لدى الحكومة الهولندية. تحتاج إليه لدى Belastingdienst وDUO والـ gemeente وUWV وشركة التأمين الصحي. تطلبه على موقع digid.nl فور حصولك على رقم BSN وتسجيلك لدى الـ gemeente. لا تشارك DigiD الخاص بك مع أي شخص آخر أبدًا.',
  },
  {
    q: 'ما الفرق بين Belastingdienst وToeslagen؟',
    a: 'إنها المنظمة نفسها، لكنهما أمران مختلفان. في الإقرار الضريبي تنظر Belastingdienst فيما إذا كان عليك دفع ضريبة أو استرداد مبلغ. أما البدلات (toeslagen) فهي مساهمات تحصل عليها، مثل zorgtoeslag وhuurtoeslag. البدلات تطلبها بنفسك وهي دفعة مقدّمة: إذا تغيّر دخلك، فأبلغ عن ذلك فورًا.',
  },
  {
    q: 'أين أبلغ عن مشكلة مع المؤجّر أو صاحب العمل؟',
    a: 'ابدأ بـ Het Juridisch Loket: فهو يقدّم استشارة أولى مجانية. وفي حالة السكن الاجتماعي يمكنك أيضًا التوجّه إلى Huurcommissie بشأن قيمة الإيجار أو تكاليف الخدمات أو الصيانة. وإذا كنت تحتاج إلى محامٍ ودخلك منخفض، فيمكنك الحصول على المساعدة القانونية المدعومة ولا تدفع سوى مساهمة ذاتية.',
  },
  {
    q: 'متى أتصل بالرقم 112 ومتى بالرقم 0900-8844؟',
    a: 'تتصل بالرقم 112 في حالات الطوارئ فقط: خطر مباشر على حياة شخص، أو جريمة تقع في تلك اللحظة، أو وضع مشبوه. أما كل ما ليس طارئًا — بلاغ، أو سؤال، أو موعد لتقديم aangifte — فتتصل من أجله بالرقم 0900-8844. ويمكن أيضًا تقديم كثير من البلاغات عبر الإنترنت على politie.nl.',
  },
  {
    q: 'ما التأمينات الإلزامية في هولندا؟',
    a: 'اثنان. التأمين الصحي zorgverzekering إلزامي لكل من يسكن أو يعمل هنا. وإذا كانت لديك سيارة أو دراجة نارية أو سكوتر، فتأمين WA إلزامي. أما التأمينات الأخرى، مثل تأمين المسؤولية المدنية وتأمين محتويات المنزل، فليست إلزامية لكنها حكيمة ورخيصة في الغالب.',
  },
  {
    q: 'وصلتني رسالة من الحكومة لا أفهمها. ماذا أفعل الآن؟',
    a: 'لا ترمِها ولا تنتظر. انظر أولًا إلى التاريخ وإلى المهلة الزمنية التي يمكنك الردّ خلالها؛ وهي غالبًا ستة أسابيع. ثم اطلب المساعدة من informatiepunt digitale overheid في المكتبة، أو من sociaal raadslieden في بلديتك، أو من Het Juridisch Loket. هذه المساعدة مجانية.',
  },
  ],
};

export default translation;
