/**
 * instanties — English.
 *
 * A translation of the Dutch body in `../instanties.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_CLIPBOARD, I_EURO, I_HOME, I_LANDMARK, I_USERS, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_AANGIFTE, SRC_DIGID, SRC_EINDTERMEN, SRC_GEMEENTE, SRC_JURIDISCHLOKET, SRC_POLITIE, SRC_RECHTSBIJSTAND, SRC_TOESLAGEN, card, row } from '../instanties';

const translation: GuideLocale = {
  title: 'KNM theme Instanties: who does what in the Netherlands?',
  description: 'Gemeente, Belastingdienst, DUO, UWV, the police and Het Juridisch Loket. Who handles what, and where do you go? The KNM theme Instanties explained.',
  breadcrumb: 'Instanties',
  dateLabel: '23 August 2026',
  eyebrow: 'KNM theme 6',
  heroTitle: 'Instanties',
  heroSubtitle: 'The Netherlands arranges a lot through organisations with abbreviations. Which one deals with what? This theme is the address book of your new life — and it comes back in almost every exam question.',
  ctaTitle: 'Practise the theme Instanties',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after each answer. No account needed.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="wie-doet-wat">Who deals with what?</h2>

<p>Start here. If you know this table, you can answer most questions in this theme — and a large
part of the rest of the exam too.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>What it is about</th><th>Where you need to go</th></tr></thead>
  <tbody>
    <tr><td>Registering, moving house, passport, driving licence, marriage, birth</td><td><strong>The gemeente</strong> (municipality)</td></tr>
    <tr><td>Bijstand (social assistance benefit), help in the household, debt help, inburgering programme</td><td><strong>The gemeente</strong></td></tr>
    <tr><td>Belastingaangifte (tax return), zorgtoeslag (healthcare allowance), huurtoeslag (rent allowance), kinderopvangtoeslag (childcare allowance)</td><td><strong>The Belastingdienst</strong> (tax office)</td></tr>
    <tr><td>Kinderbijslag (child benefit) and AOW (state pension)</td><td><strong>The SVB</strong> (Sociale Verzekeringsbank)</td></tr>
    <tr><td>WW benefit (unemployment benefit) and incapacity for work</td><td><strong>UWV</strong></td></tr>
    <tr><td>Your inburgering exams, and borrowing money for your course</td><td><strong>DUO</strong></td></tr>
    <tr><td>Residence permit, naturalisation</td><td><strong>The IND</strong></td></tr>
    <tr><td>Filing an aangifte (official report), reporting a crime, lost property</td><td><strong>The politie</strong> (police)</td></tr>
    <tr><td>Free first legal advice</td><td><strong>Het Juridisch Loket</strong></td></tr>
    <tr><td>Dispute about rent, service charges or maintenance (social housing)</td><td><strong>De Huurcommissie</strong></td></tr>
  </tbody>
</table>
</div>

${docentIn('en', 'If an exam question starts with "Ali gets a letter from…", then the real question is: who is this and what do they want? So do not learn the names, learn the topics. Who deals with money you receive, who deals with money you pay, and who deals with papers.')}

<h2 id="eindtermen">What does KNM ask about this theme?</h2>

<p>Six eindtermen (attainment targets) — more than any other theme. That shows how important this
part is.</p>

<div class="compare-rows">
  ${row('6.1', 'Dealing with government information')}
  ${row('6.2', 'Using municipal services')}
  ${row('6.3', 'Dealing with tax returns and toeslagen (allowances)')}
  ${row('6.4', 'Dealing with police services')}
  ${row('6.5', 'Using legal help')}
  ${row('6.6', 'Dealing with insurance')}
</div>

${factIn('en', 'The KNM eindtermen for the theme Instanties are: dealing with government information; using municipal services; dealing with tax returns and toeslagen; dealing with police services; using legal help; dealing with insurance.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

<h2 id="overheidsinformatie">Government information and DigiD</h2>

<p>The Dutch government works almost entirely digitally. The key to this is your
<strong>DigiD</strong>: your personal login code for the government. With it you log in at the
Belastingdienst, DUO, your gemeente, UWV, the SVB and your health insurer.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">This is how you handle DigiD</p>
    <ul>
      <li>${I_CHECK}<span>Apply for it as soon as you have a BSN and are registered with the gemeente</span></li>
      <li>${I_CHECK}<span>Install the DigiD app; that is safer and easier than sms</span></li>
      <li>${I_CHECK}<span>Cannot log in? Call the organisation itself — they will help you</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Never do this</p>
    <ul>
      <li>${I_X}<span>Share your DigiD, not even with family or an intermediary</span></li>
      <li>${I_X}<span>Log in through a link in an email or text message — that is almost always fraud</span></li>
      <li>${I_X}<span>Pay someone to "arrange your toeslagen"</span></li>
    </ul>
  </div>
</div>

<p>Did you get a letter that you do not understand? Do not throw it away and do not ignore it. At
most gemeenten and at libraries there are free <strong>informatiepunten digitale overheid</strong>
(information points for digital government) where someone looks at it with you. Ask for help; that
is normal and it is free.</p>

${factIn('en', 'With DigiD you log in at the Dutch government and at organisations in healthcare, education and pensions. DigiD is personal and you may not give it to anyone else.', 'DigiD — over DigiD', SRC_DIGID, CHECKED)}

${note('Official letters in the Netherlands often have a <strong>termijn</strong> (deadline): a number of weeks within which you must respond or can object. Usually that is six weeks. If you are too late, the decision is final, even if it was wrong. So always look first at the date and the termijn in the letter.')}

<h2 id="gemeente">The gemeente</h2>

<p>Your gemeente is the government that is closest to you, and where you go most often.</p>

<div class="guide-cards">
  ${card(I_HOME, 'Burgerzaken (civil affairs)', 'Registering, moving house, passport or ID card, driving licence, official extracts, marriage, registering a birth.')}
  ${card(I_EURO, 'Work and income', 'Bijstand benefit, bijzondere bijstand (special assistance), and help with debts.')}
  ${card(I_USERS, 'Wmo and youth care', 'Help at home, aids and equipment, day activities, and youth care for children.')}
  ${card(I_CLIPBOARD, 'Inburgering', 'The brede intake (broad intake interview), your PIP, and the support during your inburgering programme.')}
  ${card(I_LANDMARK, 'Permits and the neighbourhood', 'Building work, an event, waste, parking, and reports about public space.')}
  ${card(I_EURO, 'Municipal taxes', 'Afvalstoffenheffing (waste charge), rioolheffing (sewerage charge) and ozb (property tax) — with kwijtschelding (remission) if you have a low income.')}
</div>

${factIn('en', 'Gemeenten carry out many government tasks that directly affect residents, including civil affairs, social assistance, social support, youth care and permits.', 'Rijksoverheid — Gemeenten', SRC_GEMEENTE, CHECKED)}

<h2 id="belasting">Tax and toeslagen</h2>

<p>Two things that are often mixed up.</p>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>Belastingaangifte</h3>
      <p class="compare-when">Money that you pay (or get back)</p>
    </div>
    <div class="compare-rows">
      ${row('When', 'Once a year, usually before 1 May')}
      ${row('How', 'Online with DigiD; many details are already filled in')}
      ${row('Why do it', 'You often get money back, also if you earn little')}
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>Toeslagen</h3>
      <p class="compare-when">Money that you receive</p>
    </div>
    <div class="compare-rows">
      ${row('Which ones', 'Zorgtoeslag, huurtoeslag, kinderopvangtoeslag, kindgebonden budget')}
      ${row('How', 'You apply yourself at the Belastingdienst, with DigiD')}
      ${row('Watch out', 'It is an advance payment: if your income changes, report it immediately')}
    </div>
  </div>
</div>

<p>That last point is the most important sentence of this whole theme. A toeslag is an
<strong>advance payment</strong> based on your expected income. If you start to earn more, or if
someone comes to live with you, and you do not report it, then you have to pay everything back
later. This happens a lot, and you can prevent it with one change in Mijn Toeslagen.</p>

${factTwoIn('en', 'Toeslagen are paid out as an advance based on your expected situation; you must report changes in your income or household yourself, otherwise you have to pay back the toeslag you received too much of. You file the income tax return online each year with DigiD.', [['Belastingdienst — Toeslagen', SRC_TOESLAGEN], ['Belastingdienst — Aangifte inkomstenbelasting', SRC_AANGIFTE]], CHECKED)}

${docentIn('en', 'I advise everyone to file a tax return, also when you do not have to. Many people with a low income, or who worked for part of the year, get money back. The Belastingdienst will not come looking for you to do this — you have to do it yourself.')}

<h2 id="politie">The police</h2>

<p>Eindterm 6.4. Three numbers, and the difference is important.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>112 — emergency</h3>
    <p>Immediate danger, a crime that is happening now, or a suspicious situation. Free, day and night. You get the police, the fire brigade or an ambulance.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>0900-8844 — no emergency</h3>
    <p>To report something, to ask a question, to make an appointment to file an aangifte.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Politie.nl — online</h3>
    <p>For many matters, such as a stolen bicycle or fraud over the internet, you can file an aangifte online.</p>
  </div></div>
</div>

<p><strong>You may always file an aangifte</strong>, and the police are obliged to record it. If you
are the victim of violence, theft or discrimination, filing an aangifte is the way to make
something happen with it. The police do not deal with your residence permit; that is the IND.</p>

${factIn('en', 'Call 112 in case of immediate danger to life or health, when a crime is taking place at that moment, or in a suspicious situation. If it is not an emergency, call 0900-8844.', 'Politie.nl — Wanneer bel ik 112?', SRC_POLITIE, CHECKED)}

<h2 id="juridische-hulp">Legal help</h2>

<p>Eindterm 6.5. Do you have a legal problem — with your landlord, your employer, a web shop, or an
organisation? Then you do not have to solve it alone, and you do not have to bring in an expensive
lawyer straight away.</p>

<div class="guide-cards">
  ${card(I_CLIPBOARD, 'Het Juridisch Loket', 'Free first advice, by telephone or in person. Often enough to know what you have to do.')}
  ${card(I_EURO, 'Gesubsidieerde rechtsbijstand (subsidised legal aid)', 'Do you still need a lawyer and do you have a low income? Then the government pays part of it; you pay an eigen bijdrage (personal contribution). This is called a toevoeging.')}
  ${card(I_USERS, 'Rechtsbijstandverzekering (legal expenses insurance)', 'Some people have this through their insurance or through a trade union. Check that first.')}
  ${card(I_LANDMARK, 'Sociaal raadslieden (social advisers)', 'At many gemeenten: free help with letters, objection letters and forms.')}
</div>

${factTwoIn('en', 'Het Juridisch Loket gives free legal advice. People who need a lawyer or mediator and have a low income may be eligible for gesubsidieerde rechtsbijstand: the government then pays part of the costs and the person seeking legal help pays an eigen bijdrage.', [['Het Juridisch Loket', SRC_JURIDISCHLOKET], ['Rijksoverheid — Rechtsbijstand', SRC_RECHTSBIJSTAND]], CHECKED)}

<h2 id="verzekeringen">Insurance</h2>

<p>Eindterm 6.6. The Netherlands insures a lot. Know what is compulsory and what is not.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">Compulsory</p>
    <ul>
      <li>${I_CHECK}<span><strong>Zorgverzekering (health insurance)</strong> — for everyone who lives or works here</span></li>
      <li>${I_CHECK}<span><strong>WA-verzekering (third-party liability insurance) for your car, motorbike or scooter</strong> — without it you may not go on the road</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Not compulsory, but sensible</p>
    <ul>
      <li>${I_X}<span><strong>Aansprakelijkheidsverzekering (AVP)</strong> — liability insurance, for damage that you or your child cause</span></li>
      <li>${I_X}<span><strong>Inboedelverzekering</strong> — home contents insurance, for your belongings in case of fire or burglary</span></li>
      <li>${I_X}<span><strong>Travel and funeral insurance</strong> — a personal choice</span></li>
    </ul>
  </div>
</div>

${note('With every insurance, look at the <strong>eigen risico</strong> (excess) and at the <strong>opzegtermijn</strong> (notice period). And watch out for overlap: sometimes you are already insured for something through your bank or your employer without knowing it.')}

<h2 id="in-het-examen">How this comes back in the exam</h2>

<p>As a situation with the wrong address in it. Someone calls the police about a quarrel with the
neighbours, someone goes to the gemeente for zorgtoeslag, someone ignores a letter with a termijn.
The question is always: where should that person have gone, and when?</p>

${inlineCta('Practise this theme with exam questions', 'Letters, service desks and deadlines — exactly like in the real KNM exam.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>Gemeente: papers, bijstand, Wmo, inburgering.</li>
  <li>Belastingdienst: tax return and toeslagen. Toeslagen are an advance payment.</li>
  <li>UWV: WW. SVB: kinderbijslag and AOW. DUO: your exams.</li>
  <li>112 in an emergency, 0900-8844 when there is no emergency.</li>
  <li>Het Juridisch Loket gives free advice.</li>
  <li>Always look at the termijn in a letter — usually six weeks.</li>
</ul>`,

  faq: [
  {
    q: 'What is DigiD and how do I apply for it?',
    a: 'DigiD is your personal login code for the Dutch government. You need it for the Belastingdienst, DUO, your gemeente, UWV and your health insurer. You apply for it at digid.nl as soon as you have a BSN and are registered with the gemeente. Never share your DigiD with anyone else.',
  },
  {
    q: 'What is the difference between the Belastingdienst and Toeslagen?',
    a: 'It is the same organisation, but two different things. With the tax return, the Belastingdienst looks at whether you have to pay tax or get money back. Toeslagen are contributions that you receive, such as zorgtoeslag and huurtoeslag. You apply for toeslagen yourself and they are an advance payment: if your income changes, report it immediately.',
  },
  {
    q: 'Where do I report a problem with my landlord or employer?',
    a: 'Start at Het Juridisch Loket: it gives free first advice. With a social housing home you can also go to the Huurcommissie about the rent, service charges or maintenance. If you need a lawyer and have a low income, you can get gesubsidieerde rechtsbijstand and you only pay an eigen bijdrage.',
  },
  {
    q: 'When do I call 112 and when 0900-8844?',
    a: 'You only call 112 in an emergency: immediate danger to someone\'s life, a crime happening at that moment, or a suspicious situation. For everything that is not an emergency — a report, a question, or an appointment to file an aangifte — you call 0900-8844. You can also file many aangiftes online at politie.nl.',
  },
  {
    q: 'Which insurances are compulsory in the Netherlands?',
    a: 'Two. A zorgverzekering is compulsory for everyone who lives or works here. And if you have a car, motorbike or scooter, a WA-verzekering is compulsory. Other insurances, such as liability and home contents, are not compulsory but are sensible and usually cheap.',
  },
  {
    q: 'I have a letter from the government that I do not understand. What now?',
    a: 'Do not throw it away and do not wait. First look at the date and at the termijn within which you can respond; that is often six weeks. Then ask for help at the informatiepunt digitale overheid in the library, at the sociaal raadslieden of your gemeente or at Het Juridisch Loket. That help is free.',
  },
  ],
};

export default translation;
