/**
 * knm-examen — English.
 *
 * A translation of the Dutch body in `../knm-examen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_BOOK, I_CAP, I_CHECK, I_CLIPBOARD, I_EURO, I_HOME, I_LANDMARK, I_ROUTE, I_USER, I_USERS, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_EINDTERMEN, SRC_KENNIS, SRC_KOSTEN, SRC_PLAATSEN, SRC_REGLEMENT, SRC_ROUTES, SRC_UITSLAG, card } from '../knm-examen';

const translation: GuideLocale = {
  title: 'The KNM exam: Knowledge of Dutch Society explained',
  description: 'What is the KNM exam, which eight themes does it cover and how do you prepare? Learn about the content, the duration, the cost and the result of the KNM exam.',
  breadcrumb: 'The KNM exam',
  dateLabel: '23 August 2026',
  eyebrow: 'KNM',
  heroTitle: 'The KNM exam',
  heroSubtitle: 'KNM stands for Kennis van de Nederlandse Maatschappij (Knowledge of Dutch Society). It is not a language exam: it is about how the Netherlands works. Here you can read what is in it and how to prepare.',
  ctaTitle: 'Practise KNM with real exam questions',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after every answer. Without an account.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="wat-is-knm">What is the KNM exam?</h2>

<p>KNM is one of the exams of your inburgering (civic integration). It is not about grammar or
spelling. It is about <strong>how the Netherlands works</strong>: which doctor you go to, what you
do if your rent is too high, who makes the laws, how school works for your children.</p>

<p>You take the exam on a computer. You get questions about short videos, photos and texts. For
every question you choose an answer. The exam takes <strong>45 minutes</strong>.</p>

${factIn('en', 'DUO on KNM: "You take the KNM exam on the computer. You get different themes. For example ‘wonen’ (housing) or ‘werk en inkomen’ (work and income). For each theme you have to answer questions. The exam takes 45 minutes."', 'inburgeren.nl — Kennisexamens', SRC_KENNIS, CHECKED)}

${note('You see many websites online that write that the KNM exam has a fixed number of questions. DUO does not put that number anywhere on its own site. That is why we do not mention it. What DUO does say is written above: 45 minutes, questions about different themes.')}

<h2 id="acht-themas">The eight themes of KNM</h2>

<p>The subjects of KNM are laid down in law. Since the revised eindtermen (final attainment
levels) there are <strong>eight</strong>. Each theme has its own knowledge guide on this site.</p>

<div class="guide-cards">
  ${card(I_EURO, 'Werk en inkomen (work and income)', 'Looking for work, an employment contract, your payslip, discrimination at work, and starting your own business.')}
  ${card(I_USERS, 'Omgangsvormen, waarden en normen (manners, values and norms)', 'How people in the Netherlands deal with each other: appointments, directness, equality, and how you make contact.')}
  ${card(I_HOME, 'Wonen (housing)', 'Finding a home, renting or buying, arranging gas, water and electricity, separating waste and trouble with neighbours.')}
  ${card(I_USER, 'Gezondheid en gezondheidszorg (health and healthcare)', 'The huisarts (family doctor) as the first step, referral to the hospital, emergencies, the zorgverzekering (health insurance) and welfare work.')}
  ${card(I_BOOK, 'Geschiedenis en geografie (history and geography)', 'The main lines of Dutch history, and where the provinces, the cities and the water are.')}
  ${card(I_LANDMARK, 'Instanties (official bodies)', 'Gemeente (municipality), Belastingdienst (tax office), toeslagen (allowances), police, legal help and insurance: who does what?')}
  ${card(I_CLIPBOARD, 'Staatsinrichting en rechtsstaat (system of government and rule of law)', 'Democracy, the elections, the basic rights and the rules that everybody keeps to.')}
  ${card(I_CAP, 'Onderwijs en opvoeding (education and raising children)', 'The school system, leerplicht (compulsory education), contact with the school, and what school costs and allowances are.')}
</div>

${factIn('en', 'The KNM eindtermen have eight themes: Werk en inkomen; Omgangsvormen, waarden en normen; Wonen; Gezondheid en gezondheidszorg; Geschiedenis en geografie; Instanties; Staatsinrichting en rechtsstaat; Onderwijs en opvoeding.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

${docentIn('en', 'Many students think that KNM is a memory test with years and names. It is not. The questions are almost always about a situation: someone has pain in their stomach, someone gets a letter from the gemeente. The question is then what you do. If you practise that with real situations, it goes much faster than learning a list by heart.')}

<h2 id="moet-ik-knm">Do I have to do KNM?</h2>

<p>KNM is part of <strong>all leerroutes (learning routes)</strong> of the Wet inburgering 2021.
But not everybody takes an exam in it.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">You take the KNM exam</p>
    <ul>
      <li>${I_CHECK}<span>Are you in the <strong>B1-route</strong>? Then you take the KNM exam.</span></li>
      <li>${I_CHECK}<span>Are you in the <strong>onderwijsroute</strong> (education route)? Then you take the KNM exam.</span></li>
      <li>${I_CHECK}<span>Are you integrating under the <strong>Wet inburgering 2013</strong>? Then KNM is one of your exams too.</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">You follow KNM as lessons</p>
    <ul>
      <li>${I_X}<span>Are you in the <strong>Z-route</strong>? Then KNM is part of your course hours, and you do not take a separate exam in it.</span></li>
      <li>${I_X}<span>Have you been given a <strong>vrijstelling</strong> (exemption) or an <strong>ontheffing</strong> (waiver) by DUO? Then KNM can fall away.</span></li>
    </ul>
  </div>
</div>

<p>Are you not sure? <strong>Mijn Inburgering</strong> shows exactly which exams apply to you.
That is the only list that is correct for your situation.</p>

<h2 id="aanmelden-kosten">Registering, costs and where you take it</h2>

<p>You register through Mijn Inburgering, with DigiD. There you choose a date and a place.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Register</h3>
    <p>Log in to Mijn Inburgering and choose the exam KNM. Do this well in advance: there are often weeks between registering and the first free date.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Pay</h3>
    <p>You pay per exam. At the moment that is &euro;50 per part. If you pay with a loan from DUO, you choose that here.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Go to the exam location</h3>
    <p>You take the kennisexamens (knowledge exams) at one of the six DUO exam locations: Amsterdam, Eindhoven, Rijswijk, Rotterdam, Utrecht or Zwolle.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Result</h3>
    <p>You get the result of the kennisexamens within 8 weeks. You can see it in Mijn Inburgering.</p>
  </div></div>
</div>

${factTwoIn('en', 'DUO holds the kennisexamens and the A2 language exams at six locations: Amsterdam, Eindhoven, Rijswijk, Rotterdam, Utrecht and Zwolle. The result of these exams comes within 8 weeks.', [['inburgeren.nl — Examenplaatsen', SRC_PLAATSEN], ['inburgeren.nl — Uitslag examen', SRC_UITSLAG]], CHECKED)}

${note('Can you not come? Move or cancel your exam <strong>at least 7 days</strong> in advance through Mijn Inburgering. Then you get your money back. If you cancel later, or you do not turn up, you lose the exam fee.')}

<h2 id="cesuur">When have you passed?</h2>

<p>Here we have to be honest: <strong>DUO does not publish the pass mark for KNM</strong>.
The Examenreglement says that the limit is a <em>cesuur</em> (cut-off score) that is set by the
Minister. There is no percentage with it and no number of correct answers.</p>

<p>You often do read such numbers online. They do not come from DUO. That is why we do not put
them on this site. What you can do is make sure that you know the eight themes well — then the
exact limit is no longer your problem.</p>

${factIn('en', 'The Examenreglement inburgering states that the line between failing and passing is a cesuur that is set by the Minister. DUO does not publish a concrete number of correct answers or a percentage.', 'DUO — Examenreglement inburgering, artikel 10', SRC_REGLEMENT, CHECKED)}

<h2 id="voorbereiden">How do you prepare?</h2>

<p>Three things work, in this order.</p>

<div class="guide-cards">
  ${card(I_BOOK, 'Read theme by theme, not everything mixed', 'Take one theme at a time. Eight themes in eight sessions is better than everything at once. Every knowledge guide on this site is one theme.')}
  ${card(I_CLIPBOARD, 'Practise with questions, not with lists', 'KNM asks about situations. Learning a list of words by heart helps less than doing ten practice questions and reading the explanation.')}
  ${card(I_ROUTE, 'Look around you', 'You live in the subject. The letter from the gemeente on your doormat, the waste calendar, your child’s school: that is literally exam material.')}
</div>

${docentIn('en', 'What I see going wrong most often: people learn the right answer, but not why it is right. Then a slightly different situation comes up in the exam and suddenly the answer is not correct any more. Read the explanation with every practice question, also when you had it right.')}

${inlineCta('Practise KNM theme by theme', 'Our knowledge guides follow exactly the eight offici&euml;le themes, in simple Dutch, checked by an NT2 teacher.', '/oefenen', 'Start practising for free')}

<h2 id="zakken">And if you fail?</h2>

<p>Then you take the exam again. You only have to redo the part that you did not pass — the other
exams you have passed stay valid. You simply register again and pay the exam fee again, unless you
still have a free attempt.</p>

<p>There is no maximum to the number of times you may take an exam. But do watch your
<strong>inburgeringstermijn</strong> (integration deadline): it keeps running, and it takes weeks
before you have a new date and weeks again before the result is there. So count back from your
end date.</p>

${factIn('en', 'For the inburgeringsexamen you pay per part. At the moment that is €50 per exam. Prices are index-linked — check the current amount with DUO.', 'inburgeren.nl — Inburgeren betalen', SRC_KOSTEN, CHECKED)}

<h2 id="knm-en-de-rest">Where does KNM fit into your inburgering?</h2>

<p>KNM is one of your obligations, not the whole inburgering. Next to it you have the language
exams, and — depending on your route and your law — the PVT, the MAP or ONA.</p>

${factIn('en', 'KNM is part of all leerroutes of the Wet inburgering 2021. In the B1-route and the onderwijsroute you take an exam in it; in the Z-route you follow KNM as course hours.', 'inburgeren.nl — U gaat inburgeren', SRC_ROUTES, CHECKED)}

<p>Do you want to see the whole picture, with your own dates in it? Then use the timeline maker:
it works out by when you have to register for each exam at the latest.</p>
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>KNM is about how the Netherlands works, not about language.</li>
  <li>On the computer, 45 minutes.</li>
  <li>Eight official themes, laid down in law.</li>
  <li>At the moment &euro;50, six exam locations, result within 8 weeks.</li>
  <li>DUO does not publish the pass mark.</li>
</ul>`,

  faq: [
  {
    q: 'How many questions does the KNM exam have?',
    a: 'DUO does not give a number of questions for KNM on its own pages. What DUO does say: you take it on the computer, you get questions about different themes, and the exam takes 45 minutes. Numbers that you read elsewhere we cannot find at DUO, so we do not mention them.',
  },
  {
    q: 'How many questions do I have to get right for KNM?',
    a: 'DUO does not publish that. The Examenreglement says that the line between failing and passing is a cesuur that the Minister sets. There is no official percentage and no official number of correct answers that you can go by.',
  },
  {
    q: 'How many themes does KNM have: 7 or 8?',
    a: 'Eight. The revised eindtermen with the Regeling inburgering 2021 list eight themes: Werk en inkomen; Omgangsvormen, waarden en normen; Wonen; Gezondheid en gezondheidszorg; Geschiedenis en geografie; Instanties; Staatsinrichting en rechtsstaat; Onderwijs en opvoeding. Older course methods sometimes name seven.',
  },
  {
    q: 'Is the KNM exam in Dutch?',
    a: 'Yes. The exam is completely in Dutch, even though it is not a language exam. That is why it pays to learn the words per theme: if you do not know huisarts, verwijzing or gemeenteraad, you cannot answer the question, even when you know the answer.',
  },
  {
    q: 'Do I have to do KNM in the Z-route?',
    a: 'In the Z-route KNM is part of your course hours, not a separate exam. So you do learn the material, but you do not take an exam in it. In the B1-route and the onderwijsroute you do take the KNM exam. In Mijn Inburgering you can see what applies to you.',
  },
  {
    q: 'What does the KNM exam cost?',
    a: 'At the moment €50, just like the other parts. That price is index-linked and can change, so check it with DUO before you register. If you pay with a loan from DUO, you choose that when you register.',
  },
  ],
};

export default translation;
