/**
 * lezen-examen — English.
 *
 * A translation of the Dutch body in `../lezen-examen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_BOOK, I_CHECK, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_NT2, SRC_OEFENEN, SRC_REGELS, SRC_TAALEXAMENS, card } from '../lezen-examen';

const translation: GuideLocale = {
  title: 'The Lezen exam (A2 and B1): format, time and approach',
  description: 'How does the Lezen (reading) exam look at A2 and B1, how much time do you have per text, and which reading strategy helps you pass? Tips from an NT2 teacher.',
  breadcrumb: 'Lezen',
  dateLabel: '23 August 2026',
  eyebrow: 'Language exam',
  heroTitle: 'The Lezen exam',
  heroSubtitle: 'Reading texts and answering questions, on a computer. It looks like the easiest part, and it is the part where most people run out of time.',
  ctaTitle: 'Practise the Lezen part',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after each answer. No account.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="hoe-ziet-het-eruit">What does the exam look like?</h2>

<p>You sit at a computer. On the left there is a text, on the right there is a question with
answers. You choose one. Sometimes several questions belong to the same text.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th></th><th>A2</th><th>B1</th></tr></thead>
  <tbody>
    <tr><td><strong>Duration</strong></td><td>65 minutes</td><td>110 minutes</td></tr>
    <tr><td><strong>Where</strong></td><td>On a computer, at a DUO exam location</td><td>Staatsexamen NT2, its own locations</td></tr>
    <tr><td><strong>In DUO's oefenexamens (practice exams)</strong></td><td>25 questions</td><td>see staatsexamensnt2.nl</td></tr>
    <tr><td><strong>Type of texts</strong></td><td>Short and practical: advertisement, letter, notice, instruction</td><td>Longer and connected: news item, leaflet, article</td></tr>
  </tbody>
</table>
</div>

${factTwoIn('en', 'DUO: "Het examen Lezen op niveau A2 doet u op de computer. U moet teksten lezen. U moet ook vragen beantwoorden. Het examen duurt 65 minuten." (You take the Lezen exam at level A2 on a computer. You have to read texts. You also have to answer questions. The exam takes 65 minutes.) The Lezen exam at level B1 (staatsexamen NT2) takes 110 minutes; information about its content is on staatsexamensnt2.nl.', [['inburgeren.nl — Taalexamens', SRC_TAALEXAMENS], ['Staatsexamens NT2', SRC_NT2]], CHECKED)}

<p>DUO's A2 oefenexamens contain 25 questions. That is not a norm published by DUO for the real
exam, but it is the best number to base your preparation on: it is shown on the start screen of
the practice exams that anyone can take.</p>

${factIn('en', 'DUO makes oefenexamens (practice exams) available that anyone can take without logging in. The start screen of the A2 oefenexamens Lezen says: "U moet in dit examen 25 vragen beantwoorden" (In this exam you have to answer 25 questions), with a counter of 25 questions and 65 minutes.', 'inburgeren.nl — Oefenen', SRC_OEFENEN, CHECKED)}

<h2 id="soorten-teksten">What kind of texts do you get?</h2>

<p>At A2 they are texts from your own daily life. If you recognise them, you read them faster.</p>

<div class="guide-cards">
  ${card(I_BOOK, 'Notices', 'A note from the woningcorporatie (housing association), a sign at the entrance, an email from school about a trip.')}
  ${card(I_BOOK, 'Advertisements', 'A special offer in a leaflet, a home for rent, a second-hand bicycle.')}
  ${card(I_BOOK, 'Letters and emails', 'From an official body, a school or an association. Often with a date and an action in them.')}
  ${card(I_BOOK, 'Instructions and rules', 'How to use a device, what to do when something breaks down, house rules.')}
  ${card(I_BOOK, 'Short informative texts', 'A piece from a local newspaper or a leaflet from the gemeente (municipality).')}
</div>

<p>At B1 the texts become longer and more abstract. Then you must not only find what is written,
but also understand what the writer means and what opinion he has.</p>

<h2 id="soorten-vragen">What kind of questions do you get?</h2>

<p>Roughly three kinds, and they ask for different reading behaviour.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Search questions</h3>
    <p>"What time does the meeting start?" The answer <strong>is</strong> in the text. You do not have to read the whole text — you search.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Comprehension questions</h3>
    <p>"Why is the school sending this letter?" The answer is not there literally; you have to grasp the main idea.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Word questions</h3>
    <p>"What does the word ‘uiterlijk’ mean in this sentence?" Look at the sentences around it; the context often gives the answer away.</p>
  </div></div>
</div>

<h2 id="tijd">Time is the real exam</h2>

<p>Work it out for A2: 65 minutes for the questions of a complete oefenexamen comes down to about
<strong>two and a half minutes per question</strong> — including reading the text.
That is enough, but only if you do not get stuck.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">Do</p>
    <ul>
      <li>${I_CHECK}<span>Read <strong>the question first</strong>, and only then the text. Then you know what you are looking for.</span></li>
      <li>${I_CHECK}<span>Skip a question if you get stuck, and come back. You can go back in the exam.</span></li>
      <li>${I_CHECK}<span>Look at the heading, the date, the sender and the words in bold. Half of the answers are there.</span></li>
      <li>${I_CHECK}<span>Always fill in something. An empty answer is certainly wrong.</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Do not do</p>
    <ul>
      <li>${I_X}<span>Read every text word by word</span></li>
      <li>${I_X}<span>Stop at a word you do not know — read the sentence to the end, usually you understand it anyway</span></li>
      <li>${I_X}<span>Hesitate between two answers and spend three minutes on it</span></li>
      <li>${I_X}<span>Change your first idea without a reason</span></li>
    </ul>
  </div>
</div>

${docentIn('en', '"First the question, then the text" is the tip that makes the biggest difference with my students. They read a text from top to bottom, forget what they have read, and then read it again. Reading twice costs you the exam. Searching once with a purpose does not.')}

<h2 id="valkuilen">Three pitfalls</h2>

<ul>
  <li><strong>The answer that is almost there.</strong> Often one wrong option looks a lot like the text, but one word is not right — "altijd" (always) against "meestal" (usually), "moet" (must) against "mag" (may). Read the options just as precisely as the text.</li>
  <li><strong>Your own knowledge.</strong> The answer must come from <em>this</em> text, even if you yourself know something different.</li>
  <li><strong>Negations.</strong> "What is <em>not</em> true?" Underline that word in your head; many points are lost here by people who understood the text perfectly well.</li>
</ul>

${note('On your exam day: bring a valid identity document and be on time. If you are late, you can be refused, and then you lose your exam fee. The rules are on the DUO website.')}

${factIn('en', 'Fixed rules apply to the inburgeringsexamen about, among other things, identification and arriving late; DUO publishes these in the rules for the exam and in the Examenreglement.', 'inburgeren.nl — Regels voor het examen', SRC_REGELS, CHECKED)}

<h2 id="oefenen">How to practise</h2>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Read something real every day</h3>
    <p>A leaflet, the post, a message from school, a news app in simple Dutch. Fifteen minutes a day does more than three hours at the weekend.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Practise with the clock</h3>
    <p>Set a timer. Not because you have to read fast, but because you have to learn to feel when you are staying too long on one question.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Read the explanation, also for correct answers</h3>
    <p>What you have to learn is not the answer but the <em>reason</em>. Otherwise you will choose wrongly again with the next, slightly different question.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Do a complete oefenexamen</h3>
    <p>At least three times, in one go, without a break. That trains something different from single questions: keeping going.</p>
  </div></div>
</div>

${inlineCta('Practise Lezen with real exam questions', 'Ten questions, with an explanation after each answer. No account and no payment.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>A2: 65 minutes on the computer; B1: 110 minutes (staatsexamen NT2).</li>
  <li>DUO's A2 oefenexamens have 25 questions.</li>
  <li>Read the question first, then the text.</li>
  <li>Skip a question and come back; always fill in something.</li>
  <li>Watch out for negations and for options that are "almost" in the text.</li>
</ul>`,

  faq: [
  {
    q: 'How long does the Lezen exam take?',
    a: 'At level A2 it takes 65 minutes and you take it on a computer. At level B1 it is part of the staatsexamen NT2 and it takes 110 minutes. Information about the content of the B1 exam is on staatsexamensnt2.nl.',
  },
  {
    q: 'How many questions does the Lezen A2 exam have?',
    a: 'DUO does not publish this as an official norm. DUO\'s public oefenexamens Lezen A2 contain 25 questions in 65 minutes, and that is the best number to base your preparation on.',
  },
  {
    q: 'May I go back to a previous question?',
    a: 'Yes. Within the exam you can go forward and back, and you can still change an answer as long as the time is running. Use that: skip a question you get stuck on and come back to it at the end with the time you have left.',
  },
  {
    q: 'What do I do with words I do not know?',
    a: 'Do not stop. Read the sentence and the sentence after it to the end; very often the meaning then becomes clear from the context. The exam tests whether you understand the text, not whether you know every word. If you stay stuck, skip the question and come back later.',
  },
  {
    q: 'May I bring a dictionary to the exam?',
    a: 'No. At the inburgeringsexamen you may not use any aids of your own. Do bring a valid identity document and make sure you are on time; arriving late can mean that you may not take part and that you lose your exam fee.',
  },
  ],
};

export default translation;
