/**
 * luisteren-examen — Arabic.
 *
 * A translation of the Dutch body in `../luisteren-examen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_HEADPHONES, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_AANGEPAST, SRC_NT2, SRC_OEFENEN, SRC_TAALEXAMENS, card } from '../luisteren-examen';

const translation: GuideLocale = {
  title: 'امتحان Luisteren (A2 وB1): الشكل والوقت وطريقة التحضير',
  description: 'استماع إلى مقاطع فيديو ومحادثات والإجابة عن أسئلة. كيف يجري امتحان Luisteren في المستويين A2 وB1، وأين يذهب الوقت، وكيف تستعد له بالتدريب اليومي.',
  breadcrumb: 'Luisteren',
  dateLabel: '23 أغسطس 2026',
  eyebrow: 'امتحان اللغة',
  heroTitle: 'امتحان Luisteren (الاستماع)',
  heroSubtitle: 'تستمع إلى محادثات وإعلانات وتجيب عن أسئلة تتعلق بها. الأمر يجري بسرعة، ولا يمكنك العودة بالزمن إلى الوراء — لذلك فإن هذا هو الجزء الذي يعطي فيه التحضير أكبر مردود.',
  ctaTitle: 'تدرَّب على جزء Luisteren',
  ctaDesc: 'امتحان تجريبي مجاني من عشرة أسئلة مع صوت، وشرح بعد كل إجابة.',
  ctaLabel: 'ابدأ امتحاناً تجريبياً مجانياً',

  articleHtml: `
<h2 id="hoe-ziet-het-eruit">كيف يبدو الامتحان؟</h2>

<p>تجلس أمام جهاز كمبيوتر وعلى رأسك سماعة. تُعرض عليك مقاطع فيديو وتستمع إلى نصوص، ثم تأتي أسئلة
مع إجابات تختار من بينها.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th></th><th>A2</th><th>B1</th></tr></thead>
  <tbody>
    <tr><td><strong>المدة</strong></td><td>45 دقيقة</td><td>90 دقيقة</td></tr>
    <tr><td><strong>المكان</strong></td><td>على الكمبيوتر، في أحد مواقع امتحانات DUO</td><td>Staatsexamen NT2 (امتحان الدولة)، مواقع خاصة به</td></tr>
    <tr><td><strong>في امتحانات التدريب من DUO</strong></td><td>25 سؤالاً</td><td>انظر staatsexamensnt2.nl</td></tr>
    <tr><td><strong>ما الذي تسمعه</strong></td><td>محادثات قصيرة، مكالمات هاتفية، إعلانات، رسائل إذاعية عامة</td><td>محادثات أطول ونصوص معلوماتية أطول</td></tr>
  </tbody>
</table>
</div>

${factTwoIn('ar', 'DUO: "امتحان Luisteren في المستوى A2 تؤديه على الكمبيوتر. تحصل على أسئلة عن مقاطع فيديو وتستمع إلى نصوص. يستغرق الامتحان 45 دقيقة." أما امتحان Luisteren في المستوى B1 (staatsexamen NT2) فيستغرق 90 دقيقة؛ والمعلومات عن محتواه موجودة على staatsexamensnt2.nl.', [['inburgeren.nl — Taalexamens', SRC_TAALEXAMENS], ['Staatsexamens NT2', SRC_NT2]], CHECKED)}

${factIn('ar', 'على شاشة البدء في امتحانات التدريب العلنية من DUO لمهارة Luisteren في المستوى A2 مكتوب: "عليك الإجابة عن 25 سؤالاً في هذا الامتحان"، مع عدّاد يبيّن 25 سؤالاً و45 دقيقة.', 'inburgeren.nl — Oefenen', SRC_OEFENEN, CHECKED)}

<p>لاحظ الفرق مع Lezen (القراءة): لديك <strong>وقت أقل لعدد الأسئلة نفسه</strong>. والسبب أن الصوت
نفسه يستغرق وقتاً. لذلك لا يمكنك التفكير طويلاً.</p>

<h2 id="wat-hoor-je">ما الذي تسمعه بالضبط؟</h2>

<p>في المستوى A2 تكون المقاطع قصيرة ومن الحياة اليومية. وعادةً يرتبط بالمقطع الواحد سؤالان أو
ثلاثة أسئلة.</p>

<div class="guide-cards">
  ${card(I_HEADPHONES, 'محادثة بين شخصين', 'عند شبّاك الاستقبال، عند الطبيب، بين الجيران، في العمل. انتبه إلى مَن يقول ماذا.')}
  ${card(I_HEADPHONES, 'مكالمة هاتفية', 'غالباً تتضمن موعداً أو وقتاً أو عنواناً. الأرقام هنا هي حجر العثرة.')}
  ${card(I_HEADPHONES, 'إعلان أو بلاغ', 'بلاغ عبر مكبر الصوت في المحطة، رسالة على البريد الصوتي، إعلان داخل المتجر.')}
  ${card(I_HEADPHONES, 'شرح قصير', 'شخص يشرح كيف يعمل شيء ما أو ماذا سيحدث.')}
</div>

${docentIn('ar', 'معظم الأخطاء في Luisteren لا تتعلق بالكلمات بل بـ<strong>الأرقام</strong>: الأوقات وأرقام المنازل والمبالغ والأيام. فـ"half vier" ليست الساعة الرابعة، و"over een kwartier" ليست وقتاً محدداً بل فارقاً زمنياً. تدرَّب على ذلك على حدة — فهو جزء صغير من اللغة لكن حصته في الأسئلة كبيرة.')}

<h2 id="strategie">الاستراتيجية: اقرأ مسبقاً</h2>

<p>في Luisteren يمكنك أن تفعل شيئاً واحداً يحدد كل شيء تقريباً: <strong>اقرأ السؤال قبل أن يبدأ
الصوت</strong>. عندها تعرف ما الذي يجب أن تنتبه إليه، بدل أن تحاول حفظ كل شيء.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>اقرأ السؤال والإجابات</h3>
    <p>ما المطلوب: وقت، أم سبب، أم شعور، أم مكان؟ هذا يحدد ما الذي عليك التقاطه من الصوت.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>استمع إلى الخط العام، لا إلى كل كلمة</h3>
    <p>لا يلزم أن تفهم كل شيء. عليك أن تجد شيئاً واحداً. دع الباقي يمرّ.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>اختر، ثم امضِ قُدُماً</h3>
    <p>لا تبقَ منشغلاً بالسؤال السابق بينما المقطع التالي يعمل بالفعل. هذا يكلفك سؤالين بدل سؤال واحد.</p>
  </div></div>
</div>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">افعل</p>
    <ul>
      <li>${I_CHECK}<span>انتبه إلى كلمات الإشارة: <em>maar</em> (لكن)، <em>toch</em> (مع ذلك)، <em>helaas</em> (للأسف)، <em>eerst</em> (أولاً)، <em>daarna</em> (بعد ذلك). غالباً ما تكون الإجابة هناك.</span></li>
      <li>${I_CHECK}<span>انتبه إلى نبرة الصوت. كلمة "Nou…" مع تردد تعني عادةً لا.</span></li>
      <li>${I_CHECK}<span>افحص السماعة ومستوى الصوت قبل أن يبدأ الامتحان.</span></li>
      <li>${I_CHECK}<span>أدخل إجابة دائماً، حتى لو فاتك المقطع.</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">لا تفعل</p>
    <ul>
      <li>${I_X}<span>أن تحاول ترجمة المقطع كاملاً في رأسك</span></li>
      <li>${I_X}<span>أن تختار الإجابة التي تعرّفت فيها على كلمة سمعتها — فهذا غالباً هو الفخ بعينه</span></li>
      <li>${I_X}<span>أن تصاب بالذعر أمام متحدث سريع؛ فالسؤال عادةً يتعلق بجملة واحدة</span></li>
    </ul>
  </div>
</div>

<h2 id="valkuil">أكبر فخ: الكلمة التي تعرّفت عليها</h2>

<p>في Luisteren تُصاغ الإجابات الخاطئة كثيراً بكلمات سمعتها <em>أيضاً</em> في المقطع. يقول أحدهم:
"ik wilde eerst met de trein, maar nu ga ik met de fiets" (كنت أريد أولاً الذهاب بالقطار، لكنني
الآن سأذهب بالدراجة). والسؤال هو كيف سيذهب. من يتعرّف على كلمة "trein" يختار خطأً.</p>

<p>لذلك استمع دائماً إلى الجملة حتى نهايتها. أهم كلمة في هذا المثال هي
<strong>maar</strong>.</p>

${note('هل لديك إعاقة سمعية؟ يمكن لـ DUO تعديل الامتحان، مثلاً بوقت إضافي أو بأجهزة معدَّلة. تقدّم هذا الطلب مسبقاً مع إفادة طبية. رتّب ذلك قبل التسجيل بوقت كافٍ.')}

${factIn('ar', 'إذا كنت لا تستطيع أداء الامتحان بالطريقة العادية بسبب مرض أو إعاقة، فيمكن لـ DUO أن يسمح بامتحان معدَّل. تتقدّم بهذا الطلب مسبقاً إلى DUO.', 'inburgeren.nl — Aangepast examen bij ziekte of beperking', SRC_AANGEPAST, CHECKED)}

<h2 id="oefenen">كيف تتدرّب</h2>

<p>Luisteren هو الجزء الذي يتحسّن أسرع ما يكون بالعادات اليومية، وأبطأ ما يكون بالكتب.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>شغّل الهولندية كل يوم</h3>
    <p>الراديو في المطبخ، بودكاست بهولندية مبسّطة، نشرة الأخبار للأطفال jeugdjournaal. حتى إن لم تفهم كل شيء: أذنك تعتاد على الإيقاع.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>شاهد مع ترجمة نصية هولندية</h3>
    <p>وليس مع ترجمة بلغتك. الصوت الهولندي مع النص الهولندي يربط الصوت بالكلمة، وهذا بالضبط ما يطلبه الامتحان.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>تدرّب على الأرقام على حدة</h3>
    <p>الأوقات والأسعار وأرقام المنازل والتواريخ. اطلب من أحدهم أن يذكرها لك، أو استخدم تطبيقاً للتدريب. عشر دقائق يومياً، لمدة أسبوعين.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>أدِّ امتحانات تدريبية بسماعة رأس</h3>
    <p>وليس عبر مكبر صوت هاتفك. أنت تريد أن تعتاد على الطريقة التي يبدو بها الصوت في قاعة الامتحان.</p>
  </div></div>
</div>

${docentIn('ar', 'أسمع كثيراً: "أنا أفهم الهولنديين في الواقع، لكن ليس في الامتحان." السبب هو التوتر وغياب السياق — فأنت لا ترى وجهاً ولا تعرف الموقف. ولا ينفع ضد ذلك سوى شيء واحد: أن تتدرّب على التسجيلات بما يكفي من التكرار، إلى أن يزول شعور الجِدّة.')}

${inlineCta('تدرَّب على Luisteren بمقاطع صوتية حقيقية', 'عشرة أسئلة مع صوت، وشرح بعد كل إجابة. بدون حساب.', '/oefenen', 'ابدأ امتحاناً تجريبياً مجانياً')}
`,

  sidebarHtml: `
<p><strong>باختصار</strong></p>
<ul>
  <li>A2: 45 دقيقة على الكمبيوتر؛ B1: 90 دقيقة (staatsexamen NT2).</li>
  <li>امتحانات التدريب من DUO للمستوى A2 تضم 25 سؤالاً.</li>
  <li>اقرأ السؤال قبل أن يبدأ الصوت.</li>
  <li>احذر من الإجابات التي تحتوي على كلمة سمعتها لكنها ليست صحيحة.</li>
  <li>تدرّب على الأرقام والأوقات والتواريخ على حدة.</li>
</ul>`,

  faq: [
  {
    q: 'كم يستغرق امتحان Luisteren؟',
    a: 'في المستوى A2 يستغرق 45 دقيقة، على الكمبيوتر. وفي المستوى B1 يكون جزءاً من staatsexamen NT2 ويستغرق 90 دقيقة. المعلومات عن محتوى امتحان B1 موجودة على staatsexamensnt2.nl.',
  },
  {
    q: 'هل يمكنني الاستماع إلى المقطع مرة أخرى؟',
    a: 'في امتحاناتنا التدريبية نعم: يمكنك تشغيل المقطع بقدر ما تشاء، حتى تتعلم أين وقع الخطأ. أما كم مرة يمكن ذلك في الامتحان الحقيقي فلا ينشره DUO. لذلك افترض عند التدريب، في مرحلة ما، أن لديك فرصة واحدة فقط.',
  },
  {
    q: 'ما أفضل طريقة للتدرّب على Luisteren؟',
    a: 'أن تسمع الهولندية كل يوم، وبشكل موجَّه. شغّل الراديو أو بودكاست بهولندية مبسّطة، وشاهد مع ترجمة نصية هولندية بدلاً من لغتك، وتدرّب على الأرقام والأوقات والتواريخ على حدة. إضافةً إلى ذلك، أدِّ امتحانات تدريبية كاملة وأنت تضع سماعة رأس.',
  },
  {
    q: 'أنا أفهم الناس في الواقع، لكن ليس في الامتحان. كيف يحدث ذلك؟',
    a: 'لأنك في الواقع ترى الوجه وتعرف الموقف ويمكنك أن تطلب التكرار. أما في الامتحان فكل ذلك يغيب، ويُضاف إليه ضغط الوقت. وهذا أمر قابل للتدريب: تدرّب على التسجيلات إلى أن يصبح الموقف غير جديد بالنسبة إليك.',
  },
  {
    q: 'لديّ إعاقة سمعية. هل يمكنني الحصول على امتحان معدَّل؟',
    a: 'نعم، هذا ممكن. إذا كنت لا تستطيع أداء الامتحان بالطريقة العادية بسبب مرض أو إعاقة، فيمكن لـ DUO أن يسمح بامتحان معدَّل، مثلاً بوقت إضافي أو بأجهزة أخرى. تتقدّم بهذا الطلب مسبقاً إلى DUO، قبل تسجيلك لموعد بوقت كافٍ.',
  },
  ],
};

export default translation;
