/**
 * luisteren-examen — English.
 *
 * A translation of the Dutch body in `../luisteren-examen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_HEADPHONES, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_AANGEPAST, SRC_NT2, SRC_OEFENEN, SRC_TAALEXAMENS, card } from '../luisteren-examen';

const translation: GuideLocale = {
  title: 'The Luisteren exam (A2 and B1): format, time and approach',
  description: 'Watch clips and listen to conversations, then answer questions. How the Luisteren exam works at A2 and B1, where the time goes and how to practise.',
  breadcrumb: 'Luisteren',
  dateLabel: '23 August 2026',
  eyebrow: 'Language exam',
  heroTitle: 'The Luisteren exam',
  heroSubtitle: 'In Luisteren (listening) you hear conversations and announcements and answer questions about them. It goes fast, and you cannot go back in time — that is why this is the part where preparation pays off most.',
  ctaTitle: 'Practise the Luisteren part',
  ctaDesc: 'Free practice exam of ten questions with audio, with an explanation after every answer.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="hoe-ziet-het-eruit">What does the exam look like?</h2>

<p>You sit at a computer with headphones on. You see short films and hear texts, and after that you
get questions with answers to choose from.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th></th><th>A2</th><th>B1</th></tr></thead>
  <tbody>
    <tr><td><strong>Duration</strong></td><td>45 minutes</td><td>90 minutes</td></tr>
    <tr><td><strong>Where</strong></td><td>On the computer, at a DUO exam location</td><td>Staatsexamen NT2, its own locations</td></tr>
    <tr><td><strong>In DUO's practice exams</strong></td><td>25 questions</td><td>see staatsexamensnt2.nl</td></tr>
    <tr><td><strong>What you hear</strong></td><td>Short conversations, telephone calls, announcements, public address messages</td><td>Longer conversations and longer informative texts</td></tr>
  </tbody>
</table>
</div>

${factTwoIn('en', 'DUO: "You take the Luisteren exam at level A2 on the computer. You get questions about short films and you listen to texts. The exam takes 45 minutes." The Luisteren exam at level B1 (staatsexamen Nt2) takes 90 minutes; information about the content is on staatsexamensnt2.nl.', [['inburgeren.nl — Taalexamens', SRC_TAALEXAMENS], ['Staatsexamens NT2', SRC_NT2]], CHECKED)}

${factIn('en', 'On the start screen of DUO’s public practice exams Luisteren A2 it says: "You must answer 25 questions in this exam", with a counter of 25 questions and 45 minutes.', 'inburgeren.nl — Oefenen', SRC_OEFENEN, CHECKED)}

<p>Note the difference with Lezen (reading): you have <strong>less time for the same number of
questions</strong>. That is because the audio itself takes time. So you cannot think for long.</p>

<h2 id="wat-hoor-je">What exactly do you hear?</h2>

<p>At A2 they are short fragments from daily life. One fragment usually has two or three
questions.</p>

<div class="guide-cards">
  ${card(I_HEADPHONES, 'A conversation between two people', 'At a counter, at the doctor, between neighbours, at work. Pay attention to who says what.')}
  ${card(I_HEADPHONES, 'A telephone call', 'Often with an appointment, a time or an address in it. Numbers are the stumbling block here.')}
  ${card(I_HEADPHONES, 'An announcement', 'A public address message at the station, a voicemail, an announcement in a shop.')}
  ${card(I_HEADPHONES, 'A short explanation', 'Someone explains how something works or what is going to happen.')}
</div>

${docentIn('en', 'Most mistakes in Luisteren are not about words but about <strong>numbers</strong>: times, house numbers, amounts, days. "Half vier" (half past three) is not four o’clock, and "over een kwartier" (in a quarter of an hour) is not a point in time but a difference. Practise that separately — it is a small part of the language with a large share of the questions.')}

<h2 id="strategie">The strategy: read ahead</h2>

<p>With Luisteren there is one thing you can do that decides almost everything: <strong>read the
question before the audio starts</strong>. Then you know what to listen for, instead of trying to
remember everything.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Read the question and the answers</h3>
    <p>What is being asked: a time, a reason, a feeling, a place? That decides what you have to pick out of the audio.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Listen to the main line, not to every word</h3>
    <p>You do not have to understand everything. You have to find one thing. Let the rest go by.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Choose, and move on</h3>
    <p>Do not keep worrying about the previous question while the next fragment is already playing. That costs you two questions instead of one.</p>
  </div></div>
</div>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">Do</p>
    <ul>
      <li>${I_CHECK}<span>Pay attention to signal words: <em>maar</em> (but), <em>toch</em> (yet), <em>helaas</em> (unfortunately), <em>eerst</em> (first), <em>daarna</em> (after that). The answer is often there.</span></li>
      <li>${I_CHECK}<span>Pay attention to the tone. "Nou…" with hesitation usually means no.</span></li>
      <li>${I_CHECK}<span>Check your headphones and the volume before the exam starts.</span></li>
      <li>${I_CHECK}<span>Always fill in something, even if you missed the fragment.</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Do not</p>
    <ul>
      <li>${I_X}<span>Try to translate the whole fragment in your head</span></li>
      <li>${I_X}<span>Choose the answer in which you recognised a word that you heard — that is often exactly the trap</span></li>
      <li>${I_X}<span>Panic when a speaker is fast; the question is usually about one sentence</span></li>
    </ul>
  </div>
</div>

<h2 id="valkuil">The biggest trap: the word you recognised</h2>

<p>In Luisteren, wrong answers are often made with words that you <em>also</em> heard in the
fragment. Someone says: "ik wilde eerst met de trein, maar nu ga ik met de fiets" (at first I wanted
to go by train, but now I am going by bike). The question is how he travels. Anyone who recognises
"trein" chooses the wrong answer.</p>

<p>So always listen to the end of the sentence. The most important word in that example is
<strong>maar</strong> (but).</p>

${note('Do you have a hearing impairment? DUO can adapt the exam, for example with extra time or adapted equipment. You apply for this in advance, with a statement. Arrange it well before you register.')}

${factIn('en', 'If you cannot take the exam in the normal way because of an illness or a disability, DUO can allow an adapted exam. You apply for this in advance at DUO.', 'inburgeren.nl — Aangepast examen bij ziekte of beperking', SRC_AANGEPAST, CHECKED)}

<h2 id="oefenen">How to practise</h2>

<p>Luisteren is the part that improves fastest from daily habits, and slowest from books.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Turn on Dutch, every day</h3>
    <p>Radio in the kitchen, a podcast in simple Dutch, the jeugdjournaal (news for children). Even if you do not understand everything: your ear gets used to the speed.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Watch with Dutch subtitles</h3>
    <p>Not with subtitles in your own language. Dutch sound with Dutch text links the sound to the word, and that is exactly what the exam asks.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Practise numbers separately</h3>
    <p>Times, prices, house numbers, dates. Let someone say them out loud, or use a practice app. Ten minutes a day, for two weeks.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Do practice exams with headphones</h3>
    <p>Not through the speaker of your phone. You want to get used to how it sounds in the exam room.</p>
  </div></div>
</div>

${docentIn('en', 'I often hear: "I do understand Dutch people in real life, but not in the exam." That is because of the tension and because of the lack of context — you do not see a face, you do not know the situation. Only one thing helps against that: practising with recordings often enough, until it no longer feels new.')}

${inlineCta('Practise Luisteren with real fragments', 'Ten questions with audio, with an explanation after every answer. No account needed.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>A2: 45 minutes on the computer; B1: 90 minutes (staatsexamen NT2).</li>
  <li>DUO's A2 practice exams have 25 questions.</li>
  <li>Read the question before the audio starts.</li>
  <li>Watch out for answers with a word that you did hear but that is not correct.</li>
  <li>Practise numbers, times and dates separately.</li>
</ul>`,

  faq: [
  {
    q: 'How long does the Luisteren exam take?',
    a: 'At level A2 it takes 45 minutes, on the computer. At level B1 it is part of the staatsexamen NT2 and it takes 90 minutes. Information about the content of the B1 exam is on staatsexamensnt2.nl.',
  },
  {
    q: 'Can I listen to a fragment again?',
    a: 'In our practice exams you can: you can play a fragment as often as you like, so that you can learn where it went wrong. How often that is possible in the real exam is not published by DUO. So when you practise, at some point assume that you have only one chance.',
  },
  {
    q: 'What is the best way to practise Luisteren?',
    a: 'Hear Dutch every day, and do it in a focused way. Turn on the radio or a podcast in simple Dutch, watch with Dutch subtitles instead of subtitles in your own language, and practise numbers, times and dates separately. Also do complete practice exams with headphones on.',
  },
  {
    q: 'I do understand people in real life, but not in the exam. How is that possible?',
    a: 'Because in real life you see the face, you know the situation and you can ask for repetition. In the exam all of that falls away, and time pressure is added. You can train for that: practise with recordings until the situation no longer feels new.',
  },
  {
    q: 'I have a hearing impairment. Can I get an adapted exam?',
    a: 'Yes, that is possible. If you cannot take the exam in the normal way because of an illness or a disability, DUO can allow an adapted exam, for example with extra time or other equipment. You apply for this in advance at DUO, well before you register for a date.',
  },
  ],
};

export default translation;
