/**
 * omgangsvormen-waarden-en-normen — English.
 *
 * A translation of the Dutch body in `../omgangsvormen-waarden-en-normen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_CLIPBOARD, I_HOME, I_USERS, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_DISCRIMINATIE, SRC_EINDTERMEN, SRC_GRONDWET, SRC_PVT, SRC_VRIJWILLIG, card } from '../omgangsvormen-waarden-en-normen';

const translation: GuideLocale = {
  title: 'KNM: Manners, Values and Norms in the Netherlands',
  description: 'How do people in the Netherlands treat each other? About making appointments, directness, equality and making contact. The KNM theme Manners, values and norms.',
  breadcrumb: 'Manners',
  dateLabel: '23 August 2026',
  eyebrow: 'KNM theme 2',
  heroTitle: 'Manners, values and norms',
  heroSubtitle: 'This theme is about how people here treat each other: what is normal, what is allowed, and what the law says about it. And about how you make contact yourself.',
  ctaTitle: 'Practise the theme Manners',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after every answer. No account needed.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="wat-vraagt-knm">What does KNM ask about this theme?</h2>

<p>This theme has two eindtermen (attainment targets): you can <strong>interpret omgangsvormen (manners)</strong> — that is, understand what is happening in a situation — and you can <strong>take part in social networks</strong>.</p>

<p>Note the word <em>duiden</em> (to interpret). The exam does not ask whether you adapt. It asks whether you can read a situation: why does that neighbour react like this, what is expected of me here?</p>

${factIn('en', 'The KNM eindtermen for the theme Omgangsvormen, waarden en normen are: interpreting different manners in the Netherlands, and taking part in social networks.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

<h2 id="waarden">Values: what is laid down in law</h2>

<p>There is a difference between <strong>values</strong> and <strong>habits</strong>. Values are laid
down in law and apply to everyone. Habits differ per person, per city and per family.</p>

<p>The very first article of the Grondwet (Constitution) says that everyone in the Netherlands is
treated equally in equal cases, and that discrimination is not allowed — not on grounds of religion,
belief, political opinion, race, sex, disability or sexual orientation, and not on any other grounds
either.</p>

${factIn('en', 'Article 1 of the Grondwet: "All persons in the Netherlands shall be treated equally in equal circumstances. Discrimination on the grounds of religion, belief, political opinion, race, sex, disability, sexual orientation or on any other grounds whatsoever shall not be permitted."', 'wetten.overheid.nl — Grondwet artikel 1', SRC_GRONDWET, CHECKED)}

<p>As part of your inburgering (civic integration) you sign the
<strong>participatieverklaringstraject</strong> (PVT, participation declaration programme). That is
exactly this subject, but in the form of a signature. It is about four core values:</p>

<div class="guide-cards">
  ${card(I_USERS, 'Freedom', 'Everyone may say what they think and believe what they want. Also if someone else does not agree.')}
  ${card(I_USERS, 'Equality', 'Men and women are equal. People of different origin, religion or orientation are equal.')}
  ${card(I_USERS, 'Solidarity', 'Together we take care of people who are having a hard time, through taxes, insurance and help.')}
  ${card(I_USERS, 'Participation', 'Taking part is expected: working, learning, volunteering, or contributing in another way.')}
</div>

<p>Freedom has one limit, and that limit is the freedom of another person. You may say what you
think — but discriminating, threatening or inciting hatred is not allowed.</p>

${factTwoIn('en', 'In the participatieverklaringstraject you learn what is important in the Netherlands: "Everyone in the Netherlands is equal. Everyone may choose for themselves what they believe. Everyone may say what they think. But discriminating is not allowed." After that you sign the participatieverklaring.', [['inburgeren.nl — Kennisexamens en PVT', SRC_PVT], ['Rijksoverheid — Discriminatie', SRC_DISCRIMINATIE]], CHECKED)}

<h2 id="gewoontes">Habits: what you often see</h2>

<p>Now the habits. These are <strong>not rules</strong>, and not every Dutch person does it this way.
But you meet them often, and the exam uses them in situations.</p>

<h3>Appointments and time</h3>
<ul>
  <li>Being on time is important. If you are later than agreed, send a message.</li>
  <li>Dropping by without an appointment is not usual, not even with friends. Call or send an app message first.</li>
  <li>Having a diary is normal. "Shall we meet in two weeks?" is not a rejection.</li>
</ul>

<h3>Talking with each other</h3>
<ul>
  <li>People often say quite directly what they think. That is usually not meant to be rude.</li>
  <li>Saying "no" is allowed, and is not seen as an insult.</li>
  <li>You address adults you do not know with <em>u</em> (the formal you). Often the other person will then say: "zeg maar je" (just use je, the informal you).</li>
  <li>At a first meeting you usually shake hands. If you do not want to, you may say so — a friendly greeting is fine too.</li>
</ul>

<h3>At home and visiting</h3>
<ul>
  <li>You are invited for a certain time, and there is then usually either food or no food. Feel free to ask.</li>
  <li>At a birthday you also congratulate the family of the person whose birthday it is.</li>
  <li>In a caf&eacute; or restaurant people often each pay for themselves. This is called "gaan we splitten?" (shall we split the bill?).</li>
</ul>

${docentIn('en', 'I say it every year to a new group: directness here is not anger. If your colleague says "that report is not correct", he is saying something about the report, not about you. For many course participants that is the biggest difference, bigger than the language.')}

${note('The same is true the other way round: your habits are not wrong. You do not have to give up your own ways in order to integrate. The exam asks whether you <em>recognise</em> Dutch habits — not whether you take them over.')}

<h2 id="netwerken">Taking part in social networks</h2>

<p>The second eindterm is practical: how do you get in contact with people? For work, for the
language and for yourself this is the most important thing you can do.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">This works</p>
    <ul>
      <li>${I_CHECK}<span>Vrijwilligerswerk (volunteer work) — you practise the language and you meet people outside your own circle</span></li>
      <li>${I_CHECK}<span>A taalmaatje (language buddy) or taalcaf&eacute; (language caf&eacute;) through the library or VluchtelingenWerk</span></li>
      <li>${I_CHECK}<span>A sports club or association in the neighbourhood</span></li>
      <li>${I_CHECK}<span>Your children's school: parents' evenings, helping out on a school trip</span></li>
      <li>${I_CHECK}<span>Saying hello to your neighbours, and introducing yourself if you are new</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">This slows you down</p>
    <ul>
      <li>${I_X}<span>Contact only with people from your own country — understandable, but then you hear little Dutch</span></li>
      <li>${I_X}<span>Waiting until somebody invites you. Here you take the initiative yourself.</span></li>
      <li>${I_X}<span>Thinking that you may only take part once you speak good Dutch</span></li>
    </ul>
  </div>
</div>

${factIn('en', 'Vrijwilligerswerk is unpaid work for an organisation or association. The Rijksoverheid calls it a way of taking part in society; gemeenten and volunteer centres help arrange it.', 'Rijksoverheid — Vrijwilligerswerk', SRC_VRIJWILLIG, CHECKED)}

${docentIn('en', 'Vrijwilligerswerk is the best language lesson there is, and it is free. Two half-days a week in a buurthuis (community centre) or a kringloopwinkel (second-hand shop) does more for your speaking skills than an extra course book. And it goes on your CV.')}

<h2 id="in-het-examen">How this comes back in the exam</h2>

<p>Almost always as a situation with a question after it. A colleague says something, a neighbour
knocks at the door, you get an invitation. The question is then: what does this mean, or what do you
do?</p>

<p>Two rules of thumb help with this theme:</p>

<div class="guide-cards">
  ${card(I_CLIPBOARD, 'Talk about it yourself first', 'With a problem with a neighbour, a colleague or a school, the first good answer is almost always: start the conversation. Only after that does an official body come into the picture.')}
  ${card(I_HOME, 'Nobody has to give way', 'Answers in which someone is treated unequally because of sex, religion or origin are never correct in this exam. That is Article 1.')}
</div>

${inlineCta('Practise this theme with exam questions', 'Situations like in the real KNM exam, with an explanation after every answer.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>Values are laid down in law; habits differ per person.</li>
  <li>Article 1 Grondwet: equal treatment, no discrimination.</li>
  <li>Four core values of the PVT: freedom, equality, solidarity, participation.</li>
  <li>Making appointments, being on time and talking directly are normal here.</li>
  <li>Vrijwilligerswerk is the fastest route to contact and language.</li>
</ul>`,

  faq: [
  {
    q: 'What is the difference between a value and a norm?',
    a: 'A value is what people find important, for example equality or freedom. A norm is the rule that follows from it, for example that you may not discriminate against someone. Values such as equality are in the Grondwet (Constitution); many norms are habits and are not written down anywhere.',
  },
  {
    q: 'Do I have to shake hands if I do not want to?',
    a: 'No, that is not compulsory. Shaking hands is a habit, not a law. You can greet someone in a friendly way and explain that you do not shake hands. Do keep in mind that some employers or schools do attach value to it; the conversation about it is then more important than the handshake itself.',
  },
  {
    q: 'Why are Dutch people so direct?',
    a: 'Directness is seen here as honest and clear, not as rude. Someone who criticises your work usually says nothing about you as a person by doing so. But note: not every Dutch person is direct, and the exam asks whether you can read the situation, not whether you become like that yourself.',
  },
  {
    q: 'How do I make contact with Dutch people?',
    a: 'Take the initiative yourself and look for places where you regularly see the same people: vrijwilligerswerk (volunteer work), a sports club, a taalcafé (language café) in the library or your children\'s school. You do not have to wait until your Dutch is good; most people actually like it when you try.',
  },
  {
    q: 'What is the participatieverklaring?',
    a: 'A declaration that you sign at your gemeente (municipality), as part of your inburgering. You declare that you want to take an active part in Dutch society and that you respect what is important here: freedom, equality, solidarity and participation. The gemeente informs DUO that you have signed.',
  },
  ],
};

export default translation;
