/**
 * ona-examen — English.
 *
 * A translation of the Dutch body in `../ona-examen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_ALERT, I_CHECK, I_CLIPBOARD, I_CLOCK, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_BETALEN, SRC_EXAMENS, SRC_KENNIS, SRC_ONA_PDF, SRC_SCHOLEN, card, row } from '../ona-examen';

const translation: GuideLocale = {
  title: 'The ONA exam: portfolio, eindgesprek and planning',
  description: 'ONA is part of the Wet 2013: eight resultaatkaarten, six weeks of marking and then a final interview or 64 hours of course. How to build it in time.',
  breadcrumb: 'The ONA exam',
  dateLabel: '24 August 2026',
  eyebrow: 'Exam part',
  heroTitle: 'The ONA exam',
  heroSubtitle: 'Oriëntatie op de Nederlandse Arbeidsmarkt (orientation on the Dutch labour market). Not a test you sit on one morning, but a portfolio you build yourself — and one that most people start too late.',
  ctaTitle: 'Work on your language exams in the meantime',
  ctaDesc: 'A free practice exam of ten questions, with an explanation after every answer. No account needed.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="is-ona-van-mij">First things first: is ONA yours at all?</h2>

<p>Many people read about ONA while they do not have to do it. ONA belongs to the
<strong>Wet inburgering 2013</strong>, the old law. If you became inburgeringsplichtig (obliged to
integrate) on or after 1 January 2022, you fall under the Wet 2021 and instead do the
<strong>MAP</strong> at your gemeente (municipality). Nobody does both.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">You do ONA if…</p>
    <ul>
      <li>${I_CHECK}<span>You are inburgeringsplichtig under the <strong>Wet 2013</strong>, and you became so on or after 1 October 2017</span></li>
      <li>${I_CHECK}<span>You are integrating <strong>voluntarily</strong></span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">You do <em>not</em> do ONA if…</p>
    <ul>
      <li>${I_X}<span>You fall under the <strong>Wet 2021</strong> — then you do the MAP at your gemeente</span></li>
      <li>${I_X}<span>You had to start integrating before 1 January 2015</span></li>
      <li>${I_X}<span>You have a Dutch-language diploma from an entreeopleiding (mbo niveau 1)</span></li>
      <li>${I_X}<span>You were given an exemption because you have worked in the Netherlands</span></li>
    </ul>
  </div>
</div>

${factTwoIn('en', 'Under the Wet 2013, candidates who became inburgeringsplichtig from 1 October 2017 do the exams Lezen, Luisteren, Schrijven, Spreken, KNM, ONA and the participatieverklaringstraject. You also do the ONA exam if you are integrating voluntarily. Under the Wet 2021, your PIP and your leerroute determine which parts you do.', [['inburgeren.nl — Examen doen', SRC_EXAMENS], ['inburgeren.nl — Kennisexamens en ONA', SRC_KENNIS]], CHECKED)}

${note('Not sure which law applies to you? Look in <strong>Mijn Inburgering</strong>. It shows which parts apply to you. That is the only list that is correct — not the one from your neighbour and not the one from a forum.')}

<h2 id="hoe-werkt-het">How the exam is put together</h2>

<p>ONA has two parts, and the second one only starts once the first has been approved. That is the
most important sentence on this page: you cannot do the two parts <strong>at the same time</strong>.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>You make the portfolio</h3>
    <p>Eight resultaatkaarten (result cards), with evidence. You send them in through Mijn Inburgering and pay the exam fee at the same time.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>DUO marks it — about six weeks</h3>
    <p>Rejected? You adjust it and send it in again. And then the marking starts all over again.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>You choose: eindgesprek or course</h3>
    <p>An eindgesprek (final interview) at DUO, or 64 hours of ONA course at a recognised school. One of the two, not both.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>The result</h3>
    <p>Within eight weeks, in Mijn Inburgering.</p>
  </div></div>
</div>

<h2 id="acht-kaarten">The eight resultaatkaarten</h2>

<p>Each kaart is an assignment with a result you have to show. Some kaarten need a piece of
evidence: a vacancy you have found, a report of a conversation, a job application letter you really
sent. DUO's toelichting (explanation) says exactly what is asked for on each kaart.</p>

<div class="guide-cards">
  ${card(I_CLIPBOARD, '1. Beroepenoriëntatie (exploring occupations)', 'Which occupations exist in the Netherlands, and which of them suit you?')}
  ${card(I_CLIPBOARD, '2. Realistisch beroepsbeeld (a realistic picture of the job)', 'What does that occupation involve in practice? Working hours, training, what you really do all day.')}
  ${card(I_CLIPBOARD, '3. Je eigenschappen kennen (knowing your own qualities)', 'What are you good at, what do you enjoy, and where do you get stuck?')}
  ${card(I_CLIPBOARD, '4. Beroepskansen (job chances)', 'How big is the chance of finding work in that occupation, in your region?')}
  ${card(I_CLIPBOARD, '5. Beroepscompetenties (job skills)', 'What do you need to be able to do for that work — and what are you still missing?')}
  ${card(I_CLIPBOARD, '6. Netwerk opbouwen (building a network)', 'Who do you already know, and how do you use that to find work?')}
  ${card(I_CLIPBOARD, '7. Werk vinden (finding work)', 'How do you look for vacancies, and how do you write a job application?')}
  ${card(I_CLIPBOARD, '8. Werkcultuur (work culture)', 'How do things work on a Dutch shop floor? Being late, using "je", calling in sick.')}
</div>

${note('<strong>DUO does not help you fill it in</strong> and has no example portfolio. That is not unwillingness: the portfolio has to be about <em>your</em> occupation and your situation, and an example would make everybody hand in the same thing. Ask your language school or your klantmanager (case manager) for help.')}

${docentIn('en', 'For kaart 1, choose an occupation you are really considering, not the occupation you think looks good. All eight kaarten build on that choice, and at the eindgesprek they notice straight away if you are talking about an occupation you know nothing about. I have seen people redo the whole portfolio for that reason.')}

<h2 id="deel-twee">Eindgesprek or 64 hours of course?</h2>

<p>Once your portfolio is approved, you choose how you finish the exam. This choice is final, so read
both columns before you make it.</p>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>The eindgesprek</h3>
      <p class="compare-when">At DUO</p>
    </div>
    <div class="compare-rows">
      ${row('Waiting time', 'About 6 weeks after you register')}
      ${row('With whom', '2 people from DUO')}
      ${row('About what', 'Questions about your own resultaatkaarten')}
      ${row('How long', 'About 30 minutes')}
      ${row('Cost', 'Included in the exam fee')}
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>64 hours of ONA course</h3>
      <p class="compare-when">At a recognised school</p>
    </div>
    <div class="compare-rows">
      ${row('Waiting time', 'None — you start when the school can')}
      ${row('Where', `A school on <a href="${SRC_SCHOLEN}" target="_blank" rel="noopener">zoekinburgerschool.nl</a> that offers ONA`)}
      ${row('Cost', 'The school sets the course price; that comes on top, separately')}
      ${row('Afterwards', 'No eindgesprek needed any more')}
      ${row('Reporting', 'The school reports your hours to DUO digitally')}
    </div>
  </div>
</div>

${factTwoIn('en', 'The ONA exam consists of two parts: doing assignments (portfolio) and after that 64 hours of ONA course or an eindgesprek. The portfolio consists of 8 resultaatkaarten with evidence; the marking can take 6 weeks. After approval you register for the eindgesprek, which takes place within 6 weeks of registration, is with 2 people from DUO, lasts about 30 minutes and is about your resultaatkaarten. You receive the result within 8 weeks.', [['inburgeren.nl — Kennisexamens en ONA', SRC_KENNIS], ['DUO — Toelichting ONA (pdf)', SRC_ONA_PDF]], CHECKED)}

${note('Are you sending your portfolio in <strong>by post</strong> because logging in does not work? Then you <strong>cannot</strong> finish the exam with the 64-hour course and you do the eindgesprek. Know that <em>before</em> you choose that route.')}

<div class="verdict warn">
  <p class="verdict-answer">Choose on time, not on preference</p>
  <p>Do you still have plenty of time left in your termijn (deadline period) and would you rather not
  have an interview? Then the course is a reasonable choice. If your time is short, the 64-hour
  course is usually <em>slower</em>, not faster: you have to find a school that offers it, and those
  hours still have to fit in.</p>
</div>

<h2 id="wat-het-kost">What it costs</h2>

<p>The ONA exam currently costs <strong>&euro;40</strong>. You pay that when you send in your
resultaatkaarten through Mijn Inburgering. If you then choose the course instead of the eindgesprek,
the cost of that course comes on top, separately — the school sets that.</p>

${factIn('en', 'The ONA exam costs € 40. You pay per exam part, through Mijn Inburgering. These amounts can change; check the current rates with DUO.', 'inburgeren.nl — Inburgeren betalen', SRC_BETALEN, CHECKED)}

<h2 id="planning">The planning is the real exam</h2>

<p>Add up the waiting times and you see why this part gets people into trouble, even when they do
everything right.</p>

<div class="guide-cards">
  ${card(I_CLOCK, 'Marking the portfolio', 'About 6 weeks. If it is rejected, another 6 weeks for your adjusted version.')}
  ${card(I_CLOCK, 'Waiting for the eindgesprek', 'About 6 weeks after you register.')}
  ${card(I_CLOCK, 'Result', 'Within 8 weeks after the interview.')}
  ${card(I_ALERT, 'All together', 'Half a year or more — without you doing anything wrong.')}
</div>

<p>So this is not something you quickly do in your last few months. Start with kaart 1 as soon as you
know that ONA applies to you, and work on it while your language exams are running. Those two do not
get in each other's way.</p>

${docentIn('en', 'I see people get stuck on this planning more often than on the language. The portfolio is not difficult — it is work. And work that you put off because there is no exam date on it is exactly the work that is finished too late.')}

${inlineCta('Work out your own dates', 'The timeline tool puts your termijn, your exams and the waiting times on one timeline. No DigiD, no BSN.', '/inburgering/tools/tijdlijn', 'Make your timeline')}

<h2 id="niet-gehaald">And if the eindgesprek does not go well?</h2>

<p>Then you send your portfolio in again, pay for the exam again and do a new eindgesprek. The same
applies if you cancel the interview too late. If you want to know why you did not pass, you can ask
DUO for that by e-mail.</p>

<p>Count that whole chain in. Together with the waiting time for your language exams, this is the
part where deadlines get tight the fastest.</p>

${inlineCta('Work on your language exams in the meantime', 'While your portfolio is being marked, you can simply keep practising. Ten questions free, with explanations.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>ONA belongs to the <strong>Wet 2013</strong>. Under 2021 you do the MAP.</li>
  <li>Part 1: a portfolio of <strong>8 resultaatkaarten</strong>.</li>
  <li>Marking takes about 6 weeks — if it is rejected, another 6.</li>
  <li>Part 2: an eindgesprek of about 30 minutes, or 64 hours of course.</li>
  <li>Result within 8 weeks. Cost at the moment &euro;40.</li>
  <li>Count on half a year. Start early.</li>
</ul>`,

  faq: [
  {
    q: 'Do I have to do ONA or the MAP?',
    a: 'That depends on your law. ONA belongs to the Wet inburgering 2013 and you do it at DUO, with a portfolio and after that an eindgesprek or a course. The MAP belongs to the Wet inburgering 2021 and you do it at your gemeente. Nobody does both. Mijn Inburgering shows what applies to you.',
  },
  {
    q: 'How many parts does the ONA portfolio have?',
    a: 'Eight resultaatkaarten, from beroepenoriëntatie to werkcultuur, with evidence attached. You send them in together through Mijn Inburgering and pay the exam fee at the same time. DUO does not help you fill them in and has no example portfolio.',
  },
  {
    q: 'How long does the ONA exam take in total?',
    a: 'Count on half a year or more. Marking your portfolio takes about six weeks, and if it is rejected, another six weeks for the adjusted version. After that you wait about six weeks for the eindgesprek, and the result comes within eight weeks.',
  },
  {
    q: 'Which is better: the eindgesprek or the 64-hour course?',
    a: 'That depends on your time. The eindgesprek lasts about thirty minutes and is included in the exam fee, but you wait about six weeks for it. The course has no waiting time at DUO, but you have to find a school that offers ONA, and those 64 hours cost time and money.',
  },
  {
    q: 'What does the ONA exam cost?',
    a: 'At the moment €40, to be paid when you send in your resultaatkaarten through Mijn Inburgering. If you choose the 64-hour course instead of the eindgesprek, the cost of that course comes on top, separately; the school sets that itself. Rates can change.',
  },
  {
    q: 'What happens if my portfolio is rejected?',
    a: 'Then you adjust the kaarten that were not good enough and send the portfolio in again. The marking then starts over and takes about six weeks again. That is why it is wise to have your kaarten looked at first by your language school or your klantmanager.',
  },
  ],
};

export default translation;
