/**
 * onderwijs-en-opvoeding — English.
 *
 * A translation of the Dutch body in `../onderwijs-en-opvoeding.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CAP, I_CHECK, I_CLIPBOARD, I_EURO, I_HOME, I_USERS, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_EINDTERMEN, SRC_KINDERBIJSLAG, SRC_KINDEROPVANG, SRC_LEERPLICHT, SRC_ONDERWIJS, SRC_OUDERBIJDRAGE, SRC_VEILIGTHUIS, card, row } from '../onderwijs-en-opvoeding';

const translation: GuideLocale = {
  title: 'KNM: Education and parenting — school and children in NL',
  description: 'The Dutch school system, leerplicht, contact with the teacher, school costs and children\'s rights. The KNM theme Onderwijs en opvoeding explained.',
  breadcrumb: 'Education and parenting',
  dateLabel: '23 August 2026',
  eyebrow: 'KNM theme 8',
  heroTitle: 'Education and parenting',
  heroSubtitle: 'How does school work in the Netherlands, what is expected of parents, and what is allowed and required in raising children? This theme is about your children — and about your role in it.',
  ctaTitle: 'Practise the theme Onderwijs en opvoeding',
  ctaDesc: 'A free practice exam of ten questions, with an explanation after every answer. No account needed.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="wat-vraagt-knm">What does KNM ask about this theme?</h2>

<div class="compare-rows">
  ${row('8.1', 'Using the Dutch education system')}
  ${row('8.2', 'Responsibility for minor children')}
  ${row('8.3', 'Dealing with school costs and financial support')}
</div>

${factIn('en', 'The KNM eindtermen for the theme Onderwijs en opvoeding are: using the Dutch education system; responsibility for minor children; dealing with school costs and financial support.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

<h2 id="leerplicht">Leerplicht: going to school is compulsory</h2>

<p>Children in the Netherlands must go to school from the day they turn <strong>5</strong>.
In practice, most children already start at four, because that is allowed and because it is good for
their language. The leerplicht (compulsory education) lasts until the age of 16. After that the
<strong>kwalificatieplicht</strong> applies: until you are 18 you must go to school, unless you
obtain a startkwalificatie earlier — a havo, vwo or mbo level 2 diploma.</p>

<p>Spijbelen (truancy) is not without consequences. The school reports it to the
<strong>leerplichtambtenaar</strong> (school attendance officer) of the gemeente (municipality), who
can address parents and even fine them. A holiday outside the school holidays is only allowed in
exceptional cases and with the head teacher's permission.</p>

${factIn('en', 'In the Netherlands, children are subject to compulsory education from the first school day of the month after their fifth birthday until the end of the school year in which they turn 16. After that the kwalificatieplicht applies until the age of 18 or until a startkwalificatie is obtained.', 'Rijksoverheid — Leerplicht', SRC_LEERPLICHT, CHECKED)}

${note('Are you new to the Netherlands and does your child not speak Dutch yet? Then it usually goes first to a <strong>nieuwkomersklas</strong> (newcomers class) or a language school, often for about a year. After that it moves on to a regular school. Register your child with the gemeente or with a school in your neighbourhood; they know where such a class is.')}

<h2 id="schoolsysteem">The school system step by step</h2>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Kinderopvang and peuterspeelzaal (childcare and playgroup, 0–4 years)</h3>
    <p>Not compulsory. If you work or study, you can get kinderopvangtoeslag (childcare allowance). Many gemeenten also offer voorschoolse educatie (VVE) for children with a language delay — often free or cheap.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Basisschool (primary school, 4–12 years)</h3>
    <p>Eight groepen (year groups). You choose a school yourself; there are openbare scholen (public schools) and schools with a religious or pedagogical direction. Openbaar onderwijs is open to everyone.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>The schooladvies (school advice, groep 8)</h3>
    <p>At the end of primary school, the teacher gives an advice for voortgezet onderwijs (secondary education). After that comes the doorstroomtoets. If the test result is higher than the advice, the school has to reconsider the advice.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Voortgezet onderwijs (secondary education, 12–18 years)</h3>
    <p>Three main directions: <strong>vmbo</strong> (4 years, practical, leading to mbo), <strong>havo</strong> (5 years, leading to hbo) and <strong>vwo</strong> (6 years, leading to university).</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">5</span><div class="guide-step-body">
    <h3>Further education</h3>
    <p><strong>mbo</strong> (vocational training, level 1 to 4), <strong>hbo</strong> (university of applied sciences) and <strong>wo</strong> (university). Students can borrow money and sometimes get a grant from DUO.</p>
  </div></div>
</div>

<p>Important for parents: the Dutch system allows you to <strong>move up</strong>. A vmbo pupil can
go through mbo to hbo, and a havo pupil can go to vwo. An advice in groep 8 is not an end point.
That is one of the most reassuring things you can tell a worried parent — and it is true.</p>

${factIn('en', 'Dutch education consists of primary education, secondary education (vmbo, havo, vwo) and further education (mbo, hbo, wo). After a diploma, pupils can move on to a higher level.', 'Rijksoverheid — Schoolsysteem in Nederland', SRC_ONDERWIJS, CHECKED)}

<h2 id="ouders">What is expected of parents?</h2>

<p>More than in many other countries. Here, school and parents are partners, and the school expects
you to take part.</p>

<div class="guide-cards">
  ${card(I_USERS, 'Come to the oudergesprekken', 'Two or three times a year you discuss how things are going. Come, also when things go well, and also when your Dutch is not strong yet. Ask for an interpreter or bring someone with you.')}
  ${card(I_CLIPBOARD, 'Read the messages from school', 'Schools communicate through an app or by email: about trips, gym clothes, illness, holidays. Turn on notifications.')}
  ${card(I_HOME, 'Report your child sick', 'Before school starts, by phone or through the app. Not reporting counts as truancy.')}
  ${card(I_CAP, 'Help at home', 'Read aloud, talk about the day, and make sure there is rest and sleep. That weighs more heavily than testing homework in a language you are learning yourself.')}
</div>

${docentIn('en', 'Many parents I teach do not dare to go to a parent meeting because they are afraid they will not understand it. Just say that to the teacher. Schools are used to it and will look for a solution. Staying away is read as a lack of interest, and that is exactly the opposite of what you mean.')}

<h2 id="opvoeding">Parenting: the rights of children</h2>

<p>Eindterm 8.2. In the Netherlands a child has its own rights, also towards its parents. For many
newcomers that takes getting used to, and the exam asks about it explicitly.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">Expected of parents</p>
    <ul>
      <li>${I_CHECK}<span>Providing food, clothing, housing, safety and school</span></li>
      <li>${I_CHECK}<span>Going to the doctor and the consultatiebureau (child health clinic) when needed</span></li>
      <li>${I_CHECK}<span>Setting limits and explaining why</span></li>
      <li>${I_CHECK}<span>Letting your child have a say in things that concern him, according to age</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Forbidden</p>
    <ul>
      <li>${I_X}<span>Hitting or other physical violence — also as a way of raising a child</span></li>
      <li>${I_X}<span>Neglect: leaving a child without care or supervision</span></li>
      <li>${I_X}<span>Child marriage and forced marriage</span></li>
      <li>${I_X}<span>Female circumcision — a criminal offence, also when it happens abroad</span></li>
      <li>${I_X}<span>Keeping your child at home from school</span></li>
    </ul>
  </div>
</div>

<p>If you are worried about a child — your own child or someone else's — there is
<strong>Veilig Thuis</strong>. This is the national advice and reporting centre for domestic
violence and child abuse. You can call anonymously, also just to ask for advice.</p>

${factIn('en', 'Veilig Thuis is the national advice and reporting centre for domestic violence and child abuse. Anyone can go there for advice or to report concerns, also anonymously; the telephone number is 0800-2000 and is free.', 'Veilig Thuis', SRC_VEILIGTHUIS, CHECKED)}

${note('Do you get a visit from <strong>jeugdzorg</strong> (youth care) or the wijkteam (neighbourhood team)? That does not automatically mean that your child will be taken away. In by far the most cases it is about help at home. Cooperate and ask questions; you may always bring someone with you to such a meeting.')}

<h2 id="schoolkosten">School costs and financial support</h2>

<p>Eindterm 8.3, and probably the most useful part of this guide.</p>

<p>Openbaar and bijzonder onderwijs (public and denominational education) are <strong>free</strong>
in the Netherlands. Schools do ask for an <strong>ouderbijdrage</strong> (parental contribution)
for extras: a school trip, a Christmas celebration, an excursion. That contribution is
<strong>voluntary</strong>. A school may not exclude a child from activities if the parents do not
pay. If you cannot pay it, say so to the school — that is allowed, and there are often funds.</p>

${factIn('en', 'The parental contribution to school is voluntary. Schools may not exclude pupils from activities or from the education programme if parents do not pay the contribution.', 'Rijksoverheid — Ouderbijdrage school', SRC_OUDERBIJDRAGE, CHECKED)}

<h3>What you can count on financially</h3>

<div class="guide-cards">
  ${card(I_EURO, 'Kinderbijslag', 'From the SVB, for everyone with children up to 18 years old. You usually apply once; after that it continues.')}
  ${card(I_EURO, 'Kindgebonden budget', 'From the Belastingdienst (tax office), as an addition if you have a lower income. You often get it automatically if you already receive kinderbijslag.')}
  ${card(I_EURO, 'Kinderopvangtoeslag', 'From the Belastingdienst, if you work or study and your child goes to registered childcare.')}
  ${card(I_EURO, 'Schemes from the gemeente', 'Many gemeenten have a stadspas, a school supplies pass, or they pay for a bicycle, a laptop or a sports club if you have a low income. Ask your gemeente about it.')}
</div>

${factTwoIn('en', 'Kinderbijslag is paid out by the Sociale Verzekeringsbank for children up to 18 years old. Kinderopvangtoeslag is a contribution from the Belastingdienst towards the costs of registered childcare for working or studying parents.', [['SVB — Kinderbijslag', SRC_KINDERBIJSLAG], ['Belastingdienst — Kinderopvangtoeslag', SRC_KINDEROPVANG]], CHECKED)}

${docentIn('en', 'The schemes of the gemeente are the best kept secret of this theme. Almost every gemeente has money for sport, music lessons or a laptop for children from families with a low income. You only have to apply for it yourself, and nobody tells you about it on their own. Ask at the counter.')}

<h2 id="in-het-examen">How this comes back in the exam</h2>

<p>As situations around school and children: a child is ill, a parent wants to go on holiday outside
the school holidays, a school asks for money, a child gets an advice that the parents find too low.
The line is almost always: <strong>talk to the school, and school is compulsory and free</strong>.</p>

${inlineCta('Practise this theme with exam questions', 'School, leerplicht and parenting — with an explanation after every answer.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>Leerplicht from 5 to 16 years, after that kwalificatieplicht until 18.</li>
  <li>Primary school 4–12, then vmbo, havo or vwo; you can always move up later.</li>
  <li>Parents come to the oudergesprekken and report their child sick.</li>
  <li>Hitting is forbidden; Veilig Thuis is there for advice, also anonymously.</li>
  <li>School is free; the ouderbijdrage is voluntary.</li>
</ul>`,

  faq: [
  {
    q: 'From what age must my child go to school?',
    a: 'Your child is subject to compulsory education from the first school day of the month after its fifth birthday. Most children already start at four, because that is allowed and is good for their Dutch. The leerplicht runs until the age of 16, after that the kwalificatieplicht applies until the age of 18 or until a startkwalificatie.',
  },
  {
    q: 'Do I have to pay the ouderbijdrage to the school?',
    a: 'No, it is voluntary. A school may not exclude your child from a school trip or another activity because you do not pay. If you cannot spare the money, tell the school or ask about a scheme of your gemeente; they often have a fund for school costs.',
  },
  {
    q: 'What is the difference between vmbo, havo and vwo?',
    a: 'Vmbo takes four years and is practically oriented; after that you usually go to mbo. Havo takes five years and prepares you for hbo. Vwo takes six years and prepares you for university. An advice is not a final station: through mbo and hbo you can still move up.',
  },
  {
    q: 'May I punish my child?',
    a: 'Setting limits is allowed and is expected of you. Physical punishment is not: hitting is forbidden in the Netherlands, also by parents and also as a way of raising a child. If you are in doubt about how to handle something, you can ask for free advice at the Centrum voor Jeugd en Gezin of your gemeente or at Veilig Thuis.',
  },
  {
    q: 'What financial help is there for parents?',
    a: 'Kinderbijslag from the SVB for children up to 18 years old, kindgebonden budget from the Belastingdienst if you have a lower income, and kinderopvangtoeslag if you work or study. In addition, almost every gemeente has its own schemes for sport, music lessons, a bicycle or a laptop. You have to apply for those yourself.',
  },
  {
    q: 'My child does not speak Dutch yet. Which school can it go to?',
    a: 'Usually first to a nieuwkomersklas or a language school, where it learns Dutch intensively for about a year. After that it goes to a regular school. Ask your gemeente or a primary school in your neighbourhood where such a facility is; they know that.',
  },
  ],
};

export default translation;
