/**
 * pvt-map-en-ona — English.
 *
 * A translation of the Dutch body in `../pvt-map-en-ona.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CLIPBOARD, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_BESLUIT31, SRC_KENNIS, SRC_ONA_PDF, SRC_WET8, card, row } from '../pvt-map-en-ona';

const translation: GuideLocale = {
  title: 'PVT, MAP and ONA: the parts that are not exams',
  description: 'The participatieverklaring, the Module Arbeidsmarkt en Participatie and the ONA exam. Who does which part, how it works and which deadlines apply.',
  breadcrumb: 'PVT, MAP and ONA',
  dateLabel: '23 August 2026',
  eyebrow: 'Parts',
  heroTitle: 'PVT, MAP and ONA',
  heroSubtitle: 'Besides the language exams and KNM there are parts that are not a test but a programme. Which ones you have to do depends on your law and your leerroute (learning route). Here you can read which one is yours.',
  ctaTitle: 'Work on your language exams in the meantime',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after every answer. No account needed.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="welke-is-van-mij">Which of the three applies to you?</h2>

<p>Start here. Do you do all three? No — nobody does both MAP and ONA. It depends on which law you
integrate under.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>Part</th><th>Wet 2021</th><th>Wet 2013</th></tr></thead>
  <tbody>
    <tr><td><strong>PVT</strong> — participatieverklaringstraject (participation statement programme)</td><td>Yes, in every leerroute</td><td>Yes, if you became inburgeringsplichtig (obliged to integrate) on or after 1 October 2017</td></tr>
    <tr><td><strong>MAP</strong> — Module Arbeidsmarkt en Participatie</td><td>Yes, in the B1-route and the Z-route. <strong>Not</strong> in the onderwijsroute.</td><td>No</td></tr>
    <tr><td><strong>ONA</strong> — Ori&euml;ntatie op de Nederlandse Arbeidsmarkt</td><td>No</td><td>Yes, and also if you integrate voluntarily</td></tr>
  </tbody>
</table>
</div>

${factTwoIn('en', 'The participatieverklaringstraject applies to people who became inburgeringsplichtig on or after 1 October 2017 and who are registered with the gemeente. The Module Arbeidsmarkt en Participatie is part of the B1-route and the Z-route, but is excluded for the onderwijsroute. You only take the ONA exam if you have to integrate under the Wet 2013 or if you integrate voluntarily.', [['inburgeren.nl — Kennisexamens', SRC_KENNIS], ['Wet inburgering 2021, artikel 8', SRC_WET8]], CHECKED)}

${note('Do you not know which law applies to you? Look in <strong>Mijn Inburgering</strong>. It shows exactly which parts you have to do. That is the only list that is correct for your situation — not your neighbour&rsquo;s, and not one from a forum.')}

<h2 id="pvt">PVT: the participatieverklaring</h2>

<p>You do the PVT at your <strong>gemeente</strong> (municipality), not at DUO. You learn what is
important in the Netherlands, and after that you sign a declaration.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>You get a letter from the gemeente</h3>
    <p>It says what the programme involves and when you are expected. Have you not received a letter? Contact the gemeente where you are registered.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>You follow the programme: at least 12 hours</h3>
    <p>Usually in a few meetings. You learn about the core values: freedom, equality, solidarity and participation.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>You sign the verklaring</h3>
    <p>You declare that you want to take an active part in Dutch society and that you respect what is important here.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>The gemeente passes it on to DUO</h3>
    <p>After about three weeks you see in Mijn Inburgering that it has been processed. Check that.</p>
  </div></div>
</div>

<p>What do you learn there? The gemeente summarises it in the letter like this: everyone in the
Netherlands is equal, everyone may choose what they believe, and everyone may say what they think —
but discrimination is not allowed.</p>

${factTwoIn('en', 'The participatieverklaringstraject lasts at least 12 hours and is an introduction to the core values of Dutch society, ending with the signing of the participatieverklaring. The gemeente passes the signing on to DUO; after about three weeks it appears in Mijn Inburgering.', [['Besluit inburgering 2021, artikel 3.1', SRC_BESLUIT31], ['inburgeren.nl — Kennisexamens en PVT', SRC_KENNIS]], CHECKED)}

<div class="verdict warn">
  <p class="verdict-answer">Watch the deadline — it differs per law</p>
  <p>Under the <strong>Wet 2021</strong> you have three years to sign. Under the
  <strong>Wet 2013</strong> you have only <strong>one year</strong>, counted from your
  registration with the gemeente. If you do not manage that and it is your own fault, you get a
  fine of &euro;340 and you can also no longer borrow from DUO. Are you late through no fault of
  your own, or do you need more time? Then contact your gemeente.</p>
</div>

<h2 id="map">MAP: Module Arbeidsmarkt en Participatie</h2>

<p>The MAP belongs to the <strong>Wet 2021</strong> and is about working and looking for work. You
do it at your gemeente, and during the brede intake (broad intake interview) you hear what that
looks like in your gemeente. You must be finished before the end of your inburgeringstermijn
(integration deadline).</p>

<p>The MAP consists of two parts.</p>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>Arbeidsmarkt</h3>
      <p class="compare-when">Looking for work and applying for jobs</p>
    </div>
    <div class="compare-rows">
      ${row('You learn', 'Which jobs there are in the Netherlands')}
      ${row('And', 'Which jobs suit you')}
      ${row('And', 'How to apply for a job')}
      ${row('How', 'By doing assignments')}
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>Participatie</h3>
      <p class="compare-when">Taking part in society</p>
    </div>
    <div class="compare-rows">
      ${row('You learn', 'How to take part in Dutch society')}
      ${row('And', 'How to make a good impression on a company')}
      ${row('How', 'With practical assignments')}
      ${row('For example', 'Volunteer work, a work placement or paid work')}
    </div>
  </div>
</div>

${factIn('en', 'The MAP is about working and looking for work in the Netherlands and consists of two parts: arbeidsmarkt and participatie. In the arbeidsmarkt part you learn which jobs there are, which jobs are suitable for you and how to apply for a job, by doing assignments. In the participatie part you do practical assignments, for example volunteer work, a work placement or paid work. You must be finished before the end of your inburgeringstermijn.', 'inburgeren.nl — Kennisexamens en MAP', SRC_KENNIS, CHECKED)}

${docentIn('en', 'Course participants often see the MAP as a box to tick. That is a shame. The participatie part is exactly the volunteer work or the work placement that I tell everyone is the fastest way to improve your Dutch. Here you get the time and the guidance that you would otherwise have had to organise yourself.')}

<h2 id="ona">ONA: Ori&euml;ntatie op de Nederlandse Arbeidsmarkt</h2>

<p>ONA is the part of the <strong>old law</strong>, the Wet inburgering 2013. It is the predecessor
of the MAP and works very differently: it is a portfolio that you make yourself, plus a second part
of your choice. Below is how it works; if you want the eight resultaatkaarten (result cards) one by
one and the planning with them, read the guide
<a href="/inburgering/ona-examen">The ONA exam: portfolio, eindgesprek and planning</a>.</p>

<h3>Who does not have to do ONA?</h3>
<ul>
  <li>You had to start integrating before 1 January 2015.</li>
  <li>You are inburgeringsplichtig under the Wet inburgering 2021.</li>
  <li>You have a Dutch-language diploma from an entreeopleiding (mbo level 1).</li>
  <li>You have been given an exemption because you have worked in the Netherlands.</li>
</ul>

<h3>Part 1: the portfolio</h3>

<p>You do assignments on <strong>eight resultaatkaarten</strong>. Together with the supporting
documents that you sometimes have to send along, they form your portfolio. DUO&rsquo;s explanatory
notes say exactly how to fill in the cards. Note: <strong>DUO does not help you fill them in</strong>
and does not have a sample portfolio either.</p>

<div class="guide-cards">
  ${card(I_CLIPBOARD, 'Beroepenori&euml;ntatie — exploring jobs', 'Which jobs are there, and which ones suit you?')}
  ${card(I_CLIPBOARD, 'Realistisch beroepsbeeld — a realistic picture', 'What does that job involve in practice?')}
  ${card(I_CLIPBOARD, 'Knowing your own qualities', 'What are you good at, and what do you enjoy?')}
  ${card(I_CLIPBOARD, 'Beroepskansen — job chances', 'How big is the chance of work in that job?')}
  ${card(I_CLIPBOARD, 'Beroepscompetenties — job skills', 'What do you need to be able to do for that work, and what is still missing?')}
  ${card(I_CLIPBOARD, 'Building a network', 'Who do you know, and how do you use that to find work?')}
  ${card(I_CLIPBOARD, 'Finding work', 'How do you look for vacancies and how do you apply?')}
  ${card(I_CLIPBOARD, 'Werkcultuur — work culture', 'How do things work on a Dutch shop floor?')}
</div>

<p>You send the cards in via Mijn Inburgering, and you pay the exam fee at the same time:
<strong>&euro;40</strong>. Assessment takes about <strong>six weeks</strong>. If your portfolio is
rejected, you adjust it and send it in again — and then assessment takes another six weeks.</p>

<h3>Part 2: eindgesprek (final interview) or course</h3>

<p>If your portfolio is approved, you choose how to finish the exam.</p>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>The eindgesprek</h3>
      <p class="compare-when">At DUO</p>
    </div>
    <div class="compare-rows">
      ${row('Waiting time', 'About 6 weeks after you register')}
      ${row('With whom', '2 people from DUO')}
      ${row('About what', 'Questions about your resultaatkaarten')}
      ${row('How long', 'About 30 minutes')}
      ${row('Result', 'In Mijn Inburgering')}
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>64 hours of ONA course</h3>
      <p class="compare-when">At a recognised school</p>
    </div>
    <div class="compare-rows">
      ${row('Waiting time', 'None — you start when the school can')}
      ${row('Where', 'A school on zoekinburgerschool.nl that offers ONA')}
      ${row('Cost', 'The school sets the course price')}
      ${row('After that', 'No eindgesprek needed')}
      ${row('Reporting', 'The school reports your hours to DUO digitally')}
    </div>
  </div>
</div>

${factTwoIn('en', 'The ONA exam consists of two parts: doing assignments (portfolio) and after that 64 hours of ONA course or an eindgesprek. The portfolio consists of 8 resultaatkaarten with supporting evidence; assessment can take 6 weeks. After approval you register for the eindgesprek, which takes place within 6 weeks of registering, with 2 people from DUO, lasts about 30 minutes and is about your resultaatkaarten. You receive the result within 8 weeks. The ONA exam costs € 40.', [['inburgeren.nl — Kennisexamens en ONA', SRC_KENNIS], ['DUO — Toelichting ONA (pdf)', SRC_ONA_PDF]], CHECKED)}

${note('Are you sending your portfolio <strong>by post</strong> because logging in does not work? Then you <strong>cannot</strong> finish the exam with the 64-hour course; in that case you do the eindgesprek. Good to know before you make that choice.')}

${docentIn('en', 'Start your portfolio in good time. Six weeks of assessment, and another six weeks if it is rejected, and then six weeks waiting for the eindgesprek — that is half a year before you have done anything wrong. I see more people get stuck here than on the language.')}

<h2 id="zak">And what if the eindgesprek does not go well?</h2>

<p>Then you have to send in your portfolio again, pay for the exam again and do a new eindgesprek.
The same applies if you cancel the interview too late. If you want to know why you did not pass, you
can ask DUO for that by e-mail.</p>

<p>Include that whole chain in your planning. Together with the waiting time for your language
exams, this is the part where deadlines most quickly get into trouble.</p>

${inlineCta('Work on your language exams in the meantime', 'While your portfolio is being assessed, you can simply carry on practising. Ten questions free, with explanations.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>You do the PVT at the gemeente, in every route, at least 12 hours.</li>
  <li>MAP belongs to the Wet 2021 — not in the onderwijsroute.</li>
  <li>ONA belongs to the Wet 2013, and costs &euro;40.</li>
  <li>ONA portfolio: 8 resultaatkaarten, 6 weeks of assessment.</li>
  <li>After that: an eindgesprek of about 30 minutes, or 64 hours of course.</li>
  <li>PVT deadline: 3 years under 2021, 1 year under 2013.</li>
</ul>`,

  faq: [
  {
    q: 'What is the difference between MAP and ONA?',
    a: 'They are both about work, but they belong to different laws. The MAP belongs to the Wet inburgering 2021 and you do it at your gemeente, with assignments and practical assignments. ONA belongs to the Wet inburgering 2013 and you do it at DUO, with a portfolio of eight resultaatkaarten and after that an eindgesprek or a course. Nobody does both.',
  },
  {
    q: 'Do I have to do the MAP in the onderwijsroute?',
    a: 'No. The MAP applies to the B1-route and the Z-route; the onderwijsroute is excluded from it. You do have to do the PVT in the onderwijsroute — that applies in every leerroute. Mijn Inburgering and your PIP show what applies to you.',
  },
  {
    q: 'What does the ONA exam cost?',
    a: '€40. You pay that when you send in your resultaatkaarten via Mijn Inburgering, with iDEAL or Wero, or from your loan with DUO. If you then choose the 64-hour course instead of the eindgesprek, the cost of that course comes on top separately; the school sets that price.',
  },
  {
    q: 'How long does the ONA exam take in total?',
    a: 'Count on months. The assessment of your portfolio takes about six weeks, and if it is rejected another six weeks for the adjusted version. After that the waiting time for the eindgesprek is about six weeks, and the result comes within eight weeks. So start early.',
  },
  {
    q: 'How long does the participatieverklaringstraject take?',
    a: 'The programme lasts at least twelve hours, usually spread over a few meetings at your gemeente. After that you sign the verklaring. The gemeente passes that on to DUO; after about three weeks you see in Mijn Inburgering that it has been processed.',
  },
  {
    q: 'What happens if I do not sign the participatieverklaring on time?',
    a: 'Under the Wet 2013 you have one year from your registration with the gemeente. If you do not manage that through your own fault, you get a fine of €340 and you can no longer borrow from DUO. If you are late through no fault of your own or you need more time, contact your gemeente — then you may get extra time.',
  },
  ],
};

export default translation;
