/**
 * schrijven-examen — English.
 *
 * A translation of the Dutch body in `../schrijven-examen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_PEN, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_NIEUWS, SRC_NT2, SRC_OEFENEN, SRC_TAALEXAMENS, SRC_UITSLAG, card } from '../schrijven-examen';

const translation: GuideLocale = {
  title: 'The Schrijven exam (A2 and B1): format, time and approach',
  description: 'You take Schrijven at A2 with pen and paper: four tasks in 40 minutes. What the exam looks like, how it is marked and how to practise for it in a targeted way.',
  breadcrumb: 'Schrijven',
  dateLabel: '23 August 2026',
  eyebrow: 'Language exam',
  heroTitle: 'The Schrijven exam',
  heroSubtitle: 'Four tasks, forty minutes, and at A2 with pen and paper. This is the part where planning helps more than language knowledge — and where the result takes the longest.',
  ctaTitle: 'Practise the Schrijven part',
  ctaDesc: 'Writing tasks with feedback per criterion, drawn up by an NT2 teacher.',
  ctaLabel: 'See the modules',

  articleHtml: `
<h2 id="hoe-ziet-het-eruit">What does the exam look like?</h2>

<p>The first thing you need to know: in Schrijven (writing) at level A2 you write <strong>with pen and
paper</strong>. Not on a computer. That is the only exam part for which this is the case.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th></th><th>A2</th><th>B1</th></tr></thead>
  <tbody>
    <tr><td><strong>Length</strong></td><td>40 minutes</td><td>100 minutes</td></tr>
    <tr><td><strong>How</strong></td><td>With pen and paper</td><td>Staatsexamen NT2, see staatsexamensnt2.nl</td></tr>
    <tr><td><strong>Number of tasks</strong></td><td>4 writing tasks</td><td>see staatsexamensnt2.nl</td></tr>
    <tr><td><strong>What you write</strong></td><td>For example a short letter, or you fill in a form</td><td>Longer, connected texts</td></tr>
    <tr><td><strong>Marking</strong></td><td>By people, not by the computer</td><td>By people</td></tr>
  </tbody>
</table>
</div>

${factTwoIn('en', 'DUO: "You take the exam Schrijven at level A2 with pen and paper. You get 4 writing tasks. For example, you write a short letter. Or you fill in a form. The exam takes 40 minutes." The exam Schrijven at level B1 (staatsexamen NT2) takes 100 minutes.', [['inburgeren.nl — Taalexamens', SRC_TAALEXAMENS], ['Staatsexamens NT2', SRC_NT2]], CHECKED)}

${note('Forty minutes for four tasks is <strong>ten minutes per task</strong>. That is the most important sum of this exam. Someone who makes the first task beautiful and then has no time left hands in two empty sheets — and an empty task never earns points.')}

<h2 id="soorten-opdrachten">What kind of tasks do you get?</h2>

<p>DUO (the organisation that runs the exams) says itself: a short letter, or filling in a form. In
the public practice exams you see roughly these four forms.</p>

<div class="guide-cards">
  ${card(I_PEN, 'Filling in a form', 'Name, address, date of birth, and a few short answers. It looks easy, but this is where points are lost by skipping fields.')}
  ${card(I_PEN, 'A short message or note', 'A note to the neighbours, the school or a colleague. Short, but with a clear message.')}
  ${card(I_PEN, 'An e-mail or letter', 'With an opening and a closing. For example moving an appointment or asking a public body something.')}
  ${card(I_PEN, 'A short text about yourself or a situation', 'A few connected sentences: what happened, what you think, what you want.')}
</div>

<p>With every task the instructions say <strong>which points you must mention</strong>. That is not a
suggestion. That is the checklist you are marked on.</p>

${factIn('en', 'DUO makes practice exams available that anyone can take. The oefenexamen Schrijven A2 is a pdf and contains 4 tasks: "In this test you have to answer 4 questions."', 'inburgeren.nl — Oefenen', SRC_OEFENEN, CHECKED)}

<h2 id="beoordeling">How is it marked?</h2>

<p>By people, not by a computer. That means two things. First: it does not have to be perfect — a
marker reads whether your message comes across. Second: it takes longer before you have your
result.</p>

<p>What is looked at, broadly:</p>

<ul>
  <li><strong>Did you carry out the task?</strong> Are all the requested points in it? This weighs the heaviest, and it is the easiest to check.</li>
  <li><strong>Is it understandable?</strong> Does the reader understand what you mean, even with a few mistakes in it?</li>
  <li><strong>Does the form fit the situation?</strong> A letter to the gemeente (municipality) is different from a note to your neighbour.</li>
  <li><strong>Words and sentences.</strong> Enough variety, and sentences that run well.</li>
</ul>

${docentIn('en', 'If I could change one thing about how people prepare: first copy out the requested points as a short rough list, and tick them off while you write. I see beautiful letters that fail because three points were asked for and only two are in the text. That is not a language problem.')}

<h2 id="uitslag">Watch the waiting time</h2>

<p>The result of the language exams normally comes within 8 weeks. But for
<strong>Schrijven A2 and Spreken A2</strong> a longer period applies at the moment.</p>

${factTwoIn('en', 'DUO announced on 31 July 2026 that marking the exams Spreken A2 and Schrijven A2 took a maximum of 16 weeks at that time. Inburgeraars who get into trouble with their inburgering (civic integration) deadline because of this automatically get a six-month extension. For the other exams the usual period of 8 weeks applies.', [['inburgeren.nl — Nieuwsbericht 31-07-2026', SRC_NIEUWS], ['inburgeren.nl — Uitslag examen', SRC_UITSLAG]], CHECKED)}

<p>This is a message from DUO and it can change — check the current situation just before you
plan. But as long as it applies, the conclusion is clear: <strong>do Schrijven early</strong>. If
you plan it at the end of your deadline period and you fail, you have no time left for a resit.</p>

<h2 id="aanpak">Approach during the exam</h2>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>First look at all four tasks</h3>
    <p>One minute. That way you know what is coming and you divide your time on purpose instead of by accident.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Underline what is asked for</h3>
    <p>The points in the task are the points you are marked on. Put marks next to them.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Write, and keep it simple</h3>
    <p>Short sentences that are correct are better than long sentences that get stuck. You do not have to write beautifully, you have to be clear.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Keep five minutes for the end</h3>
    <p>Go through all four tasks: are all the requested points there, is it readable, have you skipped anything?</p>
  </div></div>
</div>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">Do</p>
    <ul>
      <li>${I_CHECK}<span>Write <strong>legibly</strong>. What the marker cannot read does not count.</span></li>
      <li>${I_CHECK}<span>Use an opening and a closing in a letter or e-mail: "Beste …" (Dear …) and "Met vriendelijke groet" (Kind regards).</span></li>
      <li>${I_CHECK}<span>Cross out neatly if you write something wrong; do not keep erasing.</span></li>
      <li>${I_CHECK}<span>Hand in all four tasks, even if one is only half finished.</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Do not</p>
    <ul>
      <li>${I_X}<span>Make one task perfect and leave the rest</span></li>
      <li>${I_X}<span>Use difficult words that you are not sure about</span></li>
      <li>${I_X}<span>Write out a page of memorised text that does not fit the task</span></li>
      <li>${I_X}<span>Forget to fill in your details at the top of the form</span></li>
    </ul>
  </div>
</div>

<h2 id="oefenen">How to practise</h2>

<p>Schrijven is the part where practising has the most direct effect, because your mistakes are
visible and so you can deal with them.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Write by hand</h3>
    <p>At A2 that is the real exam. If you only type, you will not notice until exam day how slow and how illegible you are with a pen.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Learn a few fixed building blocks</h3>
    <p>Opening, closing, "ik schrijf u omdat…" (I am writing to you because…), "kunt u mij laten weten…" (could you let me know…). Then you no longer have to think those up and you keep time for the content.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Set a timer for ten minutes</h3>
    <p>Per task. That way you learn what fits into ten minutes, and that is the skill this exam really tests.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Let someone read along</h3>
    <p>With Schrijven you cannot judge yourself well. Ask your teacher, your language buddy, or use practice material that gives you feedback per criterion.</p>
  </div></div>
</div>

${docentIn('en', 'Building blocks are not cheating. Dutch people themselves also keep using the same opening sentences. If you know five standard sentences for a request, a complaint and an appointment, then during the exam your head is busy with what you are writing instead of with how you start.')}

${inlineCta('Practise Schrijven with marking per criterion', 'Our writing tasks are marked against an assessment model drawn up by an NT2 teacher.', '/premium', 'See the modules')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>A2: 4 tasks in 40 minutes, with pen and paper.</li>
  <li>B1: 100 minutes, staatsexamen NT2.</li>
  <li>Ten minutes per task — divide your time on purpose.</li>
  <li>Mentioning all the requested points weighs the heaviest.</li>
  <li>The result for Schrijven A2 takes up to 16 weeks at the moment: plan it early.</li>
</ul>`,

  faq: [
  {
    q: 'Is the exam Schrijven on paper or on the computer?',
    a: 'At level A2 with pen and paper. That is the only language part for which this is the case; lezen, luisteren and spreken are done on the computer. So practise a few times by hand, because writing legibly and quickly with a pen is a separate skill.',
  },
  {
    q: 'How many tasks do I get in Schrijven A2?',
    a: 'Four, in 40 minutes. That comes down to about ten minutes per task. For example, you write a short letter or you fill in a form. With every task it says which points you must mention; those points are what you are marked on.',
  },
  {
    q: 'How long does the result for Schrijven take?',
    a: 'Normally within 8 weeks. DUO announced on 31 July 2026 that Spreken A2 and Schrijven A2 took up to 16 weeks at that time, with an automatic six-month extension for people who get into trouble because of this. Check the current situation with DUO, and in any case plan this part early.',
  },
  {
    q: 'What if I make a lot of spelling mistakes?',
    a: 'A few mistakes are not immediately fatal. What is looked at is whether you carried out the task, whether your message is understandable and whether the form fits the situation. Writing clearly and completely with short sentences gives you more than beautiful sentences with gaps in the content.',
  },
  {
    q: 'May I make a rough draft?',
    a: 'You get paper and you have 40 minutes for four tasks, so a complete rough draft costs too much time. Do make a short list of the requested points before you begin, and tick them off while you write. That is the cheapest way to gain points.',
  },
  ],
};

export default translation;
