/**
 * spreken-examen — English.
 *
 * A translation of the Dutch body in `../spreken-examen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_MIC, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_NIEUWS, SRC_NT2, SRC_OEFENEN, SRC_TAALEXAMENS, SRC_UITSLAG, card } from '../spreken-examen';

const translation: GuideLocale = {
  title: 'The Spreken exam (A2 and B1): format, time and approach',
  description: 'You do Spreken on a computer with a microphone: videos and pictures with questions. How the exam works at A2 and B1, and how to practise out loud.',
  breadcrumb: 'Spreken',
  dateLabel: '23 August 2026',
  eyebrow: 'Language exam',
  heroTitle: 'The exam Spreken',
  heroSubtitle: 'You speak to a computer, not to a person. That makes it strange, and for many people stressful — and it is exactly why practising out loud helps so much.',
  ctaTitle: 'Practise the exam part Spreken',
  ctaDesc: 'Speaking tasks with feedback per criterion, written by an NT2 teacher.',
  ctaLabel: 'View the modules',

  articleHtml: `
<h2 id="hoe-ziet-het-eruit">What does the exam look like?</h2>

<p>You sit at a computer with headphones and a microphone. You see a video or a picture with a
question, and you record your answer by speaking. So there is
<strong>no examiner sitting opposite you</strong>.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th></th><th>A2</th><th>B1</th></tr></thead>
  <tbody>
    <tr><td><strong>Duration</strong></td><td>35 minutes</td><td>about 30 minutes</td></tr>
    <tr><td><strong>How</strong></td><td>On the computer, with a microphone</td><td>Staatsexamen NT2, see staatsexamensnt2.nl</td></tr>
    <tr><td><strong>In DUO’s oefenexamens (practice exams)</strong></td><td>16 questions</td><td>see staatsexamensnt2.nl</td></tr>
    <tr><td><strong>Assessment</strong></td><td>Partly automatic, partly by assessors</td><td>By assessors</td></tr>
  </tbody>
</table>
</div>

${factTwoIn('en', 'DUO: "Het examen Spreken op niveau A2 doet u op de computer. U moet Nederlands spreken en verstaan. U bekijkt filmpjes en u beantwoordt vragen. Het examen duurt 35 minuten." (You take the exam Spreken at level A2 on the computer. You have to speak and understand Dutch. You watch videos and you answer questions. The exam takes 35 minutes.) The exams Spreken at level B1 and B2 (staatsexamen Nt2) take about 30 minutes.', [['inburgeren.nl — Taalexamens', SRC_TAALEXAMENS], ['Staatsexamens NT2', SRC_NT2]], CHECKED)}

<h2 id="soorten-vragen">The four types of question</h2>

<p>The start screen of DUO’s own oefenexamen Spreken A2 says it literally: there are four types of
question. That is the most practical way to divide up your preparation.</p>

<div class="guide-cards">
  ${card(I_MIC, 'A question with a video', 'Someone speaks to you and asks you something. You answer as you would in real life — short, direct, and to the point.')}
  ${card(I_MIC, 'A question with 1 picture', 'You see one photo. Usually you have to say what you see, or what you would say or do in that situation.')}
  ${card(I_MIC, 'A question with 2 pictures', 'Two options next to each other. You choose one and you explain why. The "why" is the point.')}
  ${card(I_MIC, 'A question with 3 pictures', 'Three images that together form a short story. You tell what happens, in order.')}
</div>

${factIn('en', 'The start screen of DUO’s public oefenexamens Spreken A2 says: "Het examen heeft vier soorten vragen: vragen met een video, vragen met 1 plaatje, vragen met 2 plaatjes, vragen met 3 plaatjes. U mag 35 minuten over het examen doen." (The exam has four types of question: questions with a video, questions with 1 picture, questions with 2 pictures, questions with 3 pictures. You may take 35 minutes for the exam.) The counter shows 16 questions.', 'inburgeren.nl — Oefenen', SRC_OEFENEN, CHECKED)}

${note('You get a <strong>limited speaking time</strong> for each question and the recording starts by itself. You cannot redo an answer. That feels uncomfortable, but it also means: keep talking is better than starting again.')}

<h2 id="waarop-beoordeeld">What are you assessed on?</h2>

<p>Spreken is assessed partly automatically and partly by people. Broadly speaking, four things
matter at the same time.</p>

<ul>
  <li><strong>Did you answer the question?</strong> A beautiful story about something else gives you nothing.</li>
  <li><strong>Can you be understood?</strong> Pronunciation and speed. Calm and clear is better than fast.</li>
  <li><strong>Do you use enough language?</strong> Two words is too little, even if they are correct. Make sentences.</li>
  <li><strong>Does it keep going a bit?</strong> Hesitating is allowed; falling completely silent costs you the recording.</li>
</ul>

${docentIn('en', 'The biggest problem with Spreken is not the language but the silence. Students think for three seconds, then say one word, and the recording stops. Keep talking, even if you are unsure. Say "let me think for a moment", say it in other words, repeat the question. Anything is better than saying nothing.')}

<h2 id="aanpak">Approach for each type of question</h2>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>With a video: react like a person</h3>
    <p>Someone asks you something. Answer as you would at a counter: short, friendly, with a reason. "Yes, that is fine, because I am free that day."</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>With 1 picture: name it, and expand</h3>
    <p>First say what you see, then where, then what is happening. Three sentences instead of one. "I see a man in a shop. He is standing at the till. He is paying with his pinpas (debit card)."</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>With 2 pictures: choose and give reasons</h3>
    <p>Choose quickly — which one you choose does not matter. All the points are in the "because". "I choose the bike, because it is close by and because it is cheaper than the bus."</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>With 3 pictures: tell it in order</h3>
    <p>Use sequence words: first, after that, then, finally. They turn separate sentences into a story, and that is exactly what is being asked.</p>
  </div></div>
</div>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">Do</p>
    <ul>
      <li>${I_CHECK}<span>Speak clearly and not too fast, with your mouth close to the microphone</span></li>
      <li>${I_CHECK}<span>Use full sentences, also for a simple question</span></li>
      <li>${I_CHECK}<span>Always give a reason — "omdat" (because) is the most useful word in this exam</span></li>
      <li>${I_CHECK}<span>Correct yourself out loud if you say something wrong; that is allowed and it does not count against you</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Do not</p>
    <ul>
      <li>${I_X}<span>Stay silent in order to think</span></li>
      <li>${I_X}<span>Whisper or turn away from the microphone</span></li>
      <li>${I_X}<span>Recite a learned story that does not fit the question</span></li>
      <li>${I_X}<span>Answer only "yes" or "the bike"</span></li>
    </ul>
  </div>
</div>

<h2 id="zenuwen">Nerves and the microphone</h2>

<p>Almost everyone finds it uncomfortable to speak into a computer. That is normal, and you can
train it — by doing it often, not by avoiding it.</p>

<ul>
  <li>Record yourself with your phone. The first time is strange, the fifth time is not.</li>
  <li>Listen back to your recording. You hear straight away if you speak too softly or fall silent too often.</li>
  <li>Practise out loud, also on your own: describe what you see in the street, in full sentences.</li>
  <li>Do at least one complete oefenexamen with headphones and a microphone.</li>
</ul>

${docentIn('en', 'In class I let students listen back to their own recording. That is confronting, and it is the fastest learning moment of the whole course. Almost nobody hears themselves being silent for as long as they really are.')}

<h2 id="uitslag">Waiting time: plan this part early</h2>

<p>Just like Schrijven, Spreken A2 is assessed by people, and at the moment there is a longer
waiting time for that.</p>

${factTwoIn('en', 'On 31 July 2026 DUO announced that marking the exams Spreken A2 and Schrijven A2 was at that moment taking up to 16 weeks, with an automatic extension of six months for people who get into trouble with their inburgeringstermijn (integration deadline) because of this. For the other exams the usual period of 8 weeks applies.', [['inburgeren.nl — Nieuwsbericht 31-07-2026', SRC_NIEUWS], ['inburgeren.nl — Uitslag examen', SRC_UITSLAG]], CHECKED)}

<p>That is a news item and it can change; check with DUO before you plan. But as long as it
applies: <strong>do not take Spreken last</strong>. If you fail, you still have the waiting time
for the result and for the resit ahead of you.</p>

${inlineCta('Practise Spreken with assessment per criterion', 'Record your answer as in the exam and get feedback on content, intelligibility and language use.', '/premium', 'View the modules')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>A2: 35 minutes on the computer with a microphone; B1: about 30 minutes.</li>
  <li>Four types of question: video, 1 picture, 2 pictures, 3 pictures.</li>
  <li>DUO’s A2 oefenexamens have 16 questions.</li>
  <li>Keep talking, use full sentences and always give a reason.</li>
  <li>The result for Spreken A2 currently takes up to 16 weeks: plan it early.</li>
</ul>`,

  faq: [
  {
    q: 'Do I speak to a real person in the exam Spreken?',
    a: 'No. You sit at a computer with headphones and a microphone. You see videos and pictures with questions, and you record your answer by speaking. There is no examiner sitting opposite you, and you cannot ask for anything to be repeated.',
  },
  {
    q: 'What kind of questions do I get in Spreken A2?',
    a: 'According to the start screen of DUO’s own oefenexamen there are four types: questions with a video, with one picture, with two pictures and with three pictures. With two pictures you choose one and explain why; with three pictures you tell in order what happens.',
  },
  {
    q: 'What do I do if I do not know the answer?',
    a: 'Keep talking. Silence never gives you points, half an answer sometimes does. Say the question back in your own words, name what you do see, or give a reason why you are unsure. You may also correct yourself out loud; that does not count against you.',
  },
  {
    q: 'How can I practise Spreken if I have no Dutch conversation partner?',
    a: 'Out loud, on your own, with a recording. Describe what you see in full sentences and record yourself with your phone. Then listen back: you hear straight away if you speak too softly, go too fast or stay silent too long. Also look for a taalmaatje (language buddy) or taalcafé through the library or VluchtelingenWerk.',
  },
  {
    q: 'How long does the result of Spreken take?',
    a: 'Normally within 8 weeks. On 31 July 2026 DUO announced that Spreken A2 and Schrijven A2 were at that moment taking up to 16 weeks, with an automatic extension of six months for people who get into trouble because of this. Check the current situation with DUO and do not plan this part last.',
  },
  ],
};

export default translation;
