/**
 * staatsinrichting-en-rechtsstaat — English.
 *
 * A translation of the Dutch body in `../staatsinrichting-en-rechtsstaat.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_CLIPBOARD, I_HOME, I_LANDMARK, I_USERS, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_ART1, SRC_EINDTERMEN, SRC_GRONDWET, SRC_KONING, SRC_PARLEMENT, SRC_RECHTSPRAAK, SRC_VERKIEZINGEN, card, row } from '../staatsinrichting-en-rechtsstaat';

const translation: GuideLocale = {
  title: 'KNM: Staatsinrichting en rechtsstaat explained',
  description: 'How does Dutch democracy work? Learn about the government, parliament, elections, the Grondwet and the independent judge in the KNM theme Staatsinrichting.',
  breadcrumb: 'Staatsinrichting',
  dateLabel: '23 August 2026',
  eyebrow: 'KNM theme 7',
  heroTitle: 'Staatsinrichting en rechtsstaat',
  heroSubtitle: 'Who makes the laws, who governs the country, and who checks all of that? This theme explains how Dutch democracy works — and why nobody is above the law.',
  ctaTitle: 'Practise the theme Staatsinrichting',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after every answer. Without an account.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="wat-vraagt-knm">What does KNM ask about this theme?</h2>

<div class="compare-rows">
  ${row('7.1', 'Deeper knowledge of the democratic rule of law')}
  ${row('7.2', 'Knowing legal provisions')}
</div>

${factIn('en', 'The KNM eindtermen (final attainment targets) for the theme Staatsinrichting en rechtsstaat are: deeper knowledge of the democratic rule of law, and knowing legal provisions.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

<h2 id="democratie">The Netherlands is a democracy</h2>

<p>That means: the people choose. Not the king, not the army, not one party. Every four years
there are elections for the Tweede Kamer (House of Representatives), and everyone of 18 years and
older with Dutch nationality may vote.</p>

<p>The Netherlands is also a <strong>constitutional monarchy</strong>: there is a king, but he does
not govern. The king is head of state and has a ceremonial role. The ministers are responsible, and
they answer to the parliament.</p>

${factIn('en', 'The King is inviolable; the ministers are responsible. The King is head of state and, together with the ministers, forms part of the government, but policy is the responsibility of the ministers.', 'Het Koninklijk Huis — Staatsrecht', SRC_KONING, CHECKED)}

<h3>Who does what?</h3>

<div class="guide-cards">
  ${card(I_LANDMARK, 'De regering (the government)', 'The king and the ministers. They govern the country and prepare laws. The minister-president is the chair of the ministerraad (council of ministers).')}
  ${card(I_USERS, 'De Tweede Kamer', '150 members, elected by the people. They take part in making laws, change them, and monitor the government. This is the most important political arena in the country.')}
  ${card(I_USERS, 'De Eerste Kamer', '75 members, elected by the Provinciale Staten. They only look at whether a law is sound and workable: yes or no, changing it is not allowed.')}
  ${card(I_CLIPBOARD, 'De rechter (the judge)', 'Independent of politics. The judge decides whether someone has broken the law and settles conflicts between people, companies and the government.')}
</div>

<p>That separation is the heart of this theme. The legislator makes the law, the government carries
it out, and the judge rules — and those three are separated from each other. That is called the
<strong>trias politica</strong>, or separation of powers.</p>

${factTwoIn('en', 'The parliament (Staten-Generaal) consists of the Tweede Kamer with 150 members and the Eerste Kamer with 75 members; the parliament makes laws together with the government and monitors the government. The judiciary is independent: judges rule without interference from politics or public administration.', [['Rijksoverheid — Parlement', SRC_PARLEMENT], ['Rechtspraak.nl — De rechtsstaat', SRC_RECHTSPRAAK]], CHECKED)}

<h2 id="verkiezingen">Elections: what are you voting for?</h2>

<p>There are several elections in the Netherlands, and they are about different things. This is
exactly the kind of difference the exam asks about.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>Election</th><th>What for</th><th>Who may vote</th></tr></thead>
  <tbody>
    <tr><td><strong>Tweede Kamer</strong></td><td>The national government</td><td>Dutch nationals from 18 years old</td></tr>
    <tr><td><strong>Gemeenteraad</strong></td><td>Your own gemeente (municipality)</td><td>Also non-Dutch nationals, if you have lived in the Netherlands lawfully for long enough</td></tr>
    <tr><td><strong>Provinciale Staten</strong></td><td>The province — and indirectly the Eerste Kamer</td><td>Dutch nationals from 18 years old</td></tr>
    <tr><td><strong>Waterschap</strong></td><td>Dikes and water management</td><td>Residents of the waterschap (water authority)</td></tr>
    <tr><td><strong>Europees Parlement</strong></td><td>The European Union</td><td>EU citizens</td></tr>
  </tbody>
</table>
</div>

<p>Note the second row: for the <strong>gemeenteraad</strong> (municipal council) you may usually
vote even if you do not have Dutch nationality, as long as you have lived here lawfully for long
enough. Many people doing inburgering (civic integration) do not know this. If you have the right
to vote, a stempas (voting pass) is sent to your home automatically.</p>

${factIn('en', 'For the Tweede Kamer, the right to vote applies from the age of 18 for Dutch nationals. In municipal elections, non-Dutch residents may also vote, subject to conditions about the length of their lawful residence in the Netherlands.', 'Rijksoverheid — Verkiezingen', SRC_VERKIEZINGEN, CHECKED)}

${note('Voting in the Netherlands is a <strong>right, not a duty</strong>. Nobody may force you to vote, and nobody may force you to vote for a particular party. What you vote is secret, also from your family and your employer.')}

<h3>How voting works</h3>
<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Your stempas arrives by post</h3>
    <p>If you have the right to vote, you get it at home automatically. Keep it safe.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Bring your stempas and your identity document</h3>
    <p>Without both of them you cannot vote. Your ID may be expired by no more than five years.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>In the voting booth you are alone</h3>
    <p>You colour in one box with the red pencil. Nobody may come with you, except in the case of a physical disability.</p>
  </div></div>
</div>

<h2 id="rechtsstaat">Rechtsstaat: nobody is above the law</h2>

<p>Democracy means: the majority decides. Rechtsstaat (rule of law) means: the majority must also
obey the law, and minorities are protected. Those two together make a democratic rechtsstaat.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">What that means in practice</p>
    <ul>
      <li>${I_CHECK}<span>The government must obey the law too, and you can take the government to court</span></li>
      <li>${I_CHECK}<span>Judges are independent and are not appointed or dismissed by politicians over the content of their rulings</span></li>
      <li>${I_CHECK}<span>You are innocent until a judge proves the opposite</span></li>
      <li>${I_CHECK}<span>You have the right to a lawyer, and to an interpreter if you do not speak the language</span></li>
      <li>${I_CHECK}<span>You can almost always appeal</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">What nobody is allowed to do</p>
    <ul>
      <li>${I_X}<span>Take the law into your own hands or take revenge</span></li>
      <li>${I_X}<span>Punish someone without a judge</span></li>
      <li>${I_X}<span>Discriminate, not even in the name of a religion or a tradition</span></li>
      <li>${I_X}<span>Use violence within the family — that is a criminal offence, also against your partner or your child</span></li>
    </ul>
  </div>
</div>

<h2 id="grondrechten">The Grondwet and your fundamental rights</h2>

<p>The Grondwet (Constitution) is the most important law of the country. All other laws must be in
line with it. The first articles are about your rights.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>Right</th><th>What it means</th></tr></thead>
  <tbody>
    <tr><td><strong>Equal treatment</strong></td><td>Everyone is treated equally in equal cases; discrimination is forbidden (article 1)</td></tr>
    <tr><td><strong>Freedom of religion</strong></td><td>You may believe what you want, and express that too — or believe nothing</td></tr>
    <tr><td><strong>Freedom of expression</strong></td><td>You may say and write what you think, also about the government. Inciting hatred and discrimination is not allowed.</td></tr>
    <tr><td><strong>Freedom of association and assembly</strong></td><td>You may join a club, a trade union or a party, and demonstrate</td></tr>
    <tr><td><strong>Inviolability of the body</strong></td><td>Nobody may touch you or do anything with your body without your permission</td></tr>
    <tr><td><strong>Right to education</strong></td><td>Education is free, and there is leerplicht (compulsory education) for children</td></tr>
  </tbody>
</table>
</div>

<p>Fundamental rights sometimes clash with each other — freedom of expression against the ban on
discrimination, for example. In the Netherlands the <strong>judge</strong> then decides which right
weighs more heavily in that case. Not the government, and not the majority.</p>

${factTwoIn('en', 'The Grondwet is the highest national law and contains the fundamental rights, including the ban on discrimination in article 1. Other legislation must be in accordance with the Grondwet.', [['wetten.overheid.nl — Grondwet', SRC_GRONDWET], ['wetten.overheid.nl — Artikel 1 Grondwet', SRC_ART1]], CHECKED)}

${docentIn('en', 'Students often find this theme abstract, until it is about their own life. Freedom of expression is an idea; that you may file a complaint against your gemeente and that a judge can rule against that gemeente is very concrete. For every fundamental right, look for one example from your own life — then it stays with you.')}

<h2 id="wettelijke-bepalingen">Legal provisions you have to know</h2>

<p>Eindterm 7.2 is about rules that you deal with in daily life.</p>

<div class="guide-cards">
  ${card(I_HOME, 'Identificatieplicht (duty to identify)', 'From the age of 14 you must be able to show your identity document if a police officer or an inspector asks for it.')}
  ${card(I_CLIPBOARD, 'Leerplicht', 'Children from 5 to 16 years old must go to school, and after that the kwalificatieplicht applies until the age of 18 or until a startkwalificatie (basic qualification).')}
  ${card(I_USERS, 'Equality in the family', 'Man and woman are equal before the law. Forced marriage, child marriage and polygamy are forbidden in the Netherlands.')}
  ${card(I_LANDMARK, 'Domestic violence', 'Violence against your partner or your child is a criminal offence. For help and advice there is Veilig Thuis, also anonymously.')}
  ${card(I_CLIPBOARD, 'Traffic rules', 'Bicycle lights, no alcohol on the road, and no phone in your hand — not even on a bicycle.')}
</div>

${note('Not sure whether something is allowed? Ask the Juridisch Loket (free legal advice desk) or your gemeente before you do it. In the Netherlands not knowing is no excuse, but asking for help is free and normal.')}

<h2 id="in-het-examen">How this comes back in the exam</h2>

<p>As situations about rights: may someone say this, may an employer ask this, who actually decides
here? The safe line is: <strong>everyone equal, the judge decides, the government is under the law
too</strong>.</p>

${inlineCta('Practise this theme with exam questions', 'Democracy, fundamental rights and the judge — with an explanation after every answer.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>Democracy: the people choose, every four years the Tweede Kamer (150 members).</li>
  <li>The king is head of state but does not govern; the ministers are responsible.</li>
  <li>Separation of powers: legislator, government and judge are separated.</li>
  <li>For the gemeenteraad you may often vote without a Dutch passport.</li>
  <li>The Grondwet ranks above other laws; article 1 forbids discrimination.</li>
</ul>`,

  faq: [
  {
    q: 'Who governs the Netherlands: the king or the government?',
    a: 'The government, and it consists of the king and the ministers. But the king does not govern: he is inviolable and mainly has a ceremonial role. The ministers are responsible for policy and answer to the parliament about it.',
  },
  {
    q: 'What is the difference between the Tweede Kamer and the Eerste Kamer?',
    a: 'The Tweede Kamer has 150 members and is elected directly by the voters. That chamber takes part in making laws, may change them and monitors the government. The Eerste Kamer has 75 members, is elected by the Provinciale Staten, and only looks at whether a law is sound and workable: yes or no, without changing it.',
  },
  {
    q: 'May I vote if I do not have a Dutch passport?',
    a: 'For the gemeenteraad usually yes, if you have lived in the Netherlands lawfully for long enough. For the Tweede Kamer and the Provinciale Staten you need Dutch nationality. If you have the right to vote, a stempas is sent to your home automatically.',
  },
  {
    q: 'What is a rechtsstaat?',
    a: 'A country in which everyone must obey the law, including the government itself. Judges are independent, you are innocent until the opposite is proven, you have the right to a lawyer and you can appeal. That also protects minorities against a majority that wants something else.',
  },
  {
    q: 'What does article 1 of the Grondwet say?',
    a: 'That everyone who is in the Netherlands is treated equally in equal cases, and that discrimination is not allowed — not on grounds of religion, belief, political opinion, race, sex, disability or sexual orientation, and not on any other ground either.',
  },
  ],
};

export default translation;
