/**
 * taalexamens-a2-b1 — Arabic.
 *
 * A translation of the Dutch body in `../taalexamens-a2-b1.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_BOOK, I_CHECK, I_HEADPHONES, I_MIC, I_PEN, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_KOSTEN, SRC_OEFENEN, SRC_PLAATSEN, SRC_REGLEMENT, SRC_ROUTES, SRC_TAALEXAMENS, SRC_UITSLAG, card } from '../taalexamens-a2-b1';

const translation: GuideLocale = {
  title: 'امتحانات اللغة A2 وB1: القراءة والاستماع والكتابة والتحدث',
  description: 'أربعة أجزاء لغوية ومستويان. ما الذي تفعله في القراءة والاستماع والكتابة والتحدث، وكم تستغرق مدة كل امتحان، وما الفرق بين مستوى A2 ومستوى B1.',
  breadcrumb: 'امتحانات اللغة',
  dateLabel: '23 أغسطس 2026',
  eyebrow: 'امتحانات اللغة',
  heroTitle: 'امتحانات اللغة A2 وB1',
  heroSubtitle: 'أربعة أجزاء: القراءة والاستماع والكتابة والتحدث. الأربعة مختلفة في شكلها، وتستعد لكل واحد منها بطريقة مختلفة. هنا تجد كيف تعمل.',
  ctaTitle: 'تدرّب على جزء امتحاني كامل',
  ctaDesc: 'امتحان تجريبي مجاني من عشرة أسئلة، مع شرح بعد كل إجابة. من دون حساب.',
  ctaLabel: 'ابدأ امتحاناً تجريبياً مجانياً',

  articleHtml: `
<h2 id="vier-onderdelen">أربعة أجزاء، أربعة امتحانات منفصلة</h2>

<p>امتحان اللغة الخاص بك ليس امتحاناً واحداً. إنها أربعة امتحانات، وتؤديها في أربعة أوقات
مختلفة. لذلك يمكنك أن تجتاز واحداً منها في كل مرة — وإذا لم تجتز أحدها، فلا يلزمك
إعادة سوى ذلك الجزء.</p>

<div class="guide-cards">
  ${card(I_BOOK, 'القراءة (Lezen)', 'تقرأ نصوصاً قصيرة وتجيب عن أسئلة عنها. على الكمبيوتر. في مستوى A2 يستغرق 65 دقيقة، وفي مستوى B1 110 دقيقة.')}
  ${card(I_HEADPHONES, 'الاستماع (Luisteren)', 'تشاهد مقاطع فيديو وتستمع إلى محادثات، وتجيب عن أسئلة. على الكمبيوتر. مستوى A2 يستغرق 45 دقيقة، وB1 يستغرق 90 دقيقة.')}
  ${card(I_PEN, 'الكتابة (Schrijven)', 'تكتب نصوصاً قصيرة وتملأ نماذج. في مستوى A2 تؤدي هذا <strong>بالقلم والورق</strong> خلال 40 دقيقة؛ وفي مستوى B1 يستغرق 100 دقيقة.')}
  ${card(I_MIC, 'التحدث (Spreken)', 'تتحدث عبر ميكروفون؛ وتُعرض عليك مقاطع فيديو وصور. مستوى A2 يستغرق 35 دقيقة، وB1 نحو 30 دقيقة.')}
</div>

${factIn('ar', 'DUO عن امتحانات اللغة: Lezen A2 يستغرق 65 دقيقة وLezen B1 يستغرق 110 دقيقة؛ Luisteren A2 يستغرق 45 دقيقة وLuisteren B1 يستغرق 90 دقيقة؛ Schrijven A2 تؤديه بالقلم والورق ويستغرق 40 دقيقة، وSchrijven B1 يستغرق 100 دقيقة؛ Spreken A2 يستغرق 35 دقيقة وSpreken B1 نحو 30 دقيقة.', 'inburgeren.nl — Taalexamens A2, B1 en B2', SRC_TAALEXAMENS, CHECKED)}

${note('الكتابة في مستوى A2 هي الجزء الوحيد الذي يجري <strong>على الورق</strong>. وهذا يفاجئ كثيرين ممن تدربوا على لوحة المفاتيح. اكتب أثناء تحضيرك بضع مرات على الأقل بخط اليد — فالكتابة المقروءة تحت ضغط الوقت مهارة قائمة بذاتها.')}

<h2 id="hoeveel-vragen">كم عدد الأسئلة فيه؟</h2>

<p>هنا يجب أن نتوخى الحذر، وهذا بالضبط سبب وجود هذا الموقع. <strong>DUO لا ينشر في أي مكان
كم سؤالاً يحتوي عليه الامتحان.</strong> أما ما هو علني بالفعل فهو امتحانات التدريب
(oefenexamens) الخاصة بـ DUO: يمكنك أداؤها من دون تسجيل دخول، وعلى شاشة البداية يظهر العدد.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>الجزء (A2)</th><th>في امتحانات التدريب لدى DUO</th><th>المدة</th></tr></thead>
  <tbody>
    <tr><td><strong>القراءة (Lezen)</strong></td><td>25 سؤالاً</td><td>65 دقيقة</td></tr>
    <tr><td><strong>الاستماع (Luisteren)</strong></td><td>25 سؤالاً</td><td>45 دقيقة</td></tr>
    <tr><td><strong>الكتابة (Schrijven)</strong></td><td>4 مهام</td><td>40 دقيقة</td></tr>
    <tr><td><strong>التحدث (Spreken)</strong></td><td>16 سؤالاً</td><td>35 دقيقة</td></tr>
  </tbody>
</table>
</div>

<p>لذلك لا تقل لنفسك: «الامتحان فيه 25 سؤالاً». بل قل: «امتحانات التدريب لدى DUO فيها
25 سؤالاً». هذا ما يمكنك التحقق منه، وهو كافٍ لتبني عليه تحضيرك.</p>

${factIn('ar', 'يوفّر DUO امتحانات تدريب يستطيع الجميع أداءها من دون تسجيل دخول. وعلى شاشات البداية لامتحانات التدريب لمستوى A2 يظهر عدد الأسئلة: 25 في Lezen، و25 في Luisteren، و16 في Spreken؛ أما امتحان التدريب Schrijven فيحتوي على 4 مهام.', 'inburgeren.nl — Oefenen', SRC_OEFENEN, CHECKED)}

<h2 id="a2-of-b1">A2 أم B1: أي مستوى عليّ أن أؤدي؟</h2>

<p>لا تقرر ذلك بنفسك. بموجب Wet inburgering 2021 (قانون الاندماج لعام 2021) تختار
<strong>gemeente</strong> (البلدية) بعد المقابلة الشاملة (brede intake) واختبار القابلية للتعلّم
(leerbaarheidstoets) مساراً تعليمياً، وهذا المسار يحدد مستواك.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>مسار B1 (B1-route)</h3>
    <p>تؤدي امتحانات اللغة على مستوى B1. وهذا هو المسار القياسي بموجب قانون 2021.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>المسار التعليمي (Onderwijsroute)</h3>
    <p>مخصص بالأخص للشباب الراغبين في الالتحاق بالـ mbo أو hbo أو الجامعة. تحصل على B1 أو B2.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>مسار Z (Z-route)</h3>
    <p>تتعلم اللغة الهولندية على مستوى A1. و<strong>يجوز</strong> لك أداء امتحانات اللغة على مستوى A2، لكن ذلك غير إلزامي. وتُنهي المسار بمحادثة لدى gemeente.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Wet inburgering 2013</h3>
    <p>هل ما زلت تندمج بموجب القانون القديم؟ إذاً تؤدي امتحانات اللغة على مستوى A2.</p>
  </div></div>
</div>

<p>هل أنت في مسار B1 وتبيّن أن مستوى B1 مرتفع فعلاً بالنسبة لك؟ عندئذٍ يمكنك بشروط معينة
<strong>النزول إلى مستوى A2</strong>. وهذا ممكن فقط انطلاقاً من مسار B1، وفقط إذا كنت قد تابعت
ما لا يقل عن 600 ساعة من دروس اللغة في مدرسة حاصلة على علامة الجودة (keurmerk) <strong>و</strong>
بذلت جهداً كافياً يمكن إثباته. وتتحقق gemeente من ذلك.</p>

${factTwoIn('ar', 'تحدد gemeente بناءً على المقابلة الشاملة (brede intake) أي مسار تعليمي ستتبعه. في مسار B1 تؤدي امتحانات اللغة على مستوى B1؛ وفي مسار Z تتعلم الهولندية على مستوى A1 ويجوز لك أداء امتحانات على مستوى A2، لكن ذلك غير إلزامي. والنزول من B1 إلى A2 ممكن فقط انطلاقاً من مسار B1 ويتطلب ما لا يقل عن 600 ساعة دورة لدى مؤسسة حاصلة على keurmerk.', [['inburgeren.nl — U gaat inburgeren', SRC_ROUTES], ['Besluit inburgering 2021, artikel 5.5', 'https://wetten.overheid.nl/jci1.3:c:BWBR0045555&artikel=5.5']], CHECKED)}

<h3>ما الفرق بين A2 وB1 عملياً؟</h3>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>A2</h3>
      <p class="compare-when">مستخدم أساسي</p>
    </div>
    <div class="compare-rows">
      <div class="compare-row"><p class="compare-key">النصوص</p><p class="compare-val">قصيرة وملموسة: رسالة قصيرة، إعلان، بريد إلكتروني من المدرسة</p></div>
      <div class="compare-row"><p class="compare-key">المواضيع</p><p class="compare-val">حياتك المباشرة: السكن، العمل، التسوق، الصحة</p></div>
      <div class="compare-row"><p class="compare-key">الكتابة</p><p class="compare-val">جمل منفصلة، نموذج، رسالة قصيرة</p></div>
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>B1</h3>
      <p class="compare-when">مستخدم مستقل</p>
    </div>
    <div class="compare-rows">
      <div class="compare-row"><p class="compare-key">النصوص</p><p class="compare-val">أطول ومترابطة: خبر إخباري، منشور، دليل استخدام</p></div>
      <div class="compare-row"><p class="compare-key">المواضيع</p><p class="compare-val">وأيضاً خارج نطاق حياتك: العمل، التعليم، الشأن الراهن</p></div>
      <div class="compare-row"><p class="compare-key">الكتابة</p><p class="compare-val">نص مترابط برأي خاص وببنية واضحة</p></div>
    </div>
  </div>
</div>

${docentIn('ar', 'الفرق بين A2 وB1 ليس في المقام الأول عدداً أكبر من الكلمات. الفرق هو أنك في مستوى B1 يجب أن تكون قادراً على إبداء رأي وشرحه. في A2 تقول «لا يعجبني هذا»؛ وفي B1 تقول لماذا، مع مثال، في جملتين أو ثلاث متتالية. وهذا ما لا تتدرب عليه بما يكفي إذا اكتفيت بحفظ الكلمات.')}

<h2 id="wanneer-geslaagd">متى تكون قد نجحت؟</h2>

<p>هذا لا ينشره DUO. في Examenreglement (لائحة الامتحانات) مكتوب أن الحد الفاصل بين الرسوب
والنجاح هو <strong>cesuur</strong> (حد فاصل) تحدده الوزارة. ولا تُذكر معه أي نسبة مئوية
ولا عدد إجابات صحيحة.</p>

<p>المواقع التي تذكر مثل هذا الرقم لا تستطيع إثباته. لذلك نحن لا نذكره. أما ما يمكنك فعله بالفعل:
تدرّب حتى تشعر بالارتياح في كل جزء ضمن الوقت المتاح، بدلاً من استهداف حد لا يعرفه أحد.</p>

${factIn('ar', 'تنص Examenreglement inburgering على أن الحد الفاصل بين الرسوب والنجاح يتكوّن من cesuur تحددها الوزارة. ولا ينشر DUO نسبة مئوية محددة ولا عدداً من الإجابات الصحيحة.', 'DUO — Examenreglement inburgering, artikel 10', SRC_REGLEMENT, CHECKED)}

<h2 id="aanmelden">التسجيل والتكاليف والنتيجة</h2>

<p>تسجّل لكل جزء على حدة عبر <strong>Mijn Inburgering</strong> (بيئتك الشخصية لدى DUO)، باستخدام
DigiD. وتختار بنفسك التاريخ والمكان. تؤدي امتحانات المعرفة وامتحانات اللغة A2 في أحد مواقع DUO
الستة: Amsterdam أو Eindhoven أو Rijswijk أو Rotterdam أو Utrecht أو Zwolle. أما B1 وB2 فهما
amtحانا staatsexamens NT2 (امتحانات الدولة NT2) ولهما مواقعهما الخاصة.</p>

<p>في الوقت الحالي يكلّف كل جزء €50. وهذا السعر مرتبط بمؤشر الأسعار — تحقق منه قبل أن تسجّل.</p>

<p>تصل نتيجة امتحانات اللغة A2 عادةً خلال <strong>8 أسابيع</strong>. انتبه إلى الاستثناء
الحالي أدناه.</p>

${note('أعلن DUO في 31 يوليو 2026 أن تصحيح <strong>Spreken A2 وSchrijven A2</strong> يستغرق في الوقت الحالي <strong>16 أسبوعاً</strong> كحد أقصى. ومن يقع بسبب ذلك في ضيق فيما يتعلق بمهلة الاندماج الخاصة به، يحصل تلقائياً على تمديد 6 أشهر. ينطبق هذا فقط على هذين الجزأين؛ تحقق من الوضع الحالي لدى DUO.')}

${factTwoIn('ar', 'تصل نتيجة امتحانات اللغة A2 وامتحانات المعرفة خلال 8 أسابيع. وتُعقد الامتحانات في ستة مواقع: Amsterdam وEindhoven وRijswijk وRotterdam وUtrecht وZwolle.', [['inburgeren.nl — Uitslag examen', SRC_UITSLAG], ['inburgeren.nl — Examenplaatsen', SRC_PLAATSEN]], CHECKED)}

${factIn('ar', 'تدفع مقابل امتحان الاندماج عن كل جزء على حدة؛ وفي الوقت الحالي هذا يعني €50 لكل امتحان. المبالغ مرتبطة بمؤشر الأسعار وقد تتغير.', 'inburgeren.nl — Inburgeren betalen', SRC_KOSTEN, CHECKED)}

<h2 id="volgorde">بأي ترتيب تؤديها؟</h2>

<p>لا يوجد ترتيب إلزامي. لكن يوجد ترتيب حكيم، وهو يتعلق بـ<strong>أوقات الانتظار</strong>،
لا بالصعوبة.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">تصرّف ذكي</p>
    <ul>
      <li>${I_CHECK}<span>ابدأ بـ Lezen وLuisteren: فهما يُصححان آلياً وتحصل على نتيجتهما بأسرع ما يمكن</span></li>
      <li>${I_CHECK}<span>خطّط لـ Schrijven وSpreken قبل نهاية مهلتك بوقت كافٍ — فهما يُقيَّمان من قِبل أشخاص ويستغرقان وقتاً أطول</span></li>
      <li>${I_CHECK}<span>سجّل بمجرد أن تكون <strong>شبه</strong> جاهز؛ فبين التسجيل وأول تاريخ متاح تمر أسابيع</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">تصرّف محفوف بالمخاطر</p>
    <ul>
      <li>${I_X}<span>التخطيط للأربعة معاً في الأشهر الأخيرة من مهلتك</span></li>
      <li>${I_X}<span>الانتظار بالتسجيل حتى تشعر أنك «جاهز تماماً»</span></li>
      <li>${I_X}<span>الاعتماد على إعادة الامتحان من دون حساب وقت انتظار النتيجة</span></li>
    </ul>
  </div>
</div>

${inlineCta('احسب تواريخ نهايتك الخاصة', 'أداة الجدول الزمني تحسب لكل جزء متى يجب عليك التسجيل في أقصى تقدير لتبقى ضمن مهلتك.', '/oefenen', 'ابدأ التدرّب مجاناً')}

<h2 id="oefenen">كيف تستعد</h2>

<p>الاستعداد يختلف من جزء إلى آخر. ولهذا لكل جزء على هذا الموقع دليله الخاص: ما الذي يُعرض عليك
بالضبط، وأين يذهب الوقت، وأين يتعثر معظم الناس.</p>

${docentIn('ar', 'أكبر فرق بين النجاح والرسوب لدى طلابي نادراً ما يكون المستوى. إنه الوقت. هم يعرفون الكلمات فعلاً، لكنهم لم يتدربوا قط تحت ضغط الساعة. أدِّ امتحان تدريب كاملاً مع مؤقّت ثلاث مرات على الأقل قبل أن تؤدي الامتحان الحقيقي.')}
`,

  sidebarHtml: `
<p><strong>باختصار</strong></p>
<ul>
  <li>أربعة امتحانات منفصلة: القراءة، الاستماع، الكتابة، التحدث.</li>
  <li>A2: 65 و45 و40 و35 دقيقة. B1: 110 و90 و100 ونحو 30 دقيقة.</li>
  <li>Schrijven A2 يكون بالقلم والورق.</li>
  <li>gemeente الخاصة بك تحدد عبر المسار التعليمي إن كنت تؤدي A2 أم B1.</li>
  <li>DUO لا ينشر الحد الفاصل بين الرسوب والنجاح.</li>
</ul>`,

  faq: [
  {
    q: 'كم عدد الأسئلة في امتحان الاندماج A2؟',
    a: 'لا ينشر DUO ذلك على صفحاته المعلوماتية. لكن امتحانات التدريب الخاصة بـ DUO علنية، وعليها يظهر العدد: 25 سؤالاً في Lezen، و25 في Luisteren، و16 في Spreken، و4 مهام في Schrijven. احسب على هذا الأساس، لكن لا تسمّه معياراً رسمياً.',
  },
  {
    q: 'كم إجابة صحيحة يجب أن أحصل عليها لأنجح؟',
    a: 'هذا لا يعلنه DUO. في Examenreglement مكتوب أن الحد الفاصل هو cesuur تحددها الوزارة؛ ولا توجد نسبة مئوية منشورة ولا عدد من الإجابات الصحيحة. والأرقام التي تقرأها في مواضع أخرى لا تأتي من DUO.',
  },
  {
    q: 'هل عليّ أداء A2 أم B1؟',
    a: 'يعتمد ذلك على مسارك التعليمي، وهذا تختاره gemeente الخاصة بك بعد المقابلة الشاملة (brede intake) واختبار القابلية للتعلّم (leerbaarheidstoets). في مسار B1 تؤدي الامتحانات على مستوى B1، وفي المسار التعليمي B1 أو B2، وفي مسار Z تتعلم A1 ويجوز لك أداء امتحانات A2. وإذا كنت تندمج بموجب قانون 2013، فالمستوى هو A2.',
  },
  {
    q: 'هل يمكنني العودة من B1 إلى A2؟',
    a: 'فقط انطلاقاً من مسار B1، وبشروط. يجب أن تكون قد تابعت ما لا يقل عن 600 ساعة من دروس اللغة في مدرسة لغة حاصلة على keurmerk، ويجب أن تكون قد بذلت جهداً كافياً يمكن إثباته. وتتحقق gemeente من ذلك وتقرر.',
  },
  {
    q: 'كم يستغرق الأمر قبل أن أحصل على نتيجتي؟',
    a: 'عادةً خلال 8 أسابيع لامتحانات اللغة A2 وامتحانات المعرفة. وأعلن DUO في 31 يوليو 2026 أن Spreken A2 وSchrijven A2 قد يستغرقان في الوقت الحالي حتى 16 أسبوعاً، مع تمديد تلقائي لستة أشهر لمن يقع بسبب ذلك في ضيق. تحقق من الوضع الحالي لدى DUO.',
  },
  {
    q: 'هل يمكنني أداء جزء واحد على حدة؟',
    a: 'نعم. الأجزاء اللغوية الأربعة امتحانات منفصلة لكل منها تسجيل خاص وتاريخ خاص ونتيجة خاصة. وإذا لم تجتز أحدها، تعيد ذلك الجزء فقط؛ وما اجتزته يبقى سارياً.',
  },
  ],
};

export default translation;
