/**
 * taalexamens-a2-b1 — English.
 *
 * A translation of the Dutch body in `../taalexamens-a2-b1.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_BOOK, I_CHECK, I_HEADPHONES, I_MIC, I_PEN, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_KOSTEN, SRC_OEFENEN, SRC_PLAATSEN, SRC_REGLEMENT, SRC_ROUTES, SRC_TAALEXAMENS, SRC_UITSLAG, card } from '../taalexamens-a2-b1';

const translation: GuideLocale = {
  title: 'Language exams A2 and B1: reading, listening, writing',
  description: 'Four language parts, two levels. What you do in reading, listening, writing and speaking, how long each exam takes and how A2 differs from B1.',
  breadcrumb: 'The language exams',
  dateLabel: '23 August 2026',
  eyebrow: 'Language exams',
  heroTitle: 'The A2 and B1 language exams',
  heroSubtitle: 'Four parts: Lezen (reading), Luisteren (listening), Schrijven (writing) and Spreken (speaking). All four have a different form, and you also prepare for them in different ways. Here is how they work.',
  ctaTitle: 'Practise a complete exam part',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after each answer. Without an account.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="vier-onderdelen">Four parts, four separate exams</h2>

<p>Your language exam is not one exam. There are four of them, and you take them at four
different moments. So you can also pass them one at a time — and if you do not pass one of them,
you only have to redo that part.</p>

<div class="guide-cards">
  ${card(I_BOOK, 'Lezen (reading)', 'You read short texts and answer questions about them. On the computer. At A2 it takes 65 minutes, at B1 110 minutes.')}
  ${card(I_HEADPHONES, 'Luisteren (listening)', 'You watch short videos and listen to conversations, and answer questions. On the computer. A2 takes 45 minutes, B1 90 minutes.')}
  ${card(I_PEN, 'Schrijven (writing)', 'You write short texts and fill in forms. At A2 you do this <strong>with pen and paper</strong> in 40 minutes; at B1 it takes 100 minutes.')}
  ${card(I_MIC, 'Spreken (speaking)', 'You speak into a microphone; you are shown short videos and pictures. A2 takes 35 minutes, B1 about 30 minutes.')}
</div>

${factIn('en', 'DUO on the language exams: Lezen A2 takes 65 minutes and Lezen B1 110 minutes; Luisteren A2 takes 45 minutes and Luisteren B1 90 minutes; you take Schrijven A2 with pen and paper and it lasts 40 minutes, Schrijven B1 lasts 100 minutes; Spreken A2 takes 35 minutes and Spreken B1 about 30 minutes.', 'inburgeren.nl — Taalexamens A2, B1 en B2', SRC_TAALEXAMENS, CHECKED)}

${note('Schrijven at A2 is the only part <strong>on paper</strong>. That surprises many people who have practised on a keyboard. During your preparation, write by hand at least a few times — writing legibly under time pressure is a skill in itself.')}

<h2 id="hoeveel-vragen">How many questions are there?</h2>

<p>Here we have to be careful, and that is exactly why this site exists. <strong>DUO does not
publish anywhere how many questions an exam has.</strong> What is public are DUO's own
oefenexamens (practice exams): you can take them without logging in, and the start screen shows the
number.</p>

<div class="article-table-wrap">
<table>
  <thead><tr><th>Part (A2)</th><th>In DUO's practice exams</th><th>Duration</th></tr></thead>
  <tbody>
    <tr><td><strong>Lezen</strong></td><td>25 questions</td><td>65 minutes</td></tr>
    <tr><td><strong>Luisteren</strong></td><td>25 questions</td><td>45 minutes</td></tr>
    <tr><td><strong>Schrijven</strong></td><td>4 assignments</td><td>40 minutes</td></tr>
    <tr><td><strong>Spreken</strong></td><td>16 questions</td><td>35 minutes</td></tr>
  </tbody>
</table>
</div>

<p>So do not tell yourself: "the exam has 25 questions". Say: "DUO's practice exams have 25". That
is what you can check, and it is enough to base your preparation on.</p>

${factIn('en', 'DUO makes practice exams available that anyone can take without logging in. The start screens of the A2 practice exams show the number of questions: 25 for Lezen, 25 for Luisteren and 16 for Spreken; the Schrijven practice exam contains 4 assignments.', 'inburgeren.nl — Oefenen', SRC_OEFENEN, CHECKED)}

<h2 id="a2-of-b1">A2 or B1: which level do I have to take?</h2>

<p>You do not decide that yourself. Under the Wet inburgering 2021, your <strong>gemeente
(municipality)</strong> chooses a leerroute (learning route) after the brede intake and the
leerbaarheidstoets, and that route determines your level.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>B1-route</h3>
    <p>You take the language exams at level B1. That is the standard route under the 2021 act.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Onderwijsroute</h3>
    <p>Mainly for young people who want to go to mbo, hbo or university. You reach B1 or B2.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Z-route</h3>
    <p>You learn Dutch at level A1. You may take language exams at A2, but you do not have to. You finish the route with a conversation at the gemeente.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Wet inburgering 2013</h3>
    <p>Are you still doing your inburgering under the old act? Then you take the language exams at level A2.</p>
  </div></div>
</div>

<p>Are you in the B1-route and does B1 turn out to be really too high? Then, under conditions, you
can <strong>go down to A2</strong> (afschalen). That is only possible from the B1-route, and only
if you have followed at least 600 hours of language lessons at a school with a keurmerk (quality
mark) and can show that you have done your best. The gemeente checks this.</p>

${factTwoIn('en', 'The gemeente decides on the basis of the brede intake which leerroute you follow. In the B1-route you take the language exams at level B1; in the Z-route you learn Dutch at level A1 and may take exams at A2, but you do not have to. Going down from B1 to A2 is only possible from the B1-route and requires at least 600 hours of course at an institution with a keurmerk.', [['inburgeren.nl — U gaat inburgeren', SRC_ROUTES], ['Besluit inburgering 2021, artikel 5.5', 'https://wetten.overheid.nl/jci1.3:c:BWBR0045555&artikel=5.5']], CHECKED)}

<h3>What is the difference between A2 and B1 in practice?</h3>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>A2</h3>
      <p class="compare-when">Basic user</p>
    </div>
    <div class="compare-rows">
      <div class="compare-row"><p class="compare-key">Texts</p><p class="compare-val">Short and concrete: a note, an advertisement, an email from school</p></div>
      <div class="compare-row"><p class="compare-key">Topics</p><p class="compare-val">Your immediate life: housing, work, shopping, health</p></div>
      <div class="compare-row"><p class="compare-key">Writing</p><p class="compare-val">Separate sentences, a form, a short message</p></div>
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>B1</h3>
      <p class="compare-when">Independent user</p>
    </div>
    <div class="compare-rows">
      <div class="compare-row"><p class="compare-key">Texts</p><p class="compare-val">Longer and connected: a news item, a leaflet, a manual</p></div>
      <div class="compare-row"><p class="compare-key">Topics</p><p class="compare-val">Also outside your own life: work, education, current affairs</p></div>
      <div class="compare-row"><p class="compare-key">Writing</p><p class="compare-val">A connected text with your own opinion and a structure</p></div>
    </div>
  </div>
</div>

${docentIn('en', 'The difference between A2 and B1 is not mainly more words. It is that at B1 you have to be able to give an opinion and explain it. At A2 you say "I do not think it is good"; at B1 you say why, with an example, in two or three sentences in a row. You practise that too little if you only learn words.')}

<h2 id="wanneer-geslaagd">When have you passed?</h2>

<p>DUO does not publish that. The Examenreglement says that the line between failing and passing is
a <strong>cesuur</strong> that is set by the Minister. It gives no percentage and no number of
correct answers.</p>

<p>Sites that do give such a number cannot support it. That is why we do not give one. What you can
do: practise until you feel comfortable in each part within the time, instead of aiming at a line
that nobody knows.</p>

${factIn('en', 'The Examenreglement inburgering states that the line between failing and passing is formed by a cesuur, set by the Minister. DUO does not publish a concrete percentage or number of correct answers.', 'DUO — Examenreglement inburgering, artikel 10', SRC_REGLEMENT, CHECKED)}

<h2 id="aanmelden">Registering, costs and results</h2>

<p>You register for each part through <strong>Mijn Inburgering</strong>, with DigiD. You choose the
date and the place yourself. You take the kennisexamens and the A2 language exams at one of the six
DUO locations: Amsterdam, Eindhoven, Rijswijk, Rotterdam, Utrecht or Zwolle. B1 and B2 are
staatsexamens NT2 and have their own locations.</p>

<p>At the moment each part costs €50. That price is indexed — check it before you register.</p>

<p>The result of the A2 language exams normally comes within <strong>8 weeks</strong>. Note the
current exception below.</p>

${note('DUO reported on 31 July 2026 that the marking of <strong>Spreken A2 and Schrijven A2</strong> currently takes up to <strong>16 weeks</strong>. Anyone who runs into trouble with their inburgering deadline because of this automatically gets a 6-month extension. This applies only to those two parts; check the current situation with DUO.')}

${factTwoIn('en', 'The result of the A2 language exams and the kennisexamens comes within 8 weeks. The exams are taken at six locations: Amsterdam, Eindhoven, Rijswijk, Rotterdam, Utrecht and Zwolle.', [['inburgeren.nl — Uitslag examen', SRC_UITSLAG], ['inburgeren.nl — Examenplaatsen', SRC_PLAATSEN]], CHECKED)}

${factIn('en', 'For the inburgeringsexamen you pay per part; at the moment that is €50 per exam. The amounts are indexed and can change.', 'inburgeren.nl — Inburgeren betalen', SRC_KOSTEN, CHECKED)}

<h2 id="volgorde">In which order do you take them?</h2>

<p>There is no compulsory order. But there is a sensible one, and it is about <strong>waiting
times</strong>, not about difficulty.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">Smart</p>
    <ul>
      <li>${I_CHECK}<span>Start with Lezen and Luisteren: they are marked automatically and you get the result fastest</span></li>
      <li>${I_CHECK}<span>Plan Schrijven and Spreken well before the end of your deadline — they are marked by people and take longer</span></li>
      <li>${I_CHECK}<span>Register as soon as you are almost ready; there are weeks between registering and the first free date</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Risky</p>
    <ul>
      <li>${I_X}<span>Planning all four at the same time in the last months of your deadline</span></li>
      <li>${I_X}<span>Waiting to register until you feel "completely ready"</span></li>
      <li>${I_X}<span>Counting on a retake without also counting the waiting time for the result</span></li>
    </ul>
  </div>
</div>

${inlineCta('Calculate your own end dates', 'The timeline maker works out for each part when you have to register at the latest to stay within your deadline.', '/oefenen', 'Start practising for free')}

<h2 id="oefenen">How to prepare</h2>

<p>It is different for each part. That is why every part has its own guide on this site: what
exactly you are given, where the time goes, and where most people stumble.</p>

${docentIn('en', 'With my students, the biggest difference between passing and failing is rarely the level. It is the time. They do know the words, but they have never practised with a clock. Take a complete practice exam with a timer at least three times before you take the real one.')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>Four separate exams: Lezen, Luisteren, Schrijven, Spreken (reading, listening, writing, speaking).</li>
  <li>A2: 65, 45, 40 and 35 minutes. B1: 110, 90, 100 and about 30 minutes.</li>
  <li>Schrijven A2 is with pen and paper.</li>
  <li>Your gemeente decides through the leerroute whether you take A2 or B1.</li>
  <li>DUO does not publish the pass mark.</li>
</ul>`,

  faq: [
  {
    q: 'How many questions does the inburgeringsexamen A2 have?',
    a: 'DUO does not publish that on its information pages. But DUO\'s own practice exams are public, and they show the number: 25 questions for Lezen, 25 for Luisteren, 16 for Spreken and 4 assignments for Schrijven. Use that as your guide, but do not call it an official norm.',
  },
  {
    q: 'How many questions do I have to get right to pass?',
    a: 'DUO does not make that public. The Examenreglement says that the line is a cesuur set by the Minister; there is no published percentage and no number of correct answers. Numbers you read elsewhere do not come from DUO.',
  },
  {
    q: 'Do I have to take A2 or B1?',
    a: 'That depends on your leerroute, and your gemeente chooses that after the brede intake and the leerbaarheidstoets. In the B1-route you take the exams at B1, in the onderwijsroute B1 or B2, and in the Z-route you learn A1 and may take A2 exams. If you are doing your inburgering under the 2013 act, it is A2.',
  },
  {
    q: 'Can I go back from B1 to A2?',
    a: 'Only from the B1-route, and under conditions. You must have followed at least 600 hours of language lessons at a language school with a keurmerk, and you must be able to show that you have done your best. The gemeente checks that and decides.',
  },
  {
    q: 'How long does it take before I have my result?',
    a: 'Normally within 8 weeks for the A2 language exams and the kennisexamens. DUO reported on 31 July 2026 that Spreken A2 and Schrijven A2 can currently take up to 16 weeks, with an automatic extension of six months for anyone who runs into trouble because of this. Check the current situation with DUO.',
  },
  {
    q: 'Can I take one part separately?',
    a: 'Yes. The four language parts are separate exams with their own registration, their own date and their own result. If you do not pass one of them, you only redo that part; what you have already passed stays valid.',
  },
  ],
};

export default translation;
