/**
 * vrijstelling-en-ontheffing — English.
 *
 * A translation of the Dutch body in `../vrijstelling-en-ontheffing.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_DIPLOMA, SRC_GEWERKT, SRC_IND, SRC_MINDER, SRC_RIJKS, SRC_WET4, SRC_WET5, SRC_ZIEKTE, row } from '../vrijstelling-en-ontheffing';

const translation: GuideLocale = {
  title: 'Exemption from inburgering: vrijstelling or ontheffing',
  description: 'When do you not have to do inburgering? The difference between vrijstelling and ontheffing, which diplomas exempt you, and how to apply at DUO.',
  breadcrumb: 'Vrijstelling',
  dateLabel: '23 August 2026',
  eyebrow: 'Vrijstelling',
  heroTitle: 'Vrijstelling or ontheffing',
  heroSubtitle: 'Sometimes you do not have to do inburgering (civic integration), or you do not have to take all the exams. But it does not happen by itself: you have to apply for it, and the rules are stricter than many websites suggest.',
  ctaTitle: 'Start practising now',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after every answer. No account needed.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="verschil">Vrijstelling or ontheffing: not the same thing</h2>

<p>Two words that are often used as if they mean the same, but they mean something very different.</p>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>Vrijstelling</h3>
      <p class="compare-when">You already meet the requirement</p>
    </div>
    <div class="compare-rows">
      ${row('Why', 'You already have a diploma, or you are already sufficiently integrated')}
      ${row('Proof', 'A document: a diploma, a certificate, a work history')}
      ${row('Result', 'You do not have to take (certain) exams')}
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>Ontheffing</h3>
      <p class="compare-when">You cannot meet the requirement</p>
    </div>
    <div class="compare-rows">
      ${row('Why', 'A permanent illness or disability, or special circumstances')}
      ${row('Proof', 'A medical examination or a file about your situation')}
      ${row('Result', 'The inburgering obligation ends, but with consequences — see below')}
    </div>
  </div>
</div>

${factTwoIn('en', 'The Wet inburgering 2021 has vrijstelling (article 4), among other things for people who already have a diploma or are otherwise sufficiently integrated, and ontheffing (article 5) for people who, because of a psychological or physical impairment or an intellectual disability, are permanently unable to do inburgering, or because of special individual circumstances.', [['Wet inburgering 2021, artikel 4', SRC_WET4], ['Wet inburgering 2021, artikel 5', SRC_WET5]], CHECKED)}

${note('<strong>DUO decides, not you and not your language school.</strong> Even if you are sure that a rule applies to you: you have to apply for it and you have to wait for the letter. Only stop learning once that letter has arrived.')}

<h2 id="geen-plicht">Who does not have an inburgering obligation at all?</h2>

<p>For some groups the obligation does not start at all. That is not a vrijstelling that you apply
for; you simply fall outside the law.</p>

<div class="yesno-grid">
  <div class="yesno-col no">
    <p class="yesno-title">You do not have to do inburgering</p>
    <ul>
      <li>${I_X}<span>You are younger than 18</span></li>
      <li>${I_X}<span>You are older than the pensioengerechtigde leeftijd (state pension age, AOW-leeftijd)</span></li>
      <li>${I_X}<span>You have the nationality of an EU or EEA country, or of Switzerland</span></li>
      <li>${I_X}<span>You are here temporarily, for study or work</span></li>
      <li>${I_X}<span>You lived in the Netherlands for 8 years or more when you were of compulsory school age (leerplichtig)</span></li>
      <li>${I_X}<span>You have certain Dutch diplomas — see below</span></li>
    </ul>
  </div>
  <div class="yesno-col yes">
    <p class="yesno-title">Please note</p>
    <ul>
      <li>${I_CHECK}<span>Do you reach the AOW-leeftijd during your traject? Then the obligation stops there, but you can also no longer borrow money from DUO.</span></li>
      <li>${I_CHECK}<span>Do you want to naturalise later? Then the gemeente (municipality) or the IND can still ask for an inburgeringsdiploma. Voluntary inburgering is allowed.</span></li>
      <li>${I_CHECK}<span>Turkish nationality has no longer been excluded since 1 January 2022.</span></li>
    </ul>
  </div>
</div>

${factTwoIn('en', 'People who are not inburgeringsplichtig include: people younger than 18, people older than the pensioengerechtigde leeftijd, citizens of the EU, the EEA (Norway, Iceland, Liechtenstein) and Switzerland, people who are in the Netherlands temporarily for study or work, and people who lived in the Netherlands for 8 years or more during the compulsory school age. People who are entitled to AOW no longer have to do inburgering and can also no longer borrow money.', [['Rijksoverheid — Moet ik als nieuwkomer inburgeren?', SRC_RIJKS], ['inburgeren.nl — Minder of geen examens doen', SRC_MINDER]], CHECKED)}

${docentIn('en', 'That eight-year rule is often understood the wrong way round, and that is dangerous. It is: <strong>eight years or more</strong> of Dutch schooling during your leerplicht (compulsory school age) gives a vrijstelling. <strong>Fewer</strong> than eight years does not give that vrijstelling. People who remember it the wrong way round stop learning and run into a problem later.')}

<h2 id="diploma">Which diplomas give a vrijstelling?</h2>

<p>This is the most common vrijstelling, and at the same time the point where most of the incorrect
information on the internet is found. This is the official list from DUO.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">Gives a vrijstelling</p>
    <ul>
      <li>${I_CHECK}<span>A Dutch vmbo, havo or vwo diploma</span></li>
      <li>${I_CHECK}<span>An mbo diploma at <strong>level 2 or higher</strong></span></li>
      <li>${I_CHECK}<span>An hbo or university diploma, <strong>provided it is in Dutch</strong></span></li>
      <li>${I_CHECK}<span>A Dutch-language diploma from Belgium or Suriname</span></li>
      <li>${I_CHECK}<span>A staatsexamen NT2 at level B1 or B2</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">Does not give a full vrijstelling</p>
    <ul>
      <li>${I_X}<span><strong>Praktijkonderwijs</strong> — this is not on any official list, however often you read it online</span></li>
      <li>${I_X}<span><strong>mbo level 1 (entreeopleiding)</strong> — this does release you from the ONA exam, but it does not give a full vrijstelling</span></li>
      <li>${I_X}<span>A foreign diploma that was not obtained in Dutch</span></li>
      <li>${I_X}<span>A course certificate from a language school without a recognised NT2 exam</span></li>
    </ul>
  </div>
</div>

${factIn('en', 'DUO names as diplomas that can give a vrijstelling: vmbo, havo, vwo, mbo level 2 or higher, and hbo or wo provided they were obtained in Dutch, plus Dutch-language diplomas from Belgium and Suriname.', 'inburgeren.nl — Diploma gehaald', SRC_DIPLOMA, CHECKED)}

<h3>Partial vrijstelling</h3>

<p>Sometimes you do not have to take all the exams. Two common situations:</p>

<ul>
  <li><strong>An NT2 certificate or diploma</strong> can give the right to a vrijstelling for certain language parts. Which parts depends on which parts you passed.</li>
  <li><strong>Worked in the Netherlands.</strong> Under the Wet 2013, work in the Netherlands can give the right to a vrijstelling for the ONA exam. And people who have lived in the Netherlands for ten years and worked for at least five of those years can be fully exempted.</li>
</ul>

${factIn('en', 'People who have lived in the Netherlands for ten years and have worked for at least five of those years may not have to take any exams at all. Work in the Netherlands in the past year can also lead to a partial vrijstelling.', 'inburgeren.nl — In Nederland gewerkt', SRC_GEWERKT, CHECKED)}

<h2 id="ontheffing">Ontheffing for illness or disability</h2>

<p>If, because of a psychological or physical impairment or an intellectual disability, you are
<strong>permanently</strong> unable to do inburgering, you can apply for an ontheffing at DUO. The
word <em>permanently</em> is important: a temporary situation does not give an ontheffing, but it
may give extra time.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>You apply at DUO</h3>
    <p>Via Mijn Inburgering or with a form. You pay an amount of €225 in advance for the examination.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>An independent doctor examines you</h3>
    <p>The doctor looks at whether you are permanently unable to pass the exams. Bring all your medical information with you.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>DUO decides</h3>
    <p>If you get the ontheffing, you get the €225 back. If it is refused, you lose that amount — and your deadline simply keeps running.</p>
  </div></div>
</div>

${factIn('en', 'People who, because of a psychological or physical impairment or an intellectual disability, are permanently unable to pass the inburgeringsexamen can apply for an ontheffing at DUO. The medical examination costs €225 in advance; if it is granted, you get that amount back.', 'inburgeren.nl — Ziekte of handicap', SRC_ZIEKTE, CHECKED)}

${note('Do you think your situation is <strong>temporary</strong> — an operation, a pregnancy, a death in the family, homelessness? Then do not apply for an ontheffing but for <strong>extra time</strong>. That is a different procedure, it costs nothing, and it fits better with what you need.')}

<h2 id="bio">Ontheffing for bijzondere individuele omstandigheden (BIO)</h2>

<p>There is also an ontheffing for people who have really tried and can demonstrate that they cannot
pass, without there being a medical reason. That is called an <strong>ontheffing BIO</strong>. You
then have to show that you have made a maximum effort: course hours, exam attempts, attendance.</p>

<p>There is one important disadvantage, and it is rarely mentioned: <strong>with an ontheffing BIO
you cannot naturalise.</strong> For Dutch nationality you need the inburgeringsdiploma. So people
who want to become Dutch are better off continuing to take exams — voluntarily if necessary, after
the obligation has ended.</p>

${factIn('en', 'For naturalisatie and for a permanent residence permit, inburgering is a requirement; the IND describes which proofs count for this. An ontheffing from the inburgering obligation is not automatically enough to naturalise.', 'IND — Inburgering bij een sterkere verblijfsvergunning en naturalisatie', SRC_IND, CHECKED)}

${docentIn('en', 'This is the conversation I find the hardest. Someone is relieved that the obligation is off the table, and only hears years later that the passport is off the table too. If naturalisation is your goal, discuss that before you apply for a BIO ontheffing.')}

<h2 id="hoe-aanvragen">How do you apply?</h2>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>First look in Mijn Inburgering</h3>
    <p>It shows which exams apply to you. Sometimes a vrijstelling has already been processed automatically.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Collect your proof</h3>
    <p>Diplomas, lists of grades, a statement from your employer, or medical documents. Copies of certified documents.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Submit the application to DUO</h3>
    <p>Via Mijn Inburgering or by post with the right form.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Keep learning until the letter has arrived</h3>
    <p>Your deadline simply keeps running while the application is being processed. Stopping on the basis of an expectation is the most expensive thing you can do.</p>
  </div></div>
</div>

${inlineCta('No vrijstelling yet? Then start now', 'A free practice exam of ten questions shows you straight away where you stand. No account needed.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>Vrijstelling = you already meet the requirement. Ontheffing = you cannot meet it.</li>
  <li>DUO decides; keep learning until the letter has arrived.</li>
  <li>Vmbo, havo, vwo, mbo-2 or higher, or Dutch-language hbo/wo give a vrijstelling.</li>
  <li>Praktijkonderwijs and mbo-1 do not give a full vrijstelling.</li>
  <li>A medical ontheffing costs &euro;225 in advance, refunded if it is granted.</li>
  <li>With an ontheffing BIO you cannot naturalise.</li>
</ul>`,

  faq: [
  {
    q: 'What is the difference between vrijstelling and ontheffing?',
    a: 'With a vrijstelling you already meet the requirement, for example because you have a Dutch diploma or have worked here for a long time. With an ontheffing you cannot meet the requirement, for example because of a permanent illness or disability. They have a different basis, a different procedure and different consequences.',
  },
  {
    q: 'Which diplomas give a vrijstelling from inburgering?',
    a: 'A Dutch vmbo, havo or vwo diploma, an mbo diploma at level 2 or higher, and an hbo or university diploma obtained in Dutch. Dutch-language diplomas from Belgium and Suriname also count. Praktijkonderwijs and mbo level 1 do not give a full vrijstelling, even though you often read that online.',
  },
  {
    q: 'Do I not have to do inburgering when I reach the AOW-leeftijd?',
    a: 'That is correct. People who are entitled to AOW no longer have to do inburgering; you have to do inburgering until your AOW-leeftijd and not after that. Please note: you can then also no longer borrow money from DUO. If you want to naturalise later, the gemeente (municipality) or the IND can still ask for an inburgeringsdiploma — voluntary inburgering is allowed.',
  },
  {
    q: 'What does it cost to apply for a medical ontheffing?',
    a: 'You pay €225 in advance for the independent medical examination. If the ontheffing is granted, you get that amount back. If the application is refused, you lose it and your inburgering deadline simply keeps running in the meantime.',
  },
  {
    q: 'Can I naturalise with an ontheffing?',
    a: 'Not with an ontheffing for bijzondere individuele omstandigheden (BIO): for naturalisatie an inburgeringsdiploma is required. If becoming Dutch is your goal, discuss that before you apply for such an ontheffing — continuing with the exams voluntarily is then often the better route.',
  },
  {
    q: 'May I stop my course if I have applied for a vrijstelling?',
    a: 'No, not before DUO has decided. Your inburgering deadline simply keeps running while the application is being processed. If your application is refused, you have lost months that you cannot make up. Keep learning until the letter from DUO has arrived.',
  },
  ],
};

export default translation;
