/**
 * werk-en-inkomen — English.
 *
 * A translation of the Dutch body in `../werk-en-inkomen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_DISCRIMINATIE, SRC_EINDTERMEN, SRC_KVK, SRC_MENSENRECHTEN, SRC_MINIMUMLOON, SRC_WERKNEMER, row } from '../werk-en-inkomen';

const translation: GuideLocale = {
  title: 'KNM theme Work and income: finding work and working in NL',
  description: 'Finding work, understanding your contract and payslip, dealing with discrimination at work and starting your own business. The KNM theme Work and income.',
  breadcrumb: 'Work and income',
  dateLabel: '23 August 2026',
  eyebrow: 'KNM theme 1',
  heroTitle: 'Work and income',
  heroSubtitle: 'How do you find work in the Netherlands, what is in a contract, and what do you do if you are treated unfairly? This theme is about working and about the money you earn with it.',
  ctaTitle: 'Practise the theme Work and income',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after each answer. Without an account.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="wat-vraagt-knm">What does KNM ask about this theme?</h2>

<p>In the official eindtermen (final attainment levels) this theme has four parts. They are listed
below in the same order as in the law, and the rest of this guide follows that order too.</p>

<div class="compare-rows">
  ${row('1.1', 'Looking for (new) work quickly and efficiently')}
  ${row('1.2', 'Taking an active part in a work organisation')}
  ${row('1.3', 'Dealing with (hidden) discrimination in the labour market and at work')}
  ${row('1.4', 'Making preparations to start your own business')}
</div>

${factIn('en', 'The KNM eindtermen for the theme Work and income are: looking for (new) work quickly and efficiently; taking an active part in a work organisation; dealing with (hidden) discrimination in the labour market and at work; making preparations to start your own business.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

<h2 id="werk-zoeken">Looking for work in the Netherlands</h2>

<p>In the Netherlands you usually look for work yourself. There is no organisation that gives you a
job. You look on vacancy websites, through uitzendbureaus (temping agencies), through the gemeente
(municipality), and — very important — through people you know.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Your cv</h3>
    <p>One or two pages. Your education, your work experience with years, your languages and your skills. In the Netherlands you usually put <strong>no photo, no age and no marital status</strong> on your cv. That is not impolite, that is normal.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Your application letter</h3>
    <p>Short, and different for every vacancy. You write why you fit that job, not your whole life story.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>The interview</h3>
    <p>You arrive on time — in the Netherlands that means five minutes early. You shake hands, you look people in the eye, and you may ask questions yourself too. That is appreciated.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Your network</h3>
    <p>Many jobs are found through people. Tell people at your language class, at the sports club or at your volunteer work that you are looking for work. That is not begging, that is how it works here.</p>
  </div></div>
</div>

${docentIn('en', 'My students are often shocked by the idea of "selling" yourself in an application letter. In many countries that is boasting. Here it is simply giving information. Write down what you can do, in plain sentences. That is enough.')}

<p>Have you lost your job? Then you report to <strong>UWV</strong>. That is the organisation that
deals with unemployment benefits (WW) and with incapacity for work. If you have no right to WW and
no other income either, you can apply for bijstand (social assistance) at your <strong>gemeente</strong>.</p>

<h2 id="op-het-werk">Working: contract, payslip and your rights</h2>

<p>When you have work, you get an <strong>arbeidsovereenkomst</strong> (employment contract). That is
a contract, usually on paper. Never sign anything you do not understand — ask for an explanation or
for a day to think about it.</p>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>Temporary contract</h3>
      <p class="compare-when">Bepaalde tijd (fixed term)</p>
    </div>
    <div class="compare-rows">
      ${row('Duration', 'There is an end date in it')}
      ${row('Ends', 'By itself on that date')}
      ${row('Note', 'After a number of temporary contracts you have the right to a permanent contract')}
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>Permanent contract</h3>
      <p class="compare-when">Onbepaalde tijd (indefinite term)</p>
    </div>
    <div class="compare-rows">
      ${row('Duration', 'No end date')}
      ${row('Ends', 'Only with your agreement, through UWV or through the court')}
      ${row('Note', 'Your employer may not simply dismiss you')}
    </div>
  </div>
</div>

<p>Every month you get a <strong>loonstrook</strong> (payslip, also called salarisstrook). It shows
three things you must be able to read:</p>

<ul>
  <li><strong>Brutoloon</strong> (gross pay) — your pay before the deductions.</li>
  <li><strong>Inhoudingen</strong> (deductions) — wage tax and contributions. These go to the Belastingdienst (tax office) and help pay for healthcare, AOW and benefits.</li>
  <li><strong>Nettoloon</strong> (net pay) — what comes into your account. This is always lower than the gross pay, and that is how it should be.</li>
</ul>

<p>Everyone aged 21 and older has the right to at least the <strong>wettelijk minimumloon</strong>
(statutory minimum wage). Younger employees have a minimumjeugdloon (youth minimum wage). The amounts
change twice a year; check them on the website of the Rijksoverheid.</p>

<p>You also have the right to <strong>vakantiedagen</strong> (holiday days) and to
<strong>vakantiegeld</strong> (holiday pay, usually in May). In many sectors there is a
<strong>cao</strong>: agreements between employers and trade unions that come above your own
contract. If you work in such a sector, those agreements apply to you too, also if they are not in
your contract.</p>

${factTwoIn('en', 'Everyone aged 21 and older who works in the Netherlands has the right to at least the statutory minimum wage; for younger employees the minimumjeugdloon applies. Agreements in a cao apply to all employees in that sector.', [['Rijksoverheid — Minimumloon', SRC_MINIMUMLOON], ['Rijksoverheid — Arbeidsovereenkomst en cao', SRC_WERKNEMER]], CHECKED)}

${note('Do you become ill? Then you report sick to your employer, following the rules he has given you. Your employer continues to pay a large part of your wage. If you work through an uitzendbureau (temping agency), you report sick there — not at the company where you are working.')}

<h2 id="discriminatie">Discrimination at work</h2>

<p>This is a separate eindterm, and for a reason. In the Netherlands discrimination is
<strong>forbidden</strong>. An employer may not reject you or treat you differently because of your
origin, your skin colour, your religion, your sex, your age, a disability or because you are
pregnant.</p>

<div class="yesno-grid">
  <div class="yesno-col no">
    <p class="yesno-title">This is not allowed</p>
    <ul>
      <li>${I_X}<span>"We are looking for someone without an accent" in a vacancy</span></li>
      <li>${I_X}<span>Less pay for the same work because of your origin or your sex</span></li>
      <li>${I_X}<span>Jokes or remarks about your religion or your skin colour</span></li>
      <li>${I_X}<span>Not being hired because you wear a headscarf</span></li>
    </ul>
  </div>
  <div class="yesno-col yes">
    <p class="yesno-title">This is what you can do</p>
    <ul>
      <li>${I_CHECK}<span>Write down what happened, when, and who was there</span></li>
      <li>${I_CHECK}<span>Talk to your manager or to the vertrouwenspersoon (confidential adviser) of the company</span></li>
      <li>${I_CHECK}<span>Report it to an antidiscriminatiebureau (anti-discrimination office) — that is free</span></li>
      <li>${I_CHECK}<span>Put the case to the College voor de Rechten van de Mens</span></li>
    </ul>
  </div>
</div>

<p><strong>Hidden</strong> discrimination is harder: you are not invited, and you never hear why.
That is why the eindtermen mention it separately. You do not have to prove it in order to ask for
help with it. Every gemeente must have an antidiscriminatievoorziening (anti-discrimination service)
where you can go for free.</p>

${factTwoIn('en', 'Discrimination is forbidden in the Netherlands. Every gemeente must give residents access to an antidiscriminatievoorziening; in addition, anyone can ask the College voor de Rechten van de Mens for a ruling.', [['Rijksoverheid — Discriminatie', SRC_DISCRIMINATIE], ['College voor de Rechten van de Mens', SRC_MENSENRECHTEN]], CHECKED)}

${docentIn('en', 'This subject almost always comes back in the exam as a situation: someone hears a remark at work, what does he do? The right answer is rarely "do nothing" and rarely "resign immediately". It is almost always: name it, and look for help from someone whose job that is.')}

<h2 id="eigen-bedrijf">Starting your own business</h2>

<p>Do you want to work for yourself? That is allowed, and many people doing inburgering (civic
integration) do it. The main line is short.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Am I allowed to work?</h3>
    <p>First look at your verblijfsvergunning (residence permit) and what it says on the back about work. Not every permit gives the same rights for running a business.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Registering with the KVK</h3>
    <p>You register your business with the Kamer van Koophandel. You get a KVK number and the Belastingdienst gives you a btw number (VAT number).</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Administration and btw</h3>
    <p>You keep your invoices, you usually file a btw return every quarter, and once a year you file an income tax return.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Insuring yourself</h3>
    <p>As an entrepreneur you get no wage paid during illness and you build up no employee pension. You arrange that yourself, or you consciously accept the risk.</p>
  </div></div>
</div>

${factIn('en', 'Anyone starting a business in the Netherlands registers it with the Kamer van Koophandel; the Belastingdienst then issues a btw number. The KVK describes the steps from registration to administration.', 'KVK — Een bedrijf starten', SRC_KVK, CHECKED)}

${note('Be careful with "schijnzelfstandigheid" (false self-employment): if in practice you are simply an employee but you have to register yourself as a zzp’er (self-employed person), you miss protection you are entitled to. Ask about this at a trade union or at the Juridisch Loket before you sign.')}

<h2 id="oefenen">What to remember from this</h2>

<p>The exam does not ask for amounts. It asks whether you know <em>where you have to go</em>: UWV for
WW, the gemeente for bijstand, the Belastingdienst for tax and toeslagen (allowances), the KVK for
your business, and an antidiscriminatiebureau if you are treated unfairly.</p>

${inlineCta('Practise this theme with exam questions', 'Situations like in the real KNM exam, with an explanation after each answer.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>You look for work yourself: cv, letter, interview, network.</li>
  <li>Read your contract and your loonstrook: gross, deductions, net.</li>
  <li>Minimum wage from age 21; a cao comes above your contract.</li>
  <li>Discrimination is forbidden — report it, free of charge, to an antidiscriminatiebureau.</li>
  <li>Own business: register with the KVK, file btw returns, insure yourself.</li>
</ul>`,

  faq: [
  {
    q: 'What is the difference between brutoloon and nettoloon?',
    a: 'Brutoloon (gross pay) is your pay before anything is taken off. Wage tax and contributions are taken off that. What is left is your nettoloon (net pay), and that is the amount that comes into your bank account. Both amounts are on your loonstrook every month.',
  },
  {
    q: 'What should I do if I am discriminated against at work?',
    a: 'First write down what exactly happened, when and who was there. Then discuss it with your manager or with the vertrouwenspersoon (confidential adviser) of the company. If that does not help, you can report it free of charge to the antidiscriminatiebureau of your gemeente, or ask the College voor de Rechten van de Mens for a ruling.',
  },
  {
    q: 'Where do I report if I become unemployed?',
    a: 'At UWV. They assess whether you have the right to a WW benefit. If you do not have that right and you have no other income either, you apply for bijstand (social assistance) at your own gemeente. Report quickly, because the date of your report counts.',
  },
  {
    q: 'May I start my own business in the Netherlands as someone doing inburgering?',
    a: 'Usually yes, but it depends on your verblijfsvergunning (residence permit). First look at what it says on the back of your permit about work. If it is allowed, you register your business with the Kamer van Koophandel and the Belastingdienst gives you a btw number.',
  },
  {
    q: 'What is a cao?',
    a: 'A collectieve arbeidsovereenkomst (collective labour agreement): agreements between employers and trade unions about pay, working hours and holidays in a whole sector. If you work in a sector with a cao, those agreements apply to you too, also if they are not literally in your own contract.',
  },
  ],
};

export default translation;
