/**
 * werk-en-inkomen — Arabic.
 *
 * A translation of the Dutch body in `../werk-en-inkomen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_DISCRIMINATIE, SRC_EINDTERMEN, SRC_KVK, SRC_MENSENRECHTEN, SRC_MINIMUMLOON, SRC_WERKNEMER, row } from '../werk-en-inkomen';

const translation: GuideLocale = {
  title: 'موضوع KNM العمل والدخل: البحث عن عمل والعمل في هولندا',
  description: 'البحث عن عمل، وفهم عقدك وكشف راتبك، والتعامل مع التمييز في العمل، وبدء شركة خاصة بك. شرح موضوع KNM العمل والدخل خطوة بخطوة للمقبلين على الامتحان.',
  breadcrumb: 'العمل والدخل',
  dateLabel: '23 أغسطس 2026',
  eyebrow: 'موضوع KNM رقم 1',
  heroTitle: 'العمل والدخل',
  heroSubtitle: 'كيف تجد عملاً في هولندا، وما الذي يرد في العقد، وماذا تفعل إذا عوملت معاملة غير عادلة؟ يتناول هذا الموضوع العمل والمال الذي تكسبه منه.',
  ctaTitle: 'تدرّب على موضوع العمل والدخل',
  ctaDesc: 'امتحان تجريبي مجاني من عشرة أسئلة، مع شرح بعد كل إجابة. من دون حساب.',
  ctaLabel: 'ابدأ امتحاناً تجريبياً مجانياً',

  articleHtml: `
<h2 id="wat-vraagt-knm">ماذا يطلب KNM في هذا الموضوع؟</h2>

<p>في الأهداف النهائية الرسمية (eindtermen) يتكوّن هذا الموضوع من أربعة أجزاء. وهي مذكورة أدناه بالترتيب
نفسه الوارد في القانون، وبقية هذا الدليل تتبع الترتيب نفسه أيضاً.</p>

<div class="compare-rows">
  ${row('1.1', 'البحث عن عمل (جديد) بسرعة وكفاءة')}
  ${row('1.2', 'المشاركة الفعّالة في منظمة عمل')}
  ${row('1.3', 'التعامل مع التمييز (الخفي) في سوق العمل وفي مكان العمل')}
  ${row('1.4', 'اتخاذ التحضيرات لبدء شركة خاصة')}
</div>

${factIn('ar', 'الأهداف النهائية لـ KNM في موضوع العمل والدخل هي: البحث عن عمل (جديد) بسرعة وكفاءة؛ المشاركة الفعّالة في منظمة عمل؛ التعامل مع التمييز (الخفي) في سوق العمل وفي مكان العمل؛ اتخاذ التحضيرات لبدء شركة خاصة.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

<h2 id="werk-zoeken">البحث عن عمل في هولندا</h2>

<p>في هولندا تبحث عن العمل بنفسك في العادة. لا توجد جهة تمنحك وظيفة. أنت تبحث في مواقع الوظائف الشاغرة،
وعبر مكاتب التوظيف المؤقت (uitzendbureaus)، وعبر البلدية (gemeente)، والأهم من ذلك: عبر أشخاص
تعرفهم.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>سيرتك الذاتية (cv)</h3>
    <p>صفحة أو صفحتان. تعليمك، وخبرتك المهنية مع السنوات، ولغاتك ومهاراتك. في هولندا لا تضع عادةً <strong>صورة ولا عمراً ولا حالة اجتماعية</strong> في سيرتك الذاتية. هذا ليس قلة أدب، بل هو الأمر الطبيعي.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>رسالة التقديم (sollicitatiebrief)</h3>
    <p>قصيرة، ومختلفة في كل مرة بحسب الوظيفة الشاغرة. تكتب لماذا تناسب أنت تلك الوظيفة، لا قصة حياتك كلها.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>المقابلة</h3>
    <p>تحضر في الوقت المحدد — وفي هولندا يعني ذلك قبل خمس دقائق. تصافح باليد، وتنظر إلى الناس، ويمكنك أنت أيضاً أن تطرح أسئلة. وهذا أمر يُقدَّر.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>شبكة معارفك</h3>
    <p>كثير من الوظائف يُعثر عليها عن طريق الأشخاص. أخبر في درس اللغة، أو في النادي الرياضي، أو في العمل التطوعي أنك تبحث عن عمل. هذا ليس تسوّلاً، بل هكذا تسير الأمور هنا.</p>
  </div></div>
</div>

${docentIn('ar', 'كثيراً ما يفزع طلابي من فكرة "بيع" النفس في رسالة التقديم. في بلدان كثيرة يُعدّ ذلك تفاخراً. هنا هو مجرد إعطاء معلومات. اكتب ما تستطيع فعله، بجمل عادية. هذا يكفي.')}

<p>هل فقدت وظيفتك؟ إذاً تسجّل نفسك لدى <strong>UWV</strong>. وهي الجهة المسؤولة عن إعانات البطالة
(WW) وعن العجز عن العمل. وإذا لم يكن لك حق في WW ولا دخل آخر، يمكنك تقديم طلب المساعدة الاجتماعية
(bijstand) لدى <strong>البلدية (gemeente)</strong>.</p>

<h2 id="op-het-werk">العمل: العقد وكشف الراتب وحقوقك</h2>

<p>عندما يكون لديك عمل، تحصل على <strong>عقد عمل (arbeidsovereenkomst)</strong>. وهو عقد، على الورق
في الغالب. لا توقّع أبداً شيئاً لا تفهمه — اطلب شرحاً أو يوماً للتفكير.</p>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>عقد مؤقت</h3>
      <p class="compare-when">مدة محددة (bepaalde tijd)</p>
    </div>
    <div class="compare-rows">
      ${row('المدة', 'فيه تاريخ انتهاء')}
      ${row('ينتهي', 'من تلقاء نفسه في ذلك التاريخ')}
      ${row('انتبه', 'بعد عدد من العقود المؤقتة يصبح لك الحق في عقد دائم')}
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>عقد دائم</h3>
      <p class="compare-when">مدة غير محددة (onbepaalde tijd)</p>
    </div>
    <div class="compare-rows">
      ${row('المدة', 'لا يوجد تاريخ انتهاء')}
      ${row('ينتهي', 'فقط بموافقتك، أو عن طريق UWV أو عن طريق القاضي')}
      ${row('انتبه', 'لا يجوز لصاحب العمل أن يفصلك هكذا ببساطة')}
    </div>
  </div>
</div>

<p>كل شهر تحصل على <strong>كشف راتب (loonstrook)</strong> (ويُسمّى أيضاً salarisstrook). وفيه ثلاثة
أمور يجب أن تعرف قراءتها:</p>

<ul>
  <li><strong>الراتب الإجمالي (brutoloon)</strong> — راتبك قبل الاقتطاعات.</li>
  <li><strong>الاقتطاعات (inhoudingen)</strong> — ضريبة الدخل على الأجر والاشتراكات. وهي تذهب إلى Belastingdienst (مصلحة الضرائب) وتساهم في تمويل الرعاية الصحية و AOW والإعانات.</li>
  <li><strong>الراتب الصافي (nettoloon)</strong> — ما يصل إلى حسابك. وهو دائماً أقل من الراتب الإجمالي، وهذا أمر طبيعي.</li>
</ul>

<p>لكل شخص عمره 21 سنة فأكثر الحق في <strong>الحد الأدنى القانوني للأجر (wettelijk minimumloon)</strong> على الأقل.
أما العاملون الأصغر سناً فلهم حد أدنى للأجر للأحداث (minimumjeugdloon). المبالغ تتغير مرتين في السنة؛ تحقق
منها على موقع Rijksoverheid.</p>

<p>كذلك لك الحق في <strong>أيام إجازة (vakantiedagen)</strong> وفي <strong>بدل الإجازة (vakantiegeld)</strong>
(في شهر مايو عادةً). وفي كثير من القطاعات يسري <strong>cao</strong>: اتفاقات بين أصحاب العمل والنقابات
تعلو على عقدك الخاص. فإذا كنت تعمل في قطاع كهذا، فإن تلك الاتفاقات تسري عليك أيضاً، حتى لو لم ترد في
عقدك.</p>

${factTwoIn('ar', 'لكل شخص عمره 21 سنة فأكثر يعمل في هولندا الحق في الحد الأدنى القانوني للأجر على الأقل؛ أما العاملون الأصغر سناً فيسري عليهم الحد الأدنى للأجر للأحداث. والاتفاقات الواردة في cao تسري على جميع العاملين في ذلك القطاع.', [['Rijksoverheid — Minimumloon', SRC_MINIMUMLOON], ['Rijksoverheid — Arbeidsovereenkomst en cao', SRC_WERKNEMER]], CHECKED)}

${note('هل مرضت؟ إذاً تبلّغ عن مرضك لدى صاحب العمل، وفق القواعد التي تسلّمتها منه. ويستمر صاحب العمل في دفع جزء كبير من راتبك. وإذا كنت تعمل عبر مكتب توظيف مؤقت (uitzendbureau)، فتبلّغ عن مرضك هناك — لا في الشركة التي تعمل فيها فعلياً.')}

<h2 id="discriminatie">التمييز في العمل</h2>

<p>هذا هدف نهائي مستقل، وليس ذلك من دون سبب. في هولندا التمييز <strong>محظور</strong>. لا يجوز لصاحب
العمل أن يرفضك أو يعاملك معاملة مختلفة بسبب أصلك، أو لون بشرتك، أو دينك، أو جنسك، أو عمرك، أو إعاقة،
أو لأنك حامل.</p>

<div class="yesno-grid">
  <div class="yesno-col no">
    <p class="yesno-title">هذا غير مسموح</p>
    <ul>
      <li>${I_X}<span>"نبحث عن شخص بلا لكنة" في إعلان وظيفة</span></li>
      <li>${I_X}<span>أجر أقل مقابل العمل نفسه بسبب أصلك أو جنسك</span></li>
      <li>${I_X}<span>نكات أو تعليقات عن دينك أو لون بشرتك</span></li>
      <li>${I_X}<span>عدم قبولك لأنك ترتدين غطاء رأس</span></li>
    </ul>
  </div>
  <div class="yesno-col yes">
    <p class="yesno-title">هذا ما يمكنك فعله</p>
    <ul>
      <li>${I_CHECK}<span>اكتب ما حدث، ومتى، ومن كان حاضراً</span></li>
      <li>${I_CHECK}<span>تحدّث مع رئيسك في العمل أو مع شخص الثقة (vertrouwenspersoon) في الشركة</span></li>
      <li>${I_CHECK}<span>أبلغ مكتب مكافحة التمييز (antidiscriminatiebureau) — وهذا مجاني</span></li>
      <li>${I_CHECK}<span>اعرض القضية على College voor de Rechten van de Mens (معهد حقوق الإنسان)</span></li>
    </ul>
  </div>
</div>

<p>التمييز <strong>الخفي</strong> أصعب: لا تُدعى إلى المقابلة، ولا تعرف أبداً لماذا. ولهذا تذكره الأهداف
النهائية بشكل منفصل. ولست مضطراً إلى إثباته لكي تطلب المساعدة بشأنه. كل بلدية (gemeente) ملزمة بأن يكون
لديها جهة لمكافحة التمييز (antidiscriminatievoorziening) يمكنك اللجوء إليها مجاناً.</p>

${factTwoIn('ar', 'التمييز محظور في هولندا. وعلى كل بلدية أن تتيح لسكانها الوصول إلى جهة لمكافحة التمييز؛ وإضافة إلى ذلك يمكن لأي شخص أن يطلب حكماً من College voor de Rechten van de Mens.', [['Rijksoverheid — Discriminatie', SRC_DISCRIMINATIE], ['College voor de Rechten van de Mens', SRC_MENSENRECHTEN]], CHECKED)}

${docentIn('ar', 'يعود هذا الموضوع في الامتحان دائماً تقريباً على شكل موقف: شخص يسمع تعليقاً في مكان العمل، فماذا يفعل؟ الجواب الصحيح نادراً ما يكون "لا يفعل شيئاً" ونادراً ما يكون "يستقيل فوراً". بل هو دائماً تقريباً: أن يسمّي الأمر باسمه، وأن يطلب المساعدة من جهة مختصة بذلك.')}

<h2 id="eigen-bedrijf">بدء شركة خاصة</h2>

<p>هل تريد أن تعمل لحسابك الخاص؟ هذا مسموح، وكثير من المشاركين في الاندماج يفعلون ذلك. والخطوط العريضة قصيرة.</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>هل يُسمح لي بالعمل؟</h3>
    <p>انظر أولاً في تصريح إقامتك (verblijfsvergunning) إلى ما هو مكتوب على ظهره بشأن العمل. فليس كل تصريح يمنح الحقوق نفسها لممارسة العمل الحر.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>التسجيل لدى KVK</h3>
    <p>تسجّل شركتك لدى Kamer van Koophandel (غرفة التجارة). وتحصل على رقم KVK، وتمنحك Belastingdienst رقم ضريبة القيمة المضافة (btw-nummer).</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>المحاسبة وضريبة القيمة المضافة</h3>
    <p>تحتفظ بفواتيرك، وتقدّم إقرار ضريبة القيمة المضافة (btw-aangifte) كل ربع سنة في العادة، وتقدّم مرة واحدة في السنة إقرار ضريبة الدخل (inkomstenbelasting).</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>التأمين على نفسك</h3>
    <p>بصفتك صاحب عمل حر لا يستمر دفع راتبك عند المرض ولا تبني معاشاً تقاعدياً للعاملين. عليك ترتيب ذلك بنفسك، أو أن تقبل المخاطرة عن وعي.</p>
  </div></div>
</div>

${factIn('ar', 'من يبدأ شركة في هولندا يسجّلها لدى Kamer van Koophandel؛ وبعد ذلك تمنحه Belastingdienst رقم ضريبة القيمة المضافة. وتصف KVK الخطوات من التسجيل حتى المحاسبة.', 'KVK — Een bedrijf starten', SRC_KVK, CHECKED)}

${note('انتبه من "schijnzelfstandigheid" (العمل الحر الصوري): إذا كنت عملياً موظفاً عادياً لكن عليك أن تسجّل نفسك كـ zzp’er (عامل مستقل)، فأنت تفقد حماية لك الحق فيها. استفسر عن ذلك لدى نقابة أو لدى Juridisch Loket (المكتب القانوني) قبل أن توقّع.')}

<h2 id="oefenen">ما الذي يجب أن تتذكره من هذا</h2>

<p>الامتحان لا يسأل عن مبالغ. بل يسأل هل تعرف <em>إلى أين يجب أن تذهب</em>: UWV من أجل WW، والبلدية
(gemeente) من أجل المساعدة الاجتماعية، و Belastingdienst من أجل الضرائب والإعانات (toeslagen)، و KVK من أجل
شركتك، ومكتب مكافحة التمييز إذا عوملت معاملة غير عادلة.</p>

${inlineCta('تدرّب على هذا الموضوع بأسئلة امتحانية', 'مواقف كما في امتحان KNM الحقيقي، مع شرح بعد كل إجابة.', '/oefenen', 'ابدأ امتحاناً تجريبياً مجانياً')}
`,

  sidebarHtml: `
<p><strong>باختصار</strong></p>
<ul>
  <li>تبحث عن العمل بنفسك: السيرة الذاتية، الرسالة، المقابلة، شبكة المعارف.</li>
  <li>اقرأ عقدك وكشف راتبك: الإجمالي، الاقتطاعات، الصافي.</li>
  <li>الحد الأدنى للأجر من عمر 21 سنة؛ و cao يعلو على عقدك.</li>
  <li>التمييز محظور — أبلغ عنه مجاناً لدى مكتب مكافحة التمييز.</li>
  <li>شركة خاصة: التسجيل لدى KVK، إقرار ضريبة القيمة المضافة، التأمين على نفسك.</li>
</ul>`,

  faq: [
  {
    q: 'ما الفرق بين الراتب الإجمالي (brutoloon) والراتب الصافي (nettoloon)؟',
    a: 'الراتب الإجمالي هو راتبك قبل أن يُقتطع منه شيء. تُقتطع منه ضريبة الدخل على الأجر والاشتراكات. وما يتبقى هو راتبك الصافي، وهو المبلغ الذي يصل إلى حسابك البنكي. والمبلغان يظهران كل شهر في كشف راتبك (loonstrook).',
  },
  {
    q: 'ماذا أفعل إذا تعرّضت للتمييز في عملي؟',
    a: 'اكتب أولاً ما حدث بالضبط، ومتى، ومن كان حاضراً. ثم ناقش الأمر مع رئيسك في العمل أو مع شخص الثقة (vertrouwenspersoon) في الشركة. وإذا لم يفد ذلك، يمكنك الإبلاغ مجاناً لدى مكتب مكافحة التمييز (antidiscriminatiebureau) في بلديتك أو طلب حكم من College voor de Rechten van de Mens.',
  },
  {
    q: 'إلى أين أتوجّه إذا أصبحت عاطلاً عن العمل؟',
    a: 'إلى UWV. فهي التي تقيّم ما إذا كان لك الحق في إعانة البطالة WW. وإذا لم يكن لك حق فيها ولم يكن لديك دخل آخر، فتقدّم طلب المساعدة الاجتماعية (bijstand) لدى بلديتك. سجّل نفسك بسرعة، لأن تاريخ الإبلاغ يُحتسب.',
  },
  {
    q: 'هل يُسمح لي ببدء شركة خاصة في هولندا بصفتي مشاركاً في الاندماج؟',
    a: 'في الغالب نعم، لكن ذلك يتوقف على تصريح إقامتك. انظر أولاً إلى ما هو مكتوب على ظهر تصريحك بشأن العمل. فإذا كان مسموحاً، تسجّل شركتك لدى Kamer van Koophandel وتحصل من Belastingdienst على رقم ضريبة القيمة المضافة (btw-nummer).',
  },
  {
    q: 'ما هو cao؟',
    a: 'هو اتفاقية عمل جماعية: اتفاقات بين أصحاب العمل والنقابات بشأن الأجر وساعات العمل والإجازة في قطاع بأكمله. فإذا كنت تعمل في قطاع فيه cao، فإن تلك الاتفاقات تسري عليك أيضاً، حتى لو لم ترد حرفياً في عقدك الخاص.',
  },
  ],
};

export default translation;
