/**
 * wonen — English.
 *
 * A translation of the Dutch body in `../wonen.ts`, which the NT2 docent reviewed. This
 * rendering is machine-produced and has not itself been reviewed; see the header of
 * `./index.ts` for what that means and where the page says so.
 *
 * Generated by `scripts/translate-guides.mjs`. To change the wording, edit here — the script
 * caches on a hash of the Dutch source, so it will not overwrite this unless the Dutch changes
 * or you pass `--force`. The `<h2 id>` values and the sequence of ${...} expressions are
 * load-bearing and identical to the Dutch on purpose; the script refuses a body where they are not.
 */
import type { GuideLocale } from '../types';
import { I_CHECK, I_EURO, I_HOME, I_X, docentIn, factIn, factTwoIn, inlineCta, note } from '../kit';
import { CHECKED, SRC_AFVAL, SRC_BRP, SRC_EINDTERMEN, SRC_HUURCOMMISSIE, SRC_HUURTOESLAG, SRC_HUURWONING, card, row } from '../wonen';

const translation: GuideLocale = {
  title: 'KNM theme Housing: renting, buying and sorting your home',
  description: 'Finding a home, renting or buying, connecting gas water and electricity, and sorting waste. The KNM theme Wonen explained in plain, simple English.',
  breadcrumb: 'Housing',
  dateLabel: '23 August 2026',
  eyebrow: 'KNM theme 3',
  heroTitle: 'Housing',
  heroSubtitle: 'Finding a home in the Netherlands is difficult, and there is a lot involved: registering, a rental contract, energy, insurance, waste. This theme sets it all out.',
  ctaTitle: 'Practise the theme Wonen',
  ctaDesc: 'Free practice exam of ten questions, with an explanation after every answer. No account needed.',
  ctaLabel: 'Start a free practice exam',

  articleHtml: `
<h2 id="wat-vraagt-knm">What does KNM ask about this theme?</h2>

<p>Three eindtermen (final attainment levels), and they follow exactly the path you take yourself: first a home, then the services inside it, then the life around it.</p>

<div class="compare-rows">
  ${row('3.1', 'Arranging suitable housing')}
  ${row('3.2', 'Arranging utilities and means of communication')}
  ${row('3.3', 'Contributing to a clean living environment')}
</div>

${factIn('en', 'The eindtermen for KNM in the theme Wonen are: arranging suitable housing; arranging utilities and means of communication; contributing to a clean living environment.', 'Staatscourant 2024, 15802 — Regeling inburgering 2021', SRC_EINDTERMEN, CHECKED)}

<h2 id="huren-of-kopen">Renting or buying</h2>

<p>Most people who have just arrived in the Netherlands rent. There are two kinds of rental homes, and the difference matters.</p>

<div class="compare-2">
  <div class="compare-card is-primary">
    <div class="compare-head">
      <h3>Sociale huurwoning (social housing)</h3>
      <p class="compare-when">From a woningcorporatie (housing association)</p>
    </div>
    <div class="compare-rows">
      ${row('Rent', 'Lower, with a legal maximum')}
      ${row('For whom', 'People with an income below a limit')}
      ${row('How', 'You register and wait. In many cities that means years.')}
      ${row('Allowance', 'Often entitled to huurtoeslag (rent benefit)')}
    </div>
  </div>
  <div class="compare-card">
    <div class="compare-head">
      <h3>Vrije sector (private sector)</h3>
      <p class="compare-when">From a private owner or an investor</p>
    </div>
    <div class="compare-rows">
      ${row('Rent', 'Higher, and the landlord decides more')}
      ${row('For whom', 'Usually an income requirement of 3 to 4 times the rent')}
      ${row('How', 'Through estate agents and rental websites, available faster')}
      ${row('Allowance', 'No huurtoeslag')}
    </div>
  </div>
</div>

<p>Are you a statushouder (refugee with a residence permit)? Then your <strong>gemeente (municipality)</strong> usually assigns you a home. This is called huisvesting van vergunninghouders. You then do not have to register and wait for years yourself, but you also cannot choose where you live.</p>

${note('Be careful with subletting and with "sleutelgeld" (key money). A landlord may not ask for money simply for handing over the key, and subletting without permission can mean you end up on the street from one day to the next. Always ask for a written rental contract in your own name.')}

<h2 id="inschrijven">Registering with the gemeente</h2>

<p>As soon as you have a home address, you register with the gemeente. You are then entered in the <strong>Basisregistratie Personen</strong> (BRP). This is not a formality: without registration your BSN is not linked to an address, and then almost nothing works — no health insurance, no allowance, no bank account, no school.</p>

<p>Do you move later on? Then you report this to the gemeente, no later than five days after your move. From there your new address goes automatically to many other organisations, but not to all of them: you have to inform your energy supplier, your insurer and your employer yourself.</p>

${factIn('en', 'The Basisregistratie Personen (BRP) contains the personal data of everyone living in the Netherlands. Government organisations use this data; anyone who moves reports this to the gemeente.', 'Rijksoverheid — Basisregistratie Personen', SRC_BRP, CHECKED)}

<h2 id="huurcontract">Your rental contract and your rights</h2>

<p>Your huurcontract (rental contract) is an agreement. Read it before you sign, and pay attention to these points.</p>

<ul>
  <li><strong>Kale huur (basic rent) and servicekosten (service costs).</strong> The kale huur is for the home itself; servicekosten are for things like cleaning or the lift. Together they are your monthly costs.</li>
  <li><strong>Waarborgsom (deposit).</strong> Usually one or two months of rent. You get it back if you leave the home in good order.</li>
  <li><strong>Notice period.</strong> Usually one month for you. Stricter rules apply to the landlord.</li>
  <li><strong>Maintenance.</strong> Major maintenance is for the landlord. Small things — a light bulb, a tap washer — are for you.</li>
</ul>

<p>As a tenant you are well protected in the Netherlands. A landlord cannot simply put you out of the house; a court ruling is needed for that. If you have a dispute about the rent, the service costs or overdue maintenance of a sociale huurwoning, you can go to the <strong>Huurcommissie</strong>.</p>

${factTwoIn('en', 'Tenants in the Netherlands have huurbescherming (rent protection): a landlord cannot simply end the tenancy. In disputes about rent, service costs or maintenance, a tenant can bring a case before the Huurcommissie.', [['Rijksoverheid — Huurwoning', SRC_HUURWONING], ['Huurcommissie', SRC_HUURCOMMISSIE]], CHECKED)}

<p>Do you have a low income and a rental home that is not too expensive? Then you can apply for <strong>huurtoeslag</strong> at the Belastingdienst (tax administration). Whether you can, and how much, depends on your rent, your income, your age and your assets. Check it with the trial calculation on the Belastingdienst website — amounts and limits change every year.</p>

${factIn('en', 'Huurtoeslag is a contribution from the Belastingdienst towards rental costs. Whether you are entitled to it depends among other things on your rent, your income, your age and your assets; the amounts and limits change every year.', 'Belastingdienst — Huurtoeslag', SRC_HUURTOESLAG, CHECKED)}

${docentIn('en', 'With this theme people often stumble over one word: "toeslag" (allowance). You apply for allowances yourself, they do not come automatically. And you have to stop them yourself when your situation changes. Otherwise you have to pay money back later, and that is exactly where many people get into trouble.')}

<h2 id="nutsvoorzieningen">Gas, water, electricity and internet</h2>

<p>This is the second eindterm, and it really is work you have to do yourself. If you move into an empty home, sometimes nothing is switched on.</p>

<div class="guide-cards">
  ${card(I_HOME, 'Energy: gas and electricity', 'You choose a supplier yourself and sign a contract. You pay a monthly advance and once a year you get an annual settlement: money back or extra to pay.')}
  ${card(I_HOME, 'Water', 'Water comes through the water company of your region. You cannot choose — there is only one per area.')}
  ${card(I_HOME, 'Internet and telephone', 'Free choice between providers. Watch the length of the contract: often one or two years.')}
  ${card(I_EURO, 'Municipal taxes', 'Afvalstoffenheffing (waste tax) and rioolheffing (sewerage tax) come from the gemeente; waterschapsbelasting comes from the waterschap (water authority). If you have a low income, ask about kwijtschelding (remission).')}
</div>

<p>When you move into a home, always take the <strong>meterstanden</strong> (meter readings) — gas, electricity, water — and take a photo of them. Do the same when you leave. It is the cheapest five minutes of your move.</p>

<h3>Insurance around your home</h3>
<ul>
  <li><strong>Inboedelverzekering (contents insurance)</strong> — for your belongings in case of fire, water damage or burglary. Not compulsory, but sensible.</li>
  <li><strong>Aansprakelijkheidsverzekering (AVP, liability insurance)</strong> — for damage that you or your child cause to someone else. Also not compulsory, and very cheap.</li>
  <li><strong>Opstalverzekering (building insurance)</strong> — only if you buy a home; it insures the building itself.</li>
</ul>

<h2 id="schone-leefomgeving">A clean living environment</h2>

<p>The third eindterm is about waste and about the neighbourhood. In the Netherlands you separate your waste, and the rules differ per gemeente. Look on the website of your own gemeente or in the waste app to see which bin goes out when.</p>

<div class="yesno-grid">
  <div class="yesno-col yes">
    <p class="yesno-title">This is usually how it works</p>
    <ul>
      <li>${I_CHECK}<span>Paper, glass, gft (vegetable, fruit and garden waste), plastic and residual waste separately</span></li>
      <li>${I_CHECK}<span>The container outside on the fixed day, and back in again the same day</span></li>
      <li>${I_CHECK}<span>Grofvuil (bulky waste, such as an old sofa or a mattress) you report to the gemeente or take to the milieustraat (recycling centre)</span></li>
      <li>${I_CHECK}<span>Return deposit bottles and cans (statiegeld) at the supermarket</span></li>
    </ul>
  </div>
  <div class="yesno-col no">
    <p class="yesno-title">This gets you a fine</p>
    <ul>
      <li>${I_X}<span>Putting rubbish bags next to the container</span></li>
      <li>${I_X}<span>Putting bulky waste on the street without an appointment</span></li>
      <li>${I_X}<span>Separating waste wrongly at an underground container with a pass</span></li>
    </ul>
  </div>
</div>

${factIn('en', 'In the Netherlands household waste is collected separately. Gemeenten are responsible for the collection and decide themselves how and when this happens.', 'Rijksoverheid — Afval', SRC_AFVAL, CHECKED)}

<h3>Neighbours</h3>

<p>If many people live close together, nuisance is unavoidable. The order in the Netherlands is almost always the same, and the exam likes to ask about it:</p>

<div class="guide-steps">
  <div class="guide-step"><span class="guide-step-num">1</span><div class="guide-step-body">
    <h3>Talk to your neighbours</h3>
    <p>Yourself, calmly, and as soon as possible. This solves by far the most problems.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">2</span><div class="guide-step-body">
    <h3>Call in buurtbemiddeling (neighbourhood mediation)</h3>
    <p>Many gemeenten have free buurtbemiddeling: volunteers who guide the conversation.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">3</span><div class="guide-step-body">
    <h3>Report it to the landlord or the gemeente</h3>
    <p>With a sociale huurwoning the woningcorporatie can step in.</p>
  </div></div>
  <div class="guide-step"><span class="guide-step-num">4</span><div class="guide-step-body">
    <h3>Call the police</h3>
    <p>Only in cases of serious or continuing nuisance, or danger. For non-emergencies the number is 0900-8844.</p>
  </div></div>
</div>

${docentIn('en', '"First talk to them yourself" is almost always the right answer in this theme. I see students who immediately choose the police, because that is logical in their country. Here you are expected to try to sort it out together first.')}

${inlineCta('Practise this theme with exam questions', 'Situations about renting, energy and waste, with an explanation after every answer.', '/oefenen', 'Start a free practice exam')}
`,

  sidebarHtml: `
<p><strong>In short</strong></p>
<ul>
  <li>Sociale huur is cheaper but has long waiting times; the vrije sector is faster and more expensive.</li>
  <li>Register with the gemeente (BRP) as soon as you have an address.</li>
  <li>Tenants are well protected; in a dispute there is the Huurcommissie.</li>
  <li>You apply for huurtoeslag yourself at the Belastingdienst.</li>
  <li>Waste separation differs per gemeente; in case of nuisance you first talk to your neighbours yourself.</li>
</ul>`,

  faq: [
  {
    q: 'What is the difference between sociale huur and the vrije sector?',
    a: 'A sociale huurwoning belongs to a woningcorporatie (housing association), has a lower rent with a legal maximum and is meant for people with an income below a certain limit. You register for one and wait, sometimes for years. A home in the vrije sector is more expensive, comes from a private owner or an investor, and usually requires an income of three to four times the rent.',
  },
  {
    q: 'Can I get huurtoeslag?',
    a: 'Maybe. It depends on your rent, your income, your age and your assets, and on whether you are registered with the gemeente at that address. Do the trial calculation on the Belastingdienst website; the limits change every year. You have to apply for the allowance yourself — it does not come automatically.',
  },
  {
    q: 'What do I do if my landlord does not arrange maintenance?',
    a: 'First report it to your landlord in writing, for example by e-mail, so that you can prove it. If nothing happens, with a sociale huurwoning you can go to the Huurcommissie. It can decide that you temporarily have to pay less rent until the defect is repaired.',
  },
  {
    q: 'What do I have to arrange when I move into a new home?',
    a: 'Register with the gemeente, choose an energy supplier, sign up with the water company of your region and arrange internet. Take the meter readings straight away and take a photo of them. After that, think about contents insurance and liability insurance, and give your new address to your employer, your bank and your health insurer.',
  },
  {
    q: 'What do I do about nuisance from the neighbours?',
    a: 'First talk about it calmly with your neighbours yourself; that solves most problems. If that does not work, many gemeenten have free buurtbemiddeling. After that you can report it to your landlord or the gemeente. You only call the police in cases of serious or continuing nuisance — for non-emergencies through 0900-8844.',
  },
  ],
};

export default translation;
