UPDATE questions SET explanation = 'Een hoofdstad is de belangrijkste stad van een provincie of een land, niet per se de grootste of oudste stad.' WHERE id = 231;
UPDATE questions SET explanation = 'Als je wilt inchecken met de OV-chipkaart en je ziet ''Te weinig saldo'', betekent dit dat er niet genoeg geld op je kaart staat om te reizen.' WHERE id = 232;
UPDATE questions SET explanation = 'De Afsluitdijk sluit de vroegere Zuiderzee af en beschermt zo de polder Flevoland tegen overstromingen vanuit zee.' WHERE id = 233;
UPDATE questions SET explanation = 'De Deltawerken zijn gebouwd om de zuidwestelijke delta te beschermen. Ze beschermen vooral de provincies Zuid-Holland, Zeeland en Noord-Brabant.' WHERE id = 234;
UPDATE questions SET explanation = 'Een groot deel van Nederland ligt lager dan de zee. Dijken en duinen houden het zeewater tegen en voorkomen overstromingen.' WHERE id = 235;
UPDATE questions SET explanation = 'De Deltawerken zijn gebouwd om de zee te stoppen na de ramp van 1953, toen grote delen van Nederland overstroomden.' WHERE id = 236;
UPDATE questions SET explanation = 'Door het droogleggen van polders is er extra land ontstaan waarop mensen kunnen wonen en werken, zoals in Flevoland.' WHERE id = 237;
UPDATE questions SET explanation = 'In de 17e eeuw waren veel Nederlanders rijk door de handel. Ze lieten schilderijen maken om hun rijkdom te laten zien.' WHERE id = 238;
UPDATE questions SET explanation = 'Grachtenpanden staan aan het water omdat de Nederlanders veel producten over de grachten vervoerden, wat praktisch en efficiënt was voor de handel.' WHERE id = 239;
UPDATE questions SET explanation = 'Nederland werd in de 17e eeuw rijk door handel: Nederlanders kochten producten in andere landen en verkochten die met winst.' WHERE id = 240;
UPDATE questions SET explanation = 'Nederland is nu minder trots op de 17e eeuw omdat er ook veel geweld werd gebruikt, zoals slavernij en uitbuiting van koloniale gebieden.' WHERE id = 241;
UPDATE questions SET explanation = 'Amsterdam had veel water via de grachten, waardoor de Nederlanders makkelijk konden handelen en producten konden vervoeren.' WHERE id = 242;
UPDATE questions SET explanation = 'Den Haag was de plek waar de Nederlandse regering vergaderde en pratte over de handel en het beleid van het land.' WHERE id = 243;
UPDATE questions SET explanation = 'Uit de koloniën kwamen waardevolle producten die Nederland kon verkopen. Dat bracht veel geld op, wat Nederland rijk maakte.' WHERE id = 244;
UPDATE questions SET explanation = 'Tot slaaf gemaakte mensen werkten op de plantages zonder betaald te worden. Hierdoor bleef de winst voor Nederland, wat het land verrijkte.' WHERE id = 245;
UPDATE questions SET explanation = 'Na de officiële afschaffing van de slavernij in 1863 moesten de tot slaaf gemaakten nog tien jaar verplicht op de plantages blijven werken.' WHERE id = 246;
UPDATE questions SET explanation = 'Keti Koti wordt gevierd omdat in Suriname — een voormalige Nederlandse kolonie — de feestdag begon en vandaar over de wereld verspreid is.' WHERE id = 247;
UPDATE questions SET explanation = 'Op 1 juli 1863 werd de slavernij officieel afgeschaft in de Nederlandse kolonies. Keti Koti herdenkt en viert dit moment elk jaar op die datum.' WHERE id = 248;
UPDATE questions SET explanation = 'Keti Koti heeft twee kanten: er is een herdenking voor de slachtoffers van de slavernij én een feestviering van de vrijheid.' WHERE id = 249;
UPDATE questions SET explanation = 'Hitler wilde één groot rijk vormen en bezette meerdere Europese landen, waaronder Nederland, om zijn gebiedsuitbreiding te realiseren.' WHERE id = 250;
UPDATE questions SET explanation = 'Hitler gaf Joden de schuld van alle economische en sociale problemen in Europa en gebruikte dit als rechtvaardiging voor de Holocaust.' WHERE id = 251;
UPDATE questions SET explanation = 'De geallieerden (landen als de VS, Canada en het VK) vochten tegen Nazi-Duitsland en hebben Nederland in 1945 bevrijd.' WHERE id = 252;
UPDATE questions SET explanation = 'Op 4 mei is de Nationale Dodenherdenking. Nederlanders denken dan aan alle mensen die zijn omgekomen in oorlogen, met name de Tweede Wereldoorlog.' WHERE id = 253;
UPDATE questions SET explanation = 'Op 5 mei viert Nederland Bevrijdingsdag, de dag waarop Nederland in 1945 werd bevrijd van de Duitse bezetting.' WHERE id = 254;
UPDATE questions SET explanation = 'Na de oorlog was er veel werk beschikbaar in Nederland, met name in de industrie. Arbeidsmigranten kwamen daarom naar Nederland om te werken.' WHERE id = 255;
UPDATE questions SET explanation = 'Suriname was vroeger een Nederlandse kolonie. Veel Surinamers zijn naar Nederland gekomen, vooral rond de onafhankelijkheid van Suriname in 1975.' WHERE id = 256;
UPDATE questions SET explanation = 'Als EU-lid kan Nederland vrijelijk handel drijven met andere EU-landen zonder grenzen of tarieven, wat goed is voor de Nederlandse economie.' WHERE id = 257;
UPDATE questions SET explanation = 'Via de VN en de NAVO werkt Nederland samen met andere landen op het gebied van veiligheid en krijgt bescherming als dat nodig is.' WHERE id = 258;
UPDATE questions SET explanation = 'Woningen buiten de grote steden zijn vaak goedkoper. Daardoor kijken veel mensen ook buiten de stad naar een woning.' WHERE id = 259;
UPDATE questions SET explanation = 'De sociale huur zorgt ervoor dat ook mensen met een laag inkomen een betaalbare woning kunnen huren, omdat de huurprijs begrensd is.' WHERE id = 260;
UPDATE questions SET explanation = 'In de provincie Groningen zijn woningen gemiddeld goedkoper dan in de Randstad-provincies zoals Noord-Holland of Zuid-Holland.' WHERE id = 261;
UPDATE questions SET explanation = 'In de provincie Limburg zijn woningen gemiddeld goedkoper dan in de Randstad. Den Haag en Rotterdam zijn steden, geen provincies.' WHERE id = 262;
UPDATE questions SET explanation = 'In de provincie Drenthe zijn woningen gemiddeld goedkoper dan in Utrecht. Rotterdam en Utrecht zijn steden of provincies met hogere prijzen.' WHERE id = 263;
UPDATE questions SET explanation = 'Als je een hypotheek wilt, kijkt de bank of je inkomen of werk hebt om de lening terug te kunnen betalen.' WHERE id = 264;
UPDATE questions SET explanation = 'De verkoper bepaalt of hij het bod accepteert, afwijst of een tegenbod doet. Hij moet de koper laten weten wat hij vindt.' WHERE id = 265;
UPDATE questions SET explanation = 'Een makelaar kent de markt en kan je helpen sneller een geschikte koopwoning te vinden, maar het is niet verplicht.' WHERE id = 266;
UPDATE questions SET explanation = 'Luc en Marie willen officieel samenwonen en geregistreerd staan. Een huwelijk is de officiële juridische verbintenis die past bij hun situatie.' WHERE id = 267;
UPDATE questions SET explanation = 'Toby en Diego willen samen leven maar niets officieels regelen. Samenwonen is de vrije keuze om samen te wonen zonder huwelijk of geregistreerd partnerschap.' WHERE id = 268;
UPDATE questions SET explanation = 'Sama en Zeynep willen officieel geregistreerd samenwonen, net als een huwelijk maar voor mensen die niet willen trouwen. Dit heet geregistreerd partnerschap.' WHERE id = 269;
UPDATE questions SET explanation = 'Als de verhuurder de huurprijs verhoogt buiten de afspraken van het contract, is dat contractbreuk — hij houdt zich niet aan de afspraken.' WHERE id = 270;
UPDATE questions SET explanation = 'Zolang Feng bezwaar maakt, kan hij de oude huurprijs blijven betalen. Stoppen met betalen is altijd contractbreuk.' WHERE id = 271;
UPDATE questions SET explanation = 'Als de verhuurder niet luistert, kan Feng zijn klacht indienen bij de Huurcommissie. Die behandelt geschillen over huurprijzen.' WHERE id = 272;
UPDATE questions SET explanation = 'Stoppen met huur betalen is contractbreuk, ook als je een klacht hebt. Je moet altijd blijven betalen en de klacht via de juiste weg indienen.' WHERE id = 273;
UPDATE questions SET explanation = 'Een verhuurder mag inkomenseisen stellen om te controleren of de huurder de huur kan betalen. Dit is toegestaan en niet hetzelfde als discriminatie.' WHERE id = 274;
UPDATE questions SET explanation = 'De eerste stap bij overlast is direct met de buren praten. Dat lost het probleem het snelst op.' WHERE id = 275;
UPDATE questions SET explanation = 'Als de buren niet meewerken, is de volgende stap de verhuurder informeren. Die is verantwoordelijk voor het aanpakken van overlast door huurders.' WHERE id = 276;
UPDATE questions SET explanation = 'Huurtoeslag en andere toeslagen vraag je aan bij Dienst Toeslagen, de overheidsorganisatie die toeslagen beheert.' WHERE id = 277;
UPDATE questions SET explanation = 'Als je inkomen verandert, moet je dit doorgeven aan Dienst Toeslagen. Zo wordt de huurtoeslag opnieuw berekend op basis van het nieuwe inkomen.' WHERE id = 278;
UPDATE questions SET explanation = 'Dienst Toeslagen berekent opnieuw hoeveel huurtoeslag Mahmoud krijgt op basis van zijn nieuwe inkomen van de nieuwe baan.' WHERE id = 279;
UPDATE questions SET explanation = 'Als Bartek gaat samenwonen, telt het inkomen van Lauren mee. Dienst Toeslagen berekent de huurtoeslag op basis van het gezamenlijke inkomen.' WHERE id = 280;
UPDATE questions SET explanation = 'Door samen te wonen stijgt het totale inkomen. Een hoger inkomen betekent minder recht op huurtoeslag, dus de huurtoeslag wordt lager.' WHERE id = 281;
UPDATE questions SET explanation = 'In Nederland kun je zelf een energieleverancier kiezen via internet. Je vergelijkt aanbieders en kiest degene die bij jou past.' WHERE id = 282;
UPDATE questions SET explanation = 'Met een vast tarief weet je altijd wat je betaalt. De prijs verandert niet tijdens de looptijd van het contract.' WHERE id = 283;
UPDATE questions SET explanation = 'Je kunt niet zelf een waterbedrijf kiezen; je moet je aanmelden bij het waterbedrijf dat actief is in jouw regio.' WHERE id = 284;
UPDATE questions SET explanation = 'Voor internet, telefoon en televisie moet je zelf een abonnement kiezen bij een provider. Er zijn meerdere aanbieders om uit te kiezen.' WHERE id = 285;
UPDATE questions SET explanation = 'De regels voor afvalinzameling gelden per gemeente. Yana en haar buurvrouw wonen in dezelfde gemeente (Den Haag), dus hebben dezelfde regels.' WHERE id = 286;
UPDATE questions SET explanation = 'Motorrijtuigenbelasting betaal je aan de Rijksoverheid, niet aan de gemeente. Rioolbelasting en hondenbelasting zijn gemeentelijke belastingen.' WHERE id = 287;
UPDATE questions SET explanation = 'Door afval te scheiden kunnen materialen zoals papier, glas en plastic opnieuw worden verwerkt en gebruikt.' WHERE id = 288;
UPDATE questions SET explanation = 'In Nederland schrijf je je zelf in bij een huisartsenpraktijk naar keuze. Je kiest zelf een huisarts in jouw buurt.' WHERE id = 289;
UPDATE questions SET explanation = 'Een arts heeft een medisch beroepsgeheim, maar mag informatie delen met andere artsen als de patiënt daarvoor toestemming geeft.' WHERE id = 290;
UPDATE questions SET explanation = 'In Nederland ben je vrij om van huisarts te wisselen. Je schrijft je in bij een andere praktijk in jouw gemeente.' WHERE id = 291;
UPDATE questions SET explanation = 'Kumar moet bellen met de huisartsenpraktijk (niet de post), want depressie is een medische klacht waarbij de huisarts de eerste stap is.' WHERE id = 292;
UPDATE questions SET explanation = 'De huisartsenpraktijk kan een tolk regelen via de telefoon. Een kind van 10 mag niet tolken bij medische gesprekken.' WHERE id = 293;
UPDATE questions SET explanation = 'Het medisch beroepsgeheim betekent dat een arts alleen informatie mag delen als de patiënt daar toestemming voor heeft gegeven.' WHERE id = 294;
UPDATE questions SET explanation = 'Een spoedeisende hulp (ziekenhuis) is beschikbaar voor acute situaties. Sama kan direct gaan als haar dochter acuut hulp nodig heeft.' WHERE id = 295;
UPDATE questions SET explanation = 'Voor de huisarts heb je geen verwijsbrief nodig. Je maakt gewoon een afspraak.' WHERE id = 296;
UPDATE questions SET explanation = 'Voor een specialist zoals een oogarts heb je een verwijsbrief van de huisarts nodig om een afspraak in het ziekenhuis te maken.' WHERE id = 297;
UPDATE questions SET explanation = 'Voor een psycholoog heb je een verwijsbrief van de huisarts nodig. De huisarts verwijst door bij psychische klachten.' WHERE id = 298;
UPDATE questions SET explanation = 'Voor een fysiotherapeut heb je geen verwijsbrief van de huisarts nodig. Je kunt zelf een afspraak maken bij een fysiotherapeut in de buurt.' WHERE id = 299;
UPDATE questions SET explanation = 'Een traplift aanvragen bij de gemeente gaat niet altijd automatisch. Sama moet kijken of ze recht heeft op ondersteuning via de Wmo.' WHERE id = 300;
UPDATE questions SET explanation = 'Voor de meeste medicijnen heb je een recept van de huisarts nodig. Alleen eenvoudige pijnstillers en verkoudheidsproducten zijn zonder recept verkrijgbaar.' WHERE id = 301;
UPDATE questions SET explanation = 'Bij keelpijn en hoesten is de huisarts de eerste stap. Die kan de klachten beoordelen en de juiste behandeling adviseren.' WHERE id = 302;
UPDATE questions SET explanation = 'Als de huisarts geen medicijnen voorschrijft maar wandelen adviseert, is dat het medische advies dat Mahmoud moet opvolgen.' WHERE id = 303;
UPDATE questions SET explanation = 'Regelmatige tandartscontroles helpen om problemen vroeg op te sporen en je gebit gezond te houden.' WHERE id = 304;
UPDATE questions SET explanation = 'De mondhygiënist maakt je gebit professioneel schoon en voorkomt zo dat je gaatjes of tandvleesproblemen krijgt.' WHERE id = 305;
UPDATE questions SET explanation = 'Zorg in Nederland is duur. Door een verplichte zorgverzekering zorgt iedereen mee voor de kosten van de gezondheidszorg.' WHERE id = 306;
UPDATE questions SET explanation = 'Als je medicijnen wilt declareren bij je zorgverzekeraar, vul je een formulier in op de website van de verzekeraar en stuur je een foto van de rekening.' WHERE id = 307;
UPDATE questions SET explanation = 'Als Samuel een verwijsbrief van de huisarts heeft, vergoedt de zorgverzekeraar de fysiotherapie vanuit het basispakket.' WHERE id = 308;
UPDATE questions SET explanation = 'Als je het eigen risico niet in één keer kunt betalen, kun je de zorgverzekeraar bellen om het bedrag gespreid te betalen.' WHERE id = 309;
UPDATE questions SET explanation = 'Een nieuwgeboren baby moet binnen drie dagen worden aangegeven bij de gemeente. Dit is wettelijk verplicht.' WHERE id = 310;
UPDATE questions SET explanation = 'In Nederland mag je zelf kiezen of je donor wilt zijn, maar je moet deze keuze wel registreren in het Donorregister.' WHERE id = 311;
UPDATE questions SET explanation = 'Je geeft je donorkeuze door via het Donorregister op de officiële website. Dit is de enige officiële manier.' WHERE id = 312;
UPDATE questions SET explanation = 'Na het overlijden kunnen de nabestaanden afscheid nemen voordat de organen worden gedoneerd. De orgaandonatie is niet zichtbaar van buiten.' WHERE id = 313;
UPDATE questions SET explanation = 'Voorschoolse educatie is speciaal voor kinderen van 2-4 jaar die thuis geen of weinig Nederlands spreken, zodat ze de taal leren vóór de basisschool.' WHERE id = 314;
UPDATE questions SET explanation = 'Kinderen met een beperking, zoals een visuele beperking, gaan naar het speciaal onderwijs, dat is afgestemd op hun specifieke behoeften.' WHERE id = 315;
UPDATE questions SET explanation = 'De buitenschoolse opvang (BSO) is er voor kinderen die na schooltijd — als ouders nog werken — worden opgevangen.' WHERE id = 316;
UPDATE questions SET explanation = 'Een openbare basisschool staat open voor alle kinderen, ongeacht religie of achtergrond. Er is veel diversiteit in de klas.' WHERE id = 317;
UPDATE questions SET explanation = 'Het voortgezet onderwijs is voor jongeren van 12 jaar en ouder. Ze hebben meerdere docenten voor verschillende vakken.' WHERE id = 318;
UPDATE questions SET explanation = 'Juffen en meesters bespreken de ontwikkeling van een kind tijdens een oudergesprek, een gepland gesprek op school.' WHERE id = 319;
UPDATE questions SET explanation = 'Als een juf of meester direct is, weten ouders precies wat hij of zij denkt over het kind. Dat geeft duidelijkheid en vertrouwen.' WHERE id = 320;
UPDATE questions SET explanation = 'Als ouders helpen bij activiteiten op school, zien ze zelf wat hun kind doet en hoe het zich gedraagt in de klas.' WHERE id = 321;
UPDATE questions SET explanation = 'In Nederland zingt de klas voor het jarige kind. De traditie is dat de klas samen het verjaardagslied zingt.' WHERE id = 322;
UPDATE questions SET explanation = 'Elke vervolgopleiding heeft eigen toelatingseisen, zoals een bepaald diploma of bepaalde vakken. Je moet dit altijd eerst checken.' WHERE id = 323;
UPDATE questions SET explanation = 'Als je een bepaald vak niet hebt gevolgd op de middelbare school maar dat vak is vereist voor de opleiding, mag je die opleiding niet instappen.' WHERE id = 324;
UPDATE questions SET explanation = 'De kwalificatieplicht zorgt ervoor dat jongeren een startkwalificatie halen — een diploma dat hun kansen op de arbeidsmarkt verbetert.' WHERE id = 325;
UPDATE questions SET explanation = 'Kinderen onder de 18 zijn niet juridisch aansprakelijk. Hun ouders zijn verantwoordelijk voor de schade die hun minderjarig kind veroorzaakt.' WHERE id = 326;
UPDATE questions SET explanation = 'De dochter van Yana is 20 jaar en dus meerderjarig. Zij is zelf juridisch aansprakelijk voor de schade die ze veroorzaakt.' WHERE id = 327;
UPDATE questions SET explanation = 'Aanhoudende vermoeidheid bij een kind is een medische klacht. De huisarts is de eerste stap om de oorzaak te onderzoeken.' WHERE id = 328;
UPDATE questions SET explanation = 'Als een kind moeite heeft met leren, kan de school helpen met extra ondersteuning, begeleiding of een doorverwijzing naar specialisten.' WHERE id = 329;
UPDATE questions SET explanation = 'Het Centrum voor Jeugd en Gezin (CJG) biedt hulp en advies bij vragen over de opvoeding van kinderen.' WHERE id = 330;
UPDATE questions SET explanation = 'De GGD (Gemeentelijke Gezondheidsdienst) houdt toezicht op de volksgezondheid en kan ingrijpen bij uitbraken van kinderziekten.' WHERE id = 331;
UPDATE questions SET explanation = 'Als een kind thuis niet veilig is, kan de Raad voor de Kinderbescherming ingrijpen om het kind te beschermen.' WHERE id = 332;
UPDATE questions SET explanation = 'Kinderbijslag vraag je aan bij de Sociale Verzekeringsbank (SVB). Dat is de organisatie die kinderbijslag en AOW beheert.' WHERE id = 333;
UPDATE questions SET explanation = 'De kosten van kinderopvang worden gedeeld door de ouders en Dienst Toeslagen. Ouders betalen een eigen bijdrage en krijgen kinderopvangtoeslag.' WHERE id = 334;
UPDATE questions SET explanation = 'Kinderopvangtoeslag vraag je aan bij Dienst Toeslagen. Dit is de overheidsorganisatie die alle toeslagen beheert.' WHERE id = 335;
UPDATE questions SET explanation = 'Als je de ouderbijdrage op school niet kunt betalen, vertel je dat aan de school. De school kan dan meedenken over een oplossing.' WHERE id = 336;
UPDATE questions SET explanation = 'Studiefinanciering vraag je aan bij DUO (Dienst Uitvoering Onderwijs). DUO beheert alle studiefinanciering in Nederland.' WHERE id = 337;
UPDATE questions SET explanation = 'Mert kan gaan werken om zijn studie te betalen. Studiefinanciering is ook een optie, maar de vraag stelt ''hoe kan hij betalen'' en werken is een concrete manier.' WHERE id = 338;
UPDATE questions SET explanation = 'De IDW (Internationale Diplomawaardering) helpt mensen met een buitenlands diploma te begrijpen wat ze daarmee in Nederland kunnen doen.' WHERE id = 339;
UPDATE questions SET explanation = 'Een uitzendbureau heeft veel vacatures en helpt mensen actief bij het zoeken en vinden van werk.' WHERE id = 340;
UPDATE questions SET explanation = 'Vrijwilligerswerk is werk waarvoor je geen betaling krijgt. Het is een goede manier om actief te zijn en ervaring op te doen.' WHERE id = 341;
UPDATE questions SET explanation = 'Een uitzendbureau heeft veel vacatures, ook voor tijdelijk werk. Je kunt je inschrijven en snel aan de slag.' WHERE id = 342;
UPDATE questions SET explanation = 'Een opleiding halen verhoogt je kans op werk omdat je meer kwalificaties hebt die werkgevers vragen.' WHERE id = 343;
UPDATE questions SET explanation = 'In een sollicitatiebrief schrijf je je motivatie: waarom je de baan wilt. Zeynep laat zien dat ze gemotiveerd is omdat ze koken leuk vindt.' WHERE id = 344;
UPDATE questions SET explanation = 'Als je iets niet begrijpt in een vacature, kun je het bedrijf bellen voor meer informatie. Zo weet je precies wat de baan inhoudt.' WHERE id = 345;
UPDATE questions SET explanation = 'Goede voorbereiding op een sollicitatiegesprek betekent dat je iets weet over het bedrijf en vragen bedenkt om te stellen.' WHERE id = 346;
UPDATE questions SET explanation = 'In Nederland werken veel mensen in deeltijd, bijvoorbeeld 24, 28 of 32 uur per week. Dit is gebruikelijk en geaccepteerd.' WHERE id = 347;
UPDATE questions SET explanation = 'Elke medewerker heeft een persoonlijke arbeidsovereenkomst met zijn eigen functie, salaris en uren. Dit is een individuele afspraak.' WHERE id = 348;
UPDATE questions SET explanation = 'Een cao (collectieve arbeidsovereenkomst) geldt voor alle mensen in Nederland die hetzelfde beroep uitoefenen, ongeacht het bedrijf.' WHERE id = 349;
UPDATE questions SET explanation = 'Marieke onderhandelt over haar arbeidsvoorwaarden — ze wil minder uren werken. Dit is typisch voor een onderhandeling over arbeidsvoorwaarden.' WHERE id = 350;
UPDATE questions SET explanation = 'Bij een beoordelingsgesprek bespreek je hoe het werk gaat. Je bereidt je voor door na te denken over je prestaties en eventuele vragen.' WHERE id = 351;
UPDATE questions SET explanation = 'Werknemersverzekeringen zorgen ervoor dat je een uitkering krijgt als je door ziekte niet meer kunt werken.' WHERE id = 352;
UPDATE questions SET explanation = 'Van je brutosalaris gaat loonbelasting af. De overheid gebruikt dit geld voor publieke voorzieningen zoals wegen en scholen.' WHERE id = 353;
UPDATE questions SET explanation = 'Een jaaropgave moet minimaal vijf jaar worden bewaard voor de Belastingdienst, omdat zij je over de afgelopen jaren kunnen controleren.' WHERE id = 354;
UPDATE questions SET explanation = 'De vakbond behartigt de rechten van werknemers. Bij ontslagen kan de vakbond helpen en onderhandelen over de voorwaarden.' WHERE id = 355;
UPDATE questions SET explanation = 'De ondernemingsraad (OR) vertegenwoordigt werknemers en moet geraadpleegd worden bij grote beslissingen in het bedrijf.' WHERE id = 356;
UPDATE questions SET explanation = 'De personeelsvereniging organiseert activiteiten voor collega''s. Door lid te worden leer je collega''s kennen in een informele sfeer.' WHERE id = 357;
UPDATE questions SET explanation = 'De vakbond zet zich in voor betere arbeidsomstandigheden voor werknemers, inclusief het organiseren van meer activiteiten voor personeel.' WHERE id = 358;
UPDATE questions SET explanation = 'Een vakbond beschermt werknemers door afspraken te maken over salaris, werktijden en arbeidsomstandigheden.' WHERE id = 359;
UPDATE questions SET explanation = 'Staken is een pressiemiddel maar garandeert niet altijd resultaat. De werkgever hoeft niet altijd toe te geven aan de eisen van de vakbond.' WHERE id = 360;
UPDATE questions SET explanation = 'Als lid van de OR leer je veel over hoe het bedrijf werkt, welke plannen er zijn en hoe beslissingen worden genomen.' WHERE id = 361;
UPDATE questions SET explanation = 'Een vakbond is er voor alle werknemers in een sector, ook als je geen lid bent. Zeynep kan via de vakbond actie laten ondernemen.' WHERE id = 362;
UPDATE questions SET explanation = 'Bij de Kamer van Koophandel kun je advies en informatie krijgen over het starten van een bedrijf, naast de verplichte inschrijving.' WHERE id = 363;
UPDATE questions SET explanation = 'Als je als zzp''er een eigen bedrijf begint, stopt je uitkering in de meeste gevallen, omdat je dan inkomsten uit je bedrijf kunt halen.' WHERE id = 364;
UPDATE questions SET explanation = 'In een ondernemingsplan beschrijf je wat voor bedrijf je wilt beginnen, inclusief welke producten of diensten je gaat aanbieden.' WHERE id = 365;
UPDATE questions SET explanation = 'Als zzp''er heb je geen werkgever die je verzekert. Je moet zelf een arbeidsongeschiktheidsverzekering (AOV) afsluiten.' WHERE id = 366;
UPDATE questions SET explanation = 'Als werknemer is Mariam via haar werkgever verzekerd bij arbeidsongeschiktheid via de werknemersverzekeringen (WIA).' WHERE id = 367;
UPDATE questions SET explanation = 'Als werknemer bij een supermarkt bouwt Luc via zijn werkgever pensioen op. Dit pensioen krijgt hij als hij stopt met werken.' WHERE id = 368;
UPDATE questions SET explanation = 'Als zelfstandige bouwt Sama geen pensioen op via een werkgever. Ze moet zelf sparen of een pensioenregeling afsluiten.' WHERE id = 369;
UPDATE questions SET explanation = 'Bijstand vraag je aan bij de gemeente. De gemeente beoordeelt of je recht hebt op bijstand als je onvoldoende inkomen hebt.' WHERE id = 370;
UPDATE questions SET explanation = 'Mensen met bijstand hebben het recht om een cursus of opleiding te doen om hun kansen op werk te vergroten.' WHERE id = 371;
UPDATE questions SET explanation = 'Als je een WW-uitkering hebt, ben je verplicht actief te solliciteren. Dit is een plicht die het UWV controleert.' WHERE id = 372;
UPDATE questions SET explanation = 'Een zwangerschap moet Mariam doorgeven aan het UWV, omdat dit invloed heeft op haar uitkering en recht op zwangerschapsverlof.' WHERE id = 373;
UPDATE questions SET explanation = 'Een rijbewijs vraag je aan bij de gemeente. Paspoorten, ID-kaarten en rijbewijzen worden allemaal door de gemeente afgegeven.' WHERE id = 374;
UPDATE questions SET explanation = 'Officiële documenten zoals een paspoort vernieuw je bij de gemeente. Dat geldt ook voor een ID-kaart en rijbewijs.' WHERE id = 375;
UPDATE questions SET explanation = 'Een verblijfsvergunning vraag je aan bij de IND (Immigratie- en Naturalisatiedienst), niet bij de gemeente of KVK.' WHERE id = 376;
UPDATE questions SET explanation = 'Naturalisatie — het aanvragen van de Nederlandse nationaliteit — doe je bij de IND of de gemeente.' WHERE id = 377;
UPDATE questions SET explanation = 'Als je volgens de wet van je land van herkomst geen afstand mag doen van je nationaliteit, mag je in Nederland twee nationaliteiten hebben.' WHERE id = 378;
UPDATE questions SET explanation = 'Na vijf jaar in Nederland wonen met een verblijfsvergunning en goed Nederlands spreken, voldoet Mariam aan de voorwaarden voor naturalisatie.' WHERE id = 379;
UPDATE questions SET explanation = 'In Nederland moet iedereen van 14 jaar en ouder een identiteitsbewijs kunnen tonen als de politie dat vraagt. Samuel''s zoon is 15 jaar.' WHERE id = 380;
UPDATE questions SET explanation = 'Een woningcorporatie heeft je BSN nodig om je identiteit te verifiëren en gegevens te controleren bij de overheid.' WHERE id = 381;
UPDATE questions SET explanation = 'Bij een diefstal bel je 112 en vraag je om de politie. Een diefstal is een misdrijf waarvoor de politie optreedt.' WHERE id = 382;
UPDATE questions SET explanation = 'Overlast van buren is geen spoedgeval. Je belt 0900-8844 voor de politie bij niet-urgente situaties.' WHERE id = 383;
UPDATE questions SET explanation = 'Oplichting is een misdrijf. Mariam moet aangifte doen bij de politie. In een spoedgeval belt ze 112.' WHERE id = 384;
UPDATE questions SET explanation = 'Bij een zwaargewonde na een ongeluk bel je 112 en vraag je om een ambulance. Dit is een medische noodsituatie.' WHERE id = 385;
UPDATE questions SET explanation = 'Bij discriminatie door de politie kun je hulp vragen bij het Juridisch Loket voor advies over juridische stappen.' WHERE id = 386;
UPDATE questions SET explanation = 'Als een overheidsinstantie niet reageert of niet helpt, kun je een klacht indienen bij de Nationale ombudsman.' WHERE id = 387;
UPDATE questions SET explanation = 'De gemeentelijke ombudsman behandelt klachten over de gemeente en helpt als er problemen zijn met gemeentelijke diensten.' WHERE id = 388;
UPDATE questions SET explanation = 'Bij een scheiding heb je juridisch advies nodig. Een advocaat helpt bij de juridische procedure en afspraken.' WHERE id = 389;
UPDATE questions SET explanation = 'Als je een laag inkomen hebt en een advocaat nodig hebt, betaal je een eigen bijdrage die past bij je inkomen. Je betaalt niet alles zelf.' WHERE id = 390;
UPDATE questions SET explanation = 'De politie handhaaft verkeersregels en controleert snelheid in woonstraten. De rechter oordeelt, maar de politie controleert.' WHERE id = 391;
UPDATE questions SET explanation = 'Het treinpersoneel controleert vervoersbewijzen in de trein. Als je geen geldig bewijs hebt, is de rechter degene die oordeelt over de boete.' WHERE id = 392;
UPDATE questions SET explanation = 'De minister schrijft de wet die zegt dat rijden door rood verboden is. De politie handhaaft de wet en geeft de boete.' WHERE id = 393;
UPDATE questions SET explanation = 'Als je het niet eens bent met een uitspraak van de rechter, kun je in hoger beroep gaan bij een hogere rechtbank.' WHERE id = 394;
UPDATE questions SET explanation = 'Mensen zonder Nederlandse nationaliteit maar met meer dan vijf jaar verblijfsvergunning mogen stemmen bij gemeenteraadsverkiezingen.' WHERE id = 395;
UPDATE questions SET explanation = 'Om te stemmen moet je minimaal 18 jaar oud zijn. Bartek is 15 jaar en heeft daardoor nog geen kiesrecht.' WHERE id = 396;
UPDATE questions SET explanation = 'Feng stemt bij een verkiezing. Dit is actief kiesrecht: het recht om zelf te stemmen op een kandidaat of partij.' WHERE id = 397;
UPDATE questions SET explanation = 'Passief kiesrecht is het recht om gekozen te worden. Yana staat op de kandidatenlijst en anderen kunnen op haar stemmen.' WHERE id = 398;
UPDATE questions SET explanation = 'Mensen zonder Nederlandse nationaliteit die meer dan vijf jaar in Nederland wonen met een verblijfsvergunning mogen stemmen bij gemeenteraadsverkiezingen.' WHERE id = 399;
UPDATE questions SET explanation = 'Stemmen in Nederland is geen plicht, maar een recht. Je mag zelf kiezen of je gaat stemmen.' WHERE id = 400;
UPDATE questions SET explanation = 'Koningsdag is op 27 april, de verjaardag van koning Willem-Alexander.' WHERE id = 401;
UPDATE questions SET explanation = 'Op Koningsdag viert Nederland de verjaardag van de koning. Mensen dragen oranje en er zijn markten op straat.' WHERE id = 402;
UPDATE questions SET explanation = 'Op Koningsdag dragen mensen oranje kleding als symbool van de koninklijke familie (het Huis van Oranje).' WHERE id = 403;
UPDATE questions SET explanation = 'Het volkslied van Nederland heet het Wilhelmus. Het gaat over Willem van Oranje uit de 16e eeuw.' WHERE id = 404;
UPDATE questions SET explanation = 'Het Wilhelmus wordt gezongen bij belangrijke sportwedstrijden, zoals bij Olympische Spelen of internationale voetbalwedstrijden.' WHERE id = 405;
UPDATE questions SET explanation = 'Door de machtenscheiding heeft niet één persoon of groep alle macht, wat corruptie moeilijker maakt.' WHERE id = 406;
UPDATE questions SET explanation = 'Nederland is een rechtsstaat: de wetten gelden voor iedereen, ook voor de overheid. Niemand staat boven de wet.' WHERE id = 407;
UPDATE questions SET explanation = 'Corruptie — het misbruiken van macht voor eigen voordeel — is in Nederland strafbaar bij wet.' WHERE id = 408;
UPDATE questions SET explanation = 'De Grondwet bevat de belangrijkste wetten van Nederland, zoals gelijke behandeling, vrijheid van meningsuiting en godsdienstvrijheid.' WHERE id = 409;
UPDATE questions SET explanation = 'In Nederland mag een abortus plaatsvinden tot de 24e week van de zwangerschap. Dit is wettelijk vastgelegd.' WHERE id = 410;
UPDATE questions SET explanation = 'Artikel 1 van de Grondwet garandeert gelijkheid. Mannen en vrouwen hebben in Nederland dezelfde rechten en zijn juridisch gelijk.' WHERE id = 411;
UPDATE questions SET explanation = 'De Grondwet garandeert dat iedereen gelijk is en gelijk behandeld wordt, ongeacht religie, geslacht of afkomst.' WHERE id = 412;
UPDATE questions SET explanation = 'In Nederland geldt godsdienstvrijheid. Je mag niet het dragen van een hoofddoek verbieden, want dat is een inbreuk op die vrijheid.' WHERE id = 413;
UPDATE questions SET explanation = 'Vrijheid van meningsuiting is een grondrecht. Je mag je mening geven, ook kritisch over de politie, zolang het niet strafbaar is.' WHERE id = 414;
UPDATE questions SET explanation = 'Kindermishandeling is in Nederland strafbaar. Ouders mogen geen geweld gebruiken tegen hun kinderen.' WHERE id = 415;
UPDATE questions SET explanation = 'Een religieuze instelling mag activiteiten organiseren, maar moet zich altijd aan de Nederlandse wet houden.' WHERE id = 416;
UPDATE questions SET explanation = 'Op grond van het privacyrecht heeft iedereen het recht om te zien welke gegevens overheidsinstanties over hem of haar bewaren.' WHERE id = 417;
UPDATE questions SET explanation = 'Als je denkt dat je wordt gediscrimineerd bij sollicitaties, kun je dit melden bij het meldpunt Discriminatie voor advies en ondersteuning.' WHERE id = 418;
