-- A2 funnel baseline — the minimum schema for the shipped surface.
--
-- Covers:
--   exam_submissions      email captured by the free-taster gate + the score
--   email_campaign_queue  the day2 / day7 / abandon drip
--   exams                 the 10 practice exams per skill (empty until content exists)
--
-- Deliberately does NOT create the inherited KNM tables (questions, sections, word_cards,
-- leren_content, user_*). Those come back per-surface, reshaped for A2, in Phase 2+.
--
-- Access model: /api/submit-results, /api/send-campaign-emails and /api/claim-submissions
-- all use the service-role client (lib/supabase/admin.ts), which bypasses RLS — so the two
-- funnel tables get RLS on with no policy at all. `exams` is read by lib/exams.ts through
-- the anon SSR client, so it needs an explicit public-read policy.

BEGIN;

-- ── exam_submissions ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.exam_submissions (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email      text NOT NULL,
  -- Set by /api/claim-submissions when an anonymous submitter later registers.
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  score      integer NOT NULL,
  total      integer NOT NULL,
  pct        integer NOT NULL,
  passed     boolean NOT NULL,
  cat_scores jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- NOTE: the KNM schema had UNIQUE (email, exam_number) here. That is deliberately absent.
-- Every taster submits as one exam, so the same person trying Lezen and then Luisteren
-- collided on it and the second submission was silently dropped.

-- Backs the 10-minute duplicate check in /api/submit-results.
CREATE INDEX IF NOT EXISTS exam_submissions_email_created_idx
  ON public.exam_submissions (email, created_at DESC);

CREATE INDEX IF NOT EXISTS exam_submissions_user_id_idx
  ON public.exam_submissions (user_id);

ALTER TABLE public.exam_submissions ENABLE ROW LEVEL SECURITY;

-- Let a signed-in user read back their own claimed submissions.
DROP POLICY IF EXISTS "Users read own submissions" ON public.exam_submissions;
CREATE POLICY "Users read own submissions"
  ON public.exam_submissions FOR SELECT
  USING (auth.uid() = user_id);

-- ── email_campaign_queue ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.email_campaign_queue (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email         text NOT NULL,
  campaign_type text NOT NULL CHECK (campaign_type IN ('day2', 'day7', 'abandon')),
  scheduled_for timestamptz NOT NULL,
  payload       jsonb NOT NULL DEFAULT '{}',
  status        text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'sent', 'failed')),
  sent_at       timestamptz,
  error_message text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- The cron selects pending rows whose time has come.
CREATE INDEX IF NOT EXISTS email_campaign_queue_due_idx
  ON public.email_campaign_queue (scheduled_for, status)
  WHERE status = 'pending';

-- One campaign of each type per address. /api/submit-results already tolerates the
-- resulting 23505 unique violation, so re-submitting does not error.
CREATE UNIQUE INDEX IF NOT EXISTS email_campaign_queue_email_type_idx
  ON public.email_campaign_queue (email, campaign_type)
  WHERE status IN ('pending', 'sent');

ALTER TABLE public.email_campaign_queue ENABLE ROW LEVEL SECURITY;

-- ── exams ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.exams (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill            text NOT NULL
                     CHECK (skill IN ('lezen', 'luisteren', 'schrijven', 'spreken')),
  number           smallint NOT NULL CHECK (number BETWEEN 1 AND 10),
  title            text,
  -- Exam 1 of every skill is the free one; see isFreeExam() in data/skills.ts.
  is_free          boolean NOT NULL DEFAULT false,
  duration_seconds integer NOT NULL,
  -- lib/exams.ts only returns published rows, so an exam stays "Binnenkort" on the
  -- overview page until the docent has reviewed it and flips this.
  published        boolean NOT NULL DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exams_skill_number_key UNIQUE (skill, number)
);

CREATE INDEX IF NOT EXISTS exams_skill_published_idx
  ON public.exams (skill, number) WHERE published;

ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;

-- Read by anonymous visitors on /oefenexamen/[skill] via the SSR anon client.
DROP POLICY IF EXISTS "Published exams are public" ON public.exams;
CREATE POLICY "Published exams are public"
  ON public.exams FOR SELECT
  USING (published);

-- Keep updated_at honest.
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS exams_touch_updated_at ON public.exams;
CREATE TRIGGER exams_touch_updated_at
  BEFORE UPDATE ON public.exams
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

COMMIT;

-- Make the new tables visible to PostgREST immediately.
NOTIFY pgrst, 'reload schema';
