-- De ingesproken uitleg van een les.
--
-- Een eigen tabel en geen vijf kolommen op `lessons`: 52 van de 53 lessen hebben vandaag geen
-- narratie, en vijf altijd-NULL kolommen op de tabel die élke lespagina leest is de duurdere
-- kant van die ruil. De unieke sleutel op `lesson_id` legt vast dat het er één per les is —
-- KNM had er één per sectie, maar hier heeft een les één uitlegblok bovenaan.
create table if not exists lesson_narration (
  id bigint generated by default as identity primary key,
  lesson_id integer not null references lessons (id) on delete cascade,

  -- Het voorgelezen script. Bewaard en niet weggegooid na het genereren: zonder het script kan
  -- de docent niet nakijken wát er gezegd wordt, en dat is precies wat er nagekeken moet worden.
  script text not null,

  -- De sleutel uit `data/tts-voices.json`, niet het ElevenLabs-id. Een id in de database zou de
  -- tweede plek zijn waar stemmen staan, en de regel is dat ze op één plek staan.
  voice_key text not null,

  audio_url text,
  duration_seconds numeric(6, 2),

  -- Dezelfde twee waarden als `lessons.review_status` en `stimuli.review_status`. `pending`
  -- speelt wél — anders kan de docent niet horen wat ze nakijkt — maar de pagina zegt het.
  review_status text not null default 'pending'
    check (review_status in ('pending', 'validated')),
  reviewed_by text,
  reviewed_on date,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint lesson_narration_lesson_key unique (lesson_id)
);

create index if not exists lesson_narration_lesson_idx on lesson_narration (lesson_id);

alter table lesson_narration enable row level security;

-- Publiek lezen, zoals `lessons` en `lesson_items`: de poort op lescontent staat op de module
-- in de pagina, niet in RLS. Schrijven is admin, via `is_admin()`.
create policy "Public read lesson_narration" on lesson_narration
  for select using (true);

create policy "Admins write lesson_narration" on lesson_narration
  for all using (is_admin()) with check (is_admin());

create trigger lesson_narration_touch
  before update on lesson_narration
  for each row execute function touch_updated_at();
