-- De ChatGPT-app (MCP): twee tabellen, geen wijziging aan inhoud of voortgang.
--
-- 1. `mcp_anonymous_usage` — welke proefvragen een anonieme ChatGPT-gebruiker al gehad heeft.
--    Het besluit van de eigenaar (04-10): zonder account krijg je per onderdeel precies de tien
--    vragen van de gratis taster, altijd dezelfde tien, één keer. Daarna alleen nog de uitnodiging
--    om een gratis account te maken. Dus géén dagquotum maar een lijst van uitgedeelde vragen per
--    (onderwerp, onderdeel, niveau). Het onderwerp is de geanonimiseerde gebruikers-id die ChatGPT
--    meestuurt (`_meta["openai/subject"]`), gehasht met een serverzout — we bewaren nooit de ruwe
--    waarde. `mcp_anon_serve()` doet het toevoegen en het tellen in één statement, zodat twee
--    gelijktijdige aanroepen niet allebei "nummer tien" uitdelen.
--
-- 2. `mcp_events` — de analytics van het kanaal. GA4 draait alleen in de browser en een MCP-aanroep
--    heeft geen browser, dus de zeven vragen uit de brief (hoeveel gebruikers, hoeveel afgerond,
--    hoeveel koppelen een account, hoe vaak de betaalmuur, welke tool het meest) worden hier met
--    SQL beantwoord. Geen gespreksinhoud, geen antwoordtekst, geen tokens.
--
-- Beide tabellen zijn alleen voor de admin leesbaar; de app schrijft met de service-sleutel.

CREATE TABLE IF NOT EXISTS public.mcp_anonymous_usage (
  subject_hash        text        NOT NULL,
  onderdeel           text        NOT NULL REFERENCES public.skills(slug),
  level               text        NOT NULL DEFAULT '',   -- '' voor KNM: een PK-kolom mag geen NULL zijn
  served_question_ids bigint[]    NOT NULL DEFAULT '{}',
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (subject_hash, onderdeel, level)
);

COMMENT ON TABLE public.mcp_anonymous_usage IS
  'ChatGPT-app: de proefvragen die een anonieme gebruiker (gehasht openai/subject) al gehad heeft, per onderdeel en niveau. Levenslang, geen reset.';

ALTER TABLE public.mcp_anonymous_usage ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins read mcp anonymous usage" ON public.mcp_anonymous_usage;
CREATE POLICY "Admins read mcp anonymous usage" ON public.mcp_anonymous_usage
  FOR SELECT USING (public.is_admin());

-- Voegt een vraag toe aan de lijst van dit onderwerp als er nog ruimte is (of als hij er al in
-- staat), en geeft terug of de vraag uitgedeeld mag worden. Atomair door de UPDATE-met-WHERE op
-- de bestaande rij; een INSERT voor een nieuw onderwerp kan racen met zichzelf, en dan vangt de
-- PK-conflict de tweede af en herhaalt die als UPDATE.
CREATE OR REPLACE FUNCTION public.mcp_anon_serve(
  p_subject_hash text,
  p_onderdeel    text,
  p_level        text,
  p_question_id  bigint,
  p_limit        integer
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ids bigint[];
BEGIN
  SELECT served_question_ids INTO v_ids
    FROM public.mcp_anonymous_usage
   WHERE subject_hash = p_subject_hash AND onderdeel = p_onderdeel AND level = coalesce(p_level, '')
   FOR UPDATE;

  IF NOT FOUND THEN
    BEGIN
      INSERT INTO public.mcp_anonymous_usage (subject_hash, onderdeel, level, served_question_ids)
      VALUES (p_subject_hash, p_onderdeel, coalesce(p_level, ''), ARRAY[p_question_id]);
      RETURN true;
    EXCEPTION WHEN unique_violation THEN
      SELECT served_question_ids INTO v_ids
        FROM public.mcp_anonymous_usage
       WHERE subject_hash = p_subject_hash AND onderdeel = p_onderdeel AND level = coalesce(p_level, '')
       FOR UPDATE;
    END;
  END IF;

  IF p_question_id = ANY (v_ids) THEN
    RETURN true;
  END IF;

  IF coalesce(array_length(v_ids, 1), 0) >= p_limit THEN
    RETURN false;
  END IF;

  UPDATE public.mcp_anonymous_usage
     SET served_question_ids = array_append(served_question_ids, p_question_id),
         updated_at = now()
   WHERE subject_hash = p_subject_hash AND onderdeel = p_onderdeel AND level = coalesce(p_level, '');
  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.mcp_anon_serve(text, text, text, bigint, integer) FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS public.mcp_events (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at  timestamptz NOT NULL DEFAULT now(),
  event        text        NOT NULL,
  tool         text,
  tier         text        CHECK (tier IN ('anonymous', 'connected', 'module')),
  user_id      uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  subject_hash text,
  onderdeel    text,
  level        text,
  props        jsonb       NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE public.mcp_events IS
  'ChatGPT-app: één rij per tool-aanroep of gebeurtenis. Geen gespreksinhoud, geen antwoordtekst.';

CREATE INDEX IF NOT EXISTS mcp_events_occurred_idx ON public.mcp_events (occurred_at);
CREATE INDEX IF NOT EXISTS mcp_events_event_idx    ON public.mcp_events (event, occurred_at);

ALTER TABLE public.mcp_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins read mcp events" ON public.mcp_events;
CREATE POLICY "Admins read mcp events" ON public.mcp_events
  FOR SELECT USING (public.is_admin());
