-- De woordkaarten van de leerlaag: vertalingen op `lesson_words`, plus voortgang per kandidaat.
--
-- ## Waarom niet `user_word_card_progress`
--
-- Die tabel bestaat al, maar `word_card_id` heeft een foreign key naar `word_cards` — de 366 KNM
-- kaarten. `lesson_words` is een andere tabel met een andere sleutel (level, onderdeel, dutch), dus
-- er is geen manier om de voortgang van een A2-Lezen-woord daarin te zetten zonder de FK te
-- verbreken. Twee tabellen met elk hun eigen FK is hier het juiste antwoord: één polymorfe kolom
-- die naar twee tabellen kan wijzen kan de database niet afdwingen, en dat is precies het soort
-- verwijzing dat stil naar niets gaat wijzen.
--
-- ## De statussen
--
-- `unseen → seen → learning | known`. Vier en geen twee, want "ik heb deze kaart gezien" en "ik ken
-- dit woord" zijn niet hetzelfde, en de KNM-deck gebruikt dezelfde vier — de kandidaat die van KNM
-- naar A2 Lezen loopt vindt dus dezelfde knoppen. Let op: het KNM-deel van dit repo heeft nog de
-- oudere `known boolean`; die is hier niet overgenomen omdat een boolean geen "nog leren" kan zeggen.

create table if not exists user_lesson_word_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  lesson_word_id integer not null references lesson_words (id) on delete cascade,
  status text not null default 'unseen'
    check (status in ('unseen', 'seen', 'learning', 'known')),
  updated_at timestamptz not null default now(),
  constraint user_lesson_word_progress_key unique (user_id, lesson_word_id)
);

create index if not exists user_lesson_word_progress_user_idx
  on user_lesson_word_progress (user_id);
create index if not exists user_lesson_word_progress_word_idx
  on user_lesson_word_progress (lesson_word_id);

alter table user_lesson_word_progress enable row level security;

-- Eén policy voor alles: de kandidaat beheert zijn eigen rijen en niemand anders ziet ze. `using`
-- én `with check`, want zonder `with check` slaagt een insert met een andere `user_id` gewoon.
-- Denk aan de val: een door RLS geweigerde UPDATE via PostgREST geeft 200 met nul rijen terug, dus
-- een ontbrekende policy leest als een gelukte opslag.
drop policy if exists "Users manage own lesson word progress" on user_lesson_word_progress;
create policy "Users manage own lesson word progress" on user_lesson_word_progress
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ## De vertalingen
--
-- Engels en Arabisch, de twee talen die het portaal al draagt. Ze zijn **machinaal gemaakt en niet
-- door de docent nagekeken**, precies zoals de gidsvertalingen, en dat moet de lezer kunnen zien:
-- `translations_reviewed` is de vlag waarop de kaart zijn mededeling zet, in de taal van de lezer.
-- De Nederlandse kant (`dutch`, `meaning_nl`, `example`) is wél van de docent — dat is de kant waar
-- de claim van het product over gaat, en die verandert hier niet.
--
-- Turks staat er bewust niet bij: het portaal heeft geen tr-locale, en een kolom vullen voor een
-- taal die geen enkele pagina kan tonen is content die niemand ooit ziet nakijken.
alter table lesson_words add column if not exists translation_en text;
alter table lesson_words add column if not exists translation_ar text;
alter table lesson_words add column if not exists translations_reviewed boolean not null default false;
