-- ============================================================================
-- De leerlaag: concepten, lessen en de koppeling naar de examenitems
-- ============================================================================
--
-- Tot nu toe kon het portaal één ding: examens maken. Wie A2 Lezen examen 3 verprutste wist
-- dát het fout ging en niet wát hij moest leren. KNM had een leerlaag (`leren_content`,
-- 7 thema's) en de vier taalonderdelen niets.
--
-- Dit is de tabellenkant daarvan. Drie assen, en het is de moeite ze uit elkaar te houden:
--
--   1. Een CONCEPT is één leerbaar ding op een niveau — `omdat`-woordorde, het perfectum, "de
--      afzender van een brief vinden". Het staat ÉÉN keer per niveau en wordt gedeeld door de
--      onderdelen die het nodig hebben (`concept_onderdelen`). De uitleg staat op het concept.
--   2. Een LES is één zitting binnen een (niveau, onderdeel), in een blok A–E. De OPGAVEN staan
--      op de les, niet op het concept: Luisteren oefent `omdat` op het gehoor en Schrijven laat
--      hem bouwen. Zelfde concept, zelfde uitleg, andere oefening.
--   3. Een EXAMENITEM test nul of meer concepten (`question_concepts`, `open_task_concepts`).
--      Dát is de remediatie: fout antwoord -> concept -> de les die het uitlegt.
--
-- Waarom niet `leren_content` / `user_leren_progress` uitbreiden: die zijn gekeyd op een kaal
-- `thema_id integer` zonder niveau- of onderdeel-as. A2-Lezen-les-1 daar naast KNM-thema-1
-- zetten is exact de botsing die `lib/portal-progress.ts` al één keer heeft moeten repareren
-- toen `exam_${number}` Lezen 1 en Luisteren 1 over elkaar heen schreef. KNM's leerlaag blijft
-- hier ongemoeid; `lesson_blocks.level` is nullable zodat KNM er later in kan migreren.
--
-- Twee conventies bewust overgenomen in plaats van opnieuw bedacht:
--   * `review_status` is 'pending' | 'validated', net als `stimuli` en `open_tasks`. Het plan
--     noemde dit "draft"; een derde woord voor dezelfde toestand is een derde plek om het
--     verkeerd te lezen.
--   * `onderdeel` is een FK naar `skills(slug)`, geen CHECK-lijst. De acht CHECK-constraints
--     die de vier onderdelen opsomden waren al gedrift toen 20260803000000 ze in FK's veranderde.

-- ---------------------------------------------------------------------------
-- 1. Concepten
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.concept_groups (
  id         smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level      cefr_level NOT NULL,
  slug       text NOT NULL,
  name_nl    text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT concept_groups_key UNIQUE (level, slug)
);

COMMENT ON TABLE public.concept_groups IS
  'De koppen waaronder de concepten van een niveau staan: "Zinnen bouwen", "Werkwoorden & tijd".';

-- `level` is hier NOT NULL en dat is een keuze, niet een vergetelheid: een concept is
-- taalstof en die is per definitie geniveleerd. KNM heeft geen grammaticaconcepten — zijn
-- 43 subonderwerpen zitten al in `sections` en zijn remediatie loopt daarlangs. Zou KNM ooit
-- toch concepten nodig hebben, dan is dat een migratie met een trigger zoals `lesson_blocks`
-- die hieronder heeft, en geen stille NULL.
CREATE TABLE IF NOT EXISTS public.concepts (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level         cefr_level NOT NULL,
  group_id      smallint REFERENCES public.concept_groups(id) ON DELETE SET NULL,
  slug          text NOT NULL,
  name_nl       text NOT NULL,
  kind          text NOT NULL CHECK (kind IN ('grammatica', 'woordenschat', 'strategie')),
  -- De regel onder de kaarttitel in het overzicht. Kort, in A2-Nederlands.
  one_liner     text NOT NULL,
  -- Het voorbeeldzinnetje op de kaart, met <mark> om het fragment dat het concept toont.
  example_html  text,
  -- DE uitleg van dit concept. Eén keer, gedeeld door elk onderdeel dat hem lesgeeft; nooit
  -- per onderdeel gekopieerd, want vier kopieën van het perfectum gaan uit elkaar lopen.
  body_html     text,
  sort_order    integer NOT NULL DEFAULT 0,
  review_status text NOT NULL DEFAULT 'pending'
                  CHECK (review_status IN ('pending', 'validated')),
  reviewed_by   text,
  reviewed_on   date,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT concepts_key UNIQUE (level, slug)
);

CREATE INDEX IF NOT EXISTS concepts_level_idx ON public.concepts (level, sort_order);

-- De "KOMT IN LEZEN · SCHRIJVEN · LUISTEREN"-chips. Een 'grammatica'-concept staat hier vaak
-- vier keer; een 'strategie'-concept altijd precies één keer — examenvakmanschap hoort bij
-- één onderdeel, en dat is het hele antwoord op "hoe bereid je iemand voor die alleen
-- Luisteren doet".
CREATE TABLE IF NOT EXISTS public.concept_onderdelen (
  concept_id integer NOT NULL REFERENCES public.concepts(id) ON DELETE CASCADE,
  onderdeel  text    NOT NULL REFERENCES public.skills(slug) ON UPDATE CASCADE,
  PRIMARY KEY (concept_id, onderdeel)
);

-- ---------------------------------------------------------------------------
-- 2. Blokken en lessen
-- ---------------------------------------------------------------------------

-- `level` is nullable achter dezelfde trigger als `exams.level`, zodat KNM (niet-geniveleerd)
-- hier later in past. De UNIQUE gebruikt NULLS NOT DISTINCT: in een gewone UNIQUE zijn NULLs
-- distinct, dus twee identieke KNM-blokken zouden naast elkaar mogen bestaan — precies de
-- duplicatie die de constraint moet voorkomen, terugkerend voor het nieuwe geval.
CREATE TABLE IF NOT EXISTS public.lesson_blocks (
  id         smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level      cefr_level,
  onderdeel  text NOT NULL REFERENCES public.skills(slug) ON UPDATE CASCADE,
  letter     text NOT NULL CHECK (letter ~ '^[A-Z]$'),
  name_nl    text NOT NULL,
  intro      text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lesson_blocks_key UNIQUE NULLS NOT DISTINCT (level, onderdeel, letter)
);

CREATE OR REPLACE FUNCTION public.lesson_blocks_level_matches_skill()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE levelled boolean;
BEGIN
  SELECT s.is_levelled INTO levelled FROM public.skills s WHERE s.slug = NEW.onderdeel;

  IF levelled AND NEW.level IS NULL THEN
    RAISE EXCEPTION 'Onderdeel % bestaat per niveau; level mag niet leeg zijn', NEW.onderdeel;
  END IF;
  IF NOT levelled AND NEW.level IS NOT NULL THEN
    RAISE EXCEPTION 'Onderdeel % kent geen niveaus; level moet leeg zijn', NEW.onderdeel;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS lesson_blocks_level_check ON public.lesson_blocks;
CREATE TRIGGER lesson_blocks_level_check
  BEFORE INSERT OR UPDATE OF level, onderdeel ON public.lesson_blocks
  FOR EACH ROW EXECUTE FUNCTION public.lesson_blocks_level_matches_skill();

CREATE TABLE IF NOT EXISTS public.lessons (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  block_id       smallint NOT NULL REFERENCES public.lesson_blocks(id) ON DELETE CASCADE,
  slug           text NOT NULL,
  title          text NOT NULL,
  -- "Wat je leert" — één alinea, in de tweede persoon, vóór de eerste opgave.
  what_you_learn text,
  minutes        smallint,
  is_free        boolean NOT NULL DEFAULT false,
  sort_order     integer NOT NULL DEFAULT 0,
  review_status  text NOT NULL DEFAULT 'pending'
                   CHECK (review_status IN ('pending', 'validated')),
  reviewed_by    text,
  reviewed_on    date,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lessons_key UNIQUE (block_id, slug)
);

CREATE INDEX IF NOT EXISTS lessons_block_idx ON public.lessons (block_id, sort_order);

-- Wat deze les met een concept doet. 'teaches' is de les die het concept uitlegt en waar de
-- remediatie naartoe wijst; 'reviews' is een les die er alleen op terugkomt. B1's
-- grammatica-bijlage is herhaling van A2-stof en wordt dus 'reviews' op het A2-concept —
-- niet een B1-kopie ervan, want cross-niveau-besmetting levert een volstrekt plausibele les
-- op die het verkeerde register aanleert, met nergens een fout.
CREATE TABLE IF NOT EXISTS public.lesson_concepts (
  lesson_id  integer NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE,
  concept_id integer NOT NULL REFERENCES public.concepts(id) ON DELETE CASCADE,
  role       text NOT NULL DEFAULT 'teaches' CHECK (role IN ('teaches', 'reviews')),
  PRIMARY KEY (lesson_id, concept_id)
);

-- Eén 'teaches'-les per concept per onderdeel: de remediatie moet één bestemming hebben.
-- Twee kandidaten betekent dat de link willekeurig kiest, en dat is erger dan geen link.
CREATE OR REPLACE FUNCTION public.lesson_concepts_one_teacher()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  my_level     cefr_level;
  my_onderdeel text;
  dupes        integer;
BEGIN
  IF NEW.role <> 'teaches' THEN RETURN NEW; END IF;

  -- Het bereik van deze les: (niveau, onderdeel). Apart opgehaald in plaats van als
  -- rijvergelijking tegen een subquery — `(a, b) IS NOT DISTINCT FROM (SELECT x, y ...)`
  -- is geen geldige vergelijking en faalde met "subquery must return only one column",
  -- waardoor de trigger élke insert weigerde en dus leek te werken.
  SELECT b.level, b.onderdeel INTO my_level, my_onderdeel
    FROM public.lessons l
    JOIN public.lesson_blocks b ON b.id = l.block_id
   WHERE l.id = NEW.lesson_id;

  SELECT count(*) INTO dupes
    FROM public.lesson_concepts lc
    JOIN public.lessons l       ON l.id = lc.lesson_id
    JOIN public.lesson_blocks b ON b.id = l.block_id
   WHERE lc.concept_id = NEW.concept_id
     AND lc.role = 'teaches'
     AND lc.lesson_id <> NEW.lesson_id
     AND b.level     IS NOT DISTINCT FROM my_level
     AND b.onderdeel = my_onderdeel;

  IF dupes > 0 THEN
    RAISE EXCEPTION 'Concept % heeft in % al een les die het uitlegt', NEW.concept_id, my_onderdeel
      USING HINT = 'Gebruik role = ''reviews'' voor een les die er alleen op terugkomt.';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS lesson_concepts_one_teacher_check ON public.lesson_concepts;
CREATE TRIGGER lesson_concepts_one_teacher_check
  BEFORE INSERT OR UPDATE ON public.lesson_concepts
  FOR EACH ROW EXECUTE FUNCTION public.lesson_concepts_one_teacher();

-- ---------------------------------------------------------------------------
-- 3. De inhoud van een les: uitleg én opgaven in ÉÉN lijst
-- ---------------------------------------------------------------------------
--
-- Twee tabellen (uitlegblokken en opgaven apart) zou twee sorteringen betekenen die op elkaar
-- moeten passen, en de hele belofte van deze laag is dat je na de uitleg meteen oefent — dat
-- is één lijst, niet twee schermen. `kind` discrimineert en `payload` draagt de rest; de
-- renderer is een switch met een never-default, zodat een nieuwe kind een compilefout geeft
-- en niet een leeg blok.
CREATE TABLE IF NOT EXISTS public.lesson_items (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id   integer NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE,
  sort_order  integer NOT NULL,
  kind        text NOT NULL CHECK (kind IN (
                'uitleg', 'voorbeeld', 'leestekst', 'audio', 'video',
                'woordenlijst', 'zinnenbank',
                'mcq', 'gap_choice', 'gap_type', 'woordorde', 'matchen',
                'open_zin', 'markeren')),
  -- De moeilijkheidstrap, uit de methodiek: 0 = receptief (herkennen), 1 = tussenin,
  -- 2 = productief (zelf maken). NULL voor een uitlegblok, dat niets vraagt. Dit is geen
  -- sortering maar een didactisch feit: het is waarom een les met alleen MCQ's niets bewijst,
  -- en het is wat blok E laat zeggen "je kent dit receptief en je kunt het nog niet maken".
  tier        smallint CHECK (tier BETWEEN 0 AND 2),
  payload     jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Waarom het antwoord goed is. Bij een opgave verplicht in de applicatielaag; hier
  -- nullable omdat een uitlegblok er geen heeft.
  explanation text,
  -- De tekstsoort waar deze opgave over gaat, voor blok C. Zelfde as als `stimuli.section_id`.
  section_id  smallint REFERENCES public.sections(id) ON DELETE SET NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lesson_items_sort_key UNIQUE (lesson_id, sort_order)
    DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS lesson_items_lesson_idx ON public.lesson_items (lesson_id, sort_order);

COMMENT ON CONSTRAINT lesson_items_sort_key ON public.lesson_items IS
  'DEFERRABLE helpt de editor NIET: PostgREST doet elk request in zijn eigen transactie, dus '
  'twee items omwisselen faalt op de eerste UPDATE. De editor parkeert omgesorteerde items '
  'daarom eerst op negatieve sort_order, net als FragmentEditor doet.';

-- Spiegelt `question_options`, inclusief de twee regels die daar dragend zijn: opties worden
-- per label gereconcilieerd (nooit verwijderd en opnieuw ingevoegd) en er is precies één
-- juist antwoord per opgave, afgedwongen met een partiële unique index — dus elke rij wordt
-- eerst is_correct=false geschreven en één ervan daarna omgezet.
CREATE TABLE IF NOT EXISTS public.lesson_item_options (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id    integer NOT NULL REFERENCES public.lesson_items(id) ON DELETE CASCADE,
  label      text NOT NULL CHECK (label IN ('A', 'B', 'C', 'D')),
  body       text,
  image_urls text[] NOT NULL DEFAULT '{}',
  image_alt  text,
  is_correct boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT lesson_item_options_label_key UNIQUE (item_id, label)
);

CREATE UNIQUE INDEX IF NOT EXISTS lesson_item_options_one_correct_idx
  ON public.lesson_item_options (item_id) WHERE is_correct;

-- ---------------------------------------------------------------------------
-- 4. Woorden en can-do-lijsten
-- ---------------------------------------------------------------------------
--
-- Gekeyd op (niveau, onderdeel) en niet op niveau alleen, omdat het onderdeel het woord
-- anders vraagt: Luisteren heeft de gesproken vorm nodig, Schrijven de spelling.
-- `usage` is de receptief/productief-splitsing: moet je het woord herkennen, of zelf kunnen
-- gebruiken. `frame` draagt de vaste constructie ("zich schamen (voor)") — zonder die frame
-- is een woord onbruikbaar in een productieve opgave.
CREATE TABLE IF NOT EXISTS public.lesson_words (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level         cefr_level NOT NULL,
  onderdeel     text NOT NULL REFERENCES public.skills(slug) ON UPDATE CASCADE,
  theme         text NOT NULL,
  dutch         text NOT NULL,
  article       text CHECK (article IN ('de', 'het')),
  plural        text,
  frame         text,
  meaning_nl    text NOT NULL,
  example       text,
  usage         text NOT NULL CHECK (usage IN ('receptief', 'productief')),
  audio_url     text,
  sort_order    integer NOT NULL DEFAULT 0,
  review_status text NOT NULL DEFAULT 'pending'
                  CHECK (review_status IN ('pending', 'validated')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lesson_words_key UNIQUE (level, onderdeel, dutch)
);

CREATE INDEX IF NOT EXISTS lesson_words_scope_idx
  ON public.lesson_words (level, onderdeel, theme, sort_order);

-- "Wat kun je nu?" — de can-do-lijst waarmee een blok afsluit, elke regel gekoppeld aan de
-- les(sen) die het aanleren. Dat is de remediatiekoppeling nog een keer, maar op het niveau
-- waarop de kandidaat zélf beslist wat hij overdoet.
CREATE TABLE IF NOT EXISTS public.block_outcomes (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  block_id   smallint NOT NULL REFERENCES public.lesson_blocks(id) ON DELETE CASCADE,
  text       text NOT NULL,
  lesson_ids integer[] NOT NULL DEFAULT '{}',
  sort_order integer NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- 5. De remediatie-as: welk examenitem test welk concept
-- ---------------------------------------------------------------------------
--
-- Dit is waarom de conceptenlaag bestaat en niet alleen een tweede contentsoort is. Zonder
-- deze twee tabellen weet een kandidaat na een gezakt examen dát het fout ging en niet wát
-- hij moet leren.
--
-- `weight` onderscheidt "deze vraag stáát of valt met dit concept" van "het komt er ook in
-- voor". Het resultaatscherm sorteert erop, zodat de aanbeveling niet wordt verdund door
-- concepten die de fout niet verklaren.
CREATE TABLE IF NOT EXISTS public.question_concepts (
  question_id bigint  NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  concept_id  integer NOT NULL REFERENCES public.concepts(id) ON DELETE CASCADE,
  weight      smallint NOT NULL DEFAULT 1 CHECK (weight BETWEEN 1 AND 3),
  source      text NOT NULL DEFAULT 'auto' CHECK (source IN ('auto', 'docent')),
  PRIMARY KEY (question_id, concept_id)
);

CREATE INDEX IF NOT EXISTS question_concepts_concept_idx
  ON public.question_concepts (concept_id);

CREATE TABLE IF NOT EXISTS public.open_task_concepts (
  open_task_id bigint  NOT NULL REFERENCES public.open_tasks(id) ON DELETE CASCADE,
  concept_id   integer NOT NULL REFERENCES public.concepts(id) ON DELETE CASCADE,
  weight       smallint NOT NULL DEFAULT 1 CHECK (weight BETWEEN 1 AND 3),
  source       text NOT NULL DEFAULT 'auto' CHECK (source IN ('auto', 'docent')),
  PRIMARY KEY (open_task_id, concept_id)
);

CREATE INDEX IF NOT EXISTS open_task_concepts_concept_idx
  ON public.open_task_concepts (concept_id);

-- ---------------------------------------------------------------------------
-- 6. Voortgang
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_lesson_progress (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lesson_id   integer NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE,
  state       text NOT NULL DEFAULT 'started' CHECK (state IN ('started', 'done')),
  items_done  integer NOT NULL DEFAULT 0,
  items_total integer NOT NULL DEFAULT 0,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  CONSTRAINT user_lesson_progress_key UNIQUE (user_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS user_lesson_progress_user_idx
  ON public.user_lesson_progress (user_id);

-- Beheersing telt op HET CONCEPT, over de onderdelen heen: een goed antwoord in de
-- Luisteren-les en een goed antwoord in de Schrijven-les verhogen dezelfde rij. Dat is de
-- juiste keuze en niet de gemakkelijke — "herkent `omdat` op het gehoor" en "produceert
-- `omdat` schriftelijk" zijn de tier 0 versus tier 2 op `lesson_items`, niet twee concepten.
--
-- `mastery_pct` is ONS getal en heet dat ook. Het is geen voorspelling van een DUO-uitslag:
-- SEO/facts.md §9 verbiedt een onnavolgbare slaagnorm, en een percentage dat als slaagkans
-- leest zou datzelfde doen.
CREATE TABLE IF NOT EXISTS public.user_concept_mastery (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  concept_id     integer NOT NULL REFERENCES public.concepts(id) ON DELETE CASCADE,
  seen           integer NOT NULL DEFAULT 0,
  correct        integer NOT NULL DEFAULT 0,
  -- Goede antwoorden op rij; de "nog N goede antwoorden en dit concept staat op beheerst"-regel.
  streak         integer NOT NULL DEFAULT 0,
  -- Apart geteld per trap, want receptief kunnen en productief kunnen zijn niet hetzelfde.
  correct_receptief  integer NOT NULL DEFAULT 0,
  seen_receptief     integer NOT NULL DEFAULT 0,
  correct_productief integer NOT NULL DEFAULT 0,
  seen_productief    integer NOT NULL DEFAULT 0,
  mastery_pct    smallint NOT NULL DEFAULT 0 CHECK (mastery_pct BETWEEN 0 AND 100),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_concept_mastery_key UNIQUE (user_id, concept_id)
);

CREATE INDEX IF NOT EXISTS user_concept_mastery_user_idx
  ON public.user_concept_mastery (user_id);

-- ---------------------------------------------------------------------------
-- 7. updated_at
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS concepts_touch ON public.concepts;
CREATE TRIGGER concepts_touch BEFORE UPDATE ON public.concepts
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

DROP TRIGGER IF EXISTS lessons_touch ON public.lessons;
CREATE TRIGGER lessons_touch BEFORE UPDATE ON public.lessons
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

DROP TRIGGER IF EXISTS user_lesson_progress_touch ON public.user_lesson_progress;
CREATE TRIGGER user_lesson_progress_touch BEFORE UPDATE ON public.user_lesson_progress
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

DROP TRIGGER IF EXISTS user_concept_mastery_touch ON public.user_concept_mastery;
CREATE TRIGGER user_concept_mastery_touch BEFORE UPDATE ON public.user_concept_mastery
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- 8. RLS
-- ---------------------------------------------------------------------------
--
-- Contenttabellen: publiek lezen, admin schrijven — exact zoals `questions`,
-- `question_options`, `stimuli` en `sections` het al doen. Het gevolg is dat een nog niet
-- nagekeken les langs zijn URL leesbaar is, en dat is bedoeld: precies dát maakt reviewen
-- mogelijk. De publicatiegate zit in de applicatielaag (`review_status = 'validated'`), net
-- zoals `exams.published` daar zit en niet in een policy.
--
-- Let op wat hier NIET verandert: `lesson_item_options.is_correct` is publiek leesbaar, net
-- als `question_options.is_correct`. Dat is de bestaande conventie waar de examenspeler op
-- leunt. Wat nooit publiek mag zijn, is een rubriek of een `model_answer`; daar komt in deze
-- laag niets van voor, en `open_zin` draagt zijn voorbeeldantwoord bewust wél in de payload
-- omdat de kandidaat het zelf moet kunnen vergelijken.

ALTER TABLE public.concept_groups      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.concepts            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.concept_onderdelen  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_blocks       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lessons             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_concepts     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_items        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_item_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_words        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.block_outcomes      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_concepts   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.open_task_concepts  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_lesson_progress  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_concept_mastery  ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'concept_groups', 'concepts', 'concept_onderdelen', 'lesson_blocks', 'lessons',
    'lesson_concepts', 'lesson_items', 'lesson_item_options', 'lesson_words',
    'block_outcomes', 'question_concepts', 'open_task_concepts'
  ] LOOP
    EXECUTE format(
      'DROP POLICY IF EXISTS "Public read %1$s" ON public.%1$I', t);
    EXECUTE format(
      'CREATE POLICY "Public read %1$s" ON public.%1$I FOR SELECT USING (true)', t);
    EXECUTE format(
      'DROP POLICY IF EXISTS "Admins write %1$s" ON public.%1$I', t);
    EXECUTE format(
      'CREATE POLICY "Admins write %1$s" ON public.%1$I FOR ALL USING (is_admin()) WITH CHECK (is_admin())', t);
  END LOOP;
END $$;

DROP POLICY IF EXISTS "Users manage own lesson progress" ON public.user_lesson_progress;
CREATE POLICY "Users manage own lesson progress" ON public.user_lesson_progress
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users manage own concept mastery" ON public.user_concept_mastery;
CREATE POLICY "Users manage own concept mastery" ON public.user_concept_mastery
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Admin moet de voortgang van een kandidaat kunnen zien (/admin/users). Zonder deze policy
-- ziet de docent nul rijen en leest dat als "deze gebruiker doet niets" — dezelfde stille
-- nul die de backlog-waarschuwing bij `user_question_results` al eens onbruikbaar maakte.
DROP POLICY IF EXISTS "Admins read lesson progress" ON public.user_lesson_progress;
CREATE POLICY "Admins read lesson progress" ON public.user_lesson_progress
  FOR SELECT USING (is_admin());

DROP POLICY IF EXISTS "Admins read concept mastery" ON public.user_concept_mastery;
CREATE POLICY "Admins read concept mastery" ON public.user_concept_mastery
  FOR SELECT USING (is_admin());
