-- ============================================================================
-- Spend controls on rubric grading.
--
-- Every "Nakijken" costs money at two providers (a Flash-tier model, and ElevenLabs Scribe for
-- Spreken). Until now the only cap was 3 grades per (attempt, task), which bounds one task and
-- nothing else: a candidate could open 16 Spreken tasks and grade each three times, or sit the same
-- exam repeatedly, and the bill would follow.
--
-- Two separate mechanisms, because they answer different questions:
--
--   · `grade_rate_log` answers "how much has this actor spent recently?" — a sliding window per
--     user and per IP. Abuse control. Rows are disposable and pruned.
--   · the free allowance answers "is this person entitled to another grade at all?" — counted from
--     `open_submissions`, which is the durable record. Never pruned, because deleting it would
--     silently hand somebody a fresh free quota.
--
-- The IP is kept because an account is cheap to create: the per-user cap stops one candidate looping,
-- the per-IP cap stops one candidate looping behind ten accounts. It is a coarse signal — shared
-- office and carrier NAT put real users behind one address — so the IP ceiling is deliberately much
-- looser than the per-user one, and it never blocks a *paying* user.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.grade_rate_log (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  -- Nullable: a proxy may not give us one, and a missing IP must not be a free pass *or* a block.
  ip         text,
  skill      text CHECK (skill IN ('schrijven', 'spreken')),
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.grade_rate_log IS
  'One row per grading attempt, for sliding-window rate limits. Disposable — prune freely. The '
  'durable record of what was graded is open_submissions; do not count entitlement from this table.';

CREATE INDEX IF NOT EXISTS grade_rate_log_user_idx ON public.grade_rate_log (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS grade_rate_log_ip_idx   ON public.grade_rate_log (ip, created_at DESC);

ALTER TABLE public.grade_rate_log ENABLE ROW LEVEL SECURITY;

-- Written only by the grading route with the service key, read only by admins. A candidate has no
-- business reading or writing their own rate-limit ledger.
DROP POLICY IF EXISTS "Admins read grade rate log" ON public.grade_rate_log;
CREATE POLICY "Admins read grade rate log" ON public.grade_rate_log
  FOR SELECT USING (public.is_admin());

/**
 * How many graded submissions this user already has for a skill.
 *
 * Counts distinct (attempt, task) pairs rather than rows: re-grading one answer is the same
 * *exercise*, and charging a candidate's free allowance twice for pressing Nakijken again would be
 * indistinguishable from a bug. `attempt_id IS NULL` rows (no sitting opened) fall back to the task
 * alone, so they cannot be farmed either.
 */
CREATE OR REPLACE FUNCTION public.graded_exercise_count(p_user_id uuid, p_skill text)
RETURNS integer
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT count(DISTINCT (coalesce(s.attempt_id::text, 'none'), s.task_id))::integer
  FROM public.open_submissions s
  JOIN public.open_tasks t ON t.id = s.task_id
  WHERE s.user_id = p_user_id
    AND t.skill = p_skill
    AND s.status <> 'submitted';
$$;

COMMIT;

NOTIFY pgrst, 'reload schema';
